// GENERATED from both API specs (farm + login) — do not edit by hand.
// 584 pages.

import 'page_spec.dart';

const List<PageSpec> generatedPages = [
    PageSpec(key: 'weatherforecast', title: 'Weather Forecast', path: '/WeatherForecast', needsFarmId: false, readOnly: true),
    PageSpec(key: 'announcements', title: 'Announcements', path: '/api/Announcements', needsUserId: true),
    PageSpec(key: 'announcements-manage', title: 'Manage', path: '/api/Announcements/manage', needsFarmId: false, readOnly: true),
    PageSpec(key: 'auditlogs', title: 'Audit Logs', path: '/api/AuditLogs'),
    PageSpec(key: 'auditlogs-debug-info', title: 'Info', path: '/api/AuditLogs/debug/info', needsFarmId: false, readOnly: true),
    PageSpec(key: 'auditlogs-platform', title: 'Platform', path: '/api/AuditLogs/platform', needsFarmId: false, readOnly: true),
    PageSpec(key: 'businessoffice-company-snapshot', title: 'Company snapshot', path: '/api/BusinessOffice/company-snapshot', needsCompanyType: true, readOnly: true),
    PageSpec(key: 'cash', title: 'Cash', path: '/api/Cash', needsUserId: true, readOnly: true),
    PageSpec(key: 'chat-threads', title: 'Threads', path: '/api/Chat/threads'),
    PageSpec(key: 'chat-threads-messages', title: 'Messages', path: '/api/Chat/threads/{threadId}/messages', needsFarmId: false),
    PageSpec(key: 'companytime-business-date', title: 'Business date', path: '/api/CompanyTime/business-date', readOnly: true),
    PageSpec(key: 'companytime-context', title: 'Context', path: '/api/CompanyTime/context', readOnly: true),
    PageSpec(key: 'companytime-zones', title: 'Zones', path: '/api/CompanyTime/zones', needsFarmId: false, readOnly: true),
    PageSpec(key: 'customer', title: 'Customer', path: '/api/Customer', needsUserId: true),
    PageSpec(key: 'dashboard-summary', title: 'Summary', path: '/api/Dashboard/Summary', readOnly: true),
    PageSpec(key: 'egginventoryadjustment', title: 'Egg Inventory Adjustment', path: '/api/EggInventoryAdjustment'),
    PageSpec(key: 'eggproduction', title: 'Egg Production', path: '/api/EggProduction', needsUserId: true),
    PageSpec(key: 'expense', title: 'Expense', path: '/api/Expense', needsUserId: true),
    PageSpec(key: 'expense-attachment', title: 'Attachment', path: '/api/Expense/{id}/attachment', readOnly: true),
    PageSpec(key: 'farmobservation', title: 'Farm Observation', path: '/api/FarmObservation'),
    PageSpec(key: 'farmobservation-by-week', title: 'By week', path: '/api/FarmObservation/by-week', readOnly: true),
    PageSpec(key: 'farmproductionsettings', title: 'Farm Production Settings', path: '/api/FarmProductionSettings', readOnly: true),
    PageSpec(key: 'feedinventoryadjustment', title: 'Feed Inventory Adjustment', path: '/api/FeedInventoryAdjustment'),
    PageSpec(key: 'feedusage', title: 'Feed Usage', path: '/api/FeedUsage', needsUserId: true),
    PageSpec(key: 'flock', title: 'Flock', path: '/api/Flock', needsUserId: true),
    PageSpec(key: 'health', title: 'Health', path: '/api/Health', needsUserId: true),
    PageSpec(key: 'health-attachment', title: 'Attachment', path: '/api/Health/{id}/attachment', readOnly: true),
    PageSpec(key: 'hotel-availability', title: 'Availability', path: '/api/Hotel/availability', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-billing-charges', title: 'Charges', path: '/api/Hotel/billing/charges', module: 'hotel'),
    PageSpec(key: 'hotel-billing-invoices', title: 'Invoices', path: '/api/Hotel/billing/invoices', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-billing-payments', title: 'Payments', path: '/api/Hotel/billing/payments', module: 'hotel'),
    PageSpec(key: 'hotel-bookings', title: 'Bookings', path: '/api/Hotel/bookings', module: 'hotel'),
    PageSpec(key: 'hotel-bookings-today-arrivals', title: 'Today arrivals', path: '/api/Hotel/bookings/today-arrivals', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-bookings-today-departures', title: 'Today departures', path: '/api/Hotel/bookings/today-departures', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-checkin-history', title: 'Checkin history', path: '/api/Hotel/checkin-history', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-checkout-history', title: 'Checkout history', path: '/api/Hotel/checkout-history', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-communications', title: 'Communications', path: '/api/Hotel/communications', module: 'hotel'),
    PageSpec(key: 'hotel-dashboard-summary', title: 'Summary', path: '/api/Hotel/dashboard/summary', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-deposits', title: 'Deposits', path: '/api/Hotel/deposits', module: 'hotel'),
    PageSpec(key: 'hotel-finance-cash-accounts', title: 'Cash accounts', path: '/api/Hotel/finance/cash-accounts', module: 'hotel'),
    PageSpec(key: 'hotel-finance-cash-transactions', title: 'Cash transactions', path: '/api/Hotel/finance/cash-transactions', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-finance-expense-categories', title: 'Expense categories', path: '/api/Hotel/finance/expense-categories', module: 'hotel'),
    PageSpec(key: 'hotel-finance-expenses', title: 'Expenses', path: '/api/Hotel/finance/expenses', module: 'hotel'),
    PageSpec(key: 'hotel-guest-requests', title: 'Guest requests', path: '/api/Hotel/guest-requests', module: 'hotel'),
    PageSpec(key: 'hotel-guests', title: 'Guests', path: '/api/Hotel/guests', module: 'hotel'),
    PageSpec(key: 'hotel-guests-search', title: 'Search', path: '/api/Hotel/guests/search', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-housekeeping', title: 'Housekeeping', path: '/api/Hotel/housekeeping', module: 'hotel'),
    PageSpec(key: 'hotel-housekeeping-schedule', title: 'Housekeeping schedule', path: '/api/Hotel/housekeeping-schedule', module: 'hotel'),
    PageSpec(key: 'hotel-inventory', title: 'Inventory', path: '/api/Hotel/inventory', module: 'hotel'),
    PageSpec(key: 'hotel-lost-and-found', title: 'Lost and found', path: '/api/Hotel/lost-and-found', module: 'hotel'),
    PageSpec(key: 'hotel-loyalty', title: 'Loyalty', path: '/api/Hotel/loyalty', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-loyalty-transactions', title: 'Transactions', path: '/api/Hotel/loyalty/{id}/transactions', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-maintenance', title: 'Maintenance', path: '/api/Hotel/maintenance', module: 'hotel'),
    PageSpec(key: 'hotel-night-audit', title: 'Night audit', path: '/api/Hotel/night-audit', module: 'hotel'),
    PageSpec(key: 'hotel-payroll-diag', title: 'Payroll diag', path: '/api/Hotel/payroll-diag', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-payroll-runs', title: 'Payroll runs', path: '/api/Hotel/payroll-runs', module: 'hotel'),
    PageSpec(key: 'hotel-reports-ancillary-revenue', title: 'Ancillary revenue', path: '/api/Hotel/reports/ancillary-revenue', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-reports-booking-pace', title: 'Booking pace', path: '/api/Hotel/reports/booking-pace', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-reports-cancellations', title: 'Cancellations', path: '/api/Hotel/reports/cancellations', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-reports-daily-closings', title: 'Daily closings', path: '/api/Hotel/reports/daily-closings', module: 'hotel'),
    PageSpec(key: 'hotel-reports-guest-ledger', title: 'Guest ledger', path: '/api/Hotel/reports/guest-ledger', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-reports-housekeeping-productivity', title: 'Housekeeping productivity', path: '/api/Hotel/reports/housekeeping-productivity', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-reports-length-of-stay', title: 'Length of stay', path: '/api/Hotel/reports/length-of-stay', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-reports-loyalty', title: 'Loyalty', path: '/api/Hotel/reports/loyalty', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-reports-performance-kpis', title: 'Performance kpis', path: '/api/Hotel/reports/performance-kpis', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-reports-room-type-performance', title: 'Room type performance', path: '/api/Hotel/reports/room-type-performance', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-reports-source-of-business', title: 'Source of business', path: '/api/Hotel/reports/source-of-business', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-restaurant-menu', title: 'Menu', path: '/api/Hotel/restaurant/menu', module: 'hotel'),
    PageSpec(key: 'hotel-restaurant-orders', title: 'Orders', path: '/api/Hotel/restaurant/orders', module: 'hotel'),
    PageSpec(key: 'hotel-restaurant-orders-items', title: 'Items', path: '/api/Hotel/restaurant/orders/{id}/items', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-restaurant-tables', title: 'Tables', path: '/api/Hotel/restaurant/tables', module: 'hotel'),
    PageSpec(key: 'hotel-room-rates', title: 'Room rates', path: '/api/Hotel/room-rates', module: 'hotel'),
    PageSpec(key: 'hotel-rooms', title: 'Rooms', path: '/api/Hotel/rooms', module: 'hotel'),
    PageSpec(key: 'hotel-rooms-status-summary', title: 'Status summary', path: '/api/Hotel/rooms/status-summary', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-rooms-amenities', title: 'Amenities', path: '/api/Hotel/rooms/{id}/amenities', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-setup-amenities', title: 'Amenities', path: '/api/Hotel/setup/amenities', module: 'hotel'),
    PageSpec(key: 'hotel-setup-bed-types', title: 'Bed types', path: '/api/Hotel/setup/bed-types', module: 'hotel', needsFarmId: false, readOnly: true),
    PageSpec(key: 'hotel-setup-comm-subjects', title: 'Comm subjects', path: '/api/Hotel/setup/comm-subjects', module: 'hotel', needsFarmId: false, readOnly: true),
    PageSpec(key: 'hotel-setup-floors', title: 'Floors', path: '/api/Hotel/setup/floors', module: 'hotel'),
    PageSpec(key: 'hotel-setup-hk-task-types', title: 'Hk task types', path: '/api/Hotel/setup/hk-task-types', module: 'hotel', needsFarmId: false, readOnly: true),
    PageSpec(key: 'hotel-setup-id-types', title: 'Id types', path: '/api/Hotel/setup/id-types', module: 'hotel', needsFarmId: false, readOnly: true),
    PageSpec(key: 'hotel-setup-maintenance-assets', title: 'Maintenance assets', path: '/api/Hotel/setup/maintenance-assets', module: 'hotel', needsFarmId: false, readOnly: true),
    PageSpec(key: 'hotel-setup-menu-category-types', title: 'Menu category types', path: '/api/Hotel/setup/menu-category-types', module: 'hotel', needsFarmId: false, readOnly: true),
    PageSpec(key: 'hotel-setup-menu-item-names', title: 'Menu item names', path: '/api/Hotel/setup/menu-item-names', module: 'hotel', needsFarmId: false, readOnly: true),
    PageSpec(key: 'hotel-setup-profile', title: 'Profile', path: '/api/Hotel/setup/profile', module: 'hotel'),
    PageSpec(key: 'hotel-setup-request-types', title: 'Request types', path: '/api/Hotel/setup/request-types', module: 'hotel', needsFarmId: false, readOnly: true),
    PageSpec(key: 'hotel-setup-room-categories', title: 'Room categories', path: '/api/Hotel/setup/room-categories', module: 'hotel', needsFarmId: false, readOnly: true),
    PageSpec(key: 'hotel-setup-room-types', title: 'Room types', path: '/api/Hotel/setup/room-types', module: 'hotel'),
    PageSpec(key: 'hotel-setup-supply-categories', title: 'Supply categories', path: '/api/Hotel/setup/supply-categories', module: 'hotel', needsFarmId: false, readOnly: true),
    PageSpec(key: 'hotel-setup-supply-items', title: 'Supply items', path: '/api/Hotel/setup/supply-items', module: 'hotel', needsFarmId: false, readOnly: true),
    PageSpec(key: 'hotel-setup-table-locations', title: 'Table locations', path: '/api/Hotel/setup/table-locations', module: 'hotel', needsFarmId: false, readOnly: true),
    PageSpec(key: 'hotel-shift-handovers', title: 'Shift handovers', path: '/api/Hotel/shift-handovers', module: 'hotel'),
    PageSpec(key: 'hotel-staff', title: 'Staff', path: '/api/Hotel/staff', module: 'hotel'),
    PageSpec(key: 'house', title: 'House', path: '/api/House', needsUserId: true),
    PageSpec(key: 'iam-access-audit', title: 'Access audit', path: '/api/Iam/access-audit', readOnly: true),
    PageSpec(key: 'iam-access-review', title: 'Access review', path: '/api/Iam/access-review'),
    PageSpec(key: 'iam-catalog', title: 'Catalog', path: '/api/Iam/catalog', needsFarmId: false, readOnly: true),
    PageSpec(key: 'iam-effective-permissions', title: 'Effective permissions', path: '/api/Iam/effective-permissions', readOnly: true),
    PageSpec(key: 'iam-overrides', title: 'Overrides', path: '/api/Iam/overrides'),
    PageSpec(key: 'iam-policy', title: 'Policy', path: '/api/Iam/policy', readOnly: true),
    PageSpec(key: 'iam-roles', title: 'Roles', path: '/api/Iam/roles'),
    PageSpec(key: 'iam-roles-permissions', title: 'Permissions', path: '/api/Iam/roles/{roleId}/permissions', readOnly: true),
    PageSpec(key: 'iam-sessions', title: 'Sessions', path: '/api/Iam/sessions', readOnly: true),
    PageSpec(key: 'iam-status', title: 'Status', path: '/api/Iam/status', needsFarmId: false, readOnly: true),
    PageSpec(key: 'iam-user-roles', title: 'User roles', path: '/api/Iam/user-roles', readOnly: true),
    PageSpec(key: 'inventoryitem', title: 'Inventory Item', path: '/api/InventoryItem', needsUserId: true),
    PageSpec(key: 'mainflockbatch', title: 'Main Flock Batch', path: '/api/MainFlockBatch', needsUserId: true),
    PageSpec(key: 'poultry-asset-depreciation', title: 'Asset depreciation', path: '/api/Poultry/asset-depreciation', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-asset-depreciation-due', title: 'Due', path: '/api/Poultry/asset-depreciation/due', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-assets', title: 'Assets', path: '/api/Poultry/assets', module: 'poultry'),
    PageSpec(key: 'poultry-assets-categories', title: 'Categories', path: '/api/Poultry/assets/categories', module: 'poultry'),
    PageSpec(key: 'poultry-assets-summary', title: 'Summary', path: '/api/Poultry/assets/summary', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-balances-audit', title: 'Audit', path: '/api/Poultry/balances/audit', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-cash-accounts', title: 'Cash accounts', path: '/api/Poultry/cash-accounts', module: 'poultry'),
    PageSpec(key: 'poultry-cash-accounts-transactions', title: 'Transactions', path: '/api/Poultry/cash-accounts/transactions', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-cash-flow', title: 'Cash flow', path: '/api/Poultry/cash-flow', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-cash-reconciliations', title: 'Cash reconciliations', path: '/api/Poultry/cash-reconciliations', module: 'poultry'),
    PageSpec(key: 'poultry-cash-reconciliations-account-status', title: 'Account status', path: '/api/Poultry/cash-reconciliations/account-status', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-cash-transfers', title: 'Cash transfers', path: '/api/Poultry/cash-transfers', module: 'poultry'),
    PageSpec(key: 'poultry-closing-report', title: 'Closing report', path: '/api/Poultry/closing-report', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-company', title: 'Company', path: '/api/Poultry/company', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-customer-balances', title: 'Customer balances', path: '/api/Poultry/customer-balances', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-customer-balances-summary', title: 'Summary', path: '/api/Poultry/customer-balances/summary', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-customer-balances-open-sales', title: 'Open sales', path: '/api/Poultry/customer-balances/{customerId}/open-sales', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-customer-payments', title: 'Customer payments', path: '/api/Poultry/customer-payments', module: 'poultry'),
    PageSpec(key: 'poultry-customers-statement', title: 'Statement', path: '/api/Poultry/customers/{customerId}/statement', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-daily-closings', title: 'Daily closings', path: '/api/Poultry/daily-closings', module: 'poultry'),
    PageSpec(key: 'poultry-deferred-inventory-costs', title: 'Deferred inventory costs', path: '/api/Poultry/deferred-inventory-costs', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-deferred-inventory-costs-history', title: 'History', path: '/api/Poultry/deferred-inventory-costs/{purchaseId}/history', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-deliveries', title: 'Deliveries', path: '/api/Poultry/deliveries', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-driver-delivery-expenses', title: 'Driver delivery expenses', path: '/api/Poultry/driver-delivery-expenses', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-driver-returns', title: 'Driver returns', path: '/api/Poultry/driver-returns', module: 'poultry'),
    PageSpec(key: 'poultry-driver-returns-customer-sales', title: 'Customer sales', path: '/api/Poultry/driver-returns/{id}/customer-sales', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-driver-returns-expenses', title: 'Expenses', path: '/api/Poultry/driver-returns/{id}/expenses', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-driver-returns-items', title: 'Items', path: '/api/Poultry/driver-returns/{id}/items', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-driver-shortages', title: 'Driver shortages', path: '/api/Poultry/driver-shortages', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-drivers', title: 'Drivers', path: '/api/Poultry/drivers', module: 'poultry'),
    PageSpec(key: 'poultry-drivers-list-for-farm', title: 'List for farm', path: '/api/Poultry/drivers/list-for-farm', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-employee-loans', title: 'Employee loans', path: '/api/Poultry/employee-loans', module: 'poultry'),
    PageSpec(key: 'poultry-employee-loans-eligible', title: 'Eligible', path: '/api/Poultry/employee-loans/eligible', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-employee-loans-summary', title: 'Summary', path: '/api/Poultry/employee-loans/summary', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-employee-loans-repayments', title: 'Repayments', path: '/api/Poultry/employee-loans/{id}/repayments', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-feed-formulas', title: 'Feed formulas', path: '/api/Poultry/feed-formulas', module: 'poultry'),
    PageSpec(key: 'poultry-feed-production', title: 'Feed production', path: '/api/Poultry/feed-production', module: 'poultry'),
    PageSpec(key: 'poultry-feed-production-items', title: 'Items', path: '/api/Poultry/feed-production/items', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-feed-production-reports-ingredient-usage', title: 'Ingredient usage', path: '/api/Poultry/feed-production/reports/ingredient-usage', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-feed-production-traceability', title: 'Traceability', path: '/api/Poultry/feed-production/{id}/traceability', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-financial-activity', title: 'Financial activity', path: '/api/Poultry/financial-activity', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-financial-settings-cost-recognition', title: 'Cost recognition', path: '/api/Poultry/financial-settings/cost-recognition', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-internal-usage', title: 'Internal usage', path: '/api/Poultry/internal-usage', module: 'poultry'),
    PageSpec(key: 'poultry-internal-usage-suggested-cost', title: 'Suggested cost', path: '/api/Poultry/internal-usage/suggested-cost', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-inventory-valuation', title: 'Inventory valuation', path: '/api/Poultry/inventory-valuation', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-loan-payments', title: 'Loan payments', path: '/api/Poultry/loan-payments', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-loans', title: 'Loans', path: '/api/Poultry/loans', module: 'poultry'),
    PageSpec(key: 'poultry-loans-summary', title: 'Summary', path: '/api/Poultry/loans/summary', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-loans-repayments', title: 'Repayments', path: '/api/Poultry/loans/{id}/repayments', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-loss-records', title: 'Loss records', path: '/api/Poultry/loss-records', module: 'poultry'),
    PageSpec(key: 'poultry-owner-money', title: 'Owner money', path: '/api/Poultry/owner-money', module: 'poultry'),
    PageSpec(key: 'poultry-owner-money-summary', title: 'Summary', path: '/api/Poultry/owner-money/summary', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-payments', title: 'Payments', path: '/api/Poultry/payments', module: 'poultry'),
    PageSpec(key: 'poultry-payroll-deductions', title: 'Payroll deductions', path: '/api/Poultry/payroll-deductions', module: 'poultry'),
    PageSpec(key: 'poultry-payroll-runs', title: 'Payroll runs', path: '/api/Poultry/payroll-runs', module: 'poultry'),
    PageSpec(key: 'poultry-payroll-runs-details', title: 'Details', path: '/api/Poultry/payroll-runs/{id}/details', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-production-batches', title: 'Production batches', path: '/api/Poultry/production-batches', module: 'poultry'),
    PageSpec(key: 'poultry-production-batches-materials', title: 'Materials', path: '/api/Poultry/production-batches/{id}/materials', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-production-losses', title: 'Production losses', path: '/api/Poultry/production-losses', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-products', title: 'Products', path: '/api/Poultry/products', module: 'poultry'),
    PageSpec(key: 'poultry-products-reconcile-stock', title: 'Reconcile stock', path: '/api/Poultry/products/reconcile-stock', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-products-recipe', title: 'Recipe', path: '/api/Poultry/products/{id}/recipe', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-profit-loss', title: 'Profit loss', path: '/api/Poultry/profit-loss', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-profit-loss-capital-investments', title: 'Capital investments', path: '/api/Poultry/profit-loss/capital-investments', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-profit-loss-depreciation', title: 'Depreciation', path: '/api/Poultry/profit-loss/depreciation', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-profit-loss-expenses', title: 'Expenses', path: '/api/Poultry/profit-loss/expenses', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-profit-loss-financing', title: 'Financing', path: '/api/Poultry/profit-loss/financing', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-profit-loss-inventory', title: 'Inventory', path: '/api/Poultry/profit-loss/inventory', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-profit-loss-revenue', title: 'Revenue', path: '/api/Poultry/profit-loss/revenue', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-raw-material-adjustments', title: 'Raw material adjustments', path: '/api/Poultry/raw-material-adjustments', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-raw-material-items', title: 'Raw material items', path: '/api/Poultry/raw-material-items', module: 'poultry'),
    PageSpec(key: 'poultry-raw-material-items-low-stock', title: 'Low stock', path: '/api/Poultry/raw-material-items/low-stock', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-raw-material-purchases', title: 'Raw material purchases', path: '/api/Poultry/raw-material-purchases', module: 'poultry'),
    PageSpec(key: 'poultry-raw-material-usage-history', title: 'History', path: '/api/Poultry/raw-material-usage/history', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-reports-driver-collection', title: 'Driver collection', path: '/api/Poultry/reports/driver-collection', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-reports-driver-reconciliation', title: 'Driver reconciliation', path: '/api/Poultry/reports/driver-reconciliation', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-routes', title: 'Routes', path: '/api/Poultry/routes', module: 'poultry'),
    PageSpec(key: 'poultry-staff', title: 'Staff', path: '/api/Poultry/staff', module: 'poultry'),
    PageSpec(key: 'poultry-staff-attendance', title: 'Staff attendance', path: '/api/Poultry/staff-attendance', module: 'poultry'),
    PageSpec(key: 'poultry-stock-transactions', title: 'Transactions', path: '/api/Poultry/stock/transactions', module: 'poultry'),
    PageSpec(key: 'poultry-supplier-balances', title: 'Supplier balances', path: '/api/Poultry/supplier-balances', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-supplier-balances-summary', title: 'Summary', path: '/api/Poultry/supplier-balances/summary', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-supplier-balances-open-purchases', title: 'Open purchases', path: '/api/Poultry/supplier-balances/{supplierId}/open-purchases', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-supplier-payments', title: 'Supplier payments', path: '/api/Poultry/supplier-payments', module: 'poultry'),
    PageSpec(key: 'poultry-suppliers-statement', title: 'Statement', path: '/api/Poultry/suppliers/{supplierId}/statement', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-vehicle-loadings', title: 'Vehicle loadings', path: '/api/Poultry/vehicle-loadings', module: 'poultry'),
    PageSpec(key: 'poultry-vehicle-loadings-items', title: 'Items', path: '/api/Poultry/vehicle-loadings/{id}/items', module: 'poultry', readOnly: true),
    PageSpec(key: 'poultry-vehicles', title: 'Vehicles', path: '/api/Poultry/vehicles', module: 'poultry'),
    PageSpec(key: 'productionbatchrecord', title: 'Production Batch Record', path: '/api/ProductionBatchRecord', needsUserId: true),
    PageSpec(key: 'productionrecord', title: 'Production Record', path: '/api/ProductionRecord', needsUserId: true),
    PageSpec(key: 'restaurant-crm-campaigns', title: 'Campaigns', path: '/api/Restaurant/crm/campaigns', module: 'restaurant'),
    PageSpec(key: 'restaurant-crm-customers', title: 'Customers', path: '/api/Restaurant/crm/customers', module: 'restaurant'),
    PageSpec(key: 'restaurant-crm-customers-stats', title: 'Stats', path: '/api/Restaurant/crm/customers/stats', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-crm-feedback', title: 'Feedback', path: '/api/Restaurant/crm/feedback', module: 'restaurant'),
    PageSpec(key: 'restaurant-crm-feedback-stats', title: 'Stats', path: '/api/Restaurant/crm/feedback/stats', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-custom-options', title: 'Custom options', path: '/api/Restaurant/custom-options', module: 'restaurant'),
    PageSpec(key: 'restaurant-delivery-assignments', title: 'Assignments', path: '/api/Restaurant/delivery/assignments', module: 'restaurant'),
    PageSpec(key: 'restaurant-delivery-drivers', title: 'Drivers', path: '/api/Restaurant/delivery/drivers', module: 'restaurant'),
    PageSpec(key: 'restaurant-delivery-drivers-stats', title: 'Stats', path: '/api/Restaurant/delivery/drivers/{id}/stats', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-delivery-platforms', title: 'Platforms', path: '/api/Restaurant/delivery/platforms', module: 'restaurant'),
    PageSpec(key: 'restaurant-delivery-stats', title: 'Stats', path: '/api/Restaurant/delivery/stats', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-delivery-third-party-orders', title: 'Third party orders', path: '/api/Restaurant/delivery/third-party-orders', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-delivery-zones', title: 'Zones', path: '/api/Restaurant/delivery/zones', module: 'restaurant'),
    PageSpec(key: 'restaurant-events', title: 'Events', path: '/api/Restaurant/events', module: 'restaurant'),
    PageSpec(key: 'restaurant-expenses', title: 'Expenses', path: '/api/Restaurant/expenses', module: 'restaurant'),
    PageSpec(key: 'restaurant-expenses-categories', title: 'Categories', path: '/api/Restaurant/expenses/categories', module: 'restaurant'),
    PageSpec(key: 'restaurant-expenses-receipt-template', title: 'Receipt template', path: '/api/Restaurant/expenses/receipt-template', module: 'restaurant'),
    PageSpec(key: 'restaurant-floor-floors', title: 'Floors', path: '/api/Restaurant/floor/floors', module: 'restaurant'),
    PageSpec(key: 'restaurant-floor-tables', title: 'Tables', path: '/api/Restaurant/floor/tables', module: 'restaurant'),
    PageSpec(key: 'restaurant-gift-cards', title: 'Gift cards', path: '/api/Restaurant/gift-cards', module: 'restaurant'),
    PageSpec(key: 'restaurant-gift-cards-stats', title: 'Stats', path: '/api/Restaurant/gift-cards/stats', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-gift-cards-transactions', title: 'Transactions', path: '/api/Restaurant/gift-cards/{id}/transactions', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-inventory-ingredients', title: 'Ingredients', path: '/api/Restaurant/inventory/ingredients', module: 'restaurant'),
    PageSpec(key: 'restaurant-inventory-low-stock', title: 'Low stock', path: '/api/Restaurant/inventory/low-stock', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-inventory-stock-takes', title: 'Stock takes', path: '/api/Restaurant/inventory/stock-takes', module: 'restaurant'),
    PageSpec(key: 'restaurant-inventory-stock-takes-items', title: 'Items', path: '/api/Restaurant/inventory/stock-takes/{id}/items', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-inventory-value', title: 'Value', path: '/api/Restaurant/inventory/value', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-inventory-waste', title: 'Waste', path: '/api/Restaurant/inventory/waste', module: 'restaurant'),
    PageSpec(key: 'restaurant-inventory-waste-summary', title: 'Summary', path: '/api/Restaurant/inventory/waste/summary', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-kds-queue', title: 'Queue', path: '/api/Restaurant/kds/queue', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-kds-stations', title: 'Stations', path: '/api/Restaurant/kds/stations', module: 'restaurant'),
    PageSpec(key: 'restaurant-kds-stations-items', title: 'Items', path: '/api/Restaurant/kds/stations/{stationId}/items', module: 'restaurant'),
    PageSpec(key: 'restaurant-kds-stats', title: 'Stats', path: '/api/Restaurant/kds/stats', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-loyalty-accounts', title: 'Accounts', path: '/api/Restaurant/loyalty/accounts', module: 'restaurant'),
    PageSpec(key: 'restaurant-loyalty-accounts-transactions', title: 'Transactions', path: '/api/Restaurant/loyalty/accounts/{id}/transactions', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-loyalty-settings', title: 'Settings', path: '/api/Restaurant/loyalty/settings', module: 'restaurant'),
    PageSpec(key: 'restaurant-loyalty-stats', title: 'Stats', path: '/api/Restaurant/loyalty/stats', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-menu-categories', title: 'Categories', path: '/api/Restaurant/menu/categories', module: 'restaurant'),
    PageSpec(key: 'restaurant-menu-combos', title: 'Combos', path: '/api/Restaurant/menu/combos', module: 'restaurant'),
    PageSpec(key: 'restaurant-menu-combos-items', title: 'Items', path: '/api/Restaurant/menu/combos/{comboId}/items', module: 'restaurant'),
    PageSpec(key: 'restaurant-menu-item-names', title: 'Item names', path: '/api/Restaurant/menu/item-names', module: 'restaurant'),
    PageSpec(key: 'restaurant-menu-items', title: 'Items', path: '/api/Restaurant/menu/items', module: 'restaurant'),
    PageSpec(key: 'restaurant-menu-items-modifier-groups', title: 'Modifier groups', path: '/api/Restaurant/menu/items/{menuItemId}/modifier-groups', module: 'restaurant'),
    PageSpec(key: 'restaurant-menu-items-tags', title: 'Tags', path: '/api/Restaurant/menu/items/{menuItemId}/tags', module: 'restaurant'),
    PageSpec(key: 'restaurant-menu-modifier-groups', title: 'Modifier groups', path: '/api/Restaurant/menu/modifier-groups', module: 'restaurant'),
    PageSpec(key: 'restaurant-menu-modifiers', title: 'Modifiers', path: '/api/Restaurant/menu/modifiers', module: 'restaurant'),
    PageSpec(key: 'restaurant-menu-schedules', title: 'Schedules', path: '/api/Restaurant/menu/schedules', module: 'restaurant'),
    PageSpec(key: 'restaurant-menu-schedules-items', title: 'Items', path: '/api/Restaurant/menu/schedules/{scheduleId}/items', module: 'restaurant'),
    PageSpec(key: 'restaurant-notifications', title: 'Notifications', path: '/api/Restaurant/notifications', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-notifications-settings', title: 'Settings', path: '/api/Restaurant/notifications/settings', module: 'restaurant'),
    PageSpec(key: 'restaurant-online-delivery-addresses', title: 'Delivery addresses', path: '/api/Restaurant/online/delivery-addresses', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-online-pending-orders', title: 'Pending orders', path: '/api/Restaurant/online/pending-orders', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-online-promo-codes', title: 'Promo codes', path: '/api/Restaurant/online/promo-codes', module: 'restaurant'),
    PageSpec(key: 'restaurant-online-qr-codes', title: 'Qr codes', path: '/api/Restaurant/online/qr-codes', module: 'restaurant'),
    PageSpec(key: 'restaurant-online-settings', title: 'Settings', path: '/api/Restaurant/online/settings', module: 'restaurant'),
    PageSpec(key: 'restaurant-online-throttle-check', title: 'Throttle check', path: '/api/Restaurant/online/throttle-check', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-orders', title: 'Orders', path: '/api/Restaurant/orders', module: 'restaurant'),
    PageSpec(key: 'restaurant-orders-discounts', title: 'Discounts', path: '/api/Restaurant/orders/discounts', module: 'restaurant'),
    PageSpec(key: 'restaurant-orders-items-modifiers', title: 'Modifiers', path: '/api/Restaurant/orders/items/{orderItemId}/modifiers', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-orders-items', title: 'Items', path: '/api/Restaurant/orders/{orderId}/items', module: 'restaurant'),
    PageSpec(key: 'restaurant-orders-payments', title: 'Payments', path: '/api/Restaurant/orders/{orderId}/payments', module: 'restaurant'),
    PageSpec(key: 'restaurant-public-categories', title: 'Categories', path: '/api/Restaurant/public/{farmId}/categories', module: 'restaurant', needsFarmId: false, readOnly: true),
    PageSpec(key: 'restaurant-public-delivery-addresses', title: 'Delivery addresses', path: '/api/Restaurant/public/{farmId}/delivery-addresses', module: 'restaurant', needsFarmId: false, readOnly: true),
    PageSpec(key: 'restaurant-public-menu', title: 'Menu', path: '/api/Restaurant/public/{farmId}/menu', module: 'restaurant', needsFarmId: false, readOnly: true),
    PageSpec(key: 'restaurant-public-profile', title: 'Profile', path: '/api/Restaurant/public/{farmId}/profile', module: 'restaurant', needsFarmId: false, readOnly: true),
    PageSpec(key: 'restaurant-public-settings', title: 'Settings', path: '/api/Restaurant/public/{farmId}/settings', module: 'restaurant', needsFarmId: false, readOnly: true),
    PageSpec(key: 'restaurant-reports-channel', title: 'Channel', path: '/api/Restaurant/reports/channel', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-customer-retention', title: 'Customer retention', path: '/api/Restaurant/reports/customer-retention', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-daily-sales', title: 'Daily sales', path: '/api/Restaurant/reports/daily-sales', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-delivery-performance', title: 'Delivery performance', path: '/api/Restaurant/reports/delivery-performance', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-discounts', title: 'Discounts', path: '/api/Restaurant/reports/discounts', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-events', title: 'Events', path: '/api/Restaurant/reports/events', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-expenses', title: 'Expenses', path: '/api/Restaurant/reports/expenses', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-feedback', title: 'Feedback', path: '/api/Restaurant/reports/feedback', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-food-cost', title: 'Food cost', path: '/api/Restaurant/reports/food-cost', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-kitchen-performance', title: 'Kitchen performance', path: '/api/Restaurant/reports/kitchen-performance', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-kpi-alerts', title: 'Kpi alerts', path: '/api/Restaurant/reports/kpi-alerts', module: 'restaurant'),
    PageSpec(key: 'restaurant-reports-menu-engineering', title: 'Menu engineering', path: '/api/Restaurant/reports/menu-engineering', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-payment-methods', title: 'Payment methods', path: '/api/Restaurant/reports/payment-methods', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-pnl', title: 'Pnl', path: '/api/Restaurant/reports/pnl', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-pnl-expenses', title: 'Pnl expenses', path: '/api/Restaurant/reports/pnl-expenses', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-revenue-trend', title: 'Revenue trend', path: '/api/Restaurant/reports/revenue-trend', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-sales-by-category', title: 'Sales by category', path: '/api/Restaurant/reports/sales-by-category', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-sales-by-hour', title: 'Sales by hour', path: '/api/Restaurant/reports/sales-by-hour', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-sales-by-item', title: 'Sales by item', path: '/api/Restaurant/reports/sales-by-item', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-sales-summary', title: 'Sales summary', path: '/api/Restaurant/reports/sales-summary', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-server-performance', title: 'Server performance', path: '/api/Restaurant/reports/server-performance', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-stock-on-hand', title: 'Stock on hand', path: '/api/Restaurant/reports/stock-on-hand', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-table-turnover', title: 'Table turnover', path: '/api/Restaurant/reports/table-turnover', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-tips', title: 'Tips', path: '/api/Restaurant/reports/tips', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-voids', title: 'Voids', path: '/api/Restaurant/reports/voids', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reports-waste-detail', title: 'Waste detail', path: '/api/Restaurant/reports/waste-detail', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reservations', title: 'Reservations', path: '/api/Restaurant/reservations', module: 'restaurant'),
    PageSpec(key: 'restaurant-reservations-auto-assign-table', title: 'Auto assign table', path: '/api/Restaurant/reservations/auto-assign-table', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reservations-settings', title: 'Settings', path: '/api/Restaurant/reservations/settings', module: 'restaurant'),
    PageSpec(key: 'restaurant-reservations-stats', title: 'Stats', path: '/api/Restaurant/reservations/stats', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-reservations-waitlist', title: 'Waitlist', path: '/api/Restaurant/reservations/waitlist', module: 'restaurant'),
    PageSpec(key: 'restaurant-reservations-waitlist-stats', title: 'Stats', path: '/api/Restaurant/reservations/waitlist/stats', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-setup-profile', title: 'Profile', path: '/api/Restaurant/setup/profile', module: 'restaurant'),
    PageSpec(key: 'restaurant-setup-suppliers', title: 'Suppliers', path: '/api/Restaurant/setup/suppliers', module: 'restaurant'),
    PageSpec(key: 'restaurant-staff', title: 'Staff', path: '/api/Restaurant/staff', module: 'restaurant'),
    PageSpec(key: 'sale', title: 'Sale', path: '/api/Sale', needsUserId: true),
    PageSpec(key: 'supplier', title: 'Supplier', path: '/api/Supplier', needsUserId: true),
    PageSpec(key: 'test-health', title: 'Health', path: '/api/Test/health', needsFarmId: false, readOnly: true),
    PageSpec(key: 'test-ping', title: 'Ping', path: '/api/Test/ping', needsFarmId: false, readOnly: true),
    PageSpec(key: 'water-asset-depreciation', title: 'Asset depreciation', path: '/api/Water/asset-depreciation', module: 'water', readOnly: true),
    PageSpec(key: 'water-asset-depreciation-due', title: 'Due', path: '/api/Water/asset-depreciation/due', module: 'water', readOnly: true),
    PageSpec(key: 'water-assets', title: 'Assets', path: '/api/Water/assets', module: 'water'),
    PageSpec(key: 'water-assets-categories', title: 'Categories', path: '/api/Water/assets/categories', module: 'water'),
    PageSpec(key: 'water-assets-summary', title: 'Summary', path: '/api/Water/assets/summary', module: 'water', readOnly: true),
    PageSpec(key: 'water-balances-audit', title: 'Audit', path: '/api/Water/balances/audit', module: 'water', readOnly: true),
    PageSpec(key: 'water-boreholes', title: 'Boreholes', path: '/api/Water/boreholes', module: 'water'),
    PageSpec(key: 'water-cash-accounts', title: 'Cash accounts', path: '/api/Water/cash-accounts', module: 'water'),
    PageSpec(key: 'water-cash-accounts-transactions', title: 'Transactions', path: '/api/Water/cash-accounts/transactions', module: 'water', readOnly: true),
    PageSpec(key: 'water-cash-flow', title: 'Cash flow', path: '/api/Water/cash-flow', module: 'water', readOnly: true),
    PageSpec(key: 'water-cash-reconciliations', title: 'Cash reconciliations', path: '/api/Water/cash-reconciliations', module: 'water'),
    PageSpec(key: 'water-cash-reconciliations-account-status', title: 'Account status', path: '/api/Water/cash-reconciliations/account-status', module: 'water', readOnly: true),
    PageSpec(key: 'water-cash-transfers', title: 'Cash transfers', path: '/api/Water/cash-transfers', module: 'water'),
    PageSpec(key: 'water-company', title: 'Company', path: '/api/Water/company', module: 'water', readOnly: true),
    PageSpec(key: 'water-customer-balances', title: 'Customer balances', path: '/api/Water/customer-balances', module: 'water', readOnly: true),
    PageSpec(key: 'water-customer-balances-summary', title: 'Summary', path: '/api/Water/customer-balances/summary', module: 'water', readOnly: true),
    PageSpec(key: 'water-customer-balances-open-sales', title: 'Open sales', path: '/api/Water/customer-balances/{customerId}/open-sales', module: 'water', readOnly: true),
    PageSpec(key: 'water-customer-payments', title: 'Customer payments', path: '/api/Water/customer-payments', module: 'water'),
    PageSpec(key: 'water-customers', title: 'Customers', path: '/api/Water/customers', module: 'water'),
    PageSpec(key: 'water-customers-ledger', title: 'Ledger', path: '/api/Water/customers/{customerId}/ledger', module: 'water'),
    PageSpec(key: 'water-customers-statement', title: 'Statement', path: '/api/Water/customers/{customerId}/statement', module: 'water', readOnly: true),
    PageSpec(key: 'water-daily-closings', title: 'Daily closings', path: '/api/Water/daily-closings', module: 'water'),
    PageSpec(key: 'water-daily-productions', title: 'Daily productions', path: '/api/Water/daily-productions', module: 'water'),
    PageSpec(key: 'water-dashboard-summary', title: 'Summary', path: '/api/Water/dashboard/summary', module: 'water', readOnly: true),
    PageSpec(key: 'water-deferred-inventory-costs', title: 'Deferred inventory costs', path: '/api/Water/deferred-inventory-costs', module: 'water', readOnly: true),
    PageSpec(key: 'water-deferred-inventory-costs-history', title: 'History', path: '/api/Water/deferred-inventory-costs/{purchaseId}/history', module: 'water', readOnly: true),
    PageSpec(key: 'water-delivery-expenses', title: 'Delivery expenses', path: '/api/Water/delivery-expenses', module: 'water', readOnly: true),
    PageSpec(key: 'water-driver-returns', title: 'Driver returns', path: '/api/Water/driver-returns', module: 'water'),
    PageSpec(key: 'water-driver-returns-customer-sales', title: 'Customer sales', path: '/api/Water/driver-returns/{id}/customer-sales', module: 'water', readOnly: true),
    PageSpec(key: 'water-driver-returns-expenses', title: 'Expenses', path: '/api/Water/driver-returns/{id}/expenses', module: 'water', readOnly: true),
    PageSpec(key: 'water-driver-returns-items', title: 'Items', path: '/api/Water/driver-returns/{id}/items', module: 'water', readOnly: true),
    PageSpec(key: 'water-driver-shortages', title: 'Driver shortages', path: '/api/Water/driver-shortages', module: 'water', readOnly: true),
    PageSpec(key: 'water-drivers', title: 'Drivers', path: '/api/Water/drivers', module: 'water'),
    PageSpec(key: 'water-drivers-job-roles', title: 'Job roles', path: '/api/Water/drivers/job-roles', module: 'water'),
    PageSpec(key: 'water-drivers-list-for-farm', title: 'List for farm', path: '/api/Water/drivers/list-for-farm', module: 'water', readOnly: true),
    PageSpec(key: 'water-expense-categories', title: 'Expense categories', path: '/api/Water/expense-categories', module: 'water'),
    PageSpec(key: 'water-expenses', title: 'Expenses', path: '/api/Water/expenses', module: 'water'),
    PageSpec(key: 'water-farm-settings', title: 'Farm settings', path: '/api/Water/farm-settings', module: 'water', readOnly: true),
    PageSpec(key: 'water-financial-settings-cost-recognition', title: 'Cost recognition', path: '/api/Water/financial-settings/cost-recognition', module: 'water', readOnly: true),
    PageSpec(key: 'water-financial-settings-items', title: 'Items', path: '/api/Water/financial-settings/items', module: 'water', readOnly: true),
    PageSpec(key: 'water-internal-usage', title: 'Internal usage', path: '/api/Water/internal-usage', module: 'water'),
    PageSpec(key: 'water-internal-usage-suggested-cost', title: 'Suggested cost', path: '/api/Water/internal-usage/suggested-cost', module: 'water', readOnly: true),
    PageSpec(key: 'water-loan-payments', title: 'Loan payments', path: '/api/Water/loan-payments', module: 'water', readOnly: true),
    PageSpec(key: 'water-loans', title: 'Loans', path: '/api/Water/loans', module: 'water'),
    PageSpec(key: 'water-loans-summary', title: 'Summary', path: '/api/Water/loans/summary', module: 'water', readOnly: true),
    PageSpec(key: 'water-loans-repayments', title: 'Repayments', path: '/api/Water/loans/{id}/repayments', module: 'water', readOnly: true),
    PageSpec(key: 'water-loss-records', title: 'Loss records', path: '/api/Water/loss-records', module: 'water'),
    PageSpec(key: 'water-machines', title: 'Machines', path: '/api/Water/machines', module: 'water'),
    PageSpec(key: 'water-maintenance-logs', title: 'Maintenance logs', path: '/api/Water/maintenance-logs', module: 'water'),
    PageSpec(key: 'water-maintenance-logs-due-alerts', title: 'Due alerts', path: '/api/Water/maintenance-logs/due-alerts', module: 'water', readOnly: true),
    PageSpec(key: 'water-owner-money', title: 'Owner money', path: '/api/Water/owner-money', module: 'water'),
    PageSpec(key: 'water-owner-money-summary', title: 'Summary', path: '/api/Water/owner-money/summary', module: 'water', readOnly: true),
    PageSpec(key: 'water-payments', title: 'Payments', path: '/api/Water/payments', module: 'water'),
    PageSpec(key: 'water-payroll-runs', title: 'Payroll runs', path: '/api/Water/payroll-runs', module: 'water'),
    PageSpec(key: 'water-payroll-runs-details', title: 'Details', path: '/api/Water/payroll-runs/{id}/details', module: 'water', readOnly: true),
    PageSpec(key: 'water-production-batches', title: 'Production batches', path: '/api/Water/production-batches', module: 'water'),
    PageSpec(key: 'water-production-batches-linked-expenses', title: 'Linked expenses', path: '/api/Water/production-batches/{id}/linked-expenses', module: 'water', readOnly: true),
    PageSpec(key: 'water-production-batches-linked-losses', title: 'Linked losses', path: '/api/Water/production-batches/{id}/linked-losses', module: 'water', readOnly: true),
    PageSpec(key: 'water-production-batches-linked-stock-txns', title: 'Linked stock txns', path: '/api/Water/production-batches/{id}/linked-stock-txns', module: 'water', readOnly: true),
    PageSpec(key: 'water-production-batches-materials', title: 'Materials', path: '/api/Water/production-batches/{id}/materials', module: 'water', readOnly: true),
    PageSpec(key: 'water-production-losses', title: 'Production losses', path: '/api/Water/production-losses', module: 'water', readOnly: true),
    PageSpec(key: 'water-products', title: 'Products', path: '/api/Water/products', module: 'water'),
    PageSpec(key: 'water-products-reconcile-stock', title: 'Reconcile stock', path: '/api/Water/products/reconcile-stock', module: 'water', readOnly: true),
    PageSpec(key: 'water-products-recipe', title: 'Recipe', path: '/api/Water/products/{productId}/recipe', module: 'water', readOnly: true),
    PageSpec(key: 'water-pumping-logs', title: 'Pumping logs', path: '/api/Water/pumping-logs', module: 'water'),
    PageSpec(key: 'water-quality-tests', title: 'Quality tests', path: '/api/Water/quality-tests', module: 'water'),
    PageSpec(key: 'water-raw-material-adjustments', title: 'Raw material adjustments', path: '/api/Water/raw-material-adjustments', module: 'water', readOnly: true),
    PageSpec(key: 'water-raw-material-items', title: 'Raw material items', path: '/api/Water/raw-material-items', module: 'water'),
    PageSpec(key: 'water-raw-material-items-low-stock', title: 'Low stock', path: '/api/Water/raw-material-items/low-stock', module: 'water', readOnly: true),
    PageSpec(key: 'water-raw-material-items-open-lots', title: 'Open lots', path: '/api/Water/raw-material-items/open-lots', module: 'water', readOnly: true),
    PageSpec(key: 'water-raw-material-purchases', title: 'Raw material purchases', path: '/api/Water/raw-material-purchases', module: 'water'),
    PageSpec(key: 'water-raw-material-usage', title: 'Raw material usage', path: '/api/Water/raw-material-usage', module: 'water'),
    PageSpec(key: 'water-raw-material-usage-history', title: 'History', path: '/api/Water/raw-material-usage/history', module: 'water', readOnly: true),
    PageSpec(key: 'water-reports-dashboard-extended', title: 'Dashboard extended', path: '/api/Water/reports/dashboard-extended', module: 'water', readOnly: true),
    PageSpec(key: 'water-reports-driver-collection', title: 'Driver collection', path: '/api/Water/reports/driver-collection', module: 'water', readOnly: true),
    PageSpec(key: 'water-reports-driver-reconciliation', title: 'Driver reconciliation', path: '/api/Water/reports/driver-reconciliation', module: 'water', readOnly: true),
    PageSpec(key: 'water-reports-expense-by-category', title: 'Expense by category', path: '/api/Water/reports/expense-by-category', module: 'water', readOnly: true),
    PageSpec(key: 'water-reports-inventory-tracker', title: 'Inventory tracker', path: '/api/Water/reports/inventory-tracker', module: 'water', readOnly: true),
    PageSpec(key: 'water-reports-inventory-tracker-movements', title: 'Movements', path: '/api/Water/reports/inventory-tracker/movements', module: 'water', readOnly: true),
    PageSpec(key: 'water-reports-period-pnl', title: 'Period pnl', path: '/api/Water/reports/period-pnl', module: 'water', readOnly: true),
    PageSpec(key: 'water-reports-raw-material-variance', title: 'Raw material variance', path: '/api/Water/reports/raw-material-variance', module: 'water', readOnly: true),
    PageSpec(key: 'water-reports-route-profitability', title: 'Route profitability', path: '/api/Water/reports/route-profitability', module: 'water', readOnly: true),
    PageSpec(key: 'water-reports-supplier-activity', title: 'Supplier activity', path: '/api/Water/reports/supplier-activity', module: 'water', readOnly: true),
    PageSpec(key: 'water-reports-top-customers', title: 'Top customers', path: '/api/Water/reports/top-customers', module: 'water', readOnly: true),
    PageSpec(key: 'water-routes', title: 'Routes', path: '/api/Water/routes', module: 'water'),
    PageSpec(key: 'water-sales', title: 'Sales', path: '/api/Water/sales', module: 'water'),
    PageSpec(key: 'water-staff', title: 'Staff', path: '/api/Water/staff', module: 'water'),
    PageSpec(key: 'water-staff-attendance', title: 'Staff attendance', path: '/api/Water/staff-attendance', module: 'water'),
    PageSpec(key: 'water-stock-transactions', title: 'Transactions', path: '/api/Water/stock/transactions', module: 'water'),
    PageSpec(key: 'water-supplier-balances', title: 'Supplier balances', path: '/api/Water/supplier-balances', module: 'water', readOnly: true),
    PageSpec(key: 'water-supplier-balances-summary', title: 'Summary', path: '/api/Water/supplier-balances/summary', module: 'water', readOnly: true),
    PageSpec(key: 'water-supplier-balances-open-purchases', title: 'Open purchases', path: '/api/Water/supplier-balances/{supplierId}/open-purchases', module: 'water', readOnly: true),
    PageSpec(key: 'water-supplier-payments', title: 'Supplier payments', path: '/api/Water/supplier-payments', module: 'water'),
    PageSpec(key: 'water-suppliers', title: 'Suppliers', path: '/api/Water/suppliers', module: 'water'),
    PageSpec(key: 'water-suppliers-statement', title: 'Statement', path: '/api/Water/suppliers/{supplierId}/statement', module: 'water', readOnly: true),
    PageSpec(key: 'water-vehicle-loadings', title: 'Vehicle loadings', path: '/api/Water/vehicle-loadings', module: 'water'),
    PageSpec(key: 'water-vehicle-loadings-items', title: 'Items', path: '/api/Water/vehicle-loadings/{id}/items', module: 'water', readOnly: true),
    PageSpec(key: 'water-vehicles', title: 'Vehicles', path: '/api/Water/vehicles', module: 'water'),
    PageSpec(key: 'business-categories', title: 'Business categories', path: '/api/business-categories', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-internal-usage', title: 'Internal usage', path: '/api/generic-company/internal-usage', module: 'generic'),
    PageSpec(key: 'generic-internal-usage-suggested-cost', title: 'Suggested cost', path: '/api/generic-company/internal-usage/suggested-cost', module: 'generic', readOnly: true),
    PageSpec(key: 'generic-balances-audit', title: 'Audit', path: '/api/generic-company/{farmId}/balances/audit', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-balances-customer-balances', title: 'Customer balances', path: '/api/generic-company/{farmId}/balances/customer-balances', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-balances-customer-balances-summary', title: 'Summary', path: '/api/generic-company/{farmId}/balances/customer-balances/summary', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-balances-customer-balances-open-sales', title: 'Open sales', path: '/api/generic-company/{farmId}/balances/customer-balances/{customerId}/open-sales', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-balances-customer-payments', title: 'Customer payments', path: '/api/generic-company/{farmId}/balances/customer-payments', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-balances-customers-statement', title: 'Statement', path: '/api/generic-company/{farmId}/balances/customers/{customerId}/statement', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-balances-supplier-balances', title: 'Supplier balances', path: '/api/generic-company/{farmId}/balances/supplier-balances', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-balances-supplier-balances-summary', title: 'Summary', path: '/api/generic-company/{farmId}/balances/supplier-balances/summary', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-balances-supplier-balances-open-purchases', title: 'Open purchases', path: '/api/generic-company/{farmId}/balances/supplier-balances/{supplierId}/open-purchases', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-balances-supplier-payments', title: 'Supplier payments', path: '/api/generic-company/{farmId}/balances/supplier-payments', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-balances-suppliers-statement', title: 'Statement', path: '/api/generic-company/{farmId}/balances/suppliers/{supplierId}/statement', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-billing-runs', title: 'Billing runs', path: '/api/generic-company/{farmId}/billing-runs', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-billing-runs-preview', title: 'Preview', path: '/api/generic-company/{farmId}/billing-runs/preview', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-business-settings', title: 'Business settings', path: '/api/generic-company/{farmId}/business-settings', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-business-template', title: 'Business template', path: '/api/generic-company/{farmId}/business-template', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-cash-accounts', title: 'Cash accounts', path: '/api/generic-company/{farmId}/cash-accounts', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-cash-transfers', title: 'Cash transfers', path: '/api/generic-company/{farmId}/cash-transfers', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-cash-accounts-details', title: 'Details', path: '/api/generic-company/{farmId}/cash/accounts/{accountId}/details', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-cash-accounts-reconciliations', title: 'Reconciliations', path: '/api/generic-company/{farmId}/cash/accounts/{accountId}/reconciliations', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-cash-accounts-transactions', title: 'Transactions', path: '/api/generic-company/{farmId}/cash/accounts/{accountId}/transactions', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-cash-defaults', title: 'Defaults', path: '/api/generic-company/{farmId}/cash/defaults', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-cash-ledger-report', title: 'Ledger report', path: '/api/generic-company/{farmId}/cash/ledger-report', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-cash-transactions', title: 'Transactions', path: '/api/generic-company/{farmId}/cash/transactions', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-customer-payments', title: 'Customer payments', path: '/api/generic-company/{farmId}/customer-payments', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-customer-types', title: 'Customer types', path: '/api/generic-company/{farmId}/customer-types', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-customers', title: 'Customers', path: '/api/generic-company/{farmId}/customers', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-customers-owing', title: 'Owing', path: '/api/generic-company/{farmId}/customers/owing', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-customers-ledger', title: 'Ledger', path: '/api/generic-company/{farmId}/customers/{id}/ledger', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-daily-closings', title: 'Daily closings', path: '/api/generic-company/{farmId}/daily-closings', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-expense-categories', title: 'Expense categories', path: '/api/generic-company/{farmId}/expense-categories', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-expenses', title: 'Expenses', path: '/api/generic-company/{farmId}/expenses', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-inventory-adjustments', title: 'Adjustments', path: '/api/generic-company/{farmId}/inventory/adjustments', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-inventory-movements', title: 'Movements', path: '/api/generic-company/{farmId}/inventory/movements', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-inventory-products-movements', title: 'Movements', path: '/api/generic-company/{farmId}/inventory/products/{productId}/movements', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-invoices', title: 'Invoices', path: '/api/generic-company/{farmId}/invoices', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-module-settings', title: 'Module settings', path: '/api/generic-company/{farmId}/module-settings', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-owner-entries', title: 'Owner entries', path: '/api/generic-company/{farmId}/owner-entries', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-payment-methods', title: 'Payment methods', path: '/api/generic-company/{farmId}/payment-methods', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-payroll-runs', title: 'Payroll runs', path: '/api/generic-company/{farmId}/payroll-runs', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-product-categories', title: 'Product categories', path: '/api/generic-company/{farmId}/product-categories', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-products', title: 'Products', path: '/api/generic-company/{farmId}/products', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-products-low-stock', title: 'Low stock', path: '/api/generic-company/{farmId}/products/low-stock', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-purchases', title: 'Purchases', path: '/api/generic-company/{farmId}/purchases', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-recurring-expenses', title: 'Recurring expenses', path: '/api/generic-company/{farmId}/recurring-expenses', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-recurring-expenses-preview', title: 'Preview', path: '/api/generic-company/{farmId}/recurring-expenses/preview', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-break-even', title: 'Break even', path: '/api/generic-company/{farmId}/reports/break-even', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-cash-summary', title: 'Cash summary', path: '/api/generic-company/{farmId}/reports/cash-summary', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-dashboard', title: 'Dashboard', path: '/api/generic-company/{farmId}/reports/dashboard', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-expense-report', title: 'Expense report', path: '/api/generic-company/{farmId}/reports/expense-report', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-expenses-by-category', title: 'Expenses by category', path: '/api/generic-company/{farmId}/reports/expenses-by-category', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-hosting-cost', title: 'Hosting cost', path: '/api/generic-company/{farmId}/reports/hosting-cost', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-income-split', title: 'Income split', path: '/api/generic-company/{farmId}/reports/income-split', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-inventory-value', title: 'Inventory value', path: '/api/generic-company/{farmId}/reports/inventory-value', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-mrr', title: 'Mrr', path: '/api/generic-company/{farmId}/reports/mrr', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-period-pnl', title: 'Period pnl', path: '/api/generic-company/{farmId}/reports/period-pnl', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-sales-by-customer', title: 'Sales by customer', path: '/api/generic-company/{farmId}/reports/sales-by-customer', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-sales-by-product', title: 'Sales by product', path: '/api/generic-company/{farmId}/reports/sales-by-product', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-staff-cost', title: 'Staff cost', path: '/api/generic-company/{farmId}/reports/staff-cost', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-subscription-dashboard', title: 'Subscription dashboard', path: '/api/generic-company/{farmId}/reports/subscription-dashboard', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-reports-subscription-revenue', title: 'Subscription revenue', path: '/api/generic-company/{farmId}/reports/subscription-revenue', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-sales', title: 'Sales', path: '/api/generic-company/{farmId}/sales', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-service-categories', title: 'Service categories', path: '/api/generic-company/{farmId}/service-categories', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-service-plans', title: 'Service plans', path: '/api/generic-company/{farmId}/service-plans', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-services', title: 'Services', path: '/api/generic-company/{farmId}/services', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-staff', title: 'Staff', path: '/api/generic-company/{farmId}/staff', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-staff-attendance', title: 'Staff attendance', path: '/api/generic-company/{farmId}/staff-attendance', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-staff-payments', title: 'Staff payments', path: '/api/generic-company/{farmId}/staff-payments', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-subscriptions', title: 'Subscriptions', path: '/api/generic-company/{farmId}/subscriptions', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-supplier-payments', title: 'Supplier payments', path: '/api/generic-company/{farmId}/supplier-payments', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-supplier-types', title: 'Supplier types', path: '/api/generic-company/{farmId}/supplier-types', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-suppliers', title: 'Suppliers', path: '/api/generic-company/{farmId}/suppliers', module: 'generic', needsFarmId: false),
    PageSpec(key: 'generic-suppliers-owed', title: 'Owed', path: '/api/generic-company/{farmId}/suppliers/owed', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'generic-suppliers-ledger', title: 'Ledger', path: '/api/generic-company/{farmId}/suppliers/{id}/ledger', module: 'generic', needsFarmId: false, readOnly: true),
    PageSpec(key: 'poultry-reports-birds-on-hand', title: 'Birds on hand', path: '/api/poultry/reports/birds-on-hand', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-cash-flow-detail', title: 'Cash flow detail', path: '/api/poultry/reports/cash-flow-detail', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-cash-movement', title: 'Cash movement', path: '/api/poultry/reports/cash-movement', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-cost-per-egg', title: 'Cost per egg', path: '/api/poultry/reports/cost-per-egg', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-customer-balance', title: 'Customer balance', path: '/api/poultry/reports/customer-balance', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-daily-egg-production', title: 'Daily egg production', path: '/api/poultry/reports/daily-egg-production', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-egg-sales', title: 'Egg sales', path: '/api/poultry/reports/egg-sales', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-egg-stock-balance', title: 'Egg stock balance', path: '/api/poultry/reports/egg-stock-balance', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-end-of-flock', title: 'End of flock', path: '/api/poultry/reports/end-of-flock', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-expense-summary', title: 'Expense summary', path: '/api/poultry/reports/expense-summary', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-farm-summary', title: 'Farm summary', path: '/api/poultry/reports/farm-summary', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-feed-cost-per-egg', title: 'Feed cost per egg', path: '/api/poultry/reports/feed-cost-per-egg', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-feed-inventory-balance', title: 'Feed inventory balance', path: '/api/poultry/reports/feed-inventory-balance', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-feed-usage', title: 'Feed usage', path: '/api/poultry/reports/feed-usage', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-flock-production-summary', title: 'Flock production summary', path: '/api/poultry/reports/flock-production-summary', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-hen-day-production', title: 'Hen day production', path: '/api/poultry/reports/hen-day-production', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-medicine-usage', title: 'Medicine usage', path: '/api/poultry/reports/medicine-usage', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-missing-daily-records', title: 'Missing daily records', path: '/api/poultry/reports/missing-daily-records', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-mortality', title: 'Mortality', path: '/api/poultry/reports/mortality', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-profit-loss', title: 'Profit loss', path: '/api/poultry/reports/profit-loss', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-profit-loss-by-flock', title: 'Profit loss by flock', path: '/api/poultry/reports/profit-loss-by-flock', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-supplier-balance', title: 'Supplier balance', path: '/api/poultry/reports/supplier-balance', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'poultry-reports-vaccination-schedule', title: 'Vaccination schedule', path: '/api/poultry/reports/vaccination-schedule', module: 'poultry', farmIdParam: 'FarmId', readOnly: true),
    PageSpec(key: 'admin-company-employees', title: 'Company employees', path: '/api/Admin/company-employees', source: 'login', readOnly: true),
    PageSpec(key: 'admin-employees', title: 'Employees', path: '/api/Admin/employees', needsFarmId: false, source: 'login'),
    PageSpec(key: 'admin-employees-count', title: 'Count', path: '/api/Admin/employees/count', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'admin-employees-today-logins', title: 'Today logins', path: '/api/Admin/employees/today-logins', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'admin-employees-companies', title: 'Companies', path: '/api/Admin/employees/{id}/companies', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'admin-farms', title: 'Farms', path: '/api/Admin/farms', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'admin-farms-count', title: 'Count', path: '/api/Admin/farms/count', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'admin-organization-employees', title: 'Employees', path: '/api/Admin/organization/employees', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'admin-organization-profile', title: 'Profile', path: '/api/Admin/organization/profile', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'authentication-confirmemail', title: 'Confirm Email', path: '/api/Authentication/ConfirmEmail', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'authentication-get-current-user', title: 'Get current user', path: '/api/Authentication/get-current-user', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'authentication-org', title: 'Org', path: '/api/Authentication/org', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'authentication-org-code-available', title: 'Org code available', path: '/api/Authentication/org-code-available', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'companies-mine', title: 'Mine', path: '/api/Companies/mine', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'payments-health', title: 'Health', path: '/api/Payments/health', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'payments-products', title: 'Products', path: '/api/Payments/products', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'payments-subscription-tiers', title: 'Subscription tiers', path: '/api/Payments/subscription-tiers', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'system-farms', title: 'Farms', path: '/api/System/farms', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'system-farms-count', title: 'Count', path: '/api/System/farms/count', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'userprofile-find', title: 'Find', path: '/api/UserProfile/find', needsFarmId: false, source: 'login', readOnly: true),
    PageSpec(key: 'userprofile-findbyusername', title: 'Find By User Name', path: '/api/UserProfile/findByUserName', needsFarmId: false, source: 'login', readOnly: true),

    // ---- appended: endpoints added since the first generation ----
    PageSpec(key: 'hotel-asset-depreciation', title: 'Asset depreciation', path: '/api/Hotel/asset-depreciation', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-assets', title: 'Assets', path: '/api/Hotel/assets', module: 'hotel'),
    PageSpec(key: 'hotel-assets-id-costs', title: 'Costs', path: '/api/Hotel/assets/{id}/costs', module: 'hotel'),
    PageSpec(key: 'hotel-assets-categories', title: 'Categories', path: '/api/Hotel/assets/categories', module: 'hotel'),
    PageSpec(key: 'hotel-assets-summary', title: 'Summary', path: '/api/Hotel/assets/summary', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-cash-flow', title: 'Cash flow', path: '/api/Hotel/cash-flow', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-custom-options', title: 'Custom options', path: '/api/Hotel/custom-options', module: 'hotel'),
    PageSpec(key: 'hotel-customer-payments', title: 'Customer payments', path: '/api/Hotel/customer-payments', module: 'hotel'),
    PageSpec(key: 'hotel-customers', title: 'Customers', path: '/api/Hotel/customers', module: 'hotel'),
    PageSpec(key: 'hotel-customers-id-ledger', title: 'Ledger', path: '/api/Hotel/customers/{id}/ledger', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-customers-balance-summary', title: 'Balance summary', path: '/api/Hotel/customers/balance-summary', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-customers-owed', title: 'Owed', path: '/api/Hotel/customers/owed', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-employee-loan-repayments', title: 'Employee loan repayments', path: '/api/Hotel/employee-loan-repayments', module: 'hotel'),
    PageSpec(key: 'hotel-employee-loans', title: 'Employee loans', path: '/api/Hotel/employee-loans', module: 'hotel'),
    PageSpec(key: 'hotel-employee-loans-id-repayments', title: 'Repayments', path: '/api/Hotel/employee-loans/{id}/repayments', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-employee-loans-eligible', title: 'Eligible', path: '/api/Hotel/employee-loans/eligible', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-employee-loans-staff-report', title: 'Staff report', path: '/api/Hotel/employee-loans/staff-report', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-employee-loans-summary', title: 'Summary', path: '/api/Hotel/employee-loans/summary', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-profit-loss', title: 'Profit loss', path: '/api/Hotel/profit-loss', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-profit-loss-expenses', title: 'Expenses', path: '/api/Hotel/profit-loss/expenses', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-profit-loss-revenue', title: 'Revenue', path: '/api/Hotel/profit-loss/revenue', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-supplier-payments', title: 'Supplier payments', path: '/api/Hotel/supplier-payments', module: 'hotel'),
    PageSpec(key: 'hotel-suppliers', title: 'Suppliers', path: '/api/Hotel/suppliers', module: 'hotel'),
    PageSpec(key: 'hotel-suppliers-id-ledger', title: 'Ledger', path: '/api/Hotel/suppliers/{id}/ledger', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-suppliers-balance-summary', title: 'Balance summary', path: '/api/Hotel/suppliers/balance-summary', module: 'hotel', readOnly: true),
    PageSpec(key: 'hotel-suppliers-owed', title: 'Owed', path: '/api/Hotel/suppliers/owed', module: 'hotel', readOnly: true),
    PageSpec(key: 'poultry-farm-setup-context', title: 'Context', path: '/api/PoultryFarmSetup/context', module: 'poultry', needsUserId: true, readOnly: true),
    PageSpec(key: 'poultry-farm-setup-draft', title: 'Draft', path: '/api/PoultryFarmSetup/draft', module: 'poultry', needsUserId: true, readOnly: true),
    PageSpec(key: 'poultry-farm-setup-opening-positions', title: 'Opening positions', path: '/api/PoultryFarmSetup/opening-positions', module: 'poultry', needsUserId: true, readOnly: true),
    PageSpec(key: 'poultry-farm-setup-status', title: 'Status', path: '/api/PoultryFarmSetup/status', module: 'poultry', needsUserId: true, readOnly: true),
    PageSpec(key: 'restaurant-cash-flow', title: 'Cash flow', path: '/api/Restaurant/cash-flow', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-finance-accounts', title: 'Accounts', path: '/api/Restaurant/finance/accounts', module: 'restaurant'),
    PageSpec(key: 'restaurant-finance-accounts-id-ledger', title: 'Ledger', path: '/api/Restaurant/finance/accounts/{id}/ledger', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-finance-counts', title: 'Counts', path: '/api/Restaurant/finance/counts', module: 'restaurant'),
    PageSpec(key: 'restaurant-finance-daily-closing', title: 'Daily closing', path: '/api/Restaurant/finance/daily-closing', module: 'restaurant'),
    PageSpec(key: 'restaurant-finance-daily-closing-preview', title: 'Preview', path: '/api/Restaurant/finance/daily-closing/preview', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-finance-ledger-period', title: 'Period', path: '/api/Restaurant/finance/ledger/period', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-finance-ledger-rows', title: 'Rows', path: '/api/Restaurant/finance/ledger/rows', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-finance-loans', title: 'Loans', path: '/api/Restaurant/finance/loans', module: 'restaurant'),
    PageSpec(key: 'restaurant-finance-loans-id-payments', title: 'Payments', path: '/api/Restaurant/finance/loans/{id}/payments', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-finance-loans-payments', title: 'Payments', path: '/api/Restaurant/finance/loans/payments', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-finance-owner-money', title: 'Owner money', path: '/api/Restaurant/finance/owner-money', module: 'restaurant'),
    PageSpec(key: 'restaurant-finance-pnl-lines', title: 'Pnl lines', path: '/api/Restaurant/finance/pnl-lines', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-finance-reports-profit-vs-cash', title: 'Profit vs cash', path: '/api/Restaurant/finance/reports/profit-vs-cash', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-finance-reports-takings-by-account', title: 'Takings by account', path: '/api/Restaurant/finance/reports/takings-by-account', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-finance-shifts', title: 'Shifts', path: '/api/Restaurant/finance/shifts', module: 'restaurant'),
    PageSpec(key: 'restaurant-finance-shifts-id-z-report', title: 'Z report', path: '/api/Restaurant/finance/shifts/{id}/z-report', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-finance-transfers', title: 'Transfers', path: '/api/Restaurant/finance/transfers', module: 'restaurant'),
    PageSpec(key: 'restaurant-orders-order-id-discounts', title: 'Discounts', path: '/api/Restaurant/orders/{orderId}/discounts', module: 'restaurant'),
    PageSpec(key: 'restaurant-payroll-report', title: 'Report', path: '/api/Restaurant/payroll/report', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-payroll-runs', title: 'Runs', path: '/api/Restaurant/payroll/runs', module: 'restaurant'),
    PageSpec(key: 'restaurant-staff-loans', title: 'Staff loans', path: '/api/Restaurant/staff-loans', module: 'restaurant'),
    PageSpec(key: 'restaurant-staff-loans-eligible', title: 'Eligible', path: '/api/Restaurant/staff-loans/eligible', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-staff-loans-repayments', title: 'Repayments', path: '/api/Restaurant/staff-loans/repayments', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-staff-loans-staff-report', title: 'Staff report', path: '/api/Restaurant/staff-loans/staff-report', module: 'restaurant', readOnly: true),
    PageSpec(key: 'restaurant-staff-loans-summary', title: 'Summary', path: '/api/Restaurant/staff-loans/summary', module: 'restaurant', readOnly: true),
    PageSpec(key: 'user-quick-links', title: 'User quick links', path: '/api/UserQuickLinks', needsUserId: true, readOnly: true),
    PageSpec(key: 'water-employee-loans', title: 'Employee loans', path: '/api/Water/employee-loans', module: 'water'),
    PageSpec(key: 'water-employee-loans-id-repayments', title: 'Repayments', path: '/api/Water/employee-loans/{id}/repayments', module: 'water', readOnly: true),
    PageSpec(key: 'water-employee-loans-eligible', title: 'Eligible', path: '/api/Water/employee-loans/eligible', module: 'water', readOnly: true),
    PageSpec(key: 'water-employee-loans-summary', title: 'Summary', path: '/api/Water/employee-loans/summary', module: 'water', readOnly: true),
    PageSpec(key: 'water-payroll-deductions', title: 'Payroll deductions', path: '/api/Water/payroll-deductions', module: 'water'),
    PageSpec(key: 'water-profit-loss', title: 'Profit loss', path: '/api/Water/profit-loss', module: 'water', readOnly: true),
    PageSpec(key: 'water-profit-loss-detail', title: 'Detail', path: '/api/Water/profit-loss/detail', module: 'water', readOnly: true),
];
