// GENERATED: where each form <Select> gets its options on the web.
// Keyed "specKey.fieldName". The app fetches `path` and builds the
// options from `value` / `label`, exactly as the site does.

class LookupSource {
  const LookupSource(this.path, this.value, this.label);

  /// Collection endpoint on the farm API, farm-scoped at call time.
  final String path;
  final String value;
  final String label;
}

const Map<String, LookupSource> lookupSources = {
  "egg-production-[id].flockId": LookupSource("/Flock", "flockId", "name"),
  "expenses-[id].flockId": LookupSource("/Flock", "flockId", "name"),
  "expenses-[id].poultryCashAccountId": LookupSource("/Poultry/cash-accounts", "poultryCashAccountId", "accountName"),
  "expenses-new.flockId": LookupSource("/Flock", "flockId", "name"),
  "expenses-new.poultryCashAccountId": LookupSource("/Poultry/cash-accounts", "poultryCashAccountId", "accountName"),
  "expenses.poultryCashAccountId": LookupSource("/Poultry/cash-accounts", "poultryCashAccountId", "accountName"),
  "expenses.supplierId": LookupSource("/Supplier", "supplierId", "name"),
  "feed-usage-[id].flockId": LookupSource("/Flock", "flockId", "name"),
  "feed-usage-new.flockId": LookupSource("/Flock", "flockId", "name"),
  "feed-usage.flockId": LookupSource("/Flock", "flockId", "name"),
  "flock-batch.supplierId": LookupSource("/Supplier", "supplierId", "name"),
  "generic-cash-transfers.fromGenericCashAccountId": LookupSource("/generic-company/{farmId}/cash-accounts", "genericCashAccountId", "accountName"),
  "generic-cash-transfers.toGenericCashAccountId": LookupSource("/generic-company/{farmId}/cash-accounts", "genericCashAccountId", "accountName"),
  "generic-customer-payments.genericCustomerId": LookupSource("/generic-company/{farmId}/customers", "genericCustomerId", "customerName"),
  "generic-expenses-new.genericExpenseCategoryId": LookupSource("/generic-company/{farmId}/expense-categories", "genericExpenseCategoryId", "name"),
  "generic-expenses-new.genericSupplierId": LookupSource("/Supplier", "genericSupplierId", "supplierName"),
  "generic-payroll-runs.genericCashAccountId": LookupSource("/generic-company/{farmId}/cash-accounts", "genericCashAccountId", "accountName"),
  "generic-recurring-expenses.genericExpenseCategoryId": LookupSource("/generic-company/{farmId}/expense-categories", "genericExpenseCategoryId", "name"),
  "generic-recurring-expenses.genericSupplierId": LookupSource("/Supplier", "genericSupplierId", "supplierName"),
  "generic-service-plans.genericServiceCategoryId": LookupSource("/generic-company/{farmId}/service-categories", "genericServiceCategoryId", "name"),
  "generic-subscriptions.genericCustomerId": LookupSource("/generic-company/{farmId}/customers", "genericCustomerId", "customerName"),
  "generic-subscriptions.genericServiceId": LookupSource("/generic-company/{farmId}/service-plans", "genericServiceId", "serviceName"),
  "generic-supplier-payments.genericCashAccountId": LookupSource("/generic-company/{farmId}/cash-accounts", "genericCashAccountId", "accountName"),
  "generic-supplier-payments.genericSupplierId": LookupSource("/Supplier", "genericSupplierId", "supplierName"),
  "health.flockId": LookupSource("/Flock", "flockId", "name"),
  "health.houseId": LookupSource("/House", "houseId", "name"),
  "health.itemId": LookupSource("/InventoryItem", "id", "name"),
  "hotel-bookings.hotelGuestId": LookupSource("/Hotel/guests", "hotelGuestId", "firstName"),
  "hotel-bookings.hotelRoomTypeId": LookupSource("/Hotel/setup/room-types", "hotelRoomTypeId", "name"),
  "hotel-communications.hotelGuestId": LookupSource("/Hotel/guests", "hotelGuestId", "firstName"),
  "hotel-finance-expenses.hotelCashAccountId": LookupSource("/Hotel/finance/cash-accounts", "hotelCashAccountId", "accountName"),
  "hotel-guest-requests.hotelBookingId": LookupSource("/Hotel/bookings", "hotelBookingId", "guestFirstName"),
  "hotel-guest-requests.hotelRoomId": LookupSource("/Hotel/rooms", "hotelRoomId", "hotelRoomId"),
  "hotel-housekeeping-schedule.hotelRoomId": LookupSource("/Hotel/rooms", "hotelRoomId", "hotelRoomId"),
  "hotel-lost-found.hotelRoomId": LookupSource("/Hotel/rooms", "hotelRoomId", "hotelRoomId"),
  "hotel-maintenance.hotelRoomId": LookupSource("/Hotel/rooms", "hotelRoomId", "hotelRoomId"),
  "hotel-payments.hotelBookingId": LookupSource("/Hotel/bookings", "hotelBookingId", "bookingRef"),
  "hotel-payroll-diag.hotelCashAccountId": LookupSource("/Hotel/finance/cash-accounts", "hotelCashAccountId", "accountName"),
  "hotel-restaurant.hotelBookingId": LookupSource("/Hotel/bookings", "hotelBookingId", "hotelBookingId"),
  "hotel-restaurant.tableNumber": LookupSource("/Hotel/restaurant/tables", "tableNumber", "tableNumber"),
  "hotel-rooms.hotelFloorId": LookupSource("/Hotel/setup/floors", "hotelFloorId", "name"),
  "hotel-rooms.hotelRoomTypeId": LookupSource("/Hotel/setup/room-types", "hotelRoomTypeId", "name"),
  "hotel-setup.hotelFloorId": LookupSource("/Hotel/setup/floors", "hotelFloorId", "name"),
  "hotel-setup.hotelRoomCategoryId": LookupSource("/Hotel/setup/room-categories", "hotelRoomCategoryId", "description"),
  "hotel-setup.hotelRoomTypeId": LookupSource("/Hotel/setup/room-types", "hotelRoomTypeId", "name"),
  "poultry-assets.cashAccountId": LookupSource("/Poultry/cash-accounts", "poultryCashAccountId", "accountName"),
  "poultry-cash-accounts.fromPoultryCashAccountId": LookupSource("/Poultry/cash-accounts", "poultryCashAccountId", "accountName"),
  "poultry-cash-accounts.toPoultryCashAccountId": LookupSource("/Poultry/cash-accounts", "poultryCashAccountId", "accountName"),
  "poultry-cash-transfers.fromPoultryCashAccountId": LookupSource("/Poultry/cash-accounts", "poultryCashAccountId", "accountName"),
  "poultry-cash-transfers.toPoultryCashAccountId": LookupSource("/Poultry/cash-accounts", "poultryCashAccountId", "accountName"),
  "poultry-driver-returns.poultryDriverId": LookupSource("/Poultry/drivers", "poultryDriverId", "driverName"),
  "poultry-driver-returns.poultryRouteId": LookupSource("/Poultry/routes", "poultryRouteId", "routeName"),
  "poultry-driver-returns.poultryVehicleId": LookupSource("/Poultry/vehicles", "poultryVehicleId", "vehicleName"),
  "poultry-drivers.defaultRouteId": LookupSource("/Poultry/routes", "poultryRouteId", "routeName"),
  "poultry-drivers.defaultVehicleId": LookupSource("/Poultry/vehicles", "poultryVehicleId", "vehicleName"),
  "poultry-internal-usage.poultryProductId": LookupSource("/Poultry/products", "poultryProductId", "name"),
  "poultry-loans.poultryCashAccountId": LookupSource("/Poultry/cash-accounts", "poultryCashAccountId", "accountName"),
  "poultry-loss-records.poultryProductId": LookupSource("/Poultry/products", "poultryProductId", "name"),
  "poultry-owner-money.poultryCashAccountId": LookupSource("/Poultry/cash-accounts", "poultryCashAccountId", "accountName"),
  "poultry-payroll-deductions.poultryCashAccountId": LookupSource("/Poultry/cash-accounts", "poultryCashAccountId", "accountName"),
  "poultry-payroll-deductions.poultryStaffId": LookupSource("/Poultry/staff", "poultryStaffId", "firstName"),
  "poultry-routes.defaultVehicleId": LookupSource("/Poultry/vehicles", "poultryVehicleId", "vehicleName"),
  "restaurant-floor-plan.floorId": LookupSource("/Restaurant/floor/floors", "floorId", "name"),
  "restaurant-menu.parentCategoryId": LookupSource("/Restaurant/menu/categories", "menuCategoryId", "name"),
  "restaurant-reservations.tableId": LookupSource("/Restaurant/floor/tables", "tableId", "tableId"),
  "restaurant-setup.modifierGroupId": LookupSource("/Restaurant/menu/modifier-groups", "modifierGroupId", "name"),
  "sales.poultryCashAccountId": LookupSource("/Poultry/cash-accounts", "poultryCashAccountId", "accountName"),
  "supplies.supplierId": LookupSource("/Supplier", "supplierId", "name"),
  "water-assets.cashAccountId": LookupSource("/Water/cash-accounts", "waterCashAccountId", "accountName"),
  "water-cash-accounts.fromWaterCashAccountId": LookupSource("/Water/cash-accounts", "waterCashAccountId", "accountName"),
  "water-cash-accounts.toWaterCashAccountId": LookupSource("/Water/cash-accounts", "waterCashAccountId", "accountName"),
  "water-cash-transfers.fromWaterCashAccountId": LookupSource("/Water/cash-accounts", "waterCashAccountId", "accountName"),
  "water-cash-transfers.toWaterCashAccountId": LookupSource("/Water/cash-accounts", "waterCashAccountId", "accountName"),
  "water-driver-returns.waterDriverId": LookupSource("/Water/drivers", "waterDriverId", "driverName"),
  "water-driver-returns.waterRouteId": LookupSource("/Water/routes", "waterRouteId", "routeName"),
  "water-driver-returns.waterVehicleId": LookupSource("/Water/vehicles", "waterVehicleId", "vehicleName"),
  "water-drivers.assignedWaterVehicleId": LookupSource("/Water/vehicles", "waterVehicleId", "vehicleName"),
  "water-drivers.defaultRouteId": LookupSource("/Water/routes", "waterRouteId", "routeName"),
  "water-drivers.defaultVehicleId": LookupSource("/Water/vehicles", "waterVehicleId", "vehicleName"),
  "water-expenses.supplierId": LookupSource("/Supplier", "supplierId", "name"),
  "water-expenses.waterCashAccountId": LookupSource("/Water/cash-accounts", "waterCashAccountId", "accountName"),
  "water-expenses.waterExpenseCategoryId": LookupSource("/Water/expense-categories", "waterExpenseCategoryId", "name"),
  "water-internal-usage.waterProductId": LookupSource("/Water/products", "waterProductId", "name"),
  "water-loans.waterCashAccountId": LookupSource("/Water/cash-accounts", "waterCashAccountId", "accountName"),
  "water-loss-records.waterProductId": LookupSource("/Water/products", "waterProductId", "name"),
  "water-owner-money.waterCashAccountId": LookupSource("/Water/cash-accounts", "waterCashAccountId", "accountName"),
  "water-payroll-runs.waterCashAccountId": LookupSource("/Water/cash-accounts", "waterCashAccountId", "accountName"),
  "water-payroll-runs.waterStaffId": LookupSource("/Water/staff", "waterStaffId", "firstName"),
  "water-production-batches.machineScope": LookupSource("/Water/machines", "waterMachineId", "machineName"),
  "water-production-batches.waterProductId": LookupSource("/Water/products", "waterProductId", "name"),
  "water-raw-material-usage-history.supplierId": LookupSource("/Supplier", "supplierId", "name"),
  "water-raw-material-usage-history.waterRawMaterialItemId": LookupSource("/Water/raw-material-items", "waterRawMaterialItemId", "itemName"),
  "water-routes.defaultVehicleId": LookupSource("/Water/vehicles", "waterVehicleId", "vehicleName"),
  "water-staff.assignedWaterVehicleId": LookupSource("/Water/vehicles", "waterVehicleId", "vehicleName"),
  // ---- resolved from the web pages and verified against the API ----
"eggproduction.flockId": LookupSource("/Flock", "flockId", "name"),
  "employee-loans.poultryCashAccountId": LookupSource("/Poultry/cash-accounts", "poultryCashAccountId", "accountName"),
  "employee-loans.poultryStaffId": LookupSource("/Poultry/staff", "poultryStaffId", "firstName"),
  "feedusage.flockId": LookupSource("/Flock", "flockId", "name"),
  "flock.supplierId": LookupSource("/Supplier", "supplierId", "name"),
  "flocks.batchId": LookupSource("/MainFlockBatch", "batchId", "batchName"),
  "flocks.houseId": LookupSource("/House", "houseId", "houseName"),
  "generic-customer-payments.genericCashAccountId": LookupSource("/generic-company/{farmId}/cash-accounts", "genericCashAccountId", "accountName"),
  "generic-expenses.genericCashAccountId": LookupSource("/generic-company/{farmId}/cash-accounts", "genericCashAccountId", "accountName"),
  "generic-expenses.genericSupplierId": LookupSource("/generic-company/{farmId}/suppliers", "genericSupplierId", "supplierName"),
  "generic-internal-usage.genericProductId": LookupSource("/generic-company/{farmId}/products", "genericProductId", "productName"),
  "generic-inventory-adjustments.genericProductId": LookupSource("/generic-company/{farmId}/products", "genericProductId", "productName"),
  "generic-payroll-runs.genericStaffId": LookupSource("/generic-company/{farmId}/staff", "genericStaffId", "firstName"),
  "generic-purchases.genericCashAccountId": LookupSource("/generic-company/{farmId}/cash-accounts", "genericCashAccountId", "accountName"),
  "generic-purchases.genericSupplierId": LookupSource("/generic-company/{farmId}/suppliers", "genericSupplierId", "supplierName"),
  "generic-sales.genericCashAccountId": LookupSource("/generic-company/{farmId}/cash-accounts", "genericCashAccountId", "accountName"),
  "generic-sales.genericCustomerId": LookupSource("/generic-company/{farmId}/customers", "genericCustomerId", "customerName"),
  "generic-staff-payments.genericStaffId": LookupSource("/generic-company/{farmId}/staff", "genericStaffId", "firstName"),
  "inventoryitem.supplierId": LookupSource("/Supplier", "supplierId", "name"),
  "poultry-deliveries.poultryProductId": LookupSource("/Poultry/products", "poultryProductId", "name"),
  "production-records.flockId": LookupSource("/Flock", "flockId", "name"),
  "productionbatchrecord.batchId": LookupSource("/MainFlockBatch", "batchId", "batchName"),
  "raw-materials.poultryCashAccountId": LookupSource("/Poultry/cash-accounts", "poultryCashAccountId", "accountName"),
  "raw-materials.poultryRawMaterialItemId": LookupSource("/Poultry/raw-material-items", "poultryRawMaterialItemId", "itemName"),
  "sales.flockId": LookupSource("/Flock", "flockId", "name"),
  "water-daily-closings.waterCashAccountId": LookupSource("/Water/cash-accounts", "waterCashAccountId", "accountName"),
  "water-daily-closings.waterStaffId": LookupSource("/Water/staff", "waterStaffId", "firstName"),
  "water-daily-productions.waterBoreholeId": LookupSource("/Water/boreholes", "waterBoreholeId", "boreholeName"),
  "water-daily-productions.waterProductId": LookupSource("/Water/products", "waterProductId", "name"),
  "water-sales.waterCustomerId": LookupSource("/Water/customers", "waterCustomerId", "name"),
  "water-sales.waterProductId": LookupSource("/Water/products", "waterProductId", "name"),
};

/// Selects whose options are a constant list on the web (grades,
/// business types, methods). No fetch needed.
const Map<String, List<List<String>>> staticOptions = {
  "business-office.audienceRole": [["All", "Everyone"], ["Admin", "Admins only"], ["Staff", "Staff only"]],
  "business-office.businessTypeId": [["water", "Water production"], ["poultry", "Poultry farm"], ["hotel", "Hotel"], ["restaurant", "Restaurant"], ["saas", "SaaS / software company"], ["gym", "Gym / fitness centre"], ["school", "School"], ["cleaning", "Cleaning service"], ["security", "Security service"], ["agency", "Agency"], ["retainer", "Retainer business"], ["membership", "Membership organisation"], ["retail", "Shop / retail"], ["other", "Other small business"]],
  "business-office.type": [["Info", "Info"], ["Success", "Success"], ["Warning", "Warning"], ["Critical", "Critical"], ["Maintenance", "Maintenance"], ["FeatureUpdate", "FeatureUpdate"], ["Payment", "Payment"], ["Security", "Security"]],
  "cash.adjustmentType": [["OpeningBalance", "Opening Balance"], ["OwnerInjection", "Owner injection"], ["LoanReceived", "Loan received"], ["Withdrawal", "Withdrawal"], ["Correction", "Correction"]],
  "companies.businessTypeId": [["water", "Water production"], ["poultry", "Poultry farm"], ["hotel", "Hotel"], ["restaurant", "Restaurant"], ["saas", "SaaS / software company"], ["gym", "Gym / fitness centre"], ["school", "School"], ["cleaning", "Cleaning service"], ["security", "Security service"], ["agency", "Agency"], ["retainer", "Retainer business"], ["membership", "Membership organisation"], ["retail", "Shop / retail"], ["other", "Other small business"]],
  "egg-production-new.eggGrade": [["Small", "Small"], ["Medium", "Medium"], ["Large", "Large"], ["XLarge", "X-Large"], ["Jumbo", "Jumbo"], ["Seconds", "Seconds / B-grade"], ["Cracks", "Cracks"], ["Mixed", "Mixed grades"]],
  "egg-tracker.adjustmentType": [["Correction", "Correction"], ["Stocktake", "Stocktake"], ["OpeningBalance", "Opening balance"]],
  "expenses.flockId": [["loading", "Loading flocks..."], ["none", "none"]],
  "expenses.paymentStatus": [["Paid", "Paid"], ["PartiallyPaid", "PartiallyPaid"], ["Unpaid", "Unpaid"]],
  "flock-batch.paymentMethod": [["Cash", "Cash"], ["MoMo", "MoMo"], ["Bank", "Bank"], ["Card", "Card"]],
  "flock-batch.supplierType": [["local", "Local"], ["foreign", "Foreign"]],
  "generic-customer-payments.paymentMethod": [["Cash", "Cash"], ["MoMo", "MoMo"], ["Bank", "Bank"], ["Card", "Card"]],
  "generic-customers.customerType": [["Individual", "Individual"], ["Business", "Business"], ["Walk-in", "Walk-in"], ["Retail Customer", "Retail Customer"], ["Wholesale Customer", "Wholesale Customer"], ["Other", "Other"]],
  "generic-expenses-new.paymentMethod": [["Cash", "Cash"], ["MoMo", "MoMo"], ["Bank", "Bank"], ["Card", "Card"]],
  "generic-internal-use.category": [["Electronics", "Electronics"], ["Clothing", "Clothing"], ["Documents", "Documents"], ["Jewelry", "Jewelry"], ["Personal", "Personal"], ["Other", "Other"]],
  "generic-owner-money.entryType": [["Contribution", "Contribution \u2014 the owner put money in"], ["Draw", "Draw \u2014 the owner took money out"]],
  "generic-payroll-[id].paymentMethod": [["Cash", "Cash"], ["MoMo", "MoMo"], ["Bank Transfer", "Bank Transfer"], ["Cheque", "Cheque"], ["Card", "Card"], ["Other", "Other"]],
  "generic-recurring-expenses.frequency": [["Weekly", "Weekly"], ["Monthly", "Monthly"], ["Quarterly", "Quarterly"], ["SemiAnnual", "SemiAnnual"], ["Annual", "Annual"]],
  "generic-service-plans.billingFrequency": [["Weekly", "Weekly"], ["Monthly", "Monthly"], ["Quarterly", "Quarterly"], ["Termly", "Termly"], ["SemiAnnual", "SemiAnnual"], ["Annual", "Annual"], ["OneTime", "OneTime"]],
  "generic-service-plans.planType": [["Recurring", "Recurring \u2014 bills every period"], ["OneOff", "One-off \u2014 a service you sell once"]],
  "generic-staff-[id].role": [["Owner", "Owner"], ["Manager", "Manager"], ["Accountant", "Accountant"], ["Cashier", "Cashier"], ["Salesperson", "Salesperson"], ["InventoryOfficer", "InventoryOfficer"], ["Cleaner", "Cleaner"], ["Security", "Security"], ["Driver", "Driver"], ["ServiceProvider", "ServiceProvider"], ["Other", "Other"]],
  "generic-staff-[id].salaryType": [["Daily", "Daily"], ["Weekly", "Weekly"], ["Monthly", "Monthly"], ["Commission", "Commission"], ["Mixed", "Mixed"]],
  "generic-staff.role": [["Owner", "Owner"], ["Manager", "Manager"], ["Accountant", "Accountant"], ["Cashier", "Cashier"], ["Salesperson", "Salesperson"], ["InventoryOfficer", "InventoryOfficer"], ["Cleaner", "Cleaner"], ["Security", "Security"], ["Driver", "Driver"], ["ServiceProvider", "ServiceProvider"], ["Other", "Other"]],
  "generic-staff.salaryType": [["Daily", "Daily"], ["Weekly", "Weekly"], ["Monthly", "Monthly"], ["Commission", "Commission"], ["Mixed", "Mixed"]],
  "generic-stock-adjustments.adjustmentType": [["Increase", "Increase (+)"], ["Decrease", "Decrease (\u2212)"]],
  "generic-subscriptions.billingFrequency": [["Weekly", "Weekly"], ["Monthly", "Monthly"], ["Quarterly", "Quarterly"], ["Termly", "Termly"], ["SemiAnnual", "SemiAnnual"], ["Annual", "Annual"], ["OneTime", "OneTime"]],
  "generic-supplier-payments.paymentMethod": [["Cash", "Cash"], ["MoMo", "MoMo"], ["Bank", "Bank"], ["Card", "Card"]],
  "generic-suppliers.supplierType": [["ProductSupplier", "ProductSupplier"], ["ServiceProvider", "ServiceProvider"], ["Landlord", "Landlord"], ["UtilityProvider", "UtilityProvider"], ["Contractor", "Contractor"], ["Other", "Other"]],
  "hotel-billing.chargeType": [["Room", "Room"], ["RoomService", "RoomService"], ["Minibar", "Minibar"], ["Laundry", "Laundry"], ["Damage", "Damage"], ["Restaurant", "Restaurant"], ["Spa", "Spa"], ["Transport", "Transport"], ["Telephone", "Telephone"], ["Other", "Other"]],
  "hotel-billing.paymentMethod": [["Cash", "Cash"], ["Card", "Card"], ["MobileMoney", "Mobile Money"], ["BankTransfer", "Bank Transfer"]],
  "hotel-bookings.source": [["WalkIn", "Walk-in"], ["Phone", "Phone"], ["Online", "Online"], ["Agent", "Agent"]],
  "hotel-cash-accounts.accountType": [["Cash", "Cash"], ["Bank", "Bank"], ["MobileMoney", "Mobile Money"]],
  "hotel-cash-accounts.purpose": [["__none__", "No link (General)"], ["FrontDesk", "Front Desk \u2014 receives guest payments (Credits)"], ["Expenses", "Expenses \u2014 money goes out for expenses (Debits)"], ["POS", "POS / Restaurant \u2014 receives order payments (Credits)"], ["Payroll", "Payroll \u2014 money goes out for salaries (Debits)"]],
  "hotel-communications.commType": [["Note", "Note"], ["Complaint", "Complaint"], ["Request", "Request"], ["Compliment", "Compliment"], ["Incident", "Incident"]],
  "hotel-communications.priority": [["Low", "Low"], ["Normal", "Normal"], ["High", "High"], ["Urgent", "Urgent"]],
  "hotel-finance-expenses.paymentMethod": [["Cash", "Cash"], ["MobileMoney", "Mobile Money"], ["Bank", "Bank Transfer"], ["Card", "Card"], ["Credit", "Credit (no cash account)"]],
  "hotel-housekeeping-schedule.priority": [["Low", "Low"], ["Normal", "Normal"], ["High", "High"]],
  "hotel-lost-found.category": [["Electronics", "Electronics"], ["Clothing", "Clothing"], ["Documents", "Documents"], ["Jewelry", "Jewelry"], ["Personal", "Personal"], ["Other", "Other"]],
  "hotel-maintenance.priority": [["Low", "Low"], ["Normal", "Normal"], ["High", "High"], ["Critical", "Critical"]],
  "hotel-menu.category": [["Electronics", "Electronics"], ["Clothing", "Clothing"], ["Documents", "Documents"], ["Jewelry", "Jewelry"], ["Personal", "Personal"], ["Other", "Other"]],
  "hotel-payments.paymentMethod": [["Cash", "Cash"], ["Card", "Card"], ["MobileMoney", "Mobile Money"], ["BankTransfer", "Bank Transfer"]],
  "hotel-payroll-diag.paymentMethod": [["Cash", "Cash"], ["MoMo", "MoMo"], ["Bank Transfer", "Bank Transfer"], ["Cheque", "Cheque"], ["Card", "Card"], ["Other", "Other"]],
  "hotel-restaurant.paymentMethod": [["Cash", "Cash"], ["Card", "Card"], ["Mobile Money", "Mobile Money"], ["Bank Transfer", "Bank Transfer"]],
  "hotel-shift-handovers.shiftType": [["Morning", "Morning"], ["Afternoon", "Afternoon"], ["Night", "Night"]],
  "hotel-staff.department": [["Front Desk", "Front Desk"], ["Housekeeping", "Housekeeping"], ["Restaurant", "Restaurant"], ["Kitchen", "Kitchen"], ["Bar", "Bar"], ["Maintenance", "Maintenance"], ["Security", "Security"], ["Management", "Management"], ["Finance", "Finance"], ["Laundry", "Laundry"], ["Spa", "Spa"], ["Other", "Other"]],
  "hotel-staff.role": [["Owner", "Owner"], ["Manager", "Manager"], ["Accountant", "Accountant"], ["Cashier", "Cashier"], ["Salesperson", "Salesperson"], ["InventoryOfficer", "InventoryOfficer"], ["Cleaner", "Cleaner"], ["Security", "Security"], ["Driver", "Driver"], ["ServiceProvider", "ServiceProvider"], ["Other", "Other"]],
  "poultry-cash-accounts.accountType": [["FactoryCashBox", "FactoryCashBox"], ["OwnerCash", "OwnerCash"], ["MoMoWallet", "MoMoWallet"], ["BankAccount", "BankAccount"], ["DriverCash", "DriverCash"], ["PettyCash", "PettyCash"], ["Other", "Other"]],
  "poultry-cash-accounts.notes": [["Bank deposit", "Bank deposit"], ["Bank withdrawal", "Bank withdrawal"], ["MoMo cash-out", "MoMo cash-out"], ["MoMo top-up", "MoMo top-up"], ["Driver float issued", "Driver float issued"], ["Driver float returned", "Driver float returned"], ["Petty cash top-up", "Petty cash top-up"], ["Funding payroll", "Funding payroll"], ["Funding supplier payment", "Funding supplier payment"], ["Consolidating balances", "Consolidating balances"], ["Safe keeping", "Safe keeping"], ["Other", "Other"]],
  "poultry-deliveries.unit": [["Egg", "Egg"], ["Tray", "Tray"], ["Crate", "Crate"], ["Dozen", "Dozen"], ["Piece", "Piece"], ["Unit", "Unit"]],
  "poultry-internal-usage.category": [["Electronics", "Electronics"], ["Clothing", "Clothing"], ["Documents", "Documents"], ["Jewelry", "Jewelry"], ["Personal", "Personal"], ["Other", "Other"]],
  "poultry-loans.interestType": [["Simple", "Simple"], ["ReducingBalance", "ReducingBalance"], ["Flat", "Flat"], ["Unknown", "Unknown"]],
  "poultry-loans.lenderType": [["Bank", "Bank"], ["FinancialInstitution", "FinancialInstitution"], ["Individual", "Individual"], ["Owner", "Owner"], ["FamilyFriend", "FamilyFriend"], ["Supplier", "Supplier"], ["Other", "Other"]],
  "poultry-loans.paymentFrequency": [["Weekly", "Weekly"], ["BiWeekly", "BiWeekly"], ["Monthly", "Monthly"], ["Quarterly", "Quarterly"], ["Custom", "Custom"]],
  "poultry-loss-records.lossType": [["Damage", "Damage"], ["Mortality", "Mortality"], ["Theft", "Theft"], ["Spoilage", "Spoilage"], ["MissingStock", "MissingStock"], ["Other", "Other"]],
  "poultry-owner-money.paymentMethod": [["Cash", "Cash"], ["MoMo", "MoMo"], ["Bank Transfer", "Bank Transfer"], ["Cheque", "Cheque"], ["Card", "Card"], ["Other", "Other"]],
  "poultry-products.isRawEggProduct": [["no", "No"], ["yes", "Yes"]],
  "poultry-products.productType": [["FinishedGood", "FinishedGood"], ["RawMaterial", "RawMaterial"], ["PackagingMaterial", "PackagingMaterial"], ["Other", "Other"]],
  "poultry-products.requiresRecipeSetup": [["yes", "Yes"], ["no", "No"]],
  "poultry-products.unit": [["Egg", "Egg"], ["Tray", "Tray"], ["Crate", "Crate"], ["Dozen", "Dozen"], ["Piece", "Piece"], ["Unit", "Unit"]],
  "poultry-raw-material-usage-history.category": [["Electronics", "Electronics"], ["Clothing", "Clothing"], ["Documents", "Documents"], ["Jewelry", "Jewelry"], ["Personal", "Personal"], ["Other", "Other"]],
  // POULTRY_STAFF_ROLES (lib/api/poultry-finance.ts). The generated list was
  // the Generic company's roles.
  "poultry-staff.role": [["FarmManager", "FarmManager"], ["Supervisor", "Supervisor"], ["FarmHand", "FarmHand"], ["VaccinatorHealth", "VaccinatorHealth"], ["FeedMillOperator", "FeedMillOperator"], ["EggCollector", "EggCollector"], ["Salesperson", "Salesperson"], ["Accountant", "Accountant"], ["Cleaner", "Cleaner"], ["Security", "Security"], ["Driver", "Driver"], ["Other", "Other"]],
  "poultry-staff.salaryType": [["Daily", "Daily"], ["Weekly", "Weekly"], ["Monthly", "Monthly"], ["Commission", "Commission"], ["Mixed", "Mixed"]],
  "poultry-stock-transactions.movementType": [["Increase", "Increase"], ["Adjustment", "Adjustment"], ["Decrease", "Decrease"], ["Damage/Loss", "Damage/Loss"]],
  // STATUSES in app/poultry-vehicles/page.tsx (was attendance statuses).
  "poultry-vehicles.status": [["Active", "Active"], ["Inactive", "Inactive"], ["UnderMaintenance", "UnderMaintenance"]],
  "poultry-vehicles.vehicleType": [["Truck", "Truck"], ["Van", "Van"], ["Tricycle", "Tricycle"], ["Motorbike", "Motorbike"], ["Pickup", "Pickup"], ["Other", "Other"]],
  // SEGMENTS in app/restaurant-crm/page.tsx.
  "restaurant-crm-customers.segment": [["New", "New"], ["Regular", "Regular"], ["VIP", "VIP"], ["Lapsed", "Lapsed"]],
  "restaurant-delivery.vehicleType": [["Motorcycle", "Motorcycle"], ["Car", "Car"], ["Bicycle", "Bicycle"], ["Van", "Van"]],
  "restaurant-events.eventType": [["Corporate", "Corporate"], ["Wedding", "Wedding"], ["Birthday", "Birthday"], ["HolidayParty", "HolidayParty"], ["Buffet", "Buffet"], ["Cocktail", "Cocktail"], ["Other", "Other"]],
  "restaurant-events.venue": [["InHouse", "In-House"], ["Offsite", "Offsite"]],
  "restaurant-expenses.paymentMethod": [["Cash", "Cash"], ["MoMo", "MoMo"], ["Bank Transfer", "Bank Transfer"], ["Cheque", "Cheque"], ["Card", "Card"], ["Other", "Other"]],
  "restaurant-floor-plan.shape": [["Square", "Square"], ["Round", "Round"], ["Booth", "Booth"], ["Bar", "Bar"], ["Long", "Long"]],
  "restaurant-gift-cards.cardType": [["Digital", "Digital"], ["Physical", "Physical"]],
  "restaurant-inventory.storageArea": [["Walk-in Cooler", "Walk-in Cooler"], ["Freezer", "Freezer"], ["Dry Store", "Dry Store"], ["Bar", "Bar"], ["Kitchen Counter", "Kitchen Counter"], ["Pantry", "Pantry"]],
  "restaurant-inventory.unit": [["Egg", "Egg"], ["Tray", "Tray"], ["Crate", "Crate"], ["Dozen", "Dozen"], ["Piece", "Piece"], ["Unit", "Unit"]],
  "restaurant-online-orders.channelRestriction": [["all", "All Channels"], ["Online", "Online Only"], ["QR", "QR Only"], ["Delivery", "Delivery Only"]],
  "restaurant-online-orders.discountType": [["Percentage", "Percentage"], ["FixedAmount", "Fixed Amount"], ["FreeDelivery", "Free Delivery"]],
  "restaurant-staff.salaryType": [["Daily", "Daily"], ["Weekly", "Weekly"], ["Monthly", "Monthly"], ["Commission", "Commission"], ["Mixed", "Mixed"]],
  "settings.farmType": [["Layers", "Layers (Egg Production)"], ["Broilers", "Broilers (Meat Production)"], ["Mixed", "Mixed (Layers & Broilers)"], ["Hatchery", "Hatchery"], ["Breeders", "Breeders"], ["Other", "Other"]],
  "settings.timezone": [["Africa/Accra", "Africa/Accra (GMT+0)"], ["Africa/Lagos", "Africa/Lagos (WAT, GMT+1)"], ["Africa/Nairobi", "Africa/Nairobi (EAT, GMT+3)"], ["Africa/Johannesburg", "Africa/Johannesburg (SAST, GMT+2)"], ["America/New_York", "America/New_York (EST, GMT-5)"], ["Europe/London", "Europe/London (GMT+0)"], ["Asia/Dubai", "Asia/Dubai (GST, GMT+4)"]],
  // STATUSES in app/water-boreholes/page.tsx (was attendance statuses).
  "water-boreholes.status": [["Active", "Active"], ["Inactive", "Inactive"], ["UnderMaintenance", "UnderMaintenance"]],
  "water-cash-accounts.accountType": [["FactoryCashBox", "FactoryCashBox"], ["OwnerCash", "OwnerCash"], ["MoMoWallet", "MoMoWallet"], ["BankAccount", "BankAccount"], ["DriverCash", "DriverCash"], ["PettyCash", "PettyCash"], ["Other", "Other"]],
  "water-cash-accounts.notes": [["Bank deposit", "Bank deposit"], ["Bank withdrawal", "Bank withdrawal"], ["MoMo cash-out", "MoMo cash-out"], ["MoMo top-up", "MoMo top-up"], ["Driver float issued", "Driver float issued"], ["Driver float returned", "Driver float returned"], ["Petty cash top-up", "Petty cash top-up"], ["Funding payroll", "Funding payroll"], ["Funding supplier payment", "Funding supplier payment"], ["Consolidating balances", "Consolidating balances"], ["Safe keeping", "Safe keeping"], ["Other", "Other"]],
  "water-drivers.role": [["Driver", "Driver"], ["MotorKingRider", "Motor King Rider"]],
  "water-expenses.paymentMethod": [["Cash", "Cash"], ["MoMo", "Mobile Money"], ["Bank", "Bank"], ["Card", "Card"], ["Credit", "Credit"], ["Mixed", "Mixed"]],
  "water-internal-usage.category": [["Electronics", "Electronics"], ["Clothing", "Clothing"], ["Documents", "Documents"], ["Jewelry", "Jewelry"], ["Personal", "Personal"], ["Other", "Other"]],
  "water-loans.interestType": [["Simple", "Simple"], ["ReducingBalance", "ReducingBalance"], ["Flat", "Flat"], ["Unknown", "Unknown"]],
  "water-loans.lenderType": [["Bank", "Bank"], ["FinancialInstitution", "FinancialInstitution"], ["Individual", "Individual"], ["Owner", "Owner"], ["FamilyFriend", "FamilyFriend"], ["Supplier", "Supplier"], ["Other", "Other"]],
  "water-loans.paymentFrequency": [["Weekly", "Weekly"], ["BiWeekly", "BiWeekly"], ["Monthly", "Monthly"], ["Quarterly", "Quarterly"], ["Custom", "Custom"]],
  "water-loss-records.lossType": [["Damage", "Damage"], ["Mortality", "Mortality"], ["Theft", "Theft"], ["Spoilage", "Spoilage"], ["MissingStock", "MissingStock"], ["Other", "Other"]],
  // STATUSES in app/water-machines/page.tsx (was attendance statuses).
  "water-machines.status": [["Active", "Active"], ["Down", "Down"], ["UnderMaintenance", "UnderMaintenance"]],
  "water-maintenance.assetType": [["Machine", "Machine"], ["Vehicle", "Vehicle"], ["Borehole", "Borehole"], ["Generator", "Generator"], ["Other", "Other"]],
  "water-owner-money.paymentMethod": [["Cash", "Cash"], ["MoMo", "MoMo"], ["Bank Transfer", "Bank Transfer"], ["Cheque", "Cheque"], ["Card", "Card"], ["Other", "Other"]],
  "water-production-batches.shift": [["Morning", "Morning"], ["Afternoon", "Afternoon"], ["Night", "Night"], ["FullDay", "FullDay"]],
  "water-products-[id].productType": [["FinishedGood", "FinishedGood"], ["RawMaterial", "RawMaterial"], ["PackagingMaterial", "PackagingMaterial"], ["Other", "Other"]],
  "water-products.packagingUnit": [["Bag", "Bag"], ["Pack", "Pack"], ["Crate", "Crate"], ["Carton", "Carton"], ["Case", "Case"], ["Bundle", "Bundle"], ["Tray", "Tray"], ["Pallet", "Pallet"], ["None \u2014 Sold individually", "None \u2014 Sold individually"], ["Other", "Other"]],
  "water-products.productCategory": [["Sachet Water", "Sachet Water"], ["Bottled Water", "Bottled Water"], ["Dispenser Water", "Dispenser Water"], ["Bulk Water", "Bulk Water"], ["Packaging Materials", "Packaging Materials"], ["Water Treatment Materials", "Water Treatment Materials"], ["Cleaning Supplies", "Cleaning Supplies"], ["Machine Parts", "Machine Parts"], ["Vehicle Supplies", "Vehicle Supplies"], ["Other", "Other"]],
  "water-products.productType": [["FinishedGood", "FinishedGood"], ["RawMaterial", "RawMaterial"], ["PackagingMaterial", "PackagingMaterial"], ["Other", "Other"]],
  "water-products.sizeUnit": [["ml", "ml"], ["L", "L"], ["cl", "cl"], ["g", "g"], ["kg", "kg"], ["Other", "Other"]],
  "water-products.unit": [["Sachet", "Sachet"], ["Bottle", "Bottle"], ["Dispenser Bottle", "Dispenser Bottle"], ["Cup", "Cup"], ["Container", "Container"], ["Piece", "Piece"], ["Litre", "Litre"], ["Other", "Other"]],
  "water-raw-material-usage-history.category": [["Electronics", "Electronics"], ["Clothing", "Clothing"], ["Documents", "Documents"], ["Jewelry", "Jewelry"], ["Personal", "Personal"], ["Other", "Other"]],
  "water-raw-material-usage-history.paymentMethod": [["Cash", "Cash"], ["MoMo", "MoMo"], ["Bank Transfer", "Bank Transfer"], ["Cheque", "Cheque"], ["Card", "Card"], ["Other", "Other"]],
  // ROLES in app/water-staff/page.tsx (was the Generic company's roles).
  "water-staff.role": [["MachineOperator", "MachineOperator"], ["PackagingWorker", "PackagingWorker"], ["Loader", "Loader"], ["Driver", "Driver"], ["MotorKingRider", "MotorKingRider"], ["Salesperson", "Salesperson"], ["FactoryManager", "FactoryManager"], ["Accountant", "Accountant"], ["Cleaner", "Cleaner"], ["Security", "Security"], ["Other", "Other"]],
  "water-staff.salaryType": [["Daily", "Daily"], ["Weekly", "Weekly"], ["Monthly", "Monthly"], ["Commission", "Commission"], ["Mixed", "Mixed"]],
  "water-stock-transactions.txnType": [["Restock", "Restock (add stock)"], ["Adjust", "Adjust (signed)"], ["Return", "Return (add back)"]],
  "water-suppliers.isActive": [["yes", "Active"], ["no", "Inactive"]],
  "water-suppliers.supplierType": [["Raw Material Supplier", "Raw Material Supplier"], ["Packaging Supplier", "Packaging Supplier"], ["Fuel Supplier", "Fuel Supplier"], ["Machine Parts Supplier", "Machine Parts Supplier"], ["Vehicle Repair Supplier", "Vehicle Repair Supplier"], ["Utility Provider", "Utility Provider"], ["Service Provider", "Service Provider"], ["Other", "Other"]],
  "water-vehicles.status": [["Present", "Present"], ["Absent", "Absent"], ["Late", "Late"], ["HalfDay", "HalfDay"], ["OffDay", "OffDay"]],
  "water-vehicles.vehicleType": [["Truck", "Truck"], ["Van", "Van"], ["Tricycle", "Tricycle"], ["Motorbike", "Motorbike"], ["Pickup", "Pickup"], ["Other", "Other"]],
  // ---- resolved from the web pages and verified against the API ----
"egginventoryadjustment.adjustmentType": [["Correction", "Correction"], ["Correction", "Correction"], ["Stocktake", "Stocktake"], ["Stocktake", "Stocktake"], ["OpeningBalance", "OpeningBalance"], ["Opening balance", "Opening balance"]],
  "flock.supplierType": [["local", "Local"], ["foreign", "Foreign"]],
  "generic-inventory-adjustments.adjustmentType": [["Increase", "Increase (+)"], ["Decrease", "Decrease (−)"]],
  "hotel-billing-charges.chargeType": [["Room", "Room"], ["RoomService", "RoomService"], ["Minibar", "Minibar"], ["Laundry", "Laundry"], ["Damage", "Damage"], ["Restaurant", "Restaurant"], ["Spa", "Spa"], ["Transport", "Transport"], ["Telephone", "Telephone"], ["Other", "Other"]],
  "hotel-finance-cash-accounts.accountType": [["Cash", "Cash"], ["Bank", "Bank"], ["MobileMoney", "Mobile Money"]],
  "hotel-finance-cash-accounts.purpose": [["FrontDesk", "Front Desk — guest payments in"], ["Expenses", "Expenses — money out"], ["POS", "POS / Restaurant — orders in"], ["Payroll", "Payroll — salaries out"]],
  "poultry-assets.treatment": [["capitalise", "Capitalise to this investment"], ["expense", "Record as an operating expense"]],
  "restaurant-delivery-drivers.vehicleType": [["Motorcycle", "Motorcycle"], ["Car", "Car"], ["Bicycle", "Bicycle"], ["Van", "Van"]],
  "restaurant-floor-floors.shape": [["Square", "Square"], ["Round", "Round"], ["Booth", "Booth"], ["Bar", "Bar"], ["Long", "Long"]],
  "restaurant-online-settings.channelRestriction": [["Online", "Online Only"], ["QR", "QR Only"], ["Delivery", "Delivery Only"]],
  "restaurant-online-settings.discountType": [["Percentage", "Percentage"], ["FixedAmount", "Fixed Amount"], ["FreeDelivery", "Free Delivery"]],
  "water-assets.treatment": [["capitalise", "Capitalise to this asset"], ["expense", "Record as an operating expense"]],
"expenses.category": [["Feed", "Feed"], ["Veterinary", "Veterinary"], ["Equipment", "Equipment"], ["Labor", "Labor"], ["Utilities", "Utilities"], ["Other", "Other"]],
  "expenses.paymentMethod": [["Cash", "Cash"], ["Mobile Money", "Mobile Money"], ["Credit Card", "Credit Card"], ["Bank Transfer", "Bank Transfer"], ["Check", "Check"], ["Other", "Other"]],
  "feedusage.feedType": [["Starter Feed", "Starter Feed"], ["Grower Feed", "Grower Feed"], ["Layer Feed", "Layer Feed"], ["Broiler Feed", "Broiler Feed"], ["Organic Feed", "Organic Feed"], ["Custom Mix", "Custom Mix"]],
  "inventoryitem.category": [["Feed", "Feed"], ["Medication", "Medication"], ["Equipment", "Equipment"], ["Supplies", "Supplies"], ["Eggs", "Eggs"], ["Other", "Other"]],
  "inventoryitem.type": [["Feed", "Feed"], ["Medication", "Medication"], ["Equipment", "Equipment"], ["Tools", "Tools"], ["Cleaning Supplies", "Cleaning Supplies"], ["Other", "Other"]],
  "sales.paymentMethod": [["Cash", "Cash"], ["Credit Card", "Credit Card"], ["Bank Transfer", "Bank Transfer"], ["Check", "Check"], ["Mobile Money", "Mobile Money"]],
};
