// GENERATED from the API controllers: which verbs each page's endpoint
// supports. Drives whether the app offers create, edit and delete.

class PageVerbs {
  const PageVerbs({this.post = false, this.put = false, this.delete = false});
  final bool post;
  final bool put;
  final bool delete;
}

const Map<String, PageVerbs> pageVerbs = {
  // Hand-added: the curated spec points at /Admin/employees, not the
  // read-only /Admin/company-employees the generator saw.
  "admin-company-employees": PageVerbs(post: true, put: true, delete: true),
  "announcements": PageVerbs(post: true, delete: true),
  "assets": PageVerbs(post: true, put: true),
  "auditlogs": PageVerbs(post: true),
  "business-categories": PageVerbs(put: true),
  "chat-threads": PageVerbs(post: true),
  "chat-threads-messages": PageVerbs(post: true),
  "customer": PageVerbs(post: true, put: true, delete: true),
  "egginventoryadjustment": PageVerbs(post: true, put: true, delete: true),
  "eggproduction": PageVerbs(post: true, put: true, delete: true),
  "employee-loans": PageVerbs(post: true, put: true, delete: true),
  "expense": PageVerbs(post: true, put: true, delete: true),
  "expenses": PageVerbs(post: true, put: true, delete: true),
  "farmobservation": PageVerbs(post: true),
  "farmproductionsettings": PageVerbs(put: true),
  "feedinventoryadjustment": PageVerbs(post: true, put: true, delete: true),
  "feedusage": PageVerbs(post: true, put: true, delete: true),
  "flock": PageVerbs(post: true, put: true, delete: true),
  "flocks": PageVerbs(post: true, put: true, delete: true),
  "generic-balances-customer-payments": PageVerbs(post: true),
  "generic-balances-supplier-payments": PageVerbs(post: true),
  "generic-business-settings": PageVerbs(put: true),
  "generic-business-template": PageVerbs(post: true),
  "generic-cash-accounts": PageVerbs(post: true, put: true, delete: true),
  "generic-cash-defaults": PageVerbs(put: true),
  "generic-cash-transfers": PageVerbs(post: true),
  "generic-customer-payments": PageVerbs(post: true),
  "generic-customers": PageVerbs(post: true, put: true, delete: true),
  "generic-daily-closings": PageVerbs(post: true),
  "generic-expense-categories": PageVerbs(post: true, put: true, delete: true),
  "generic-expenses": PageVerbs(post: true),
  "generic-internal-usage": PageVerbs(post: true, put: true, delete: true),
  "generic-inventory-adjustments": PageVerbs(post: true),
  "generic-module-settings": PageVerbs(put: true),
  "generic-owner-entries": PageVerbs(post: true),
  "generic-payroll-runs": PageVerbs(post: true, put: true),
  "generic-product-categories": PageVerbs(post: true, put: true, delete: true),
  "generic-products": PageVerbs(post: true, put: true, delete: true),
  "generic-purchases": PageVerbs(post: true),
  "generic-recurring-expenses": PageVerbs(post: true),
  "generic-sales": PageVerbs(post: true),
  "generic-service-categories": PageVerbs(post: true, put: true, delete: true),
  "generic-service-plans": PageVerbs(put: true),
  "generic-services": PageVerbs(post: true, put: true, delete: true),
  "generic-staff": PageVerbs(post: true, put: true, delete: true),
  "generic-staff-attendance": PageVerbs(post: true, put: true, delete: true),
  "generic-staff-payments": PageVerbs(post: true),
  "generic-subscriptions": PageVerbs(post: true),
  "generic-supplier-payments": PageVerbs(post: true),
  "generic-suppliers": PageVerbs(post: true, put: true, delete: true),
  "health": PageVerbs(post: true, put: true, delete: true),
  "hotel-billing-charges": PageVerbs(post: true),
  "hotel-billing-payments": PageVerbs(post: true),
  "hotel-bookings": PageVerbs(post: true, put: true),
  "hotel-communications": PageVerbs(post: true),
  "hotel-deposits": PageVerbs(post: true),
  "hotel-finance-cash-accounts": PageVerbs(post: true, delete: true),
  "hotel-finance-expense-categories": PageVerbs(post: true),
  "hotel-finance-expenses": PageVerbs(post: true),
  "hotel-guest-requests": PageVerbs(post: true),
  "hotel-guests": PageVerbs(post: true, put: true, delete: true),
  "hotel-housekeeping": PageVerbs(post: true),
  "hotel-housekeeping-schedule": PageVerbs(post: true),
  "hotel-inventory": PageVerbs(post: true),
  "hotel-lost-and-found": PageVerbs(post: true),
  "hotel-maintenance": PageVerbs(post: true),
  "hotel-night-audit": PageVerbs(post: true),
  "hotel-payroll-runs": PageVerbs(post: true, delete: true),
  "hotel-reports-daily-closings": PageVerbs(post: true),
  "hotel-restaurant-menu": PageVerbs(post: true, put: true, delete: true),
  "hotel-restaurant-orders": PageVerbs(post: true),
  "hotel-restaurant-tables": PageVerbs(post: true),
  "hotel-room-rates": PageVerbs(post: true, delete: true),
  "hotel-rooms": PageVerbs(post: true, put: true, delete: true),
  "hotel-rooms-amenities": PageVerbs(delete: true),
  "hotel-setup-amenities": PageVerbs(post: true, put: true, delete: true),
  "hotel-setup-floors": PageVerbs(post: true, put: true, delete: true),
  "hotel-setup-profile": PageVerbs(post: true),
  "hotel-setup-room-types": PageVerbs(post: true, put: true, delete: true),
  "hotel-shift-handovers": PageVerbs(post: true),
  "hotel-staff": PageVerbs(post: true, put: true, delete: true),
  "house": PageVerbs(post: true, put: true, delete: true),
  "iam-access-review": PageVerbs(post: true),
  "iam-overrides": PageVerbs(post: true, delete: true),
  "iam-policy": PageVerbs(put: true),
  "iam-roles": PageVerbs(post: true, delete: true),
  "iam-roles-permissions": PageVerbs(put: true),
  "iam-sessions": PageVerbs(delete: true),
  "inventoryitem": PageVerbs(post: true, put: true, delete: true),
  "loans": PageVerbs(post: true, put: true),
  "mainflockbatch": PageVerbs(post: true, put: true, delete: true),
  "owner-money": PageVerbs(post: true, put: true),
  "poultry-assets": PageVerbs(post: true, put: true),
  "poultry-assets-categories": PageVerbs(post: true),
  "poultry-cash-accounts": PageVerbs(post: true, put: true, delete: true),
  "poultry-cash-reconciliations": PageVerbs(post: true, put: true, delete: true),
  "poultry-cash-transfers": PageVerbs(post: true, put: true),
  "poultry-company": PageVerbs(put: true),
  "poultry-customer-payments": PageVerbs(post: true),
  "poultry-daily-closings": PageVerbs(post: true, delete: true),
  "poultry-driver-returns": PageVerbs(post: true, delete: true),
  "poultry-drivers": PageVerbs(post: true, put: true, delete: true),
  "poultry-employee-loans": PageVerbs(post: true, put: true, delete: true),
  "poultry-feed-formulas": PageVerbs(post: true, delete: true),
  "poultry-feed-production": PageVerbs(post: true, delete: true),
  "poultry-financial-settings-cost-recognition": PageVerbs(put: true),
  "poultry-internal-usage": PageVerbs(post: true, put: true, delete: true),
  "poultry-loans": PageVerbs(post: true, put: true),
  "poultry-loss-records": PageVerbs(post: true, put: true, delete: true),
  "poultry-owner-money": PageVerbs(post: true, put: true),
  "poultry-payments": PageVerbs(post: true),
  "poultry-payroll-deductions": PageVerbs(post: true, delete: true),
  "poultry-payroll-runs": PageVerbs(post: true, delete: true),
  "poultry-production-batches": PageVerbs(post: true, put: true, delete: true),
  "poultry-production-losses": PageVerbs(post: true, put: true, delete: true),
  "poultry-products": PageVerbs(post: true, put: true, delete: true),
  "poultry-products-recipe": PageVerbs(put: true, delete: true),
  "poultry-raw-material-adjustments": PageVerbs(post: true, put: true, delete: true),
  "poultry-raw-material-items": PageVerbs(post: true, put: true, delete: true),
  "poultry-raw-material-purchases": PageVerbs(post: true, put: true, delete: true),
  "poultry-routes": PageVerbs(post: true, put: true, delete: true),
  "poultry-staff": PageVerbs(post: true, put: true, delete: true),
  "poultry-staff-attendance": PageVerbs(post: true, delete: true),
  "poultry-stock-transactions": PageVerbs(post: true),
  "poultry-supplier-payments": PageVerbs(post: true),
  "poultry-vehicle-loadings": PageVerbs(post: true, delete: true),
  "poultry-vehicles": PageVerbs(post: true, put: true, delete: true),
  "production-records": PageVerbs(post: true, put: true, delete: true),
  "productionbatchrecord": PageVerbs(post: true, put: true, delete: true),
  "productionrecord": PageVerbs(post: true, put: true, delete: true),
  "raw-materials": PageVerbs(post: true, put: true, delete: true),
  "restaurant-crm-campaigns": PageVerbs(post: true, delete: true),
  "restaurant-crm-customers": PageVerbs(post: true, put: true, delete: true),
  "restaurant-crm-feedback": PageVerbs(post: true),
  "restaurant-custom-options": PageVerbs(post: true, delete: true),
  "restaurant-delivery-assignments": PageVerbs(post: true),
  "restaurant-delivery-drivers": PageVerbs(post: true, put: true, delete: true),
  "restaurant-delivery-platforms": PageVerbs(post: true, put: true, delete: true),
  "restaurant-delivery-zones": PageVerbs(post: true, put: true, delete: true),
  "restaurant-events": PageVerbs(post: true, put: true, delete: true),
  "restaurant-expenses": PageVerbs(post: true, put: true, delete: true),
  "restaurant-expenses-categories": PageVerbs(post: true, delete: true),
  "restaurant-expenses-receipt-template": PageVerbs(post: true),
  "restaurant-floor-floors": PageVerbs(post: true, put: true, delete: true),
  "restaurant-floor-tables": PageVerbs(post: true, put: true, delete: true),
  "restaurant-gift-cards": PageVerbs(post: true, put: true, delete: true),
  "restaurant-inventory-ingredients": PageVerbs(post: true, put: true, delete: true),
  "restaurant-inventory-stock-takes": PageVerbs(post: true),
  "restaurant-inventory-waste": PageVerbs(post: true),
  "restaurant-kds-stations": PageVerbs(post: true, put: true, delete: true),
  "restaurant-kds-stations-items": PageVerbs(post: true),
  "restaurant-loyalty-accounts": PageVerbs(post: true),
  "restaurant-loyalty-settings": PageVerbs(post: true),
  "restaurant-menu": PageVerbs(post: true, put: true, delete: true),
  "restaurant-menu-categories": PageVerbs(post: true, put: true, delete: true),
  "restaurant-menu-combos": PageVerbs(post: true, put: true, delete: true),
  "restaurant-menu-combos-items": PageVerbs(post: true),
  "restaurant-menu-item-names": PageVerbs(post: true),
  "restaurant-menu-items": PageVerbs(post: true, put: true, delete: true),
  "restaurant-menu-items-modifier-groups": PageVerbs(post: true),
  "restaurant-menu-items-tags": PageVerbs(post: true),
  "restaurant-menu-modifier-groups": PageVerbs(post: true, put: true, delete: true),
  "restaurant-menu-modifiers": PageVerbs(post: true, put: true, delete: true),
  "restaurant-menu-schedules": PageVerbs(post: true, put: true, delete: true),
  "restaurant-menu-schedules-items": PageVerbs(post: true),
  "restaurant-notifications": PageVerbs(post: true, put: true, delete: true),
  "restaurant-notifications-settings": PageVerbs(post: true),
  "restaurant-online-promo-codes": PageVerbs(post: true, put: true, delete: true),
  "restaurant-online-qr-codes": PageVerbs(post: true, delete: true),
  "restaurant-online-settings": PageVerbs(post: true),
  "restaurant-orders": PageVerbs(post: true),
  "restaurant-orders-discounts": PageVerbs(post: true, put: true, delete: true),
  "restaurant-orders-items": PageVerbs(post: true),
  "restaurant-orders-payments": PageVerbs(post: true),
  "restaurant-reports-kpi-alerts": PageVerbs(post: true, delete: true),
  "restaurant-reservations": PageVerbs(post: true, put: true, delete: true),
  "restaurant-reservations-settings": PageVerbs(post: true),
  "restaurant-reservations-waitlist": PageVerbs(post: true, delete: true),
  "restaurant-setup-profile": PageVerbs(post: true),
  // PUT added by hand: the web edits suppliers (updateSupplier).
  "restaurant-setup-suppliers": PageVerbs(post: true, put: true, delete: true),
  "restaurant-staff": PageVerbs(post: true, put: true, delete: true),
  "sale": PageVerbs(post: true, put: true, delete: true),
  "sales": PageVerbs(post: true, put: true, delete: true),
  "supplier": PageVerbs(post: true, put: true, delete: true),
  "water-assets": PageVerbs(post: true, put: true),
  "water-assets-categories": PageVerbs(post: true),
  "water-boreholes": PageVerbs(post: true, put: true, delete: true),
  "water-cash-accounts": PageVerbs(post: true, put: true, delete: true),
  "water-cash-reconciliations": PageVerbs(post: true, put: true, delete: true),
  "water-cash-transfers": PageVerbs(post: true, put: true, delete: true),
  "water-company": PageVerbs(put: true),
  "water-customer-payments": PageVerbs(post: true),
  "water-customers": PageVerbs(post: true, put: true, delete: true),
  "water-customers-ledger": PageVerbs(post: true),
  "water-daily-closings": PageVerbs(post: true, delete: true),
  "water-daily-productions": PageVerbs(post: true, put: true, delete: true),
  "water-driver-returns": PageVerbs(post: true, delete: true),
  "water-drivers": PageVerbs(post: true, put: true, delete: true),
  "water-drivers-job-roles": PageVerbs(post: true),
  "water-expense-categories": PageVerbs(post: true, put: true, delete: true),
  "water-expenses": PageVerbs(post: true, put: true, delete: true),
  "water-financial-settings-cost-recognition": PageVerbs(put: true),
  "water-internal-usage": PageVerbs(post: true, put: true, delete: true),
  "water-loans": PageVerbs(post: true, put: true),
  "water-loss-records": PageVerbs(post: true, put: true, delete: true),
  "water-machines": PageVerbs(post: true, put: true, delete: true),
  "water-maintenance": PageVerbs(post: true, put: true, delete: true),
  "water-maintenance-logs": PageVerbs(post: true, put: true, delete: true),
  "water-owner-money": PageVerbs(post: true, put: true),
  "water-payments": PageVerbs(post: true),
  "water-payroll-runs": PageVerbs(post: true, delete: true),
  "water-production-batches": PageVerbs(post: true, put: true, delete: true),
  "water-production-losses": PageVerbs(post: true, put: true, delete: true),
  "water-products": PageVerbs(post: true, put: true, delete: true),
  "water-products-recipe": PageVerbs(post: true, put: true, delete: true),
  "water-pumping-logs": PageVerbs(post: true),
  "water-quality-tests": PageVerbs(post: true),
  "water-raw-material-adjustments": PageVerbs(post: true, put: true, delete: true),
  "water-raw-material-items": PageVerbs(post: true, put: true, delete: true),
  "water-raw-material-purchases": PageVerbs(post: true, put: true, delete: true),
  "water-raw-material-usage": PageVerbs(post: true, put: true, delete: true),
  "water-raw-material-usage-history": PageVerbs(post: true),
  "water-routes": PageVerbs(post: true, put: true, delete: true),
  "water-sales": PageVerbs(post: true, delete: true),
  "water-staff": PageVerbs(post: true, put: true, delete: true),
  "water-staff-attendance": PageVerbs(post: true, delete: true),
  "water-stock-transactions": PageVerbs(post: true),
  "water-supplier-payments": PageVerbs(post: true),
  "water-suppliers": PageVerbs(post: true, put: true, delete: true),
  "water-vehicle-loadings": PageVerbs(post: true, delete: true),
  "water-vehicles": PageVerbs(post: true, put: true, delete: true),
};
