// GENERATED from the web: the page name and blurb the site shows.
//
// Without an entry a page falls back to the generated spec title,
// which is an API action name — that is how a page ended up titled
// "Get current user". Every wired page has a real name here.

class PageHeaderDef {
  const PageHeaderDef({required this.title, required this.description,
      this.color, this.action});

  final String title;
  final String description;
  final String? color;
  final String? action;
}

const Map<String, PageHeaderDef> pageHeaders = {
  "admin-company-employees": PageHeaderDef(title: "Employees", description: "Manage your staff members and their access", color: "blue", action: "Add Employee"),
  "assets": PageHeaderDef(title: "Capital Investments/Assets", description: "Track major long-term business investments, their cost, depreciation, and current book value.", action: "New investment"),
  "auditlogs": PageHeaderDef(title: "Poultry Changes Report", description: "Every create, update and delete on this farm \u2014 who changed what, and when.", action: "Record details"),
  "authentication-get-current-user": PageHeaderDef(title: "Profile", description: ""),
  "businessoffice-company-snapshot": PageHeaderDef(title: "Business Office", description: "", action: "Create company"),
  "cash": PageHeaderDef(title: "Cash", description: "", action: "Add Adjustment"),
  "companies-mine": PageHeaderDef(title: "Companies", description: "", action: "New company"),
  "customer": PageHeaderDef(title: "Customers", description: "Manage your customer database", color: "purple", action: "Add Customer"),
  "egginventoryadjustment": PageHeaderDef(title: "Egg tracker", description: "Ledger from egg sorting production, egg sales, and optional manual adjustments (like Cash at hand).", action: "Add adjustment"),
  "eggproduction": PageHeaderDef(title: "Egg Sorting", description: "Daily collection by flock (9am / 12pm / 4pm) for the filters below.", color: "yellow", action: "Add Egg Sorting record"),
  "employee-loans": PageHeaderDef(title: "Poultry Employee Loans", description: "", action: "New loan / advance"),
  "expenses": PageHeaderDef(title: "Expenses", description: "Track operational costs and financial records", color: "red", action: "Add Expense"),
  "farmproductionsettings": PageHeaderDef(title: "Egg Pick Time Settings", description: "Configure the time of day each egg pick represents for this farm. These times are used for display and reporting, while production records are labelled 1st Pick through 6th Pick.", color: "emerald"),
  "feedusage": PageHeaderDef(title: "Feed Usage", description: "", action: "Add Usage"),
  "flock": PageHeaderDef(title: "Flock Purchases (Batches)", description: "Manage your bird flock batches", color: "green", action: "Add Flock Batch"),
  "flocks": PageHeaderDef(title: "Flock Groups (Pens / Flocks)", description: "Manage your bird flocks", color: "green", action: "Add Flock"),
  "generic-billing-runs": PageHeaderDef(title: "Billing runs", description: ""),
  "generic-business-template": PageHeaderDef(title: "Generic Setup/Wizard", description: "", action: "Add your"),
  "generic-cash-accounts": PageHeaderDef(title: "Cash & Accounts", description: ""),
  "generic-cash-transfers": PageHeaderDef(title: "Generic Cash Transfers", description: "", action: "New transfer"),
  "generic-customer-payments": PageHeaderDef(title: "Generic Customer Payments", description: "", action: "Record payment"),
  "generic-customers": PageHeaderDef(title: "Generic Customers", description: ""),
  "generic-daily-closings": PageHeaderDef(title: "Daily Closing", description: ""),
  "generic-expenses": PageHeaderDef(title: "Generic Expenses", description: "", action: "New expense"),
  "generic-internal-usage": PageHeaderDef(title: "Generic Internal Use", description: "", action: "Record internal use"),
  "generic-inventory-adjustments": PageHeaderDef(title: "Generic Stock Adjustments", description: "", action: "New adjustment"),
  "generic-owner-entries": PageHeaderDef(title: "Generic Owner Money", description: ""),
  "generic-payroll-runs": PageHeaderDef(title: "Generic Payroll", description: "", action: "New payroll run"),
  "generic-products": PageHeaderDef(title: "Inventory", description: "Stock-on-hand for every tracked product. Adjustments via Stock Adjustments page."),
  "generic-purchases": PageHeaderDef(title: "Generic Purchases", description: "", action: "New purchase"),
  "generic-recurring-expenses": PageHeaderDef(title: "Generic Recurring Expenses", description: "", action: "New recurring expense"),
  "generic-reports-dashboard": PageHeaderDef(title: "Generic Dashboard", description: "", action: "New sale"),
  "generic-sales": PageHeaderDef(title: "Generic Sales", description: "", action: "New sale"),
  "generic-service-plans": PageHeaderDef(title: "Generic Service Plans", description: ""),
  "generic-staff": PageHeaderDef(title: "Generic Staff", description: "", action: "Add staff"),
  "generic-staff-attendance": PageHeaderDef(title: "Attendance", description: ""),
  "generic-staff-payments": PageHeaderDef(title: "Generic Staff Payments", description: "", action: "Record payment"),
  "generic-subscriptions": PageHeaderDef(title: "Generic Subscriptions", description: ""),
  "generic-supplier-payments": PageHeaderDef(title: "Generic Supplier Payments", description: "", action: "Record payment"),
  "generic-suppliers": PageHeaderDef(title: "Generic Suppliers", description: "", action: "New supplier"),
  "health": PageHeaderDef(title: "Health Records", description: "Track vaccinations, medications, and water consumption", color: "red", action: "Add Health Record"),
  "hotel-billing-charges": PageHeaderDef(title: "Hotel Billing", description: "", action: "Add Charge"),
  "hotel-billing-invoices": PageHeaderDef(title: "Invoices", description: ""),
  "hotel-billing-payments": PageHeaderDef(title: "Hotel Reports/Billing Report", description: ""),
  "hotel-bookings": PageHeaderDef(title: "Hotel Reports/Guest Report", description: "", action: "New Guests"),
  "hotel-checkin-history": PageHeaderDef(title: "Hotel Stay History", description: ""),
  "hotel-communications": PageHeaderDef(title: "Hotel Communications", description: "", action: "Log Entry"),
  "hotel-finance-cash-accounts": PageHeaderDef(title: "Hotel Reports/Cash Flow Report", description: ""),
  "hotel-finance-expense-categories": PageHeaderDef(title: "Hotel Expenses", description: "", action: "Record Expense"),
  "hotel-finance-expenses": PageHeaderDef(title: "Hotel Payments", description: "", action: "Record Payment"),
  "hotel-guest-requests": PageHeaderDef(title: "Hotel Guest Requests", description: "", action: "New Request"),
  "hotel-guests": PageHeaderDef(title: "Hotel Guests", description: "", action: "Add Guest"),
  "hotel-housekeeping": PageHeaderDef(title: "Housekeeping", description: ""),
  "hotel-housekeeping-schedule": PageHeaderDef(title: "Hotel Housekeeping Schedule", description: "", action: "Add Schedule Entry"),
  "hotel-inventory": PageHeaderDef(title: "Hotel Reports/Inventory Report", description: ""),
  "hotel-lost-and-found": PageHeaderDef(title: "Hotel Lost Found", description: "", action: "Log Item"),
  "hotel-maintenance": PageHeaderDef(title: "Hotel Reports/Maintenance Report", description: ""),
  "hotel-night-audit": PageHeaderDef(title: "Hotel Night Audit", description: ""),
  "hotel-payroll-runs": PageHeaderDef(title: "Hotel Payroll", description: "", action: "New payroll run"),
  "hotel-reports-daily-closings": PageHeaderDef(title: "Hotel Reports/Weekly Report", description: ""),
  "hotel-restaurant-orders": PageHeaderDef(title: "Room Service", description: ""),
  "hotel-restaurant-tables": PageHeaderDef(title: "Hotel Menu", description: "", action: "Add Item"),
  "hotel-rooms": PageHeaderDef(title: "Hotel Rooms", description: "", action: "Add Room"),
  "hotel-setup-amenities": PageHeaderDef(title: "Hotel Setup", description: "Work left to right \u2014 each step feeds the next", action: "Add Room"),
  "hotel-setup-profile": PageHeaderDef(title: "Hotel Company Setup", description: ""),
  "hotel-setup-room-types": PageHeaderDef(title: "Hotel Availability", description: ""),
  "hotel-shift-handovers": PageHeaderDef(title: "Hotel Shift Handover", description: "", action: "New Handover"),
  "hotel-staff": PageHeaderDef(title: "Hotel Staff", description: "", action: "Add Staff"),
  "house": PageHeaderDef(title: "Houses", description: "Manage poultry houses", color: "blue", action: "Add House"),
  "inventoryitem": PageHeaderDef(title: "Supplies", description: "Track and manage farm supplies", color: "purple", action: "Add Supply"),
  "loans": PageHeaderDef(title: "Poultry Loans", description: "", action: "Record loan"),
  "mainflockbatch": PageHeaderDef(title: "Batch Production Summary", description: "Production performance rolled up per flock batch.", color: "emerald"),
  "owner-money": PageHeaderDef(title: "Poultry Owner Money", description: "", action: "Record contribution"),
  "payments-subscription-tiers": PageHeaderDef(title: "Billing", description: ""),
  "poultry-cash-accounts": PageHeaderDef(title: "Supplier Payments", description: ""),
  "poultry-cash-flow": PageHeaderDef(title: "Cash Flow", description: "", action: "Add Adjustment"),
  "poultry-cash-reconciliations": PageHeaderDef(title: "Poultry Cash Reconciliation", description: "", action: "Post it"),
  "poultry-cash-transfers": PageHeaderDef(title: "Poultry Cash Transfers", description: "", action: "Record transfer"),
  "poultry-closing-report": PageHeaderDef(title: "Closing by Category", description: "Period totals grouped into financial, production, inventory and birds."),
  "poultry-company": PageHeaderDef(title: "Poultry farm setup", description: "Everything the daily flow depends on \u2014 products, drivers, houses, flock groups, suppliers, staff. Add a row here to make it available in production, sales, deliveries and payroll."),
  "poultry-customer-balances": PageHeaderDef(title: "Customer Balances", description: ""),
  "poultry-daily-closings": PageHeaderDef(title: "Daily Closing", description: "", action: "New closing"),
  "poultry-deferred-inventory-costs": PageHeaderDef(title: "Deferred inventory cost", description: "Track inventory purchases whose costs are recognized in Profit &amp; Loss as the inventory is consumed."),
  "poultry-deliveries": PageHeaderDef(title: "Poultry Deliveries", description: "", action: "New load"),
  "poultry-driver-returns": PageHeaderDef(title: "Poultry Driver Returns", description: "", action: "Add product"),
  "poultry-drivers": PageHeaderDef(title: "Poultry Drivers", description: "", action: "New employee"),
  "poultry-feed-formulas": PageHeaderDef(title: "Feed Formulas", description: "Reusable recipes for producing finished feed from ingredients. Used to auto-calculate quantities when producing feed.", action: "New Formula"),
  "poultry-feed-production": PageHeaderDef(title: "Feed Production", description: "Produce finished feed from ingredients \u2014 with full costing, inventory and cash impact.", action: "New Batch"),
  "poultry-financial-activity": PageHeaderDef(title: "Financial Activity", description: "See how business activity affects cash, revenue, expenses, profit and financial position."),
  "poultry-financial-settings-cost-recognition": PageHeaderDef(title: "Poultry Financial Settings", description: ""),
  "poultry-internal-usage": PageHeaderDef(title: "Poultry Internal Use", description: "", action: "Record internal use"),
  "poultry-loss-records": PageHeaderDef(title: "Loss & Damage Records", description: "Manual losses \u2014 damages, mortality, spoilage, missing stock.", action: "New record"),
  "poultry-owner-money": PageHeaderDef(title: "Poultry/Reports/Money", description: ""),
  "poultry-payments": PageHeaderDef(title: "Payments", description: ""),
  "poultry-payroll-deductions": PageHeaderDef(title: "Poultry Payroll", description: "", action: "New payroll run"),
  "poultry-products": PageHeaderDef(title: "Poultry inventory", description: "Finished products and raw materials in one place."),
  "poultry-raw-material-items": PageHeaderDef(title: "Medication Tracker", description: "Each medication tracked separately \u2014 purchases in, production usage out, and the quantity left for each. Same source as Raw Materials &amp; Supplies."),
  "poultry-raw-material-purchases": PageHeaderDef(title: "Feed inventory tracker", description: "Ledger from purchases, feed production, flock consumption and adjustments \u2014 every movement behind one ingredient&apos;s or finished feed&apos;s stock figure."),
  "poultry-reports-birds-on-hand": PageHeaderDef(title: "Birds on Hand", description: ""),
  "poultry-reports-cash-flow-detail": PageHeaderDef(title: "Cash Flow Detail", description: ""),
  "poultry-reports-cash-movement": PageHeaderDef(title: "Cash Movement", description: ""),
  "poultry-reports-cost-per-egg": PageHeaderDef(title: "Cost Per Egg", description: ""),
  "poultry-reports-customer-balance": PageHeaderDef(title: "Customer Balance", description: ""),
  "poultry-reports-daily-egg-production": PageHeaderDef(title: "Daily Egg Production", description: ""),
  "poultry-reports-driver-collection": PageHeaderDef(title: "Poultry Driver Report", description: ""),
  "poultry-reports-driver-reconciliation": PageHeaderDef(title: "Poultry Reports/Driver Accountability", description: ""),
  "poultry-reports-egg-sales": PageHeaderDef(title: "Egg Sales", description: ""),
  "poultry-reports-egg-stock-balance": PageHeaderDef(title: "Egg Stock Balance", description: ""),
  "poultry-reports-end-of-flock": PageHeaderDef(title: "End-of-Flock", description: ""),
  "poultry-reports-expense-summary": PageHeaderDef(title: "Expense Summary", description: ""),
  "poultry-reports-feed-cost-per-egg": PageHeaderDef(title: "Feed Cost Per Egg", description: ""),
  "poultry-reports-feed-inventory-balance": PageHeaderDef(title: "Feed Inventory Balance", description: ""),
  "poultry-reports-feed-usage": PageHeaderDef(title: "Feed Usage", description: ""),
  "poultry-reports-flock-production-summary": PageHeaderDef(title: "Flock Production Summary", description: ""),
  "poultry-reports-hen-day-production": PageHeaderDef(title: "Hen-Day Production", description: ""),
  "poultry-reports-medicine-usage": PageHeaderDef(title: "Medicine Usage", description: ""),
  "poultry-reports-missing-daily-records": PageHeaderDef(title: "Missing Daily Records", description: ""),
  "poultry-reports-mortality": PageHeaderDef(title: "Mortality", description: ""),
  "poultry-reports-profit-loss": PageHeaderDef(title: "Profit & Loss", description: ""),
  "poultry-reports-profit-loss-by-flock": PageHeaderDef(title: "Profit & Loss by Flock", description: ""),
  "poultry-reports-supplier-balance": PageHeaderDef(title: "Supplier Balance", description: ""),
  "poultry-reports-vaccination-schedule": PageHeaderDef(title: "Vaccination Schedule", description: ""),
  "poultry-routes": PageHeaderDef(title: "Poultry Routes", description: "", action: "New route"),
  "poultry-staff": PageHeaderDef(title: "Poultry Staff", description: "", action: "New staff"),
  "poultry-stock-transactions": PageHeaderDef(title: "Stock Movements", description: "All stock increases and decreases \u2014 finished products and raw materials. Production, sales, purchases and manual entries.", action: "New movement"),
  "poultry-supplier-balances": PageHeaderDef(title: "Supplier Balances", description: ""),
  "poultry-vehicles": PageHeaderDef(title: "Poultry Vehicles", description: "", action: "New vehicle"),
  "production-records": PageHeaderDef(title: "Production Records", description: "Track daily egg production and performance metrics", color: "emerald", action: "Log Production"),
  "productionbatchrecord": PageHeaderDef(title: "Batch Production Records", description: "Log batch-level production and allocate totals across flocks", color: "emerald", action: "Log Batch Production"),
  "raw-materials": PageHeaderDef(title: "Raw Materials &amp; Supplies", description: "Track feed inputs, packaging, medication and other supplies \u2014 purchases, costing and usage.", action: "New Item"),
  "restaurant-crm-customers": PageHeaderDef(title: "Customer Relationships", description: "Profiles, feedback, and campaigns", action: "Add Customer"),
  "restaurant-delivery-drivers": PageHeaderDef(title: "Delivery Management", description: "Drivers, zones, dispatch and third-party platforms", action: "Add Driver"),
  "restaurant-events": PageHeaderDef(title: "Restaurant Events", description: "", action: "New Event"),
  "restaurant-expenses": PageHeaderDef(title: "Restaurant Expenses", description: "", action: "Record Expense"),
  "restaurant-floor-floors": PageHeaderDef(title: "Restaurant Floor Plan", description: "", action: "Add Area"),
  "restaurant-gift-cards": PageHeaderDef(title: "Restaurant Gift Cards", description: "", action: "Issue Card"),
  "restaurant-inventory-ingredients": PageHeaderDef(title: "Restaurant Inventory", description: "", action: "Add Ingredient"),
  "restaurant-kds-stations": PageHeaderDef(title: "Restaurant Kds", description: ""),
  "restaurant-loyalty-accounts": PageHeaderDef(title: "Restaurant Loyalty", description: "", action: "Add Points"),
  "restaurant-menu-items": PageHeaderDef(title: "Hotel Reports/Menu Performance", description: ""),
  "restaurant-notifications": PageHeaderDef(title: "Restaurant Notifications", description: ""),
  "restaurant-online-pending-orders": PageHeaderDef(title: "Restaurant Pending Orders", description: ""),
  "restaurant-online-qr-codes": PageHeaderDef(title: "Restaurant Qr Print", description: ""),
  "restaurant-online-settings": PageHeaderDef(title: "Online Ordering", description: "QR codes, promo codes and delivery settings", action: "Create it"),
  "restaurant-orders": PageHeaderDef(title: "Restaurant Pos", description: "", action: "New Order"),
  "restaurant-public-menu": PageHeaderDef(title: "Restaurant not found", description: "That code didn&apos;t match a restaurant. Please scan the QR code again, or ask a member of staff for help."),
  "restaurant-reservations": PageHeaderDef(title: "Reservations & Waitlist", description: "Manage bookings and walk-in guests", action: "New Reservation"),
  "restaurant-setup-profile": PageHeaderDef(title: "Restaurant Setup", description: "Configure your restaurant profile, menu schedules and modifiers", action: "Add Schedule"),
  "restaurant-staff": PageHeaderDef(title: "Restaurant Staff", description: "", action: "Add Staff"),
  "sales": PageHeaderDef(title: "Sales", description: "Manage your farm sales and transactions", color: "green", action: "Add Sale"),
  "supplier": PageHeaderDef(title: "Suppliers", description: "Manage vendors you buy feed and supplies from", action: "Add supplier"),
  "system-farms": PageHeaderDef(title: "System farms", description: "Registered farms, subscription status (paid flag on any farm user), and headcounts."),
  "water-assets": PageHeaderDef(title: "Assets", description: "Track major long-term business assets, their cost, depreciation, and current book value.", action: "New asset"),
  "water-boreholes": PageHeaderDef(title: "Water Boreholes", description: "", action: "New borehole"),
  "water-cash-accounts": PageHeaderDef(title: "Water Cash Accounts", description: "", action: "Record Cash Adjustment"),
  "water-cash-flow": PageHeaderDef(title: "Water Cash Flow", description: "", action: "Add Adjustment"),
  "water-cash-reconciliations": PageHeaderDef(title: "Water Cash Reconciliation", description: "", action: "Post it"),
  "water-cash-transfers": PageHeaderDef(title: "Water Cash Transfers", description: "", action: "Record transfer"),
  "water-company": PageHeaderDef(title: "Water company setup", description: "Everything the daily flow depends on \u2014 products, drivers, machines, routes, suppliers, staff. Add a row here to make it available in production, sales, payroll, etc."),
  "water-customer-balances": PageHeaderDef(title: "Customer Balances", description: ""),
  "water-customers": PageHeaderDef(title: "Water Customers", description: "", action: "New customer"),
  "water-daily-closings": PageHeaderDef(title: "Water Daily Closing", description: "", action: "Create draft"),
  "water-daily-productions": PageHeaderDef(title: "Batch production", description: "Record the day&apos;s totals, then split them across the machines that produced them.", color: "sky", action: "Log batch production"),
  "water-dashboard-summary": PageHeaderDef(title: "Water Dashboard", description: ""),
  "water-deferred-inventory-costs": PageHeaderDef(title: "Deferred inventory cost", description: "Track raw material purchases whose costs are recognized in Profit &amp; Loss as production consumes the stock."),
  "water-driver-returns": PageHeaderDef(title: "Water Driver Returns", description: "", action: "Add product"),
  "water-drivers-list-for-farm": PageHeaderDef(title: "Water Drivers", description: "", action: "New employee"),
  "water-expenses": PageHeaderDef(title: "Water Expenses", description: "", action: "Record expense"),
  "water-financial-settings-items": PageHeaderDef(title: "Water Financial Settings", description: ""),
  "water-internal-usage": PageHeaderDef(title: "Water Internal Use", description: "", action: "Record internal use"),
  "water-loans": PageHeaderDef(title: "Water Loans", description: "", action: "Record loan"),
  "water-loss-records": PageHeaderDef(title: "Water Loss Records", description: "", action: "Record loss"),
  "water-machines": PageHeaderDef(title: "Water Machines", description: "", action: "New machine"),
  "water-maintenance": PageHeaderDef(title: "Water Maintenance", description: "", action: "Log issue"),
  "water-owner-money": PageHeaderDef(title: "Water Owner Money", description: "", action: "Record contribution"),
  "water-payments": PageHeaderDef(title: "Payments", description: ""),
  "water-payroll-runs": PageHeaderDef(title: "Water Payroll", description: "", action: "New run"),
  "water-production-batches": PageHeaderDef(title: "Production", description: "{batches.length} production record{batches.length === 1 ? \"\" : \"s\"} on file.", color: "sky", action: "Record production"),
  "water-production-losses": PageHeaderDef(title: "Production losses", description: "Damaged bags / rejected sachets auto-recorded on production approval.", color: "rose"),
  "water-products": PageHeaderDef(title: "Water Products", description: "", action: "New product"),
  "water-raw-material-purchases": PageHeaderDef(title: "Water Raw Materials", description: "", action: "New item"),
  "water-raw-material-usage-history": PageHeaderDef(title: "Water Reports/Raw Material Usage", description: ""),
  "water-reports-driver-collection": PageHeaderDef(title: "Water Driver Report", description: ""),
  "water-reports-driver-reconciliation": PageHeaderDef(title: "Water Reports/Operational", description: ""),
  "water-reports-inventory-tracker": PageHeaderDef(title: "Inventory tracker", description: "Ledger from production, sales, vehicle loadings, internal use and adjustments \u2014 every movement behind a product&apos;s stock figure."),
  "water-reports-period-pnl": PageHeaderDef(title: "Water Reports/Profit Loss", description: ""),
  "water-reports-route-profitability": PageHeaderDef(title: "Water Reports/Route Performance", description: ""),
  "water-reports-supplier-activity": PageHeaderDef(title: "Water Reports/Supplier Activity", description: ""),
  "water-reports-top-customers": PageHeaderDef(title: "Water Reports/Top Customers", description: ""),
  "water-routes": PageHeaderDef(title: "Water Routes", description: "", action: "New route"),
  "water-sales": PageHeaderDef(title: "Water Sales", description: "", action: "New sale"),
  "water-staff": PageHeaderDef(title: "Water Staff", description: "", action: "New staff"),
  "water-stock-transactions": PageHeaderDef(title: "Water Stock", description: "", action: "New entry"),
  "water-supplier-balances": PageHeaderDef(title: "Supplier Balances", description: ""),
  "water-supplier-payments": PageHeaderDef(title: "Supplier Payments", description: ""),
  "water-suppliers": PageHeaderDef(title: "Water Suppliers", description: "", action: "New supplier"),
  "water-vehicle-loadings": PageHeaderDef(title: "Water Reports/Vehicle Usage", description: ""),
  "water-vehicles": PageHeaderDef(title: "Water Vehicles", description: "", action: "New vehicle"),
};
