// GENERATED from the web: each page's create-button label and whether it
// offers per-row edit / delete.

class PageActions {
  const PageActions({this.action, this.canEdit = false, this.canDelete = false});
  final String? action;
  final bool canEdit;
  final bool canDelete;
}

const Map<String, PageActions> pageActions = {
  "admin-company-employees": PageActions(action: "Add Employee", canEdit: true, canDelete: true),
  "announcements": PageActions(canDelete: true),
  "assets": PageActions(canEdit: true),
  "authentication-get-current-user": PageActions(canEdit: true),
  "cash": PageActions(action: "Add Adjustment", canEdit: true, canDelete: true),
  "companies-mine": PageActions(action: "New company"),
  "customer": PageActions(action: "Add Customer", canEdit: true, canDelete: true),
  "eggproduction": PageActions(action: "Add Egg Sorting record", canEdit: true, canDelete: true),
  "employee-loans": PageActions(action: "New loan / advance"),
  "expenses": PageActions(action: "Add Expense", canEdit: true, canDelete: true),
  "feedusage": PageActions(action: "Add Usage", canEdit: true, canDelete: true),
  "flock": PageActions(action: "Add Flock Batch", canEdit: true, canDelete: true),
  "flocks": PageActions(action: "Add Flock", canEdit: true, canDelete: true),
  "generic-business-template": PageActions(action: "Add your"),
  "generic-cash-transfers": PageActions(action: "New transfer"),
  "generic-customer-payments": PageActions(action: "Record payment"),
  "generic-customers": PageActions(canEdit: true, canDelete: true),
  "generic-expenses": PageActions(action: "New expense"),
  "generic-internal-usage-suggested-cost": PageActions(canEdit: true, canDelete: true),
  "generic-inventory-adjustments": PageActions(action: "New adjustment"),
  "generic-payroll-runs": PageActions(action: "New payroll run"),
  "generic-products": PageActions(action: "New product", canEdit: true, canDelete: true),
  "generic-purchases": PageActions(action: "New purchase"),
  "generic-recurring-expenses": PageActions(action: "New recurring expense"),
  "generic-sales": PageActions(action: "New sale"),
  "generic-service-plans": PageActions(canEdit: true),
  "generic-staff": PageActions(action: "Add staff", canEdit: true, canDelete: true),
  "generic-staff-payments": PageActions(action: "Record payment"),
  "generic-supplier-payments": PageActions(action: "Record payment"),
  "generic-suppliers": PageActions(action: "New supplier", canEdit: true, canDelete: true),
  "health": PageActions(action: "Add Health Record", canEdit: true, canDelete: true),
  "hotel-billing-charges": PageActions(action: "Add Charge"),
  "hotel-finance-cash-accounts": PageActions(action: "Add Account", canDelete: true),
  "hotel-finance-expenses": PageActions(action: "Record Payment"),
  "hotel-guests": PageActions(action: "New Guests", canEdit: true, canDelete: true),
  "hotel-lost-and-found": PageActions(action: "Log Item"),
  "hotel-payroll-runs": PageActions(canDelete: true),
  "hotel-restaurant-tables": PageActions(action: "Add Item", canEdit: true, canDelete: true),
  "hotel-setup-amenities": PageActions(action: "Add Room", canEdit: true, canDelete: true),
  "hotel-staff": PageActions(action: "Add Staff", canEdit: true, canDelete: true),
  "house": PageActions(action: "Add House", canEdit: true, canDelete: true),
  "inventoryitem": PageActions(action: "Add Supply", canEdit: true, canDelete: true),
  "loans": PageActions(action: "Record loan"),
  "poultry-cash-accounts": PageActions(action: "Record transfer", canEdit: true, canDelete: true),
  "poultry-cash-reconciliations": PageActions(action: "Post it", canEdit: true, canDelete: true),
  "poultry-company": PageActions(canEdit: true, canDelete: true),
  "poultry-daily-closings": PageActions(action: "New closing", canEdit: true, canDelete: true),
  "poultry-deliveries": PageActions(action: "New load"),
  "poultry-driver-returns": PageActions(action: "Add product", canEdit: true, canDelete: true),
  "poultry-drivers": PageActions(action: "New employee", canEdit: true, canDelete: true),
  "poultry-feed-formulas": PageActions(action: "New Formula", canEdit: true, canDelete: true),
  "poultry-feed-production": PageActions(action: "New Batch", canEdit: true, canDelete: true),
  "poultry-internal-usage-suggested-cost": PageActions(canEdit: true, canDelete: true),
  "poultry-loss-records": PageActions(action: "New record", canEdit: true, canDelete: true),
  "poultry-payroll-deductions": PageActions(action: "New payroll run", canEdit: true, canDelete: true),
  "poultry-products": PageActions(action: "New product", canEdit: true, canDelete: true),
  "poultry-staff": PageActions(action: "New staff", canEdit: true, canDelete: true),
  "poultry-vehicles": PageActions(action: "New vehicle", canEdit: true, canDelete: true),
  "production-records": PageActions(action: "Log Production", canEdit: true, canDelete: true),
  "productionbatchrecord": PageActions(action: "Log Batch Production"),
  "raw-materials": PageActions(action: "New Item", canEdit: true, canDelete: true),
  "restaurant-crm-feedback": PageActions(canEdit: true, canDelete: true),
  "restaurant-delivery-zones": PageActions(canEdit: true, canDelete: true),
  "restaurant-events": PageActions(action: "New Event", canDelete: true),
  "restaurant-expenses": PageActions(action: "Record Expense", canDelete: true),
  "restaurant-floor-floors": PageActions(action: "Add Area", canEdit: true, canDelete: true),
  "restaurant-gift-cards": PageActions(action: "Issue Card"),
  "restaurant-inventory-ingredients": PageActions(action: "Add Ingredient", canEdit: true, canDelete: true),
  "restaurant-loyalty-accounts": PageActions(action: "Add Points"),
  "restaurant-menu-item-names": PageActions(canEdit: true, canDelete: true),
  "restaurant-online-qr-codes": PageActions(canEdit: true, canDelete: true),
  "restaurant-orders": PageActions(action: "New Order"),
  "restaurant-public-menu": PageActions(canDelete: true),
  "restaurant-reservations": PageActions(action: "New Reservation", canEdit: true, canDelete: true),
  "restaurant-setup-profile": PageActions(action: "Add Schedule", canEdit: true, canDelete: true),
  "restaurant-staff": PageActions(action: "Add Staff", canEdit: true, canDelete: true),
  "sales": PageActions(action: "Add Sale", canEdit: true, canDelete: true),
  "supplier": PageActions(action: "Add supplier", canEdit: true, canDelete: true),
  "water-assets": PageActions(action: "New asset", canEdit: true),
  "water-boreholes": PageActions(action: "New borehole", canEdit: true, canDelete: true),
  "water-cash-accounts": PageActions(canDelete: true),
  "water-cash-flow": PageActions(action: "Add Adjustment", canEdit: true, canDelete: true),
  "water-cash-reconciliations": PageActions(action: "Post it", canEdit: true, canDelete: true),
  "water-cash-reconciliations-account-status": PageActions(canEdit: true, canDelete: true),
  "water-cash-transfers": PageActions(action: "Record transfer"),
  "water-customers": PageActions(action: "New customer", canEdit: true, canDelete: true),
  "water-daily-closings": PageActions(action: "Create draft", canEdit: true, canDelete: true),
  "water-daily-productions": PageActions(action: "Post allocation", canEdit: true, canDelete: true),
  "water-driver-returns": PageActions(action: "Add product", canEdit: true, canDelete: true),
  "water-drivers-list-for-farm": PageActions(canEdit: true, canDelete: true),
  "water-expenses": PageActions(action: "Record expense"),
  "water-internal-usage-suggested-cost": PageActions(canEdit: true, canDelete: true),
  "water-loans": PageActions(action: "Record loan"),
  "water-loss-records": PageActions(action: "Record loss", canEdit: true),
  "water-machines": PageActions(action: "New machine", canEdit: true, canDelete: true),
  "water-maintenance": PageActions(action: "Log issue", canDelete: true),
  "water-owner-money": PageActions(action: "Record contribution"),
  "water-payroll-runs": PageActions(action: "New run", canDelete: true),
  "water-production-batches": PageActions(action: "Record production", canEdit: true, canDelete: true),
  "water-products": PageActions(action: "Add material", canEdit: true, canDelete: true),
  "water-raw-material-purchases": PageActions(canEdit: true, canDelete: true),
  "water-sales": PageActions(action: "New sale", canDelete: true),
  "water-staff": PageActions(action: "New staff", canEdit: true, canDelete: true),
  "water-suppliers": PageActions(action: "New supplier", canEdit: true, canDelete: true),
  "water-vehicles": PageActions(action: "New vehicle", canEdit: true, canDelete: true),
};
