import 'package:flutter/material.dart';

import '../../../design/ui/buttons.dart';
import '../../../design/ui/inputs.dart';
import '../../../models/company.dart';
import '../../../state/session.dart';
import '../../../widgets/module_sidebar.dart';
import '../../shared/business_dates.dart';
import 'poultry_report_screen.dart';
import 'report_export.dart';
import 'report_format.dart';
import 'report_widgets.dart';
import 'reports_catalog_screen.dart';

const emerald500s = Color(0xFF10B981);
const emerald600s = Color(0xFF059669);

/// The web's `ReportShell` (components/reports/report-shell.tsx) on a phone:
/// back to Reports, Email report and Export PDF, the white card with its
/// emerald band, farm, title and record count, the Period / Currency /
/// Generated / Generated by lines, the period filter with Clear filters, an
/// error banner, the summary tiles, then the body.
class ReportShellScreen extends StatefulWidget {
  const ReportShellScreen({
    super.key,
    required this.session,
    required this.company,
    required this.href,
    required this.title,
    this.description,
    required this.busy,
    this.error,
    this.onClearError,
    this.fromDate,
    this.toDate,
    this.onRangeChanged,
    this.extraFilters = const [],
    this.onClearFilters,
    this.activeFilters = const [],
    this.tiles = const [],
    this.document,
    this.recordCount,
    required this.body,
    this.onRefresh,
  });
  final Session session;
  final Company company;
  final String href;
  final String title;
  final String? description;
  final bool busy;
  final String? error;
  final VoidCallback? onClearError;
  final String? fromDate, toDate;
  final void Function(String from, String to)? onRangeChanged;
  final List<Widget> extraFilters;
  final VoidCallback? onClearFilters;

  /// Filters beyond the dates, for the header's "Filters used" line.
  final List<(String, String)> activeFilters;
  final List<SummaryCardData> tiles;

  /// The PDF / email definition; null disables Email report.
  final ReportDocument Function()? document;
  final int? recordCount;
  final List<Widget> body;
  final Future<void> Function()? onRefresh;

  @override
  State<ReportShellScreen> createState() => _ReportShellScreenState();
}

class _ReportShellScreenState extends State<ReportShellScreen> {
  FarmMoney _money = const FarmMoney();
  late final String _generatedAt = generatedNow();
  bool _downloading = false;

  @override
  void initState() {
    super.initState();
    FarmMoney.load(widget.session, widget.company).then((m) {
      if (mounted) setState(() => _money = m);
    });
  }

  ReportDocument? _brand() {
    final d = widget.document?.call();
    if (d == null) return null;
    return ReportDocument(
      title: d.title,
      filename: d.filename,
      farmName: d.farmName.isEmpty ? widget.company.name : d.farmName,
      fromDate: d.fromDate ?? widget.fromDate,
      toDate: d.toDate ?? widget.toDate,
      generatedBy: d.generatedBy ?? reportUser(widget.session),
      currencyLabel: d.currencyLabel ?? _money.label,
      filters: d.filters.isNotEmpty ? d.filters : widget.activeFilters,
      cards: d.cards,
      sections: d.sections,
      landscape: d.landscape,
      subtitle: d.subtitle,
      notes: d.notes,
    );
  }

  Future<void> _pdf() async {
    final d = _brand();
    if (d == null) return;
    setState(() => _downloading = true);
    try {
      await ReportExport.sharePdf(d);
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Export failed. $e')));
    } finally {
      if (mounted) setState(() => _downloading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final lead = sidebarLeading(context, widget.session, widget.company, href: widget.href);
    final from = widget.fromDate, to = widget.toDate;
    final hasRange = widget.onRangeChanged != null && from != null && to != null;
    final def = defaultReportRange();
    final rangeIsDefault = !hasRange || (from == def.from && to == def.to);
    final canClear = (!rangeIsDefault || widget.activeFilters.isNotEmpty) && !widget.busy;
    final invalid = from != null && to != null && from.compareTo(to) > 0;
    final user = reportUser(widget.session) ?? '—';
    final list = ListView(
      padding: const EdgeInsets.fromLTRB(14, 12, 14, 32),
      children: [
        Wrap(spacing: 8, runSpacing: 8, alignment: WrapAlignment.spaceBetween, children: [
          AppButton(
            label: 'Reports',
            icon: Icons.arrow_back,
            variant: AppButtonVariant.outline,
            size: AppButtonSize.sm,
            onPressed: () => Navigator.of(context).push(MaterialPageRoute(
              builder: (_) => PoultryReportsCatalogScreen(session: widget.session, company: widget.company),
            )),
          ),
          Wrap(spacing: 8, children: [
            AppButton(
              label: 'Email report',
              icon: Icons.mail_outline,
              variant: AppButtonVariant.outline,
              size: AppButtonSize.sm,
              onPressed: widget.document == null
                  ? null
                  : () => showReportEmailDialog(
                        context,
                        client: widget.session.farmClient,
                        document: () => _brand()!,
                        defaultRecipient: defaultEmailRecipient(widget.session, widget.company),
                      ),
            ),
            AppButton(
              label: 'Export PDF',
              icon: Icons.print_outlined,
              size: AppButtonSize.sm,
              busy: _downloading,
              onPressed: _downloading || widget.document == null ? null : _pdf,
            ),
          ]),
        ]),
        const SizedBox(height: 12),
        Container(
          decoration: BoxDecoration(
            color: Colors.white,
            border: Border.all(color: slate200),
            borderRadius: BorderRadius.circular(12),
            boxShadow: const [BoxShadow(color: Color(0x0D000000), blurRadius: 2, offset: Offset(0, 1))],
          ),
          clipBehavior: Clip.antiAlias,
          child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
            Container(height: 6, decoration: const BoxDecoration(gradient: LinearGradient(colors: [emerald600s, emerald500s]))),
            Padding(
              padding: const EdgeInsets.all(14),
              child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
                // ---- header
                Container(
                  padding: const EdgeInsets.only(bottom: 12),
                  margin: const EdgeInsets.only(bottom: 12),
                  decoration: const BoxDecoration(border: Border(bottom: BorderSide(color: slate200))),
                  child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
                    Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
                      Expanded(
                        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                          Text(widget.company.name.isEmpty ? '—' : widget.company.name.toUpperCase(),
                              style: const TextStyle(fontSize: 11.5, fontWeight: FontWeight.w600, letterSpacing: .8, color: emerald700)),
                          const SizedBox(height: 2),
                          Text(widget.title, style: const TextStyle(fontSize: 21, fontWeight: FontWeight.w600, color: slate900)),
                          if (widget.description != null)
                            Padding(
                              padding: const EdgeInsets.only(top: 4),
                              child: Text(widget.description!, style: const TextStyle(fontSize: 13, color: slate500)),
                            ),
                        ]),
                      ),
                      if (widget.recordCount != null)
                        Column(crossAxisAlignment: CrossAxisAlignment.end, children: [
                          Text(fmtNum(widget.recordCount!, 0),
                              style: const TextStyle(fontSize: 21, fontWeight: FontWeight.w600, color: slate900)),
                          const Text('RECORDS', style: TextStyle(fontSize: 10.5, letterSpacing: .6, color: slate500)),
                        ]),
                    ]),
                    const SizedBox(height: 8),
                    for (final (k, v) in [
                      if (from != null && to != null) ('Period', '$from → $to'),
                      ('Currency', _money.label),
                      ('Generated', _generatedAt),
                      ('Generated by', user),
                      if (widget.activeFilters.isNotEmpty)
                        ('Filters used', widget.activeFilters.map((f) => '${f.$1} = ${f.$2}').join('; ')),
                    ])
                      Padding(
                        padding: const EdgeInsets.only(bottom: 2),
                        child: Text.rich(TextSpan(style: const TextStyle(fontSize: 13, color: slate500), children: [
                          TextSpan(text: '$k: ', style: const TextStyle(fontWeight: FontWeight.w500, color: slate600)),
                          TextSpan(text: v),
                        ])),
                      ),
                  ]),
                ),
                // ---- filters
                if (hasRange) ...[
                  const Text('Period', style: TextStyle(fontSize: 12, color: slate600)),
                  const SizedBox(height: 4),
                  AppSelect<String>(
                    value: rangeToPeriod(from, to),
                    items: [
                      for (final (group, opts) in periodGroups)
                        for (final (k, l) in opts) AppSelectItem(value: k, label: '$l  ·  $group'),
                    ],
                    onChanged: (k) {
                      final r = k == null ? null : periodToRange(k);
                      if (r != null) widget.onRangeChanged!(r.from, r.to);
                    },
                  ),
                  const SizedBox(height: 8),
                  Row(children: [
                    Expanded(child: _dateField('From', from, (v) => widget.onRangeChanged!(v, to))),
                    const SizedBox(width: 8),
                    Expanded(child: _dateField('To', to, (v) => widget.onRangeChanged!(from, v))),
                  ]),
                  const SizedBox(height: 8),
                ],
                ...widget.extraFilters,
                if (hasRange || widget.onClearFilters != null)
                  Padding(
                    padding: const EdgeInsets.only(bottom: 12),
                    child: AppButton(
                      label: 'Clear filters',
                      variant: AppButtonVariant.outline,
                      size: AppButtonSize.sm,
                      fullWidth: true,
                      onPressed: canClear
                          ? () {
                              if (hasRange) widget.onRangeChanged!(def.from, def.to);
                              widget.onClearFilters?.call();
                            }
                          : null,
                    ),
                  ),
                if (invalid)
                  _banner(
                    'The From date ($from) is after the To date ($to). Adjust the range to see results.',
                    amber50,
                    amber200,
                    amber800,
                  ),
                if (widget.error != null)
                  _banner(widget.error!, const Color(0xFFFFF1F2), const Color(0xFFFECDD3), const Color(0xFF9F1239),
                      onDismiss: widget.onClearError),
                if (widget.busy)
                  const Padding(
                    padding: EdgeInsets.symmetric(vertical: 24),
                    child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [
                      SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2)),
                      SizedBox(width: 8),
                      Text('Loading…', style: TextStyle(fontSize: 13, color: slate400)),
                    ]),
                  )
                else ...[
                  if (widget.tiles.isNotEmpty) SummaryTiles(widget.tiles),
                  ...widget.body,
                ],
              ]),
            ),
          ]),
        ),
      ],
    );
    return Scaffold(
      backgroundColor: slate50,
      appBar: AppBar(leading: lead.leading, leadingWidth: lead.width, title: Text(widget.title, overflow: TextOverflow.ellipsis)),
      body: widget.onRefresh == null ? list : RefreshIndicator(onRefresh: widget.onRefresh!, child: list),
    );
  }

  Widget _dateField(String label, String value, void Function(String) onPick) =>
      Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Text(label, style: const TextStyle(fontSize: 12, color: slate600)),
        const SizedBox(height: 4),
        AppDateField(
          value: businessDateAsDateTime(value),
          firstDate: DateTime(2000),
          onChanged: (d) {
            if (d != null) onPick(isoDay(d));
          },
        ),
      ]);

  Widget _banner(String text, Color bg, Color border, Color ink, {VoidCallback? onDismiss}) => Container(
        margin: const EdgeInsets.only(bottom: 12),
        padding: const EdgeInsets.fromLTRB(10, 8, 4, 8),
        decoration: BoxDecoration(color: bg, border: Border.all(color: border), borderRadius: BorderRadius.circular(6)),
        child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Padding(padding: const EdgeInsets.only(top: 1), child: Icon(Icons.error_outline, size: 16, color: ink)),
          const SizedBox(width: 8),
          Expanded(child: Text(text, style: TextStyle(fontSize: 13, color: ink))),
          if (onDismiss != null)
            TextButton(
              onPressed: onDismiss,
              style: TextButton.styleFrom(visualDensity: VisualDensity.compact),
              child: Text('dismiss', style: TextStyle(fontSize: 12, color: ink)),
            ),
        ]),
      );
}

/// SumTile: a slate rail unless an accent is given.
class SummaryTiles extends StatelessWidget {
  const SummaryTiles(this.tiles, {super.key});
  final List<SummaryCardData> tiles;

  @override
  Widget build(BuildContext context) => Padding(
        padding: const EdgeInsets.only(bottom: 14),
        child: twoColumns([
          for (final t in tiles)
            Container(
              decoration: BoxDecoration(color: Colors.white, border: Border.all(color: slate200), borderRadius: BorderRadius.circular(10)),
              clipBehavior: Clip.antiAlias,
              child: Stack(children: [
                Padding(
                  padding: const EdgeInsets.fromLTRB(14, 10, 10, 10),
                  child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                    Text(t.label.toUpperCase(), style: const TextStyle(fontSize: 10.5, letterSpacing: .5, color: slate500)),
                    const SizedBox(height: 4),
                    Text(t.value, style: TextStyle(fontSize: 17, fontWeight: FontWeight.w600, color: accentValue(t.accent))),
                    if (t.note != null) Text(t.note!, style: const TextStyle(fontSize: 10, color: slate500)),
                  ]),
                ),
                Positioned(left: 0, top: 0, bottom: 0, width: 4, child: ColoredBox(color: t.accent == null ? slate300 : accentRail(t.accent))),
              ]),
            ),
        ]),
      );
}

/// ReportTableCards: each row a card (first value bold, second under it, the
/// rest two-up), 20 at a time with "Show n more", the Totals card, and "View
/// table format" for the plain table that scrolls sideways.
class ShellCards extends StatefulWidget {
  const ShellCards({
    super.key,
    required this.columns,
    required this.rows,
    this.totals,
    this.empty,
    this.valueColor,
    this.struck,
  });
  final List<ReportColumn> columns;
  final List<List<String>> rows;
  final List<String>? totals;
  final String? empty;

  /// A coloured value (green In, red Out); null = plain.
  final Color? Function(int row, int col)? valueColor;

  /// A reversed record: shown, struck through, never counted.
  final bool Function(int row, int col)? struck;

  @override
  State<ShellCards> createState() => _ShellCardsState();
}

class _ShellCardsState extends State<ShellCards> {
  static const _step = 20;
  int _limit = _step;
  bool _table = false;

  @override
  Widget build(BuildContext context) {
    final cols = widget.columns, rows = widget.rows;
    if (rows.isEmpty) {
      return Padding(
        padding: const EdgeInsets.symmetric(vertical: 12),
        child: Text(widget.empty ?? 'No rows.', textAlign: TextAlign.center, style: const TextStyle(fontSize: 13, color: slate500)),
      );
    }
    String text(String v) => v.isEmpty ? '—' : v;
    TextStyle valueStyle(int r, int c, {double size = 14, FontWeight w = FontWeight.w500}) {
      final s = widget.struck?.call(r, c) ?? false;
      return TextStyle(
        fontSize: size,
        fontWeight: w,
        color: s ? slate400 : (widget.valueColor?.call(r, c) ?? slate900),
        decoration: s ? TextDecoration.lineThrough : null,
      );
    }

    if (_table) {
      return Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
        Container(
          padding: const EdgeInsets.fromLTRB(12, 4, 4, 4),
          decoration: BoxDecoration(color: slate50, border: Border.all(color: slate200), borderRadius: BorderRadius.circular(8)),
          child: Row(children: [
            const Expanded(child: Text('Table • Scroll → for more', style: TextStyle(fontSize: 12, color: slate600))),
            TextButton.icon(onPressed: () => setState(() => _table = false), icon: const Icon(Icons.expand_less, size: 18), label: const Text('Cards')),
          ]),
        ),
        const SizedBox(height: 8),
        SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: DataTable(
            headingRowColor: const WidgetStatePropertyAll(Color(0xFFECFDF5)),
            headingTextStyle: const TextStyle(fontSize: 11.5, fontWeight: FontWeight.w600, letterSpacing: .5, color: Color(0xFF064E3B)),
            columns: [for (final c in cols) DataColumn(label: Text(c.header.toUpperCase()), numeric: c.right)],
            rows: [
              for (final (ri, r) in rows.indexed)
                DataRow(
                  color: WidgetStatePropertyAll(ri.isOdd ? const Color(0x99F8FAFC) : Colors.white),
                  cells: [for (final (ci, v) in r.indexed) DataCell(Text(text(v), style: valueStyle(ri, ci, size: 13, w: FontWeight.w400)))],
                ),
              if (widget.totals != null)
                DataRow(
                  color: const WidgetStatePropertyAll(slate100),
                  cells: [for (final v in widget.totals!) DataCell(Text(v, style: const TextStyle(fontWeight: FontWeight.w600)))],
                ),
            ],
          ),
        ),
      ]);
    }

    final shown = rows.take(_limit).toList();
    final rest = rows.length - shown.length;
    return Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
      for (final (ri, r) in shown.indexed) ...[
        Container(
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: Colors.white,
            border: Border.all(color: slate200),
            borderRadius: BorderRadius.circular(8),
            boxShadow: const [BoxShadow(color: Color(0x0D000000), blurRadius: 2, offset: Offset(0, 1))],
          ),
          child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
            Text(text(r[0]), style: valueStyle(ri, 0, size: 14.5, w: FontWeight.w600)),
            if (cols.length > 1)
              Padding(padding: const EdgeInsets.only(top: 2), child: Text(text(r[1]), style: const TextStyle(fontSize: 13, color: slate600))),
            if (cols.length > 2) ...[
              const Divider(height: 18, color: slate100),
              twoColumns(gap: 8, [
                for (var ci = 2; ci < cols.length && ci < r.length; ci++)
                  Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                    Text(cols[ci].header, style: const TextStyle(fontSize: 12, color: slate500)),
                    Text(text(r[ci]), style: valueStyle(ri, ci, size: 13.5)),
                  ]),
              ]),
            ],
          ]),
        ),
        const SizedBox(height: 8),
      ],
      if (widget.totals != null && widget.totals!.any((v) => v.isNotEmpty)) ...[
        Container(
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: const Color(0xFFECFDF5),
            border: Border.all(color: const Color(0xFFA7F3D0)),
            borderRadius: BorderRadius.circular(8),
          ),
          child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
            const Text('TOTALS', style: TextStyle(fontSize: 11.5, fontWeight: FontWeight.w600, letterSpacing: .5, color: Color(0xFF064E3B))),
            const SizedBox(height: 8),
            twoColumns(gap: 8, [
              for (final (ci, v) in widget.totals!.indexed)
                if (v.isNotEmpty && ci < cols.length)
                  Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                    Text(cols[ci].header, style: const TextStyle(fontSize: 12, color: Color(0xB3065F46))),
                    Text(v, style: const TextStyle(fontSize: 13.5, fontWeight: FontWeight.w600)),
                  ]),
            ]),
          ]),
        ),
        const SizedBox(height: 8),
      ],
      if (rest > 0)
        AppButton(
          label: 'Show ${fmtNum(rest < _step ? rest : _step, 0)} more (${fmtNum(shown.length, 0)} of ${fmtNum(rows.length, 0)})',
          variant: AppButtonVariant.outline,
          fullWidth: true,
          onPressed: () => setState(() => _limit += _step),
        ),
      TextButton.icon(
        onPressed: () => setState(() => _table = true),
        icon: const Icon(Icons.expand_more, size: 18),
        label: const Text('View table format'),
      ),
    ]);
  }
}

/// A heading inside a report body, as the web's uppercase section titles.
class ShellHeading extends StatelessWidget {
  const ShellHeading(this.text, {super.key});
  final String text;

  @override
  Widget build(BuildContext context) => Padding(
        padding: const EdgeInsets.only(top: 14, bottom: 8),
        child: Text(text.toUpperCase(), style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600, letterSpacing: .6, color: slate600)),
      );
}
