import type { EggProduction } from "@/lib/api/egg-production"
import type { Sale } from "@/lib/api/sale"
import type { Flock } from "@/lib/api/flock"
import { resolveEggProductionFlockName } from "@/lib/utils/resolve-egg-flock-name"
import { formatEggGradeLabel } from "@/lib/constants/egg-grade"

export interface EggLedgerRow {
  sortKey: string
  date: string
  type: string
  description: string
  in: number
  out: number
  balance: number
}

export function isEggSaleProduct(product: string | undefined | null): boolean {
  if (!product?.trim()) return false
  return product.trim().toLowerCase().includes("egg")
}

/**
 * True for the Sale rows that the driver-distribution and delivery modules
 * generate themselves when a return / delivery is reconciled.
 *
 * Those eggs already left the ledger as a 'Driver Load Out' / 'Delivery Load'
 * move at load time, and only the UNSOLD portion is put back by
 * 'Driver Return In' / 'Delivery Return'. The generated Sale books the revenue,
 * it does not move stock — counting it here as well deducted the sold eggs a
 * second time, which is why this page read lower than /poultry-inventory by
 * exactly the sold quantity on every reconciled delivery.
 *
 * Matches the descriptions written by sppoultrydriverreturn_approve
 * ('Driver return #<id>') and sppoultrydelivery_reconcile ('Delivery #<id>').
 */
export function isStockLedgerBackedSale(description: string | undefined | null): boolean {
  const d = description?.trim().toLowerCase()
  if (!d) return false
  return d.startsWith("driver return #") || d.startsWith("delivery #")
}

type LineInput = {
  sortKey: string
  date: string
  type: string
  description: string
  in: number
  out: number
  order: number
}

/** Manual corrections from Egg tracker (API); positive adds eggs, negative removes. */
export interface EggInventoryAdjustmentLedgerInput {
  adjustmentId: number
  adjustmentDate: string
  eggDelta: number
  adjustmentType: string
  description?: string | null
}

/**
 * Non-production, non-sale movements posted to the poultry stock ledger for the
 * egg product — driver load-outs, deliveries, restocks and the Set stock /
 * Reconcile corrections made from /poultry-inventory.
 *
 * The Egg Tracker used to ignore these entirely, so a 2,000-egg driver load-out
 * never reduced "Eggs on hand" and this page disagreed with the inventory's
 * "In stock". Production and Sale rows are deliberately NOT taken from here:
 * they are already derived from the production records and the sales list, and
 * pulling them in as well would double-count them.
 */
export interface EggStockMoveLedgerInput {
  poultryStockTransactionId: number
  createdDate: string
  txnType: string
  quantity: number
  note?: string | null
  /** Source record this row was posted for: a ProductionRecord id for
   *  'Production', a Sale id for 'Sale'. Null means the row was posted by hand
   *  from /poultry-stock and has no source record anywhere — see the loop below. */
  relatedId?: number | null
}

function formatEggAdjustmentType(t: string): string {
  switch (t) {
    case "OpeningBalance":
      return "Opening balance"
    case "Stocktake":
      return "Stocktake"
    case "Correction":
      return "Correction"
    default:
      return t || "Adjustment"
  }
}

/**
 * The non-saleable categories deducted from collected eggs, in ledger order.
 * An egg is on hand only if it is not broken, meaty, soft-shelled or lost — the
 * same rule as spPoultryReport_EggStockBalance and the weekly report's "Egg
 * loss" figure. Each is its own ledger line so the deduction is visible and the
 * page's type filter can isolate it.
 */
const EGG_LOSS_LINES: {
  key: "brokenEggs" | "meatyEggs" | "softEggs" | "lostEggs"
  type: string
  note: string
  order: number
}[] = [
  { key: "brokenEggs", type: "Broken eggs", note: "non-saleable", order: 1 },
  { key: "meatyEggs", type: "Meaty eggs", note: "non-saleable", order: 2 },
  { key: "softEggs", type: "Soft eggs", note: "non-saleable", order: 3 },
  { key: "lostEggs", type: "Lost eggs", note: "lost", order: 4 },
]

/** Running egg inventory: production (in) − broken/meaty/soft/lost (out) − egg sales (out) ± adjustments ± stock-ledger moves. Chronological balance on each row.
 *  Sales generated by a driver return / delivery are skipped — the stock-ledger
 *  moves already account for those eggs.
 *
 *  `ledgerBalance` is the authoritative figure: SUM(PoultryStockTransactions.Quantity)
 *  for the egg product, exactly as sppoultryproduct_getall computes the "In stock"
 *  shown on /poultry-inventory. When it is supplied, it — not the sum of the rows
 *  below — is returned as `currentEggsAtHand`, and any difference is surfaced as a
 *  final "Unmatched ledger movements" row so the history still adds up to it.
 *
 *  The rows are assembled from the SOURCE tables (production records, sales) plus
 *  the non-Production/Sale ledger moves, which is only equivalent to the ledger
 *  while every 'Production'/'Sale' ledger row has a source record behind it.
 *  Nothing enforces that: /poultry-stock can post a raw movement typed 'Sale' with
 *  no Sale row, and one such row (a -1,000 "Manual stock entry") is why this page
 *  read 1,164 while /poultry-inventory read 164 for the same farm. Deriving the
 *  balance instead of reading it is the bug; the remainder row makes any future
 *  divergence visible rather than silent. */
export function buildEggStockLedger(
  productions: EggProduction[],
  sales: Sale[],
  flocks: Flock[] = [],
  adjustments: EggInventoryAdjustmentLedgerInput[] = [],
  stockMoves: EggStockMoveLedgerInput[] = [],
  ledgerBalance?: number
): {
  rows: EggLedgerRow[]
  currentEggsAtHand: number
  lastUpdatedIso: string
  unmatchedLedgerDelta: number
} {
  const lines: LineInput[] = []

  for (const p of productions) {
    const inCount = Math.max(0, Number(p.totalProduction) || 0)
    const flock = resolveEggProductionFlockName(p, flocks)
    const date = p.productionDate
    const grade = p.eggGrade?.trim()
    const gradeBit = grade ? ` — ${formatEggGradeLabel(grade)}` : ""

    lines.push({
      sortKey: `prod_${p.productionId}`,
      date,
      type: "Production",
      description: `${flock}${gradeBit} — collected`,
      in: inCount,
      out: 0,
      order: 0,
    })

    for (const loss of EGG_LOSS_LINES) {
      const qty = Math.max(0, Number(p[loss.key]) || 0)
      if (qty <= 0) continue
      lines.push({
        sortKey: `${loss.key}_${p.productionId}`,
        date,
        type: loss.type,
        description: `${flock} — ${loss.note}`,
        in: 0,
        out: qty,
        order: loss.order,
      })
    }
  }

  for (const s of sales) {
    if (!isEggSaleProduct(s.product)) continue
    // Already accounted for by the load-out / return-in stock moves below.
    if (isStockLedgerBackedSale(s.saleDescription)) continue
    const qty = Math.max(0, Number(s.quantity) || 0)
    if (qty <= 0) continue
    const who = s.customerName?.trim()
    lines.push({
      sortKey: `sale_${s.saleId}`,
      date: s.saleDate,
      type: "Sale",
      description: who ? `${who} — ${s.product}` : (s.product || "Egg sale"),
      in: 0,
      out: qty,
      order: 5,
    })
  }

  for (const a of adjustments) {
    const d = Math.round(Number(a.eggDelta) || 0)
    if (d === 0) continue
    const dateStr = a.adjustmentDate
      ? new Date(a.adjustmentDate).toISOString()
      : new Date(0).toISOString()
    const typeLabel = formatEggAdjustmentType(a.adjustmentType)
    const desc = (a.description || "").trim() || typeLabel
    lines.push({
      sortKey: `eggadj_${a.adjustmentId}`,
      date: dateStr,
      type: "Adjustment",
      description: `${typeLabel}: ${desc}`,
      in: d > 0 ? d : 0,
      out: d < 0 ? -d : 0,
      order: 6,
    })
  }

  for (const m of stockMoves) {
    const type = m.txnType?.trim()
    if (!type) continue
    // 'Production' and 'Sale' rows are normally the ledger's copy of a record
    // already listed above from productionrecords / sale, so including them here
    // too would deduct the same eggs twice.
    //
    // A row with NO RelatedId is the exception: nothing posted it on behalf of a
    // source record, so there is no line above for it and skipping it here means
    // nobody counts it. That is exactly what hid the -1,000 "Manual stock entry"
    // (txn 285) — visible on /poultry-stock and in /poultry-inventory's total,
    // invisible in this table. Show it; the sign on `quantity` already says
    // which way the eggs went.
    if ((type === "Production" || type === "Sale") && m.relatedId != null) continue
    const qty = Math.round(Number(m.quantity) || 0)
    if (qty === 0) continue
    const note = (m.note || "").trim()
    lines.push({
      sortKey: `stockmove_${m.poultryStockTransactionId}`,
      date: m.createdDate,
      type,
      description: note || type,
      in: qty > 0 ? qty : 0,
      out: qty < 0 ? -qty : 0,
      order: 7,
    })
  }

  lines.sort((a, b) => {
    const da = new Date(a.date).getTime()
    const db = new Date(b.date).getTime()
    if (da !== db) return da - db
    if (a.order !== b.order) return a.order - b.order
    return a.sortKey.localeCompare(b.sortKey)
  })

  let bal = 0
  const rows: EggLedgerRow[] = lines.map((line) => {
    bal += line.in - line.out
    return {
      sortKey: line.sortKey,
      date: line.date,
      type: line.type,
      description: line.description,
      in: line.in,
      out: line.out,
      balance: bal,
    }
  })

  const derivedBalance = rows.length > 0 ? rows[rows.length - 1].balance : 0

  // Reconcile the assembled history against the authoritative ledger. Anything
  // the rows above could not account for gets its own line rather than being
  // silently dropped, so the running balance still lands on the ledger figure
  // and the missing movement is named on the page instead of in a SQL console.
  const authoritative = Number.isFinite(ledgerBalance as number)
    ? Math.round(ledgerBalance as number)
    : derivedBalance
  const unmatchedLedgerDelta = authoritative - derivedBalance

  if (unmatchedLedgerDelta !== 0) {
    const last = rows[rows.length - 1]
    rows.push({
      sortKey: "unmatched_ledger",
      date: last ? last.date : new Date().toISOString(),
      type: "Unmatched",
      description:
        "Unmatched ledger movements — stock transactions with no matching production, sale or adjustment record",
      in: unmatchedLedgerDelta > 0 ? unmatchedLedgerDelta : 0,
      out: unmatchedLedgerDelta < 0 ? -unmatchedLedgerDelta : 0,
      balance: authoritative,
    })
  }

  const lastUpdatedIso =
    rows.length > 0 ? rows[rows.length - 1].date : new Date().toISOString()

  return {
    rows,
    currentEggsAtHand: authoritative,
    lastUpdatedIso,
    unmatchedLedgerDelta,
  }
}
