// Generates lib/pages/shared/currencies.dart from the same ICU data the web's
// currency picker reads (poultrycore-main/lib/constants/currencies.ts):
// Intl.supportedValuesOf("currency"), Intl.DisplayNames for the English name,
// and the narrowSymbol (then symbol) for the sign, in the web's order.
//
//   node tool/gen_currencies.js
//
// Dart has no ICU currency names, so the list is generated, not computed.

const fs = require("fs")
const path = require("path")

const PRIORITY = ["GHS", "NGN", "USD", "EUR", "GBP", "XOF", "XAF", "ZAR", "KES", "UGX", "TZS", "CFA"]

const codes = [...new Set(Intl.supportedValuesOf("currency").map((c) => c.toUpperCase()))].sort()
const names = new Intl.DisplayNames(["en"], { type: "currency" })

function symbolFor(code) {
  for (const currencyDisplay of ["narrowSymbol", "symbol"]) {
    try {
      const part = new Intl.NumberFormat("en", { style: "currency", currency: code, currencyDisplay })
        .formatToParts(0)
        .find((p) => p.type === "currency")
      if (part && part.value) return part.value
    } catch {}
  }
  return code
}

function nameFor(code) {
  try { return names.of(code) || code } catch { return code }
}

const rank = (c) => { const i = PRIORITY.indexOf(c); return i === -1 ? PRIORITY.length : i }
const options = codes
  .map((code) => ({ code, name: nameFor(code), symbol: symbolFor(code) }))
  .sort((a, b) => rank(a.code) - rank(b.code) || a.code.localeCompare(b.code))

const dart = (s) => "'" + s.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\$/g, "\\$") + "'"

let out = `// GENERATED by tool/gen_currencies.js — do not edit by hand.
// Same ICU data and order as the web picker (lib/constants/currencies.ts).

class CurrencyOption {
  const CurrencyOption(this.code, this.name, this.symbol);
  final String code;
  final String name;
  final String symbol;

  /// "GHS — Ghanaian Cedi (GH₵)", as the web's formatCurrencyOption words it.
  String get label => symbol != code ? '$code — $name ($symbol)' : '$code — $name';
}

const allCurrencies = <CurrencyOption>[
`
for (const o of options) out += `  CurrencyOption(${dart(o.code)}, ${dart(o.name)}, ${dart(o.symbol)}),\n`
out += `];

CurrencyOption? findCurrency(String? code) {
  final c = (code ?? '').toUpperCase();
  for (final o in allCurrencies) {
    if (o.code == c) return o;
  }
  return null;
}

/// currencySymbolFor: the symbol, or the code when there is none.
String currencySymbolFor(String code) => findCurrency(code)?.symbol ?? code.toUpperCase();
`

const target = path.join(__dirname, "..", "lib", "pages", "shared", "currencies.dart")
fs.writeFileSync(target, out)
console.log(`${options.length} currencies →`, options.slice(0, 3).map((o) => `${o.code} ${o.name} ${o.symbol}`).join(" | "))
