-- =============================================================================
-- Migration 004: Finance, Billing, Restaurant
-- =============================================================================
SET NOCOUNT ON; SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
GO

IF OBJECT_ID('dbo.HotelStayCharges', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelStayCharges (HotelStayChargeId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, HotelBookingId INT NOT NULL, ChargeType NVARCHAR(50) NOT NULL, Description NVARCHAR(500) NOT NULL, Quantity INT NOT NULL DEFAULT(1), UnitPrice DECIMAL(12,2) NOT NULL, TotalAmount DECIMAL(12,2) NOT NULL, ChargeDate DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), PostedBy NVARCHAR(450) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), CONSTRAINT FK_HSC_Booking FOREIGN KEY (HotelBookingId) REFERENCES dbo.HotelBookings(HotelBookingId)); CREATE INDEX IX_HSC_FarmId ON dbo.HotelStayCharges(FarmId); END
GO

IF OBJECT_ID('dbo.HotelInvoices', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelInvoices (HotelInvoiceId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, HotelBookingId INT NOT NULL, HotelGuestId INT NOT NULL, InvoiceNumber NVARCHAR(30) NOT NULL, SubTotal DECIMAL(12,2) NOT NULL DEFAULT(0), TaxAmount DECIMAL(12,2) NOT NULL DEFAULT(0), TaxRate DECIMAL(5,2) NOT NULL DEFAULT(0), DiscountAmount DECIMAL(12,2) NOT NULL DEFAULT(0), TotalAmount DECIMAL(12,2) NOT NULL DEFAULT(0), AmountPaid DECIMAL(12,2) NOT NULL DEFAULT(0), Balance DECIMAL(12,2) NOT NULL DEFAULT(0), Status NVARCHAR(20) NOT NULL DEFAULT('Draft'), IssuedDate DATE NOT NULL DEFAULT(CAST(GETUTCDATE() AS DATE)), DueDate DATE NULL, Notes NVARCHAR(MAX) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), UpdatedAt DATETIME2 NULL); CREATE UNIQUE INDEX UX_HI_Number ON dbo.HotelInvoices(FarmId, InvoiceNumber); CREATE INDEX IX_HI_FarmId ON dbo.HotelInvoices(FarmId); END
GO

IF OBJECT_ID('dbo.HotelPayments', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelPayments (HotelPaymentId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, HotelInvoiceId INT NULL, HotelBookingId INT NOT NULL, Amount DECIMAL(12,2) NOT NULL, PaymentMethod NVARCHAR(30) NOT NULL, Reference NVARCHAR(100) NULL, PaymentDate DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), ReceivedBy NVARCHAR(450) NULL, Notes NVARCHAR(MAX) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME())); CREATE INDEX IX_HP_FarmId ON dbo.HotelPayments(FarmId); END
GO

IF OBJECT_ID('dbo.HotelExpenses', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelExpenses (HotelExpenseId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, Category NVARCHAR(100) NOT NULL, Description NVARCHAR(500) NOT NULL, Amount DECIMAL(12,2) NOT NULL, ExpenseDate DATE NOT NULL DEFAULT(CAST(GETUTCDATE() AS DATE)), Vendor NVARCHAR(200) NULL, ReceiptRef NVARCHAR(100) NULL, Status NVARCHAR(20) NOT NULL DEFAULT('Draft'), ApprovedBy NVARCHAR(450) NULL, Notes NVARCHAR(MAX) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), UpdatedAt DATETIME2 NULL); CREATE INDEX IX_HE_FarmId ON dbo.HotelExpenses(FarmId); END
GO

IF OBJECT_ID('dbo.HotelCashAccounts', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelCashAccounts (HotelCashAccountId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, AccountName NVARCHAR(100) NOT NULL, AccountType NVARCHAR(30) NOT NULL DEFAULT('Cash'), OpeningBalance DECIMAL(12,2) NOT NULL DEFAULT(0), CurrentBalance DECIMAL(12,2) NOT NULL DEFAULT(0), IsActive BIT NOT NULL DEFAULT(1), Notes NVARCHAR(MAX) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), UpdatedAt DATETIME2 NULL); CREATE INDEX IX_HCA_FarmId ON dbo.HotelCashAccounts(FarmId); END
GO

IF OBJECT_ID('dbo.HotelCashTransactions', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelCashTransactions (HotelCashTxnId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, HotelCashAccountId INT NOT NULL, TxnType NVARCHAR(20) NOT NULL, Amount DECIMAL(12,2) NOT NULL, BalanceAfter DECIMAL(12,2) NOT NULL, Description NVARCHAR(500) NULL, Reference NVARCHAR(100) NULL, TxnDate DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), CreatedBy NVARCHAR(450) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME())); CREATE INDEX IX_HCT_FarmId ON dbo.HotelCashTransactions(FarmId); END
GO

IF OBJECT_ID('dbo.HotelMenuCategories', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelMenuCategories (HotelMenuCategoryId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, Name NVARCHAR(100) NOT NULL, SortOrder INT NOT NULL DEFAULT(0), IsActive BIT NOT NULL DEFAULT(1), CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME())); CREATE INDEX IX_HMC_FarmId ON dbo.HotelMenuCategories(FarmId); END
GO

IF OBJECT_ID('dbo.HotelMenuItems', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelMenuItems (HotelMenuItemId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, Name NVARCHAR(150) NOT NULL, Category NVARCHAR(100) NOT NULL, Description NVARCHAR(500) NULL, Price DECIMAL(12,2) NOT NULL, IsAvailable BIT NOT NULL DEFAULT(1), IsActive BIT NOT NULL DEFAULT(1), CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), UpdatedAt DATETIME2 NULL); CREATE INDEX IX_HMI_FarmId ON dbo.HotelMenuItems(FarmId); END
GO

IF OBJECT_ID('dbo.HotelRestaurantTables', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelRestaurantTables (HotelRestaurantTableId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, TableNumber NVARCHAR(20) NOT NULL, Capacity INT NOT NULL DEFAULT(4), Location NVARCHAR(100) NULL, Status NVARCHAR(20) NOT NULL DEFAULT('Available'), CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME())); CREATE UNIQUE INDEX UX_HRT_Number ON dbo.HotelRestaurantTables(FarmId, TableNumber); CREATE INDEX IX_HRT_FarmId ON dbo.HotelRestaurantTables(FarmId); END
GO

IF OBJECT_ID('dbo.HotelRestaurantOrders', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelRestaurantOrders (HotelRestaurantOrderId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, HotelBookingId INT NULL, HotelRoomId INT NULL, TableNumber NVARCHAR(20) NULL, ServerName NVARCHAR(100) NULL, Status NVARCHAR(20) NOT NULL DEFAULT('Placed'), SubTotal DECIMAL(12,2) NOT NULL DEFAULT(0), TaxAmount DECIMAL(12,2) NOT NULL DEFAULT(0), TipAmount DECIMAL(12,2) NOT NULL DEFAULT(0), TotalAmount DECIMAL(12,2) NOT NULL DEFAULT(0), OrderTime DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), DeliveredTime DATETIME2 NULL, Notes NVARCHAR(MAX) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), UpdatedAt DATETIME2 NULL); CREATE INDEX IX_HRO_FarmId ON dbo.HotelRestaurantOrders(FarmId); END
GO

IF OBJECT_ID('dbo.HotelRestaurantOrderItems', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelRestaurantOrderItems (HotelRestaurantOrderItemId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, HotelRestaurantOrderId INT NOT NULL, HotelMenuItemId INT NOT NULL, Quantity INT NOT NULL DEFAULT(1), UnitPrice DECIMAL(12,2) NOT NULL, Notes NVARCHAR(200) NULL, CONSTRAINT FK_HROI_Order FOREIGN KEY (HotelRestaurantOrderId) REFERENCES dbo.HotelRestaurantOrders(HotelRestaurantOrderId), CONSTRAINT FK_HROI_MenuItem FOREIGN KEY (HotelMenuItemId) REFERENCES dbo.HotelMenuItems(HotelMenuItemId)); END
GO

IF OBJECT_ID('dbo.HotelRoomServiceOrders', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelRoomServiceOrders (HotelRoomServiceOrderId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, HotelBookingId INT NOT NULL, HotelRoomId INT NOT NULL, OrderType NVARCHAR(30) NOT NULL DEFAULT('Food'), Status NVARCHAR(20) NOT NULL DEFAULT('Placed'), TotalAmount DECIMAL(12,2) NOT NULL DEFAULT(0), OrderTime DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), DeliveredTime DATETIME2 NULL, Notes NVARCHAR(MAX) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), UpdatedAt DATETIME2 NULL); CREATE INDEX IX_HRSO_FarmId ON dbo.HotelRoomServiceOrders(FarmId); END
GO

PRINT 'Migration 004 completed successfully.';
GO
