-- =============================================================================
-- Migration 005: Staff, Inventory, Maintenance, Reports
-- =============================================================================
SET NOCOUNT ON; SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON;
GO

IF OBJECT_ID('dbo.HotelStaff', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelStaff (HotelStaffId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, FirstName NVARCHAR(100) NOT NULL, LastName NVARCHAR(100) NOT NULL, Email NVARCHAR(200) NULL, Phone NVARCHAR(50) NULL, Role NVARCHAR(50) NOT NULL, Department NVARCHAR(50) NOT NULL, HireDate DATE NOT NULL DEFAULT(CAST(GETUTCDATE() AS DATE)), IsActive BIT NOT NULL DEFAULT(1), HourlyRate DECIMAL(12,2) NULL, SalaryAmount DECIMAL(12,2) NOT NULL DEFAULT(0), PaymentFrequency NVARCHAR(20) NOT NULL DEFAULT('Monthly'), Notes NVARCHAR(MAX) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), UpdatedAt DATETIME2 NULL); CREATE INDEX IX_HS_FarmId ON dbo.HotelStaff(FarmId); END
GO

IF OBJECT_ID('dbo.HotelShifts', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelShifts (HotelShiftId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, HotelStaffId INT NOT NULL, ShiftDate DATE NOT NULL, StartTime TIME NOT NULL, EndTime TIME NOT NULL, ActualStart TIME NULL, ActualEnd TIME NULL, Status NVARCHAR(20) NOT NULL DEFAULT('Scheduled'), Notes NVARCHAR(MAX) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), CONSTRAINT FK_HSh_Staff FOREIGN KEY (HotelStaffId) REFERENCES dbo.HotelStaff(HotelStaffId)); CREATE INDEX IX_HSh_FarmId ON dbo.HotelShifts(FarmId); END
GO

IF OBJECT_ID('dbo.HotelPayrollRuns', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelPayrollRuns (HotelPayrollRunId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, PeriodStart DATE NOT NULL, PeriodEnd DATE NOT NULL, Status NVARCHAR(20) NOT NULL DEFAULT('Draft'), TotalGrossPay DECIMAL(12,2) NOT NULL DEFAULT(0), TotalDeductions DECIMAL(12,2) NOT NULL DEFAULT(0), TotalNetPay DECIMAL(12,2) NOT NULL DEFAULT(0), ProcessedBy NVARCHAR(450) NULL, ProcessedAt DATETIME2 NULL, CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), UpdatedAt DATETIME2 NULL); CREATE INDEX IX_HPR_FarmId ON dbo.HotelPayrollRuns(FarmId); END
GO

IF OBJECT_ID('dbo.HotelPayrollItems', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelPayrollItems (HotelPayrollItemId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, HotelPayrollRunId INT NOT NULL, HotelStaffId INT NOT NULL, GrossPay DECIMAL(12,2) NOT NULL DEFAULT(0), Deductions DECIMAL(12,2) NOT NULL DEFAULT(0), NetPay DECIMAL(12,2) NOT NULL DEFAULT(0), HoursWorked DECIMAL(8,2) NULL, OvertimeHours DECIMAL(8,2) NULL, Notes NVARCHAR(MAX) NULL, CONSTRAINT FK_HPI_Run FOREIGN KEY (HotelPayrollRunId) REFERENCES dbo.HotelPayrollRuns(HotelPayrollRunId), CONSTRAINT FK_HPI_Staff FOREIGN KEY (HotelStaffId) REFERENCES dbo.HotelStaff(HotelStaffId)); END
GO

IF OBJECT_ID('dbo.HotelInventoryItems', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelInventoryItems (HotelInventoryItemId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, Name NVARCHAR(150) NOT NULL, Category NVARCHAR(50) NOT NULL, Unit NVARCHAR(30) NOT NULL, StockOnHand INT NOT NULL DEFAULT(0), ReorderLevel INT NOT NULL DEFAULT(0), UnitCost DECIMAL(12,2) NOT NULL DEFAULT(0), IsActive BIT NOT NULL DEFAULT(1), CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), UpdatedAt DATETIME2 NULL); CREATE INDEX IX_HII_FarmId ON dbo.HotelInventoryItems(FarmId); END
GO

IF OBJECT_ID('dbo.HotelInventoryTxns', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelInventoryTxns (HotelInventoryTxnId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, HotelInventoryItemId INT NOT NULL, TxnType NVARCHAR(20) NOT NULL, Quantity INT NOT NULL, UnitCost DECIMAL(12,2) NULL, Reference NVARCHAR(100) NULL, Notes NVARCHAR(MAX) NULL, CreatedBy NVARCHAR(450) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), CONSTRAINT FK_HIT_Item FOREIGN KEY (HotelInventoryItemId) REFERENCES dbo.HotelInventoryItems(HotelInventoryItemId)); CREATE INDEX IX_HIT_FarmId ON dbo.HotelInventoryTxns(FarmId); END
GO

IF OBJECT_ID('dbo.HotelMaintenanceRequests', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelMaintenanceRequests (HotelMaintenanceRequestId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, HotelRoomId INT NULL, AssetDescription NVARCHAR(200) NOT NULL, IssueDescription NVARCHAR(MAX) NOT NULL, Priority NVARCHAR(20) NOT NULL DEFAULT('Normal'), Status NVARCHAR(20) NOT NULL DEFAULT('Open'), AssignedTo NVARCHAR(200) NULL, VendorName NVARCHAR(200) NULL, EstimatedCost DECIMAL(12,2) NOT NULL DEFAULT(0), ActualCost DECIMAL(12,2) NOT NULL DEFAULT(0), ReportedBy NVARCHAR(200) NULL, ReportedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), CompletedAt DATETIME2 NULL, Notes NVARCHAR(MAX) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME()), UpdatedAt DATETIME2 NULL); CREATE INDEX IX_HMR_FarmId ON dbo.HotelMaintenanceRequests(FarmId); END
GO

IF OBJECT_ID('dbo.HotelDailyClosings', 'U') IS NULL
BEGIN CREATE TABLE dbo.HotelDailyClosings (HotelDailyClosingId INT IDENTITY(1,1) PRIMARY KEY, FarmId NVARCHAR(450) NOT NULL, ClosingDate DATE NOT NULL, TotalRevenue DECIMAL(12,2) NOT NULL DEFAULT(0), RoomRevenue DECIMAL(12,2) NOT NULL DEFAULT(0), FnBRevenue DECIMAL(12,2) NOT NULL DEFAULT(0), OtherRevenue DECIMAL(12,2) NOT NULL DEFAULT(0), TotalExpenses DECIMAL(12,2) NOT NULL DEFAULT(0), OccupancyRate DECIMAL(5,2) NOT NULL DEFAULT(0), RoomsOccupied INT NOT NULL DEFAULT(0), TotalRooms INT NOT NULL DEFAULT(0), ADR DECIMAL(12,2) NOT NULL DEFAULT(0), RevPAR DECIMAL(12,2) NOT NULL DEFAULT(0), Notes NVARCHAR(MAX) NULL, ClosedBy NVARCHAR(450) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT(SYSUTCDATETIME())); CREATE UNIQUE INDEX UX_HDC_Date ON dbo.HotelDailyClosings(FarmId, ClosingDate); CREATE INDEX IX_HDC_FarmId ON dbo.HotelDailyClosings(FarmId); END
GO

PRINT 'Migration 005 completed successfully.';
GO
