/* =============================================================================
   067_FixProductionBatchCostingAndLinkedRecords.sql

   Prompt: "Production Batch Costing, Inventory, Loss, Expense, and UI Fixes".

   What this migration does
   ------------------------
   1. Cost per Bag + All-in Total Cost are now returned by the GetAll / GetById
      SPs so the list page can stop computing zero.  Formula:
        AllInCost  = TotalProductionCost + RawMaterialCost
                    (= Electricity+Fuel+Labor+Other + sum(rawMatUsage))
        GoodBags   = BagsProduced - DamagedBags
        CostPerBag = AllInCost / GoodBags   (0 when GoodBags = 0)

   2. WaterProductionBatches.MachineScope NVARCHAR(20).
      Values: 'SingleMachine' (default) or 'AllMachines'. When AllMachines
      the WaterMachineId stays NULL but the batch is clearly labelled as
      combined-production in the list and details views.

   3. New table dbo.WaterProductionLosses for damaged-bag / rejected-sachet
      loss records created automatically by the Approve SP. Each loss row
      points back to its production batch via SourceType+SourceId so the
      Loss page can list everything generated by production.

   4. Approve now creates linked records in one atomic transaction:
        - Finished-goods Restock row (existing — unchanged)
        - Raw material decrements (existing — unchanged)
        - WaterExpenses rows for Electricity/Fuel/Labor/Other > 0
          (auto-Approved, paid from a default cash account when one exists)
        - WaterProductionLosses rows for damaged bags / rejected sachets > 0

      The expense category lookup is forgiving: it tries the obvious name
      first ('Electricity / Utilities' for electricity, etc.) and falls
      back to a generic 'Production' category, which it auto-creates if
      missing. No new infrastructure required on the user side.

   5. Reopen now reverses everything Approve created — expenses are
      Cancelled (with reverse cash txn), production-loss rows for the
      batch are deleted, raw material is restored (existing), stock txn
      reversed (existing). So an approve/reopen/approve cycle is safe:
      the second approve recreates a fresh, single set of linked records.

   6. Approve uses `WHERE NOT EXISTS` checks before re-inserting, so even
      an out-of-band double-approve cannot create duplicate linked rows.

   Idempotent: COL_LENGTH / OBJECT_ID guards everywhere.
   ============================================================================= */

SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

-- -----------------------------------------------------------------------------
-- 1. WaterProductionBatches.MachineScope
-- -----------------------------------------------------------------------------
IF COL_LENGTH('dbo.WaterProductionBatches', 'MachineScope') IS NULL
BEGIN
    PRINT 'Adding WaterProductionBatches.MachineScope';
    ALTER TABLE dbo.WaterProductionBatches
        ADD MachineScope NVARCHAR(20) NOT NULL
            CONSTRAINT DF_WaterProductionBatches_MachineScope DEFAULT ('SingleMachine') WITH VALUES;
END
GO

-- -----------------------------------------------------------------------------
-- 2. WaterProductionLosses — damage/reject loss records
-- -----------------------------------------------------------------------------
-- One row per damage+reject event (per batch). SourceType='ProductionBatch',
-- SourceId = WaterProductionBatchId so the Loss page can resolve back.
IF OBJECT_ID('dbo.WaterProductionLosses', 'U') IS NULL
BEGIN
    PRINT 'Creating dbo.WaterProductionLosses';
    CREATE TABLE dbo.WaterProductionLosses (
        WaterProductionLossId    INT IDENTITY(1,1) PRIMARY KEY,
        FarmId                   NVARCHAR(450) NOT NULL,
        LossDate                 DATE          NOT NULL,
        LossType                 NVARCHAR(40)  NOT NULL CONSTRAINT DF_WaterProductionLosses_Type DEFAULT ('ProductionDamage'),
        SourceType               NVARCHAR(40)  NOT NULL CONSTRAINT DF_WaterProductionLosses_SrcType DEFAULT ('ProductionBatch'),
        SourceId                 INT           NULL,
        WaterProductId           INT           NULL,
        BagsLost                 INT           NOT NULL CONSTRAINT DF_WaterProductionLosses_Bags DEFAULT (0),
        SachetsLost              INT           NOT NULL CONSTRAINT DF_WaterProductionLosses_Sachets DEFAULT (0),
        SachetsPerBag            INT           NOT NULL CONSTRAINT DF_WaterProductionLosses_SPB DEFAULT (30),
        CostPerBag               DECIMAL(14,4) NOT NULL CONSTRAINT DF_WaterProductionLosses_CPB DEFAULT (0),
        BagsLossValue            DECIMAL(14,2) NOT NULL CONSTRAINT DF_WaterProductionLosses_BagsVal DEFAULT (0),
        SachetsLossValue         DECIMAL(14,2) NOT NULL CONSTRAINT DF_WaterProductionLosses_SacVal DEFAULT (0),
        TotalValue               AS (BagsLossValue + SachetsLossValue) PERSISTED,
        Reason                   NVARCHAR(500) NULL,
        Status                   NVARCHAR(20)  NOT NULL CONSTRAINT DF_WaterProductionLosses_Status DEFAULT ('Approved'),
        Notes                    NVARCHAR(1000) NULL,
        CreatedBy                NVARCHAR(450) NULL,
        CreatedAt                DATETIME2     NOT NULL CONSTRAINT DF_WaterProductionLosses_CreatedAt DEFAULT (SYSUTCDATETIME()),
        IsDeleted                BIT           NOT NULL CONSTRAINT DF_WaterProductionLosses_IsDeleted DEFAULT (0),
        CONSTRAINT FK_WaterProductionLosses_Product FOREIGN KEY (WaterProductId)
            REFERENCES dbo.WaterProducts (WaterProductId)
    );

    CREATE INDEX IX_WaterProductionLosses_FarmId    ON dbo.WaterProductionLosses (FarmId);
    CREATE INDEX IX_WaterProductionLosses_Date      ON dbo.WaterProductionLosses (LossDate);
    CREATE INDEX IX_WaterProductionLosses_Source    ON dbo.WaterProductionLosses (SourceType, SourceId);
    CREATE INDEX IX_WaterProductionLosses_Product   ON dbo.WaterProductionLosses (WaterProductId);
END
GO

-- =============================================================================
-- 3. Helper: spWaterExpenseCategory_EnsureProductionDefaults
-- =============================================================================
-- Inserts (idempotently) the four production-related categories used by the
-- Approve SP. Safe to call repeatedly — uses NOT EXISTS guards.
CREATE OR ALTER PROCEDURE dbo.spWaterExpenseCategory_EnsureProductionDefaults
    @FarmId NVARCHAR(450)
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.WaterExpenseCategories
                   WHERE FarmId = @FarmId AND Name = N'Electricity / Utilities')
        INSERT INTO dbo.WaterExpenseCategories (FarmId, Name, Description, IsActive)
        VALUES (@FarmId, N'Electricity / Utilities',
                N'Auto-created for production-linked electricity expenses.', 1);

    IF NOT EXISTS (SELECT 1 FROM dbo.WaterExpenseCategories
                   WHERE FarmId = @FarmId AND Name = N'Fuel')
        INSERT INTO dbo.WaterExpenseCategories (FarmId, Name, Description, IsActive)
        VALUES (@FarmId, N'Fuel',
                N'Auto-created for production-linked fuel expenses.', 1);

    IF NOT EXISTS (SELECT 1 FROM dbo.WaterExpenseCategories
                   WHERE FarmId = @FarmId AND Name = N'Labor')
        INSERT INTO dbo.WaterExpenseCategories (FarmId, Name, Description, IsActive)
        VALUES (@FarmId, N'Labor',
                N'Auto-created for production-linked labor expenses.', 1);

    IF NOT EXISTS (SELECT 1 FROM dbo.WaterExpenseCategories
                   WHERE FarmId = @FarmId AND Name = N'Production Other')
        INSERT INTO dbo.WaterExpenseCategories (FarmId, Name, Description, IsActive)
        VALUES (@FarmId, N'Production Other',
                N'Auto-created for production-linked miscellaneous expenses.', 1);
END
GO

-- =============================================================================
-- 4. spWaterProductionBatch_GetAll  — now returns GoodBags / AllInCost /
--    CostPerBag / MachineScope, plus the existing fields.
-- =============================================================================
CREATE OR ALTER PROCEDURE dbo.spWaterProductionBatch_GetAll
    @FarmId   NVARCHAR(450),
    @Status   NVARCHAR(20) = NULL,
    @FromDate DATE         = NULL,
    @ToDate   DATE         = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT  b.*,
            p.Name AS ProductName,
            m.MachineName,
            bh.BoreholeName,
            -- Derived columns the list page now relies on.
            (b.BagsProduced - ISNULL(b.DamagedBags, 0)) AS GoodBags,
            (b.TotalProductionCost + ISNULL(b.RawMaterialCost, 0)) AS AllInCost,
            CASE
                WHEN (b.BagsProduced - ISNULL(b.DamagedBags, 0)) > 0
                THEN (b.TotalProductionCost + ISNULL(b.RawMaterialCost, 0))
                     / (b.BagsProduced - ISNULL(b.DamagedBags, 0))
                ELSE 0
            END AS CostPerBag,
            CASE
                WHEN (b.BagsProduced * b.SachetsPerBag) > 0
                THEN CAST(((b.BagsProduced * b.SachetsPerBag) - ISNULL(b.RejectedSachets,0)) * 100.0
                          / (b.BagsProduced * b.SachetsPerBag) AS DECIMAL(6,2))
                ELSE 0
            END AS ProductionEfficiencyPercent
    FROM    dbo.WaterProductionBatches b
    INNER   JOIN dbo.WaterProducts p   ON p.WaterProductId = b.WaterProductId
    LEFT    JOIN dbo.WaterMachines m   ON m.WaterMachineId = b.WaterMachineId
    LEFT    JOIN dbo.WaterBoreholes bh ON bh.WaterBoreholeId = b.WaterBoreholeId
    WHERE   b.FarmId = @FarmId AND b.IsDeleted = 0
       AND  (@Status   IS NULL OR b.Status = @Status)
       AND  (@FromDate IS NULL OR b.ProductionDate >= @FromDate)
       AND  (@ToDate   IS NULL OR b.ProductionDate <= @ToDate)
    ORDER  BY b.ProductionDate DESC, b.WaterProductionBatchId DESC;
END
GO

CREATE OR ALTER PROCEDURE dbo.spWaterProductionBatch_GetById
    @WaterProductionBatchId INT,
    @FarmId                 NVARCHAR(450)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT  b.*,
            p.Name AS ProductName,
            m.MachineName,
            bh.BoreholeName,
            (b.BagsProduced - ISNULL(b.DamagedBags, 0)) AS GoodBags,
            (b.TotalProductionCost + ISNULL(b.RawMaterialCost, 0)) AS AllInCost,
            CASE
                WHEN (b.BagsProduced - ISNULL(b.DamagedBags, 0)) > 0
                THEN (b.TotalProductionCost + ISNULL(b.RawMaterialCost, 0))
                     / (b.BagsProduced - ISNULL(b.DamagedBags, 0))
                ELSE 0
            END AS CostPerBag,
            CASE
                WHEN (b.BagsProduced * b.SachetsPerBag) > 0
                THEN CAST(((b.BagsProduced * b.SachetsPerBag) - ISNULL(b.RejectedSachets,0)) * 100.0
                          / (b.BagsProduced * b.SachetsPerBag) AS DECIMAL(6,2))
                ELSE 0
            END AS ProductionEfficiencyPercent
    FROM    dbo.WaterProductionBatches b
    INNER   JOIN dbo.WaterProducts p   ON p.WaterProductId = b.WaterProductId
    LEFT    JOIN dbo.WaterMachines m   ON m.WaterMachineId = b.WaterMachineId
    LEFT    JOIN dbo.WaterBoreholes bh ON bh.WaterBoreholeId = b.WaterBoreholeId
    WHERE   b.WaterProductionBatchId = @WaterProductionBatchId
      AND   b.FarmId = @FarmId;
END
GO

-- =============================================================================
-- 5. spWaterProductionBatch_Insert / _Update — accept @MachineScope
-- =============================================================================
-- Drop-in replacement. The MachineScope param defaults to 'SingleMachine' so
-- legacy callers (pre-Prompt 1) keep working without code changes.

CREATE OR ALTER PROCEDURE dbo.spWaterProductionBatch_Insert
    @FarmId                   NVARCHAR(450),
    @BatchNumber              NVARCHAR(60),
    @ProductionDate           DATE,
    @Shift                    NVARCHAR(20)  = 'FullDay',
    @WaterMachineId           INT           = NULL,
    @WaterBoreholeId          INT           = NULL,
    @OperatorStaffId          INT           = NULL,
    @StartTime                DATETIME2     = NULL,
    @EndTime                  DATETIME2     = NULL,
    @WaterProductId           INT,
    @BagsProduced             INT           = 0,
    @SachetsPerBag            INT           = 30,
    @LooseSachetsProduced     INT           = 0,
    @RejectedSachets          INT           = 0,
    @DamagedBags              INT           = 0,
    @PackagingRollsUsed       INT           = 0,
    @EstimatedWaterUsedLitres INT           = NULL,
    @ElectricityCost          DECIMAL(14,2) = 0,
    @FuelCost                 DECIMAL(14,2) = 0,
    @LaborCost                DECIMAL(14,2) = 0,
    @OtherProductionCost      DECIMAL(14,2) = 0,
    @QualityStatus            NVARCHAR(20)  = 'Pending',
    @QualityPHLevel           DECIMAL(5,2)  = NULL,
    @QualityChlorinePpm       DECIMAL(8,4)  = NULL,
    @QualityTurbidity         DECIMAL(8,4)  = NULL,
    @QualityTDS               INT           = NULL,
    @QualityNotes             NVARCHAR(500) = NULL,
    @Notes                    NVARCHAR(1000) = NULL,
    @CreatedBy                NVARCHAR(450) = NULL,
    @MaterialsUsedJson        NVARCHAR(MAX) = NULL,
    @MachineScope             NVARCHAR(20)  = 'SingleMachine'
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    IF (@BagsProduced < 0)
    BEGIN RAISERROR('BagsProduced cannot be negative.', 16, 1); RETURN; END
    IF (@SachetsPerBag <= 0) SET @SachetsPerBag = 30;
    IF (@DamagedBags < 0 OR @DamagedBags > @BagsProduced)
    BEGIN RAISERROR('DamagedBags must be between 0 and BagsProduced.', 16, 1); RETURN; END
    IF (@MachineScope IS NULL OR @MachineScope = N'') SET @MachineScope = N'SingleMachine';
    IF (@MachineScope NOT IN (N'SingleMachine', N'AllMachines'))
    BEGIN RAISERROR('MachineScope must be SingleMachine or AllMachines.', 16, 1); RETURN; END

    -- "All Machines / Combined" → ignore any machine id the caller sent.
    IF (@MachineScope = N'AllMachines') SET @WaterMachineId = NULL;

    BEGIN TRANSACTION;

    INSERT INTO dbo.WaterProductionBatches (
        FarmId, BatchNumber, ProductionDate, Shift, WaterMachineId, WaterBoreholeId,
        OperatorStaffId, StartTime, EndTime, WaterProductId, BagsProduced, SachetsPerBag,
        LooseSachetsProduced, RejectedSachets, DamagedBags, PackagingRollsUsed,
        EstimatedWaterUsedLitres, ElectricityCost, FuelCost, LaborCost, OtherProductionCost,
        QualityStatus, QualityPHLevel, QualityChlorinePpm, QualityTurbidity, QualityTDS,
        QualityNotes, Notes, Status, CreatedBy, MachineScope
    )
    VALUES (
        @FarmId, @BatchNumber, @ProductionDate, @Shift, @WaterMachineId, @WaterBoreholeId,
        @OperatorStaffId, @StartTime, @EndTime, @WaterProductId, @BagsProduced, @SachetsPerBag,
        @LooseSachetsProduced, @RejectedSachets, @DamagedBags, @PackagingRollsUsed,
        @EstimatedWaterUsedLitres, @ElectricityCost, @FuelCost, @LaborCost, @OtherProductionCost,
        @QualityStatus, @QualityPHLevel, @QualityChlorinePpm, @QualityTurbidity, @QualityTDS,
        @QualityNotes, @Notes, 'Draft', @CreatedBy, @MachineScope
    );

    DECLARE @BatchId INT = CAST(SCOPE_IDENTITY() AS INT);

    IF @MaterialsUsedJson IS NOT NULL AND LEN(@MaterialsUsedJson) > 2
    BEGIN
        INSERT INTO dbo.WaterRawMaterialUsage
            (FarmId, WaterRawMaterialItemId, WaterProductionBatchId, UsedDate,
             QuantityUsed, ExpectedQuantityUsed, UnitCost, VarianceReason, Notes, CreatedBy)
        SELECT
            @FarmId,
            j.WaterRawMaterialItemId,
            @BatchId,
            ISNULL(j.UsedDate, CAST(@ProductionDate AS DATETIME2)),
            ISNULL(j.QuantityUsed, 0),
            j.ExpectedQuantityUsed,
            j.UnitCost,
            j.VarianceReason,
            j.Notes,
            @CreatedBy
        FROM OPENJSON(@MaterialsUsedJson)
        WITH (
            WaterRawMaterialItemId INT             '$.waterRawMaterialItemId',
            QuantityUsed           DECIMAL(14,3)   '$.quantityUsed',
            ExpectedQuantityUsed   DECIMAL(14,3)   '$.expectedQuantityUsed',
            UnitCost               DECIMAL(14,4)   '$.unitCost',
            VarianceReason         NVARCHAR(500)   '$.varianceReason',
            Notes                  NVARCHAR(500)   '$.notes',
            UsedDate               DATETIME2       '$.usedDate'
        ) j
        WHERE j.WaterRawMaterialItemId IS NOT NULL;

        UPDATE b
        SET    b.RawMaterialCost = ISNULL((
                   SELECT SUM(u.TotalCost)
                   FROM   dbo.WaterRawMaterialUsage u
                   WHERE  u.WaterProductionBatchId = @BatchId), 0)
        FROM   dbo.WaterProductionBatches b
        WHERE  b.WaterProductionBatchId = @BatchId;
    END

    COMMIT TRANSACTION;

    SELECT @BatchId;
END
GO

CREATE OR ALTER PROCEDURE dbo.spWaterProductionBatch_Update
    @WaterProductionBatchId   INT,
    @FarmId                   NVARCHAR(450),
    @BatchNumber              NVARCHAR(60),
    @ProductionDate           DATE,
    @Shift                    NVARCHAR(20),
    @WaterMachineId           INT           = NULL,
    @WaterBoreholeId          INT           = NULL,
    @OperatorStaffId          INT           = NULL,
    @StartTime                DATETIME2     = NULL,
    @EndTime                  DATETIME2     = NULL,
    @WaterProductId           INT,
    @BagsProduced             INT,
    @SachetsPerBag            INT,
    @LooseSachetsProduced     INT,
    @RejectedSachets          INT,
    @DamagedBags              INT,
    @PackagingRollsUsed       INT,
    @EstimatedWaterUsedLitres INT           = NULL,
    @ElectricityCost          DECIMAL(14,2),
    @FuelCost                 DECIMAL(14,2),
    @LaborCost                DECIMAL(14,2),
    @OtherProductionCost      DECIMAL(14,2),
    @QualityStatus            NVARCHAR(20),
    @QualityPHLevel           DECIMAL(5,2)  = NULL,
    @QualityChlorinePpm       DECIMAL(8,4)  = NULL,
    @QualityTurbidity         DECIMAL(8,4)  = NULL,
    @QualityTDS               INT           = NULL,
    @QualityNotes             NVARCHAR(500) = NULL,
    @Notes                    NVARCHAR(1000) = NULL,
    @MaterialsUsedJson        NVARCHAR(MAX) = NULL,
    @MachineScope             NVARCHAR(20)  = 'SingleMachine'
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    IF EXISTS (SELECT 1 FROM dbo.WaterProductionBatches
               WHERE WaterProductionBatchId = @WaterProductionBatchId
                 AND FarmId = @FarmId AND Status = 'Approved')
    BEGIN
        RAISERROR('Cannot edit an Approved production batch. Reopen it first.', 16, 1);
        RETURN;
    END

    IF (@MachineScope IS NULL OR @MachineScope = N'') SET @MachineScope = N'SingleMachine';
    IF (@MachineScope NOT IN (N'SingleMachine', N'AllMachines'))
    BEGIN RAISERROR('MachineScope must be SingleMachine or AllMachines.', 16, 1); RETURN; END
    IF (@MachineScope = N'AllMachines') SET @WaterMachineId = NULL;

    BEGIN TRANSACTION;

    UPDATE dbo.WaterProductionBatches
    SET BatchNumber = @BatchNumber, ProductionDate = @ProductionDate, Shift = @Shift,
        WaterMachineId = @WaterMachineId, WaterBoreholeId = @WaterBoreholeId,
        OperatorStaffId = @OperatorStaffId, StartTime = @StartTime, EndTime = @EndTime,
        WaterProductId = @WaterProductId, BagsProduced = @BagsProduced,
        SachetsPerBag = @SachetsPerBag, LooseSachetsProduced = @LooseSachetsProduced,
        RejectedSachets = @RejectedSachets, DamagedBags = @DamagedBags,
        PackagingRollsUsed = @PackagingRollsUsed,
        EstimatedWaterUsedLitres = @EstimatedWaterUsedLitres,
        ElectricityCost = @ElectricityCost, FuelCost = @FuelCost,
        LaborCost = @LaborCost, OtherProductionCost = @OtherProductionCost,
        QualityStatus = @QualityStatus, QualityPHLevel = @QualityPHLevel,
        QualityChlorinePpm = @QualityChlorinePpm, QualityTurbidity = @QualityTurbidity,
        QualityTDS = @QualityTDS, QualityNotes = @QualityNotes, Notes = @Notes,
        MachineScope = @MachineScope,
        UpdatedAt = SYSUTCDATETIME()
    WHERE WaterProductionBatchId = @WaterProductionBatchId AND FarmId = @FarmId;

    IF @MaterialsUsedJson IS NOT NULL
    BEGIN
        DELETE FROM dbo.WaterRawMaterialUsage
        WHERE  FarmId = @FarmId AND WaterProductionBatchId = @WaterProductionBatchId;

        IF LEN(@MaterialsUsedJson) > 2
        BEGIN
            INSERT INTO dbo.WaterRawMaterialUsage
                (FarmId, WaterRawMaterialItemId, WaterProductionBatchId, UsedDate,
                 QuantityUsed, ExpectedQuantityUsed, UnitCost, VarianceReason, Notes)
            SELECT
                @FarmId,
                j.WaterRawMaterialItemId,
                @WaterProductionBatchId,
                ISNULL(j.UsedDate, CAST(@ProductionDate AS DATETIME2)),
                ISNULL(j.QuantityUsed, 0),
                j.ExpectedQuantityUsed,
                j.UnitCost,
                j.VarianceReason,
                j.Notes
            FROM OPENJSON(@MaterialsUsedJson)
            WITH (
                WaterRawMaterialItemId INT             '$.waterRawMaterialItemId',
                QuantityUsed           DECIMAL(14,3)   '$.quantityUsed',
                ExpectedQuantityUsed   DECIMAL(14,3)   '$.expectedQuantityUsed',
                UnitCost               DECIMAL(14,4)   '$.unitCost',
                VarianceReason         NVARCHAR(500)   '$.varianceReason',
                Notes                  NVARCHAR(500)   '$.notes',
                UsedDate               DATETIME2       '$.usedDate'
            ) j
            WHERE j.WaterRawMaterialItemId IS NOT NULL;
        END

        UPDATE b
        SET    b.RawMaterialCost = ISNULL((
                   SELECT SUM(u.TotalCost)
                   FROM   dbo.WaterRawMaterialUsage u
                   WHERE  u.WaterProductionBatchId = @WaterProductionBatchId), 0)
        FROM   dbo.WaterProductionBatches b
        WHERE  b.WaterProductionBatchId = @WaterProductionBatchId;
    END

    COMMIT TRANSACTION;
END
GO

-- =============================================================================
-- 6. spWaterProductionBatch_Approve — atomic linked-record creation
-- =============================================================================
-- Drop-in replacement of the body in migration 063. Adds:
--   - Auto-created Approved WaterExpenses for Electricity/Fuel/Labor/Other > 0
--   - Auto-created WaterProductionLosses for DamagedBags / RejectedSachets > 0
--
-- Duplicate-safety: each linked block uses NOT EXISTS so the SP is safe even
-- if a previous approve partially succeeded and someone manually re-ran it.
CREATE OR ALTER PROCEDURE dbo.spWaterProductionBatch_Approve
    @WaterProductionBatchId INT,
    @FarmId                 NVARCHAR(450),
    @ApprovedBy             NVARCHAR(450) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    -- Idempotent: already-approved batches return their current state.
    IF EXISTS (SELECT 1 FROM dbo.WaterProductionBatches
               WHERE WaterProductionBatchId = @WaterProductionBatchId AND FarmId = @FarmId AND Status = 'Approved')
    BEGIN
        SELECT WaterProductionBatchId, Status, ApprovedBy, ApprovedAt
        FROM dbo.WaterProductionBatches
        WHERE WaterProductionBatchId = @WaterProductionBatchId AND FarmId = @FarmId;
        RETURN;
    END

    DECLARE @Status         NVARCHAR(20),
            @ProductId      INT,
            @BagsProduced   INT,
            @DamagedBags    INT,
            @RejectedSachets INT,
            @SachetsPerBag  INT,
            @TotalCost      DECIMAL(14,2),
            @RawMatCost     DECIMAL(14,2),
            @ElectricityCost DECIMAL(14,2),
            @FuelCost       DECIMAL(14,2),
            @LaborCost      DECIMAL(14,2),
            @OtherCost      DECIMAL(14,2),
            @ProductionDate DATE,
            @BatchNo        NVARCHAR(60);

    SELECT @Status = Status, @ProductId = WaterProductId,
           @BagsProduced = BagsProduced, @DamagedBags = DamagedBags,
           @RejectedSachets = RejectedSachets,
           @SachetsPerBag = SachetsPerBag,
           @TotalCost = TotalProductionCost,
           @RawMatCost = ISNULL(RawMaterialCost, 0),
           @ElectricityCost = ElectricityCost,
           @FuelCost = FuelCost, @LaborCost = LaborCost,
           @OtherCost = OtherProductionCost,
           @ProductionDate = ProductionDate,
           @BatchNo = BatchNumber
    FROM   dbo.WaterProductionBatches
    WHERE  WaterProductionBatchId = @WaterProductionBatchId
       AND FarmId = @FarmId AND IsDeleted = 0;

    IF @Status IS NULL
    BEGIN RAISERROR('Production batch %d not found.', 16, 1, @WaterProductionBatchId); RETURN; END
    IF @Status <> 'Draft'
    BEGIN RAISERROR('Production batch cannot be approved from status %s.', 16, 1, @Status); RETURN; END

    -- Pre-check raw material availability.
    DECLARE @ShortName NVARCHAR(150), @ShortHave DECIMAL(14,3), @ShortNeed DECIMAL(14,3);
    SELECT TOP 1
           @ShortName = mi.ItemName,
           @ShortHave = mi.CurrentQuantity,
           @ShortNeed = u.QuantityUsed
    FROM   dbo.WaterRawMaterialUsage u
    JOIN   dbo.WaterRawMaterialItems mi ON mi.WaterRawMaterialItemId = u.WaterRawMaterialItemId
    WHERE  u.FarmId = @FarmId
      AND  u.WaterProductionBatchId = @WaterProductionBatchId
      AND  u.QuantityUsed > mi.CurrentQuantity;

    IF @ShortName IS NOT NULL
    BEGIN
        DECLARE @msg NVARCHAR(400) = CONCAT(
            'Not enough stock of "', @ShortName, '". Available: ',
            CAST(@ShortHave AS NVARCHAR(30)), ', needed: ',
            CAST(@ShortNeed AS NVARCHAR(30)),
            '. Record a purchase or reduce the actual quantity used.'
        );
        RAISERROR(N'%s', 16, 1, @msg);
        RETURN;
    END

    DECLARE @GoodBags INT = @BagsProduced - ISNULL(@DamagedBags, 0);
    IF (@GoodBags < 0) SET @GoodBags = 0;

    -- All-in cost (excl loss writeoffs) for per-bag costing.
    DECLARE @AllInCost DECIMAL(14,2) = @TotalCost + @RawMatCost;
    DECLARE @CostPerBag DECIMAL(14,4) =
        CASE WHEN @GoodBags > 0 THEN @AllInCost * 1.0 / @GoodBags ELSE 0 END;

    -- Ensure the four production expense categories exist.
    EXEC dbo.spWaterExpenseCategory_EnsureProductionDefaults @FarmId = @FarmId;

    DECLARE @CatElectricity INT, @CatFuel INT, @CatLabor INT, @CatOther INT;
    SELECT @CatElectricity = WaterExpenseCategoryId
    FROM   dbo.WaterExpenseCategories
    WHERE  FarmId = @FarmId AND Name = N'Electricity / Utilities';
    SELECT @CatFuel = WaterExpenseCategoryId
    FROM   dbo.WaterExpenseCategories
    WHERE  FarmId = @FarmId AND Name = N'Fuel';
    SELECT @CatLabor = WaterExpenseCategoryId
    FROM   dbo.WaterExpenseCategories
    WHERE  FarmId = @FarmId AND Name = N'Labor';
    SELECT @CatOther = WaterExpenseCategoryId
    FROM   dbo.WaterExpenseCategories
    WHERE  FarmId = @FarmId AND Name = N'Production Other';

    BEGIN TRANSACTION;

    UPDATE dbo.WaterProductionBatches
    SET    Status = 'Approved', ApprovedBy = @ApprovedBy,
           ApprovedAt = SYSUTCDATETIME(), UpdatedAt = SYSUTCDATETIME()
    WHERE  WaterProductionBatchId = @WaterProductionBatchId AND FarmId = @FarmId;

    -- ---------------------------------------------------------------
    -- A. Finished goods Restock (GoodBags only — never damaged bags).
    -- ---------------------------------------------------------------
    IF (@GoodBags > 0)
       AND NOT EXISTS (
           SELECT 1 FROM dbo.WaterStockTransactions
           WHERE  FarmId = @FarmId AND WaterProductId = @ProductId
             AND  TxnType = 'Restock'
             AND  Note    = CONCAT('Production batch ', @BatchNo)
       )
    BEGIN
        INSERT INTO dbo.WaterStockTransactions (
            FarmId, WaterProductId, TxnType, Quantity, UnitCost, RelatedSaleId,
            Note, CreatedBy
        )
        VALUES (
            @FarmId, @ProductId, 'Restock', @GoodBags,
            CAST(@CostPerBag AS DECIMAL(12,2)), NULL,
            CONCAT('Production batch ', @BatchNo), @ApprovedBy
        );
    END

    -- ---------------------------------------------------------------
    -- B. Raw material decrements.
    -- ---------------------------------------------------------------
    UPDATE mi
    SET    mi.CurrentQuantity = mi.CurrentQuantity - u.QuantityUsed,
           mi.UpdatedAt       = SYSUTCDATETIME()
    FROM   dbo.WaterRawMaterialItems mi
    JOIN   dbo.WaterRawMaterialUsage u ON u.WaterRawMaterialItemId = mi.WaterRawMaterialItemId
    WHERE  u.FarmId = @FarmId
      AND  u.WaterProductionBatchId = @WaterProductionBatchId;

    -- ---------------------------------------------------------------
    -- C. Production-linked Expense rows (Electricity / Fuel / Labor / Other).
    --     We pick a default cash account if one exists, otherwise use Credit
    --     so the expense still books without forcing the user to configure
    --     cash accounts. The expense row is auto-Approved.
    -- ---------------------------------------------------------------
    DECLARE @DefaultCashAccountId INT;
    SELECT TOP 1 @DefaultCashAccountId = WaterCashAccountId
    FROM   dbo.WaterCashAccounts
    WHERE  FarmId = @FarmId AND IsActive = 1
    ORDER  BY WaterCashAccountId;

    DECLARE @ProdDateTime DATETIME2 = CAST(@ProductionDate AS DATETIME2);

    -- Helper inline: only insert when amount > 0 AND no prior linked row
    -- exists for this batch+category (idempotent re-approve).
    IF (@ElectricityCost > 0 AND @CatElectricity IS NOT NULL
        AND NOT EXISTS (SELECT 1 FROM dbo.WaterExpenses
                        WHERE FarmId = @FarmId
                          AND LinkedWaterProductionBatchId = @WaterProductionBatchId
                          AND WaterExpenseCategoryId = @CatElectricity
                          AND IsDeleted = 0
                          AND Status IN ('Draft','Submitted','Approved')))
    BEGIN
        INSERT INTO dbo.WaterExpenses
            (FarmId, ExpenseDate, WaterExpenseCategoryId, Description, Amount,
             PaymentMethod, WaterCashAccountId, LinkedWaterProductionBatchId,
             Status, Notes, CreatedBy, ApprovedBy, ApprovedAt)
        VALUES
            (@FarmId, @ProdDateTime, @CatElectricity,
             CONCAT('Electricity — Production batch ', @BatchNo),
             @ElectricityCost,
             CASE WHEN @DefaultCashAccountId IS NULL THEN 'Credit' ELSE 'Cash' END,
             @DefaultCashAccountId, @WaterProductionBatchId,
             'Approved',
             N'Auto-created from production batch approval.',
             @ApprovedBy, @ApprovedBy, SYSUTCDATETIME());
    END

    IF (@FuelCost > 0 AND @CatFuel IS NOT NULL
        AND NOT EXISTS (SELECT 1 FROM dbo.WaterExpenses
                        WHERE FarmId = @FarmId
                          AND LinkedWaterProductionBatchId = @WaterProductionBatchId
                          AND WaterExpenseCategoryId = @CatFuel
                          AND IsDeleted = 0
                          AND Status IN ('Draft','Submitted','Approved')))
    BEGIN
        INSERT INTO dbo.WaterExpenses
            (FarmId, ExpenseDate, WaterExpenseCategoryId, Description, Amount,
             PaymentMethod, WaterCashAccountId, LinkedWaterProductionBatchId,
             Status, Notes, CreatedBy, ApprovedBy, ApprovedAt)
        VALUES
            (@FarmId, @ProdDateTime, @CatFuel,
             CONCAT('Fuel — Production batch ', @BatchNo),
             @FuelCost,
             CASE WHEN @DefaultCashAccountId IS NULL THEN 'Credit' ELSE 'Cash' END,
             @DefaultCashAccountId, @WaterProductionBatchId,
             'Approved',
             N'Auto-created from production batch approval.',
             @ApprovedBy, @ApprovedBy, SYSUTCDATETIME());
    END

    IF (@LaborCost > 0 AND @CatLabor IS NOT NULL
        AND NOT EXISTS (SELECT 1 FROM dbo.WaterExpenses
                        WHERE FarmId = @FarmId
                          AND LinkedWaterProductionBatchId = @WaterProductionBatchId
                          AND WaterExpenseCategoryId = @CatLabor
                          AND IsDeleted = 0
                          AND Status IN ('Draft','Submitted','Approved')))
    BEGIN
        INSERT INTO dbo.WaterExpenses
            (FarmId, ExpenseDate, WaterExpenseCategoryId, Description, Amount,
             PaymentMethod, WaterCashAccountId, LinkedWaterProductionBatchId,
             Status, Notes, CreatedBy, ApprovedBy, ApprovedAt)
        VALUES
            (@FarmId, @ProdDateTime, @CatLabor,
             CONCAT('Labor — Production batch ', @BatchNo),
             @LaborCost,
             CASE WHEN @DefaultCashAccountId IS NULL THEN 'Credit' ELSE 'Cash' END,
             @DefaultCashAccountId, @WaterProductionBatchId,
             'Approved',
             N'Auto-created from production batch approval.',
             @ApprovedBy, @ApprovedBy, SYSUTCDATETIME());
    END

    IF (@OtherCost > 0 AND @CatOther IS NOT NULL
        AND NOT EXISTS (SELECT 1 FROM dbo.WaterExpenses
                        WHERE FarmId = @FarmId
                          AND LinkedWaterProductionBatchId = @WaterProductionBatchId
                          AND WaterExpenseCategoryId = @CatOther
                          AND IsDeleted = 0
                          AND Status IN ('Draft','Submitted','Approved')))
    BEGIN
        INSERT INTO dbo.WaterExpenses
            (FarmId, ExpenseDate, WaterExpenseCategoryId, Description, Amount,
             PaymentMethod, WaterCashAccountId, LinkedWaterProductionBatchId,
             Status, Notes, CreatedBy, ApprovedBy, ApprovedAt)
        VALUES
            (@FarmId, @ProdDateTime, @CatOther,
             CONCAT('Other production cost — Production batch ', @BatchNo),
             @OtherCost,
             CASE WHEN @DefaultCashAccountId IS NULL THEN 'Credit' ELSE 'Cash' END,
             @DefaultCashAccountId, @WaterProductionBatchId,
             'Approved',
             N'Auto-created from production batch approval.',
             @ApprovedBy, @ApprovedBy, SYSUTCDATETIME());
    END

    -- ---------------------------------------------------------------
    -- D. Production-linked Loss record (damaged bags + rejected sachets).
    --     Only inserted when at least one quantity > 0.
    -- ---------------------------------------------------------------
    IF (ISNULL(@DamagedBags,0) > 0 OR ISNULL(@RejectedSachets,0) > 0)
       AND NOT EXISTS (
           SELECT 1 FROM dbo.WaterProductionLosses
           WHERE  FarmId = @FarmId
             AND  SourceType = 'ProductionBatch'
             AND  SourceId   = @WaterProductionBatchId
             AND  IsDeleted  = 0
       )
    BEGIN
        DECLARE @BagsLossValue    DECIMAL(14,2) =
            CAST(ISNULL(@DamagedBags,0) AS DECIMAL(14,2)) * @CostPerBag;
        DECLARE @SachetsLossValue DECIMAL(14,2) =
            CASE WHEN @SachetsPerBag > 0
                 THEN (CAST(ISNULL(@RejectedSachets,0) AS DECIMAL(14,2)) / @SachetsPerBag) * @CostPerBag
                 ELSE 0 END;

        INSERT INTO dbo.WaterProductionLosses
            (FarmId, LossDate, LossType, SourceType, SourceId,
             WaterProductId, BagsLost, SachetsLost, SachetsPerBag,
             CostPerBag, BagsLossValue, SachetsLossValue,
             Reason, Status, Notes, CreatedBy)
        VALUES
            (@FarmId, @ProductionDate, 'ProductionDamage',
             'ProductionBatch', @WaterProductionBatchId,
             @ProductId, ISNULL(@DamagedBags,0), ISNULL(@RejectedSachets,0),
             @SachetsPerBag,
             @CostPerBag,
             @BagsLossValue, @SachetsLossValue,
             N'Production damage / rejected during production',
             'Approved',
             CONCAT('Auto-created from production batch ', @BatchNo),
             @ApprovedBy);
    END

    COMMIT TRANSACTION;

    SELECT WaterProductionBatchId, Status, ApprovedBy, ApprovedAt
    FROM   dbo.WaterProductionBatches
    WHERE  WaterProductionBatchId = @WaterProductionBatchId AND FarmId = @FarmId;
END
GO

-- =============================================================================
-- 7. spWaterProductionBatch_Reopen — reverse the linked records too
-- =============================================================================
CREATE OR ALTER PROCEDURE dbo.spWaterProductionBatch_Reopen
    @WaterProductionBatchId INT,
    @FarmId                 NVARCHAR(450),
    @ReopenedBy             NVARCHAR(450) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    DECLARE @Status       NVARCHAR(20),
            @ProductId    INT,
            @BagsProduced INT,
            @DamagedBags  INT,
            @BatchNo      NVARCHAR(60);

    SELECT @Status       = Status,
           @ProductId    = WaterProductId,
           @BagsProduced = BagsProduced,
           @DamagedBags  = DamagedBags,
           @BatchNo      = BatchNumber
    FROM   dbo.WaterProductionBatches
    WHERE  WaterProductionBatchId = @WaterProductionBatchId
       AND FarmId = @FarmId
       AND IsDeleted = 0;

    IF @Status IS NULL
    BEGIN RAISERROR('Production batch %d not found.', 16, 1, @WaterProductionBatchId); RETURN; END
    IF @Status <> 'Approved'
    BEGIN RAISERROR('Only Approved batches can be reopened. Current status: %s.', 16, 1, @Status); RETURN; END

    DECLARE @GoodBags INT = @BagsProduced - ISNULL(@DamagedBags, 0);
    IF (@GoodBags < 0) SET @GoodBags = 0;

    DECLARE @CurrentStock INT = ISNULL((
        SELECT SUM(Quantity) FROM dbo.WaterStockTransactions
        WHERE FarmId = @FarmId AND WaterProductId = @ProductId
    ), 0);

    IF @GoodBags > 0 AND @CurrentStock < @GoodBags
    BEGIN
        RAISERROR('Cannot reopen: only %d bags of this product remain in stock, but the batch added %d. Cancel related sales or adjust stock first.',
                  16, 1, @CurrentStock, @GoodBags);
        RETURN;
    END

    BEGIN TRANSACTION;

    -- Reverse the finished goods restock with a balancing Adjust txn.
    IF (@GoodBags > 0)
    BEGIN
        INSERT INTO dbo.WaterStockTransactions
            (FarmId, WaterProductId, TxnType, Quantity, UnitCost, RelatedSaleId, Note, CreatedBy)
        VALUES
            (@FarmId, @ProductId, 'Adjust', -@GoodBags, NULL, NULL,
             CONCAT('Reopen production batch ', @BatchNo), @ReopenedBy);
    END

    -- Restore raw material quantities.
    UPDATE mi
    SET    mi.CurrentQuantity = mi.CurrentQuantity + u.QuantityUsed,
           mi.UpdatedAt       = SYSUTCDATETIME()
    FROM   dbo.WaterRawMaterialItems mi
    JOIN   dbo.WaterRawMaterialUsage u ON u.WaterRawMaterialItemId = mi.WaterRawMaterialItemId
    WHERE  u.FarmId = @FarmId
      AND  u.WaterProductionBatchId = @WaterProductionBatchId;

    -- Cancel linked expenses. For non-credit expenses that had been booked
    -- against a cash account at approve time, post a reversing CashIn so the
    -- balance comes back to where it was. Expenses already Rejected/Cancelled
    -- are skipped.
    DECLARE @ExpenseId INT, @ExpenseAmount DECIMAL(14,2),
            @ExpensePayment NVARCHAR(20), @ExpenseCash INT;
    DECLARE expense_cursor CURSOR LOCAL FAST_FORWARD FOR
        SELECT WaterExpenseId, Amount, PaymentMethod, WaterCashAccountId
        FROM   dbo.WaterExpenses
        WHERE  FarmId = @FarmId
          AND  LinkedWaterProductionBatchId = @WaterProductionBatchId
          AND  IsDeleted = 0
          AND  Status IN ('Draft','Submitted','Approved');

    OPEN expense_cursor;
    FETCH NEXT FROM expense_cursor INTO @ExpenseId, @ExpenseAmount, @ExpensePayment, @ExpenseCash;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF (@ExpensePayment <> 'Credit' AND @ExpenseCash IS NOT NULL
            AND EXISTS (SELECT 1 FROM dbo.WaterCashTransactions
                        WHERE SourceType = 'Expense' AND SourceId = @ExpenseId
                          AND Amount < 0))
        BEGIN
            INSERT INTO dbo.WaterCashTransactions (
                FarmId, WaterCashAccountId, TransactionDate, TransactionType,
                SourceType, SourceId, Amount, Description, CreatedBy, ApprovedBy, ApprovedAt)
            VALUES (
                @FarmId, @ExpenseCash, SYSUTCDATETIME(), 'Adjustment',
                'Expense', @ExpenseId, @ExpenseAmount,
                CONCAT('Reverse — production batch ', @BatchNo, ' reopened'),
                @ReopenedBy, @ReopenedBy, SYSUTCDATETIME());

            UPDATE dbo.WaterCashAccounts
            SET    CurrentBalance = CurrentBalance + @ExpenseAmount,
                   UpdatedAt = SYSUTCDATETIME()
            WHERE  WaterCashAccountId = @ExpenseCash;
        END

        UPDATE dbo.WaterExpenses
        SET    Status     = 'Cancelled',
               UpdatedAt  = SYSUTCDATETIME(),
               Notes      = LEFT(ISNULL(Notes, N'') + CHAR(10) +
                                 N'Cancelled — production batch reopened.', 1000)
        WHERE  WaterExpenseId = @ExpenseId;

        FETCH NEXT FROM expense_cursor INTO @ExpenseId, @ExpenseAmount, @ExpensePayment, @ExpenseCash;
    END
    CLOSE expense_cursor;
    DEALLOCATE expense_cursor;

    -- Soft-delete linked loss rows. (We don't hard-delete so the auditor can
    -- still see "what was once recorded".)
    UPDATE dbo.WaterProductionLosses
    SET    IsDeleted = 1,
           Status    = 'Cancelled'
    WHERE  FarmId = @FarmId
      AND  SourceType = 'ProductionBatch'
      AND  SourceId   = @WaterProductionBatchId
      AND  IsDeleted  = 0;

    -- Flip the batch back to Draft.
    UPDATE dbo.WaterProductionBatches
    SET    Status      = 'Draft',
           ApprovedBy  = NULL,
           ApprovedAt  = NULL,
           UpdatedAt   = SYSUTCDATETIME()
    WHERE  WaterProductionBatchId = @WaterProductionBatchId
       AND FarmId = @FarmId;

    COMMIT TRANSACTION;

    SELECT WaterProductionBatchId, Status, ApprovedBy, ApprovedAt
    FROM   dbo.WaterProductionBatches
    WHERE  WaterProductionBatchId = @WaterProductionBatchId AND FarmId = @FarmId;
END
GO

-- =============================================================================
-- 8. Loss + linked-records read SPs
-- =============================================================================
CREATE OR ALTER PROCEDURE dbo.spWaterProductionLoss_GetAll
    @FarmId   NVARCHAR(450),
    @FromDate DATE = NULL,
    @ToDate   DATE = NULL,
    @Status   NVARCHAR(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SELECT  l.WaterProductionLossId, l.FarmId, l.LossDate, l.LossType,
            l.SourceType, l.SourceId,
            l.WaterProductId, p.Name AS ProductName,
            l.BagsLost, l.SachetsLost, l.SachetsPerBag,
            l.CostPerBag, l.BagsLossValue, l.SachetsLossValue, l.TotalValue,
            l.Reason, l.Status, l.Notes, l.CreatedBy, l.CreatedAt,
            b.BatchNumber
    FROM    dbo.WaterProductionLosses l
    LEFT    JOIN dbo.WaterProducts p ON p.WaterProductId = l.WaterProductId
    LEFT    JOIN dbo.WaterProductionBatches b
            ON b.WaterProductionBatchId = l.SourceId AND l.SourceType = 'ProductionBatch'
    WHERE   l.FarmId = @FarmId
      AND   l.IsDeleted = 0
      AND   (@FromDate IS NULL OR l.LossDate >= @FromDate)
      AND   (@ToDate   IS NULL OR l.LossDate <= @ToDate)
      AND   (@Status   IS NULL OR l.Status = @Status)
    ORDER  BY l.LossDate DESC, l.WaterProductionLossId DESC;
END
GO

CREATE OR ALTER PROCEDURE dbo.spWaterProductionLoss_GetByBatch
    @FarmId                 NVARCHAR(450),
    @WaterProductionBatchId INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT  l.WaterProductionLossId, l.FarmId, l.LossDate, l.LossType,
            l.SourceType, l.SourceId,
            l.WaterProductId, p.Name AS ProductName,
            l.BagsLost, l.SachetsLost, l.SachetsPerBag,
            l.CostPerBag, l.BagsLossValue, l.SachetsLossValue, l.TotalValue,
            l.Reason, l.Status, l.Notes, l.CreatedBy, l.CreatedAt
    FROM    dbo.WaterProductionLosses l
    LEFT    JOIN dbo.WaterProducts p ON p.WaterProductId = l.WaterProductId
    WHERE   l.FarmId = @FarmId
      AND   l.SourceType = 'ProductionBatch'
      AND   l.SourceId   = @WaterProductionBatchId
      AND   l.IsDeleted  = 0
    ORDER  BY l.WaterProductionLossId;
END
GO

-- Helper used by the details view to list the production-linked expenses for
-- a given batch in one call.
CREATE OR ALTER PROCEDURE dbo.spWaterProductionBatch_GetLinkedExpenses
    @FarmId                 NVARCHAR(450),
    @WaterProductionBatchId INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT  e.WaterExpenseId, e.FarmId, e.ExpenseDate,
            e.WaterExpenseCategoryId, c.Name AS CategoryName,
            e.Description, e.Amount, e.PaidTo, e.PaymentMethod,
            e.WaterCashAccountId, ca.AccountName AS CashAccountName,
            e.LinkedWaterProductionBatchId,
            e.Status, e.Notes, e.CreatedBy, e.ApprovedBy, e.ApprovedAt, e.CreatedAt
    FROM    dbo.WaterExpenses e
    INNER   JOIN dbo.WaterExpenseCategories c ON c.WaterExpenseCategoryId = e.WaterExpenseCategoryId
    LEFT    JOIN dbo.WaterCashAccounts ca     ON ca.WaterCashAccountId   = e.WaterCashAccountId
    WHERE   e.FarmId = @FarmId
      AND   e.LinkedWaterProductionBatchId = @WaterProductionBatchId
      AND   e.IsDeleted = 0
    ORDER  BY e.WaterExpenseId;
END
GO

CREATE OR ALTER PROCEDURE dbo.spWaterProductionBatch_GetLinkedStockTxns
    @FarmId                 NVARCHAR(450),
    @WaterProductionBatchId INT
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @BatchNo NVARCHAR(60);
    SELECT @BatchNo = BatchNumber
    FROM   dbo.WaterProductionBatches
    WHERE  WaterProductionBatchId = @WaterProductionBatchId AND FarmId = @FarmId;

    IF @BatchNo IS NULL RETURN;

    -- Finished goods movements written by Approve/Reopen.
    SELECT  s.StockTxnId AS WaterStockTransactionId,
            s.WaterProductId, p.Name AS ProductName,
            s.TxnType, s.Quantity, s.UnitCost, s.Note,
            s.CreatedDate AS CreatedAt
    FROM    dbo.WaterStockTransactions s
    INNER   JOIN dbo.WaterProducts p ON p.WaterProductId = s.WaterProductId
    WHERE   s.FarmId = @FarmId
      AND   (s.Note = CONCAT('Production batch ', @BatchNo)
             OR s.Note = CONCAT('Reopen production batch ', @BatchNo))
    ORDER  BY s.StockTxnId;
END
GO

-- =============================================================================
-- 9. Grant execute on the new SPs
-- =============================================================================
IF EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'PoultryAppRole' AND type = 'R')
BEGIN
    GRANT EXECUTE ON dbo.spWaterExpenseCategory_EnsureProductionDefaults TO PoultryAppRole;
    GRANT EXECUTE ON dbo.spWaterProductionBatch_GetAll                   TO PoultryAppRole;
    GRANT EXECUTE ON dbo.spWaterProductionBatch_GetById                  TO PoultryAppRole;
    GRANT EXECUTE ON dbo.spWaterProductionBatch_Insert                   TO PoultryAppRole;
    GRANT EXECUTE ON dbo.spWaterProductionBatch_Update                   TO PoultryAppRole;
    GRANT EXECUTE ON dbo.spWaterProductionBatch_Approve                  TO PoultryAppRole;
    GRANT EXECUTE ON dbo.spWaterProductionBatch_Reopen                   TO PoultryAppRole;
    GRANT EXECUTE ON dbo.spWaterProductionLoss_GetAll                    TO PoultryAppRole;
    GRANT EXECUTE ON dbo.spWaterProductionLoss_GetByBatch                TO PoultryAppRole;
    GRANT EXECUTE ON dbo.spWaterProductionBatch_GetLinkedExpenses        TO PoultryAppRole;
    GRANT EXECUTE ON dbo.spWaterProductionBatch_GetLinkedStockTxns       TO PoultryAppRole;
END
GO

PRINT '067_FixProductionBatchCostingAndLinkedRecords.sql complete.';
GO
