-- =============================================================================
-- 212_AddPoultryCompanyProfile.postgres.sql
--
-- Problem
-- -------
-- Water companies have a real, database-backed company profile: migration 049
-- created WaterCompanyProfiles plus spWaterCompany_GetProfile / _Setup /
-- _UpdateProfile, and /water-company-setup reads and writes it through
-- /api/Water/company. Generic companies have the same via GenericCompanyProfiles
-- (migration 028).
--
-- Poultry has nothing equivalent. Its "farm profile" page, /settings, keeps
-- everything in the BROWSER: 30 localStorage calls, no API, no table. Three
-- consequences, all live today:
--
--   * Nothing persists. Clearing site data or moving to another machine loses
--     the farm's name, location, currency and owner details.
--   * The keys are not namespaced per company (farmName, currency, ownerName
--     ...), so a user who switches company sees the previous company's values
--     and can overwrite them.
--   * Nothing downstream can read the profile, because the server never sees
--     it. Reports and receipts cannot use the brand name or currency.
--
-- Fix
-- ---
-- Mirror the Water design for Poultry, keeping every field /settings collects
-- today so the page loses nothing when it moves to the database.
--
--   PoultryCompanyProfiles     one row per farmid, unique on farmid
--   sppoultrycompany_getprofile
--   sppoultrycompany_setup        first-time setup; also seeds finance defaults
--   sppoultrycompany_updateprofile
--
-- Poultry equivalents of Water's two enums:
--   BusinessType    Layers | Broilers | Both   (Water: Sachet | Bottled | Both)
--   HousingSystem   DeepLitter | BatteryCage | FreeRange | Mixed
--                                              (Water: WaterSourceType)
--   DefaultCrateEggCount                       (Water: DefaultBagSachetCount)
--
-- DefaultCrateEggCount earns its place: eggs-per-crate is currently hardcoded
-- to 30 in the vehicle-loading form and defaulted to 30 in the loading tables.
-- Migration 211 made that number load-bearing for egg stock, so a farm that
-- uses a different crate size needs somewhere to say so.
--
-- setup() calls sppoultryfinance_seeddefaults (migration 129), matching how
-- spWaterCompany_Setup calls spWaterFinance_SeedDefaults, so one POST prepares
-- a brand-new poultry company completely.
--
-- Unlike the Water proc, setup() returns ONE result set (the profile). The
-- Water version emits the seed verification counts first, which forced
-- WaterCompanyService to skip result sets by sniffing for a column name; there
-- is no reason to repeat that here.
--
-- Output columns are quoted so the reader can address them as
-- "PoultryCompanyProfileId", "FarmId", ... exactly like the Water service does.
--
-- Additive and idempotent: CREATE TABLE IF NOT EXISTS, CREATE OR REPLACE
-- FUNCTION. Nothing existing is modified.
-- =============================================================================

\set ON_ERROR_STOP on

-- -----------------------------------------------------------------------------
-- 1. PoultryCompanyProfiles (one row per farmid)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS poultrycompanyprofiles (
    poultrycompanyprofileid  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmid                   text          NOT NULL,
    brandname                varchar(150)  NULL,
    businesstype             varchar(30)   NOT NULL DEFAULT 'Layers',      -- Layers | Broilers | Both
    farmsiteaddress          varchar(500)  NULL,
    mainlocation             varchar(255)  NULL,
    housingsystem            varchar(30)   NOT NULL DEFAULT 'DeepLitter',  -- DeepLitter | BatteryCage | FreeRange | Mixed
    defaultcurrency          varchar(10)   NOT NULL DEFAULT 'GHC',
    defaultcrateeggcount     integer       NOT NULL DEFAULT 30,
    totalcapacity            integer       NULL,                           -- birds the farm can house
    operatinghours           varchar(100)  NULL,
    ownername                varchar(150)  NULL,
    phonenumber              varchar(50)   NULL,
    email                    varchar(150)  NULL,
    notes                    varchar(1000) NULL,
    createdat                timestamp     NOT NULL DEFAULT (now() at time zone 'utc'),
    updatedat                timestamp     NULL,
    CONSTRAINT uq_poultrycompanyprofiles_farmid UNIQUE (farmid)
);

CREATE INDEX IF NOT EXISTS ix_poultrycompanyprofiles_farmid ON poultrycompanyprofiles (farmid);

-- -----------------------------------------------------------------------------
-- 1b. sppoultryfinance_seeddefaults -- ported from T-SQL migration 129.
--
-- The Water equivalent (spwaterfinance_seeddefaults) exists on this database,
-- but the poultry one was never converted: migration 129 defined
-- spPoultryFinance_SeedDefaults in T-SQL and the conversion missed it. Setup
-- has nothing to call without it, so it is ported here.
--
-- Cash accounts only. Water seeds expense categories as well, but poultry has
-- no poultryexpensecategories table -- poultry expenses use the shared Expense
-- table with a free-text Category -- so there is nothing to seed there. The
-- four accounts and their types are migration 129's list verbatim.
--
-- Idempotent: ON CONFLICT on the existing uq_poultrycashaccounts_farm_name.
-- Returns the resulting account count, matching the T-SQL readout.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.sppoultryfinance_seeddefaults(p_farmid text)
RETURNS TABLE ("CashAccountCount" integer)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO poultrycashaccounts (farmid, accountname, accounttype, openingbalance, currentbalance)
    SELECT p_farmid, a.accountname, a.accounttype, 0, 0
    FROM   (VALUES
              ('Farm Cash Box', 'FarmCashBox'),
              ('MoMo Wallet',   'MoMoWallet'),
              ('Bank Account',  'BankAccount'),
              ('Petty Cash',    'PettyCash')
           ) AS a(accountname, accounttype)
    ON CONFLICT (farmid, accountname) DO NOTHING;

    RETURN QUERY
    SELECT (SELECT COUNT(*) FROM poultrycashaccounts ka WHERE ka.farmid = p_farmid)::int;
END;
$$;

-- -----------------------------------------------------------------------------
-- 2. Get the profile. Returns no rows when the farm has not been set up yet --
--    the controller turns that into a 404 and the page treats it as "new".
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.sppoultrycompany_getprofile(p_farmid text)
RETURNS TABLE (
    "PoultryCompanyProfileId" integer,
    "FarmId"                  text,
    "BrandName"               text,
    "BusinessType"            text,
    "FarmSiteAddress"         text,
    "MainLocation"            text,
    "HousingSystem"           text,
    "DefaultCurrency"         text,
    "DefaultCrateEggCount"    integer,
    "TotalCapacity"           integer,
    "OperatingHours"          text,
    "OwnerName"               text,
    "PhoneNumber"             text,
    "Email"                   text,
    "Notes"                   text,
    "CreatedAt"               timestamp,
    "UpdatedAt"               timestamp
)
LANGUAGE sql
STABLE
AS $$
    SELECT p.poultrycompanyprofileid, p.farmid, p.brandname::text, p.businesstype::text,
           p.farmsiteaddress::text, p.mainlocation::text, p.housingsystem::text,
           p.defaultcurrency::text, p.defaultcrateeggcount, p.totalcapacity,
           p.operatinghours::text, p.ownername::text, p.phonenumber::text,
           p.email::text, p.notes::text, p.createdat, p.updatedat
    FROM   poultrycompanyprofiles p
    WHERE  p.farmid = p_farmid;
$$;

-- -----------------------------------------------------------------------------
-- 3. Setup. Validates the farm exists and is Type='Poultry', upserts the
--    profile, seeds the finance defaults, and returns the resulting row.
--    Idempotent: running it again updates the existing profile in place.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.sppoultrycompany_setup(
    p_farmid               text,
    p_brandname            text    DEFAULT NULL,
    p_businesstype         text    DEFAULT 'Layers',
    p_farmsiteaddress      text    DEFAULT NULL,
    p_mainlocation         text    DEFAULT NULL,
    p_housingsystem        text    DEFAULT 'DeepLitter',
    p_defaultcurrency      text    DEFAULT 'GHC',
    p_defaultcrateeggcount integer DEFAULT 30,
    p_totalcapacity        integer DEFAULT NULL,
    p_operatinghours       text    DEFAULT NULL,
    p_ownername            text    DEFAULT NULL,
    p_phonenumber          text    DEFAULT NULL,
    p_email                text    DEFAULT NULL,
    p_notes                text    DEFAULT NULL
)
RETURNS TABLE (
    "PoultryCompanyProfileId" integer,
    "FarmId"                  text,
    "BrandName"               text,
    "BusinessType"            text,
    "FarmSiteAddress"         text,
    "MainLocation"            text,
    "HousingSystem"           text,
    "DefaultCurrency"         text,
    "DefaultCrateEggCount"    integer,
    "TotalCapacity"           integer,
    "OperatingHours"          text,
    "OwnerName"               text,
    "PhoneNumber"             text,
    "Email"                   text,
    "Notes"                   text,
    "CreatedAt"               timestamp,
    "UpdatedAt"               timestamp
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_farmtype text;
    v_biz      text := COALESCE(NULLIF(btrim(p_businesstype),  ''), 'Layers');
    v_house    text := COALESCE(NULLIF(btrim(p_housingsystem), ''), 'DeepLitter');
    v_curr     text := COALESCE(NULLIF(btrim(p_defaultcurrency), ''), 'GHC');
    v_crate    integer := COALESCE(p_defaultcrateeggcount, 30);
    v_seedfn   text;
BEGIN
    -- 1. The farm must exist and be a poultry company.
    SELECT f.type INTO v_farmtype FROM farms f WHERE f.farmid = p_farmid LIMIT 1;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Company % does not exist.', p_farmid;
    END IF;
    IF v_farmtype IS DISTINCT FROM 'Poultry' THEN
        RAISE EXCEPTION 'Company % is not a Poultry company (Type=%).', p_farmid, COALESCE(v_farmtype, 'null');
    END IF;

    -- 2. Validate the enums. Matched case-insensitively and stored canonically,
    --    so a form that sends 'layers' or 'BATTERYCAGE' is accepted rather than
    --    rejected with an error the user cannot act on.
    v_biz := CASE lower(v_biz)
                WHEN 'layers'   THEN 'Layers'
                WHEN 'broilers' THEN 'Broilers'
                WHEN 'both'     THEN 'Both'
                ELSE NULL
             END;
    IF v_biz IS NULL THEN
        RAISE EXCEPTION 'BusinessType must be Layers, Broilers, or Both.';
    END IF;

    v_house := CASE lower(v_house)
                WHEN 'deeplitter'  THEN 'DeepLitter'
                WHEN 'batterycage' THEN 'BatteryCage'
                WHEN 'freerange'   THEN 'FreeRange'
                WHEN 'mixed'       THEN 'Mixed'
                ELSE NULL
             END;
    IF v_house IS NULL THEN
        RAISE EXCEPTION 'HousingSystem must be DeepLitter, BatteryCage, FreeRange, or Mixed.';
    END IF;

    IF v_crate < 1 THEN
        RAISE EXCEPTION 'DefaultCrateEggCount must be at least 1.';
    END IF;
    IF p_totalcapacity IS NOT NULL AND p_totalcapacity < 0 THEN
        RAISE EXCEPTION 'TotalCapacity cannot be negative.';
    END IF;

    -- 3. Upsert the profile.
    INSERT INTO poultrycompanyprofiles (
        farmid, brandname, businesstype, farmsiteaddress, mainlocation, housingsystem,
        defaultcurrency, defaultcrateeggcount, totalcapacity, operatinghours,
        ownername, phonenumber, email, notes
    )
    VALUES (
        p_farmid, p_brandname, v_biz, p_farmsiteaddress, p_mainlocation, v_house,
        v_curr, v_crate, p_totalcapacity, p_operatinghours,
        p_ownername, p_phonenumber, p_email, p_notes
    )
    ON CONFLICT (farmid) DO UPDATE SET
        brandname            = EXCLUDED.brandname,
        businesstype         = EXCLUDED.businesstype,
        farmsiteaddress      = EXCLUDED.farmsiteaddress,
        mainlocation         = EXCLUDED.mainlocation,
        housingsystem        = EXCLUDED.housingsystem,
        defaultcurrency      = EXCLUDED.defaultcurrency,
        defaultcrateeggcount = EXCLUDED.defaultcrateeggcount,
        totalcapacity        = EXCLUDED.totalcapacity,
        operatinghours       = EXCLUDED.operatinghours,
        ownername            = EXCLUDED.ownername,
        phonenumber          = EXCLUDED.phonenumber,
        email                = EXCLUDED.email,
        notes                = EXCLUDED.notes,
        updatedat            = (now() at time zone 'utc');

    -- 4. Seed the finance defaults (expense categories + cash accounts).
    --    Idempotent per migration 129, so safe on every re-run.
    --
    --    Resolved by lookup rather than called directly. The T-SQL -> Postgres
    --    conversion renames procedures that return a result set: spWaterCompany_Setup
    --    became spwatercompany_setup_rs1, and spPoultryFinance_SeedDefaults ends
    --    with a SELECT ... AS CashAccountCount, so it may have been renamed the
    --    same way. Binding the name at call time means setup() works under
    --    either spelling, and a company still gets its profile (with a notice)
    --    if the seed function is missing entirely.
    SELECT p.proname INTO v_seedfn
    FROM   pg_proc p
    JOIN   pg_namespace n ON n.oid = p.pronamespace
    WHERE  n.nspname = 'public'
      AND  p.proname IN ('sppoultryfinance_seeddefaults', 'sppoultryfinance_seeddefaults_rs1')
      AND  p.pronargs = 1
    ORDER  BY p.proname
    LIMIT  1;

    IF v_seedfn IS NOT NULL THEN
        EXECUTE format('SELECT * FROM public.%I($1)', v_seedfn) USING p_farmid;
    ELSE
        RAISE NOTICE 'sppoultryfinance_seeddefaults not found; profile saved without seeding finance defaults.';
    END IF;

    -- 5. Return the profile. One result set only.
    RETURN QUERY SELECT * FROM sppoultrycompany_getprofile(p_farmid);
END;
$$;

-- -----------------------------------------------------------------------------
-- 4. Update only. No farm-type check and no finance seed -- this is the
--    "edit the details" path for a company already set up. NULL means "leave
--    as it is", matching spWaterCompany_UpdateProfile's ISNULL semantics.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.sppoultrycompany_updateprofile(
    p_farmid               text,
    p_brandname            text    DEFAULT NULL,
    p_businesstype         text    DEFAULT NULL,
    p_farmsiteaddress      text    DEFAULT NULL,
    p_mainlocation         text    DEFAULT NULL,
    p_housingsystem        text    DEFAULT NULL,
    p_defaultcurrency      text    DEFAULT NULL,
    p_defaultcrateeggcount integer DEFAULT NULL,
    p_totalcapacity        integer DEFAULT NULL,
    p_operatinghours       text    DEFAULT NULL,
    p_ownername            text    DEFAULT NULL,
    p_phonenumber          text    DEFAULT NULL,
    p_email                text    DEFAULT NULL,
    p_notes                text    DEFAULT NULL
)
RETURNS TABLE (
    "PoultryCompanyProfileId" integer,
    "FarmId"                  text,
    "BrandName"               text,
    "BusinessType"            text,
    "FarmSiteAddress"         text,
    "MainLocation"            text,
    "HousingSystem"           text,
    "DefaultCurrency"         text,
    "DefaultCrateEggCount"    integer,
    "TotalCapacity"           integer,
    "OperatingHours"          text,
    "OwnerName"               text,
    "PhoneNumber"             text,
    "Email"                   text,
    "Notes"                   text,
    "CreatedAt"               timestamp,
    "UpdatedAt"               timestamp
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_biz   text;
    v_house text;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM poultrycompanyprofiles p WHERE p.farmid = p_farmid) THEN
        RAISE EXCEPTION 'Poultry Company profile not set up for company %. Call sppoultrycompany_setup first.', p_farmid;
    END IF;

    IF NULLIF(btrim(COALESCE(p_businesstype, '')), '') IS NOT NULL THEN
        v_biz := CASE lower(btrim(p_businesstype))
                    WHEN 'layers'   THEN 'Layers'
                    WHEN 'broilers' THEN 'Broilers'
                    WHEN 'both'     THEN 'Both'
                    ELSE NULL
                 END;
        IF v_biz IS NULL THEN
            RAISE EXCEPTION 'BusinessType must be Layers, Broilers, or Both.';
        END IF;
    END IF;

    IF NULLIF(btrim(COALESCE(p_housingsystem, '')), '') IS NOT NULL THEN
        v_house := CASE lower(btrim(p_housingsystem))
                    WHEN 'deeplitter'  THEN 'DeepLitter'
                    WHEN 'batterycage' THEN 'BatteryCage'
                    WHEN 'freerange'   THEN 'FreeRange'
                    WHEN 'mixed'       THEN 'Mixed'
                    ELSE NULL
                 END;
        IF v_house IS NULL THEN
            RAISE EXCEPTION 'HousingSystem must be DeepLitter, BatteryCage, FreeRange, or Mixed.';
        END IF;
    END IF;

    IF p_defaultcrateeggcount IS NOT NULL AND p_defaultcrateeggcount < 1 THEN
        RAISE EXCEPTION 'DefaultCrateEggCount must be at least 1.';
    END IF;
    IF p_totalcapacity IS NOT NULL AND p_totalcapacity < 0 THEN
        RAISE EXCEPTION 'TotalCapacity cannot be negative.';
    END IF;

    UPDATE poultrycompanyprofiles p
    SET    brandname            = COALESCE(p_brandname,            p.brandname),
           businesstype         = COALESCE(v_biz,                  p.businesstype),
           farmsiteaddress      = COALESCE(p_farmsiteaddress,      p.farmsiteaddress),
           mainlocation         = COALESCE(p_mainlocation,         p.mainlocation),
           housingsystem        = COALESCE(v_house,                p.housingsystem),
           defaultcurrency      = COALESCE(NULLIF(btrim(COALESCE(p_defaultcurrency,'')),''), p.defaultcurrency),
           defaultcrateeggcount = COALESCE(p_defaultcrateeggcount, p.defaultcrateeggcount),
           totalcapacity        = COALESCE(p_totalcapacity,        p.totalcapacity),
           operatinghours       = COALESCE(p_operatinghours,       p.operatinghours),
           ownername            = COALESCE(p_ownername,            p.ownername),
           phonenumber          = COALESCE(p_phonenumber,          p.phonenumber),
           email                = COALESCE(p_email,                p.email),
           notes                = COALESCE(p_notes,                p.notes),
           updatedat            = (now() at time zone 'utc')
    WHERE  p.farmid = p_farmid;

    RETURN QUERY SELECT * FROM sppoultrycompany_getprofile(p_farmid);
END;
$$;

-- -----------------------------------------------------------------------------
-- 5. Grants for the runtime user.
-- -----------------------------------------------------------------------------
DO $grant$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'Techretainer') THEN
        EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON poultrycompanyprofiles TO "Techretainer"';
        EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE poultrycompanyprofiles_poultrycompanyprofileid_seq TO "Techretainer"';
        EXECUTE 'GRANT EXECUTE ON FUNCTION public.sppoultryfinance_seeddefaults(text) TO "Techretainer"';
        EXECUTE 'GRANT EXECUTE ON FUNCTION public.sppoultrycompany_getprofile(text) TO "Techretainer"';
        EXECUTE 'GRANT EXECUTE ON FUNCTION public.sppoultrycompany_setup(text, text, text, text, text, text, text, integer, integer, text, text, text, text, text) TO "Techretainer"';
        EXECUTE 'GRANT EXECUTE ON FUNCTION public.sppoultrycompany_updateprofile(text, text, text, text, text, text, text, integer, integer, text, text, text, text, text) TO "Techretainer"';
        RAISE NOTICE '212: granted table + sppoultrycompany_* to Techretainer.';
    END IF;
END
$grant$;

-- 212_AddPoultryCompanyProfile.postgres.sql complete.
