-- =============================================================================
-- 231_PoultryCashFlowRows.postgres.sql
--
-- Purpose
-- -------
-- One server-side definition of "what counts as company cash movement", so the
-- Cash Flow page and the Cash Movement report stop disagreeing.
--
-- Today the answer exists three times and differs three ways:
--
--   /cash-flow                        the cash ledger, merged in the BROWSER with
--                                     unlinked expenses and legacy adjustments
--   sppoultryreport_cashmovement      dbo.Sale + dbo.Expense, ignoring the ledger
--                                     entirely (121:112, written before 128/129
--                                     added cash accounts)
--   /cash                             the same Sale + Expense merge, in C#
--
-- Each is defensible on its own and none of them tie. Worse, the merge rules the
-- page applies -- which unlinked expenses count, which legacy adjustments have
-- already been copied into the ledger -- live only in TypeScript, so no report,
-- export or SP can reuse them.
--
-- This file moves those rules here. The page becomes a renderer; the report can
-- call the same function and finally agree with it.
--
-- WHAT COUNTS
-- -----------
-- 1. Every poultrycashtransactions row. This is money that actually reached a
--    cash account.
--
-- 2. Expenses with NO cash account, MINUS three kinds that are auto-generated by
--    something which has already accounted for the money:
--
--      paymentmethod 'NonCash'                Internal Use (216:487). The cash
--                                             left when the stock was bought;
--                                             counting it here invents a payment.
--      'Raw Materials / Inventory Purchase'   The purchase posts its own cash via
--                                             sppoultryrawmaterialpurchasecash_sync
--                                             (207:122). Counting the expense row
--                                             too double-counts it.
--      'Flock / Bird Purchase'                Same, through the supplier payment
--                                             (224:416).
--
--    expense.sourcetype would be the honest discriminator, but it is not on the
--    API model and these three values ARE what the migrations write, so they are
--    a faithful proxy rather than a guess.
--
-- 3. Legacy CashAdjustment rows -- owner injections, loans received, opening
--    balances, withdrawals, corrections -- entered through the old account-less
--    /cash dialog, which never wrote to poultrycashtransactions.
--
--    Skipped INDIVIDUALLY where migration 230 has already copied one into the
--    ledger (sourcetype 'LegacyAdjustment', sourceid = adjustmentid). Per-row,
--    not "has the backfill run": 230 is one-time, so an adjustment recorded after
--    it exists only in CashAdjustment, and an all-or-nothing test would suppress
--    exactly the rows that still need this source.
--
-- WHY THE ADJUSTMENT LEG IS DYNAMIC SQL
-- -------------------------------------
-- The legacy table's name is not settled. Migration 230 looked for
-- public.cashadjustment and public.cashadjustments and found neither, yet
-- GET /api/Cash works -- so spcashadjustment_getall reads something this repo
-- cannot see. A static reference would make this whole function fail to run on
-- such a database. EXECUTE defers the lookup, and to_regclass decides at run time
-- whether there is anything to read at all.
--
-- FARMID TYPES
-- ------------
-- poultrycashtransactions.farmid is text; expense.farmid is the older uuid column
-- (see ExpenseService.cs:72 and the ::uuid cast at :92). lower(...::text) on both
-- sides survives whichever each one is, and whichever case the guid was stored
-- in. Joining them raw matches nothing and reports a clean run -- see 229's note.
--
-- Read-only. Idempotent: CREATE OR REPLACE only, no DROP, no data written.
-- =============================================================================

\set ON_ERROR_STOP on

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. The rows.
-- -----------------------------------------------------------------------------
-- amount is SIGNED throughout: positive is money in, negative money out. That is
-- the ledger's own convention and every caller relies on it.
--
-- offledger says whether this money reached a cash account. It is the difference
-- between "cash the business moved" and "cash an account is holding", and any
-- caller that needs the balances to tie must respect it.
CREATE OR REPLACE FUNCTION public.sppoultrycashflow_rows(
    p_farmid   text,
    p_fromdate timestamp DEFAULT NULL,
    p_todate   timestamp DEFAULT NULL)
RETURNS TABLE (
    rowsource       text,        -- Ledger | UnlinkedExpense | LegacyAdjustment
    offledger       boolean,
    sourcerowid     integer,     -- id within rowsource, NOT globally unique
    cashaccountid   integer,
    accountname     text,
    transactiondate timestamp,
    transactiontype text,
    sourcetype      text,
    sourceid        integer,
    istransfer      boolean,
    amount          numeric,
    description     text)
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_tbl  text;
    v_from timestamp := COALESCE(p_fromdate, '-infinity'::timestamp);
    v_to   timestamp := COALESCE(p_todate,   'infinity'::timestamp);
BEGIN
    -- ---- 1. the cash ledger ------------------------------------------------
    RETURN QUERY
    SELECT 'Ledger'::text,
           FALSE,
           t.poultrycashtransactionid,
           t.poultrycashaccountid,
           a.accountname::text,
           t.transactiondate,
           t.transactiontype::text,
           t.sourcetype::text,
           t.sourceid,
           -- Belt and braces, as the page does: either marker alone identifies a
           -- transfer, and they are always written together (129:296).
           (COALESCE(t.sourcetype, '') = 'Transfer'
            OR COALESCE(t.transactiontype, '') IN ('TransferIn', 'TransferOut')),
           t.amount,
           t.description::text
    FROM   poultrycashtransactions t
    JOIN   poultrycashaccounts a
           ON a.poultrycashaccountid = t.poultrycashaccountid
    WHERE  t.farmid = p_farmid
      AND  t.transactiondate >= v_from
      AND  t.transactiondate <= v_to;

    -- ---- 2. expenses that moved money but named no account -----------------
    RETURN QUERY
    SELECT 'UnlinkedExpense'::text,
           TRUE,
           e.expenseid,
           NULL::integer,
           NULL::text,
           e.expensedate,
           'CashOut'::text,
           'Expense'::text,
           e.expenseid,
           FALSE,
           -COALESCE(e.amount, 0)::numeric,   -- expense.amount is unsigned; cash out is negative
           COALESCE(NULLIF(btrim(e.description), ''), e.category)::text
    FROM   expense e
    WHERE  lower(e.farmid::text) = lower(p_farmid)
      AND  e.poultrycashaccountid IS NULL
      AND  COALESCE(e.amount, 0) > 0
      AND  COALESCE(e.paymentmethod, '') <> 'NonCash'
      AND  COALESCE(e.category, '') NOT IN ('Raw Materials / Inventory Purchase',
                                            'Flock / Bird Purchase')
      AND  e.expensedate >= v_from
      AND  e.expensedate <= v_to;

    -- ---- 3. legacy account-less adjustments --------------------------------
    v_tbl := COALESCE(to_regclass('public.cashadjustment')::text,
                      to_regclass('public.cashadjustments')::text);

    IF v_tbl IS NULL THEN
        RETURN;                     -- nothing to add; the two legs above stand
    END IF;

    RETURN QUERY EXECUTE format($sql$
        SELECT 'LegacyAdjustment'::text,
               TRUE,
               ca.adjustmentid,
               NULL::integer,
               NULL::text,
               ca.adjustmentdate,
               CASE WHEN ca.amount >= 0 THEN 'AdjustmentIn' ELSE 'AdjustmentOut' END::text,
               COALESCE(NULLIF(btrim(ca.adjustmenttype), ''), 'Adjustment')::text,
               ca.adjustmentid,
               FALSE,
               ca.amount::numeric,     -- already signed: the old UI negated withdrawals
               COALESCE(NULLIF(btrim(ca.description), ''), ca.adjustmenttype)::text
        FROM   %s ca
        WHERE  lower(ca.farmid::text) = lower($1)
          AND  ca.amount <> 0
          AND  ca.adjustmentdate >= $2
          AND  ca.adjustmentdate <= $3
          -- Already copied into the ledger by 230? Then it arrives through leg 1.
          AND  NOT EXISTS (
                   SELECT 1 FROM poultrycashtransactions t
                   WHERE  t.sourcetype = 'LegacyAdjustment'
                     AND  t.sourceid   = ca.adjustmentid
                     AND  t.farmid     = $1)
    $sql$, v_tbl)
    USING p_farmid, v_from, v_to;
END;
$function$;

-- -----------------------------------------------------------------------------
-- 2. The summary.
-- -----------------------------------------------------------------------------
-- The five figures a cash-flow screen or report needs, derived from the rows
-- above so the two can never disagree.
--
-- TWO SCOPES, DELIBERATELY. moneyin/moneyout/net are for the PERIOD. cashathand
-- is AS OF NOW and ignores the date range entirely -- a balance that moved when
-- you changed the dates would be worthless. openingbalance is then derived, not
-- measured: whatever the business must have held at the start for the period's
-- movement to land on today's figure. That makes
--     openingbalance + moneyin - moneyout = cashathand
-- true by construction, which is what lets a report print the sum and have it add
-- up.
--
-- ledgercash is broken out because cashathand no longer equals the sum of the
-- account balances -- it cannot, once money that never reached an account is
-- counted. A caller that needs to tie to the accounts uses ledgercash; one that
-- wants what the business actually holds uses cashathand.
CREATE OR REPLACE FUNCTION public.sppoultrycashflow_summary(
    p_farmid   text,
    p_fromdate timestamp DEFAULT NULL,
    p_todate   timestamp DEFAULT NULL)
RETURNS TABLE (
    moneyin            numeric,
    moneyout           numeric,
    netcashflow        numeric,
    ledgercash         numeric,
    offledgernet       numeric,
    cashathand         numeric,
    openingbalance     numeric,
    transfervolume     numeric,
    offledgerin        numeric,
    offledgerout       numeric,
    rowcount           bigint)
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_in      numeric := 0;
    v_out     numeric := 0;
    v_xfer    numeric := 0;
    v_offin   numeric := 0;
    v_offout  numeric := 0;
    v_n       bigint  := 0;
    v_ledger  numeric := 0;
    v_offall  numeric := 0;
BEGIN
    -- Period movement. Transfers are excluded from in/out because moving money
    -- between the company's own accounts is not income and not spending; their
    -- volume is reported separately.
    SELECT COALESCE(SUM(r.amount) FILTER (WHERE r.amount > 0 AND NOT r.istransfer), 0),
           COALESCE(SUM(-r.amount) FILTER (WHERE r.amount < 0 AND NOT r.istransfer), 0),
           COALESCE(SUM(r.amount) FILTER (WHERE r.amount > 0 AND r.istransfer), 0),
           COALESCE(SUM(r.amount) FILTER (WHERE r.amount > 0 AND r.offledger), 0),
           COALESCE(SUM(-r.amount) FILTER (WHERE r.amount < 0 AND r.offledger), 0),
           COUNT(*) FILTER (WHERE NOT r.istransfer)
      INTO v_in, v_out, v_xfer, v_offin, v_offout, v_n
    FROM   public.sppoultrycashflow_rows(p_farmid, p_fromdate, p_todate) r;

    -- What the accounts hold, all time. openingbalance is on the account and is
    -- NOT a ledger row (spPoultryCashAccount_Insert seeds the balance and writes
    -- no transaction), so it has to be added, not summed from the ledger.
    SELECT COALESCE(SUM(a.openingbalance
                        + COALESCE((SELECT SUM(t.amount)
                                    FROM   poultrycashtransactions t
                                    WHERE  t.poultrycashaccountid = a.poultrycashaccountid
                                      AND  t.farmid = a.farmid), 0)), 0)
      INTO v_ledger
    FROM   poultrycashaccounts a
    WHERE  a.farmid = p_farmid;

    -- Off-ledger money ALL TIME, not just this period — see the note above.
    SELECT COALESCE(SUM(r.amount), 0) INTO v_offall
    FROM   public.sppoultrycashflow_rows(p_farmid, NULL, NULL) r
    WHERE  r.offledger;

    RETURN QUERY SELECT
        ROUND(v_in, 2),
        ROUND(v_out, 2),
        ROUND(v_in - v_out, 2),
        ROUND(v_ledger, 2),
        ROUND(v_offall, 2),
        ROUND(v_ledger + v_offall, 2),
        ROUND((v_ledger + v_offall) - (v_in - v_out), 2),
        ROUND(v_xfer, 2),
        ROUND(v_offin, 2),
        ROUND(v_offout, 2),
        v_n;
END;
$function$;

COMMIT;

-- -----------------------------------------------------------------------------
-- 3. Verification.
-- -----------------------------------------------------------------------------
SELECT 'functions (2 expected)' AS check,
       CASE WHEN count(*) = 2 THEN 'OK' ELSE 'ONLY ' || count(*) END AS result
FROM   pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE  n.nspname = 'public'
  AND  p.proname IN ('sppoultrycashflow_rows', 'sppoultrycashflow_summary')
UNION ALL
SELECT 'legacy adjustment table',
       COALESCE(to_regclass('public.cashadjustment')::text,
                to_regclass('public.cashadjustments')::text,
                'not present - leg 3 returns nothing, which is fine');

-- The identity, per farm. openingbalance + in - out must equal cashathand on
-- every row; anything else means the arithmetic above has drifted.
SELECT f.farmid,
       s.openingbalance, s.moneyin, s.moneyout, s.cashathand,
       ROUND(s.openingbalance + s.moneyin - s.moneyout - s.cashathand, 2) AS should_be_zero,
       s.ledgercash,
       s.offledgernet AS of_which_never_reached_an_account
FROM   (SELECT DISTINCT farmid FROM poultrycashaccounts) f
CROSS  JOIN LATERAL public.sppoultrycashflow_summary(f.farmid, NULL, NULL) s
ORDER  BY f.farmid;
