-- =============================================================================
-- 232_PoultryCashMovementOnLedger.postgres.sql
--
-- Purpose
-- -------
-- Point the Cash Movement report at sppoultrycashflow_rows / _summary (231) so
-- it and the Cash Flow page stop giving different answers to the same question.
--
-- What it used to do
-- ------------------
-- spPoultryReport_CashMovement (121:112) reconstructed cash from dbo.Sale and
-- dbo.Expense, with its own comment admitting why:
--
--     "best-effort, since poultry has no dedicated cash-account ledger"
--
-- That was true when it was written. Migrations 128/129 added the ledger three
-- migrations later and nothing came back to update this. So the report has been
-- ignoring cash accounts, transfers, adjustments and opening balances ever since.
--
-- Three behaviours change, all of them fixes
-- ------------------------------------------
-- 1. PART-PAID SALES NOW COUNT WHAT WAS RECEIVED. The old body did
--        CASE WHEN Paid = 1 THEN TotalAmount ELSE 0 END
--    so a GHC 500 sale with GHC 300 collected contributed NOTHING until the last
--    payment landed. Migration 223 already fixed this in the ledger and its
--    header calls the old behaviour out as the bug it was; the report kept it.
--    Inflow will RISE on any farm that takes part payments.
--
-- 2. TRANSFERS ARE EXCLUDED. Moving money between the company's own accounts is
--    not income and not spending. The old body could not see transfers at all,
--    so this is new information rather than a changed figure.
--
-- 3. EXPENSES WITH NO CASH ACCOUNT ARE NARROWED. The old body counted every
--    expense row. 231 drops the three kinds that are auto-generated by something
--    which already accounted for the money -- Internal Use, raw-material
--    purchases and flock purchases -- because counting them either invents a
--    payment or double-counts one. Outflow will FALL on any farm using internal
--    use or supplier payments, and it will be MORE correct, not less.
--
-- Expect the report's totals to move on the day this is applied. That is the
-- point, but tell whoever reads it before they notice on their own.
--
-- DROP then CREATE, unusually
-- ---------------------------
-- rs2 gains a cashaccount column, and CREATE OR REPLACE cannot change a RETURNS
-- TABLE column list. Normally that would be a blocker for a body this repo
-- cannot read (see 229's note) -- but here the whole point is to REPLACE the
-- logic, so not knowing the old body costs nothing.
--
-- Idempotent: DROP IF EXISTS + CREATE, no data written.
-- =============================================================================

\set ON_ERROR_STOP on

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. Opening balance.
-- -----------------------------------------------------------------------------
-- Was: paid sales minus expenses before the range. Now: the figure 231 derives,
-- which accounts for cash accounts, their opening balances, adjustments and
-- money that never reached an account.
DROP FUNCTION IF EXISTS public.sppoultryreport_cashmovement_rs1(text, date, date);

CREATE OR REPLACE FUNCTION public.sppoultryreport_cashmovement_rs1(
    p_farmid    text,
    p_startdate date,
    p_enddate   date)
RETURNS TABLE (openingcashbalance numeric)
LANGUAGE sql
STABLE
AS $$
    SELECT s.openingbalance
    FROM   public.sppoultrycashflow_summary(
               p_farmid,
               p_startdate::timestamp,
               -- The end date is inclusive of the whole day. Passing a bare date
               -- means midnight, which silently drops everything recorded on the
               -- last day of the range -- the same bug the ledger read had.
               (p_enddate + 1)::timestamp - interval '1 microsecond') s;
$$;

-- -----------------------------------------------------------------------------
-- 2. Movement rows.
-- -----------------------------------------------------------------------------
-- Transfers are filtered out here rather than in the caller: this result set IS
-- the report's definition of cash movement, and a transfer is not movement.
DROP FUNCTION IF EXISTS public.sppoultryreport_cashmovement_rs2(text, date, date);

CREATE OR REPLACE FUNCTION public.sppoultryreport_cashmovement_rs2(
    p_farmid    text,
    p_startdate date,
    p_enddate   date)
RETURNS TABLE (
    "Date"      timestamp,
    cashaccount text,
    sourcetype  text,
    reference   text,
    description text,
    inflow      numeric,
    outflow     numeric,
    createdby   text)
LANGUAGE sql
STABLE
AS $$
    SELECT r.transactiondate,
           -- Was hardcoded to the literal 'Farm cash' in C# on every row
           -- (PoultryAdvancedReportService.cs:921), because the old body had no
           -- account to report. Off-ledger money genuinely has none, and saying
           -- so is the useful answer.
           COALESCE(r.accountname, 'No cash account')::text,
           r.sourcetype::text,
           CASE r.rowsource
               WHEN 'UnlinkedExpense'  THEN 'Expense #'    || r.sourcerowid::text
               WHEN 'LegacyAdjustment' THEN 'Adjustment #' || r.sourcerowid::text
               ELSE COALESCE(r.sourcetype, 'Txn') || ' #' || COALESCE(r.sourceid, r.sourcerowid)::text
           END::text,
           r.description::text,
           CASE WHEN r.amount > 0 THEN  r.amount ELSE 0 END,
           CASE WHEN r.amount < 0 THEN -r.amount ELSE 0 END,
           NULL::text
    FROM   public.sppoultrycashflow_rows(
               p_farmid,
               p_startdate::timestamp,
               (p_enddate + 1)::timestamp - interval '1 microsecond') r
    WHERE  NOT r.istransfer
    ORDER  BY r.transactiondate, r.rowsource, r.sourcerowid;
$$;

COMMIT;

-- -----------------------------------------------------------------------------
-- 3. Verification.
-- -----------------------------------------------------------------------------
SELECT 'functions (2 expected)' AS check,
       CASE WHEN count(*) = 2 THEN 'OK' ELSE 'ONLY ' || count(*) END AS result
FROM   pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE  n.nspname = 'public'
  AND  p.proname IN ('sppoultryreport_cashmovement_rs1',
                     'sppoultryreport_cashmovement_rs2');

-- The report and the page must now agree. For each farm, all-time:
--   report_in/out   = what rs2 returns
--   page_in/out     = what the summary says
-- Any non-zero difference means one of them is filtering something the other is
-- not, and this is the query that finds it.
SELECT f.farmid,
       SUM(rs.inflow)  AS report_in,
       SUM(rs.outflow) AS report_out,
       s.moneyin       AS page_in,
       s.moneyout      AS page_out,
       ROUND(SUM(rs.inflow)  - s.moneyin, 2)  AS in_should_be_zero,
       ROUND(SUM(rs.outflow) - s.moneyout, 2) AS out_should_be_zero
FROM   (SELECT DISTINCT farmid FROM poultrycashaccounts) f
CROSS  JOIN LATERAL public.sppoultryreport_cashmovement_rs2(
                        f.farmid, '1900-01-01'::date, '2999-12-31'::date) rs
CROSS  JOIN LATERAL public.sppoultrycashflow_summary(f.farmid, NULL, NULL) s
GROUP  BY f.farmid, s.moneyin, s.moneyout
ORDER  BY f.farmid;



