-- =============================================================================
-- 283_WaterCapitalAssets.postgres.sql
--
-- Purpose
-- -------
-- The water mirror of 270. Phase 3, part 2: the Asset Register. A borehole, a
-- sachet machine or a delivery truck is not this month's expense -- it is money
-- the company still owns.
--
-- THE ONE DECISION EVERYTHING ELSE FOLLOWS
-- ========================================
-- A capital acquisition rides the EXISTING expense rail. It writes an ordinary
-- `waterexpenses` row, classified CapitalAsset by 282, and that row is what
-- moves the cash, opens the supplier payable, appears on Supplier Balances, and
-- gets settled by an ordinary supplier payment.
--
-- Nothing about cash or payables is rebuilt here. The alternative -- a second
-- money rail for assets -- would mean a second Supplier Balances, a second cash
-- posting, a second reversal, and two sets of rules that would drift apart by
-- the second migration.
--
-- What makes an asset acquisition different from a bill is exactly ONE thing:
-- financialcosttype = 'CapitalAsset' keeps it out of profit. 282 already made
-- that mean something.
--
-- THREE PLACES WATER DIFFERS FROM POULTRY, AND WHY
-- ================================================
--
-- 1. THE MONEY LEG IS WRITTEN INLINE, NOT THROUGH AN INSERT SP.
--    270 calls spexpense_insert. Water's spwaterexpense_insert writes fifteen
--    columns through a body this repo does not contain (240 section 6 says so
--    in terms), so calling it would mean guessing at its Postgres parameter
--    names. 227 hit exactly this and solved it by writing the waterexpenses row
--    inline -- "same category name ... but with no dependency on that
--    function's Postgres parameter naming". This file follows 227's shape
--    exactly, including its cash convention.
--
-- 2. WATER CASH AMOUNTS ARE SIGNED.
--    poultrycashtransactions stores a positive amount with a transactiontype and
--    a balanceaftertransaction. watercashtransactions stores a NEGATIVE amount
--    for CashOut and has no balance column, and the account balance is updated
--    separately. Copying poultry's convention here would put money back into an
--    account every time an asset was bought.
--
-- 3. ONE EXPENSE PER SOURCE DOCUMENT IS ENFORCED BY AN INDEX.
--    waterexpenses carries a unique index the poultry table has no equivalent
--    of:
--
--      ux_waterexpenses_farmsource_active (farmid, sourcetype, sourceid)
--        WHERE sourcetype IS NOT NULL AND isdeleted = false
--
--    So a system-generated expense is unique per source document, and
--    `sourceid` has to identify the DOCUMENT, not the asset. The acquisition is
--    'CapitalAsset' keyed on the asset id -- there is exactly one per asset --
--    but an additional cost is 'CapitalAssetCost' keyed on the COST ROW's id.
--    Keying both on the asset id would let an asset take one capitalised cost
--    and reject the second, which is precisely the construction workflow this
--    file exists to support.
--
--    That is why spwatercapitalassetcost_add writes its cost row FIRST and
--    passes the new id down as p_sourceid, then links the expense back onto it.
--    The index is a gift rather than an obstacle: it makes the money leg
--    idempotent, and because it is partial on `isdeleted = false`, a reversed
--    acquisition frees its key so the asset can be recorded again.
--
-- 4. fnwaterpayables HAD TO BE WIDENED, AND THIS IS THE SUBTLE ONE.
--    240 ends fnwaterpayables with `AND e.sourcetype IS NULL` -- "only bills a
--    person typed in are payable; anything with a sourcetype is another
--    document's shadow". That rule exists to stop a recursion: paying a supplier
--    writes a 'WaterSupplierPayment' expense row, and if that row were itself
--    payable, paying it would write another.
--
--    But a capital asset bought on credit is a REAL debt to a real supplier, not
--    the shadow of anything. Left under that filter it would never reach
--    Supplier Balances, and the company would owe money the system could not
--    show. So the filter now admits 'CapitalAsset' and 'CapitalAssetCost' and
--    nothing else. Neither is generated by a payment, so the recursion 240 was
--    guarding against cannot come back through this door.
--
-- WHY THE ORIGINAL COST IS NOT A COLUMN
-- =====================================
-- A borehole is drilled, not bought: the drilling, then the pump, then the
-- casing, then the wiring. Storing originalcost as a number would mean a column
-- that has to be kept in step with the cost rows behind it, and the day they
-- disagree there is no way to tell which one is right.
--
-- So originalcost is the SUM of watercapitalassetcosts, always, and
-- fnwatercapitalasset_originalcost is the only place that sum is written. That
-- also gives the construction workflow for free: adding a cost to a Draft asset
-- is the same operation as acquiring one.
--
-- WHY THE DEPRECIATION TABLE IS DEFINED HERE
-- ==========================================
-- Because book value is not optional on an asset register, and book value needs
-- the depreciation ledger. The TABLE is here so the reads below can be written
-- once and be correct; the depreciation ENGINE -- generating, posting,
-- reversing -- is 284. Until 284 runs the table is empty and every asset reads
-- accumulated depreciation 0, which is exactly true.
--
-- WHAT THIS FILE IS NOT
-- =====================
-- It is not a general ledger, a chart of accounts, or journal entries. It is not
-- tax depreciation. It does not touch the P&L report (285 does). And it does not
-- reclassify one single historical expense: a row saying "Generator" stays an
-- expense until a human decides otherwise.
--
-- Order: after 282.
--
-- Idempotent throughout.
-- =============================================================================

\set ON_ERROR_STOP on

BEGIN;

-- -----------------------------------------------------------------------------
-- 0. Drop by NAME, not by signature.
--
-- spwatercapitalassetexpense_post gained a p_sourceid argument after the first
-- dry run hit ux_waterexpenses_farmsource_active (header, point 3), and
-- CREATE OR REPLACE cannot add a parameter -- it would leave the old overload in
-- place beside the new one, and every named-argument call would then fail as
-- ambiguous. Dropping by name is the house rule for exactly this.
-- -----------------------------------------------------------------------------
DO $drop$
DECLARE
    r record;
BEGIN
    FOR r IN
        SELECT p.oid::regprocedure AS sig
        FROM   pg_proc p
        JOIN   pg_namespace n ON n.oid = p.pronamespace
        WHERE  n.nspname = 'public'
          AND  p.proname IN ('spwatercapitalassetexpense_post',
                             'spwatercapitalasset_create',
                             'spwatercapitalassetcost_add')
    LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS ' || r.sig;
    END LOOP;
END
$drop$;

-- -----------------------------------------------------------------------------
-- 1. Asset categories. Per company, seeded on demand, editable.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS waterassetcategories (
    waterassetcategoryid    serial PRIMARY KEY,
    farmid                  varchar(450) NOT NULL,
    categoryname            varchar(80)  NOT NULL,
    -- A default life is a suggestion the form fills in, never a rule: two
    -- companies can disagree about how long a borehole pump lasts and both be
    -- right.
    defaultusefullifemonths integer,
    sortorder               integer      NOT NULL DEFAULT 0,
    isactive                boolean      NOT NULL DEFAULT TRUE,
    createdby               varchar(100),
    createdat               timestamp    NOT NULL DEFAULT (now() at time zone 'utc')
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_waterassetcategories_name
    ON waterassetcategories (farmid, lower(categoryname));

-- -----------------------------------------------------------------------------
-- 2. The asset itself.
--
-- No originalcost, no accumulateddepreciation, no currentbookvalue: all three
-- are derived. What is stored is what a person decided -- the name, the life,
-- the residual value, the dates -- and nothing that a sum can answer.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS watercapitalassets (
    watercapitalassetid  serial PRIMARY KEY,
    farmid               varchar(450) NOT NULL,
    assetnumber          varchar(40)  NOT NULL,
    assetname            varchar(150) NOT NULL,
    waterassetcategoryid integer REFERENCES waterassetcategories(waterassetcategoryid),
    description          varchar(500),
    acquisitiondate      date         NOT NULL,
    -- Depreciation starts here, not at acquisition: a borehole finished in March
    -- and commissioned in June has not been earning anything since March.
    inservicedate        date,
    residualvalue        numeric(14,2) NOT NULL DEFAULT 0,
    usefullifemonths     integer,
    depreciationmethod   varchar(20)  NOT NULL DEFAULT 'StraightLine',
    supplierid           integer,
    location             varchar(150),
    serialnumber         varchar(80),
    status               varchar(20)  NOT NULL DEFAULT 'Draft',
    disposaldate         date,
    disposalproceeds     numeric(14,2),
    disposalnotes        varchar(500),
    notes                varchar(500),
    createdby            varchar(100),
    createdat            timestamp    NOT NULL DEFAULT (now() at time zone 'utc'),
    updatedby            varchar(100),
    updatedat            timestamp,
    reversedby           varchar(100),
    reversedat           timestamp,
    reversalreason       varchar(500),
    CONSTRAINT ck_watercapitalassets_status CHECK (status IN
        ('Draft', 'Active', 'FullyDepreciated', 'Disposed', 'Reversed')),
    CONSTRAINT ck_watercapitalassets_residual CHECK (residualvalue >= 0),
    CONSTRAINT ck_watercapitalassets_life CHECK (usefullifemonths IS NULL OR usefullifemonths > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_watercapitalassets_number
    ON watercapitalassets (farmid, assetnumber);
CREATE INDEX IF NOT EXISTS ix_watercapitalassets_farm
    ON watercapitalassets (farmid, status);

-- -----------------------------------------------------------------------------
-- 3. Every cedi capitalised into an asset, and where it came from.
--
-- One row per capitalised cost. `waterexpenseid` is the expense that moved the
-- money or opened the payable -- the link that makes "what did we pay, and to
-- whom" answerable without this table having to know anything about cash.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS watercapitalassetcosts (
    watercapitalassetcostid serial PRIMARY KEY,
    farmid                  varchar(450) NOT NULL,
    watercapitalassetid     integer      NOT NULL
        REFERENCES watercapitalassets(watercapitalassetid) ON DELETE CASCADE,
    costdate                date         NOT NULL,
    description             varchar(300),
    costcategory            varchar(80),
    amount                  numeric(14,2) NOT NULL,
    -- Acquisition (the first cost) | AdditionalCost (built up over time).
    sourcetype              varchar(40)  NOT NULL DEFAULT 'Acquisition',
    waterexpenseid          integer,
    supplierid              integer,
    status                  varchar(20)  NOT NULL DEFAULT 'Posted',
    createdby               varchar(100),
    createdat               timestamp    NOT NULL DEFAULT (now() at time zone 'utc'),
    reversedby              varchar(100),
    reversedat              timestamp,
    reversalreason          varchar(500),
    CONSTRAINT ck_watercapitalassetcosts_amount CHECK (amount > 0),
    CONSTRAINT ck_watercapitalassetcosts_status CHECK (status IN ('Posted', 'Reversed'))
);

CREATE INDEX IF NOT EXISTS ix_watercapitalassetcosts_asset
    ON watercapitalassetcosts (watercapitalassetid, status);
CREATE INDEX IF NOT EXISTS ix_watercapitalassetcosts_expense
    ON watercapitalassetcosts (waterexpenseid);

-- -----------------------------------------------------------------------------
-- 4. The depreciation ledger. Table only -- 284 owns the engine.
--
-- Append-only, like every other financial ledger here: a reversal writes an
-- opposite row and both are kept. `amount` is signed, so accumulated
-- depreciation is a SUM and never a subtraction of two half-truths.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS waterassetdepreciation (
    waterassetdepreciationid serial PRIMARY KEY,
    farmid                   varchar(450) NOT NULL,
    watercapitalassetid      integer      NOT NULL
        REFERENCES watercapitalassets(watercapitalassetid) ON DELETE CASCADE,
    periodstart              date         NOT NULL,
    periodend                date         NOT NULL,
    depreciationdate         date         NOT NULL,
    amount                   numeric(14,2) NOT NULL,
    depreciationmethod       varchar(20)  NOT NULL DEFAULT 'StraightLine',
    -- Scheduled (the monthly charge) | CatchUp | ManualAdjustment | Reversal.
    sourcetype               varchar(30)  NOT NULL DEFAULT 'Scheduled',
    status                   varchar(20)  NOT NULL DEFAULT 'Posted',
    waterexpenseid           integer,
    reversalofid             integer REFERENCES waterassetdepreciation(waterassetdepreciationid),
    createdby                varchar(100),
    createdat                timestamp    NOT NULL DEFAULT (now() at time zone 'utc'),
    reversedby               varchar(100),
    reversedat               timestamp,
    reversalreason           varchar(500),
    CONSTRAINT ck_waterassetdepreciation_status CHECK (status IN ('Posted', 'Reversed'))
);

-- One SCHEDULED charge per asset per period, and that index is the whole of
-- "prevent duplicate depreciation": pressing Generate twice cannot charge the
-- same month twice, whatever the caller believes. Reversals and manual
-- adjustments are deliberately outside it -- there can be several of those.
CREATE UNIQUE INDEX IF NOT EXISTS ux_waterassetdepreciation_period
    ON waterassetdepreciation (watercapitalassetid, periodstart)
    WHERE sourcetype = 'Scheduled';

CREATE INDEX IF NOT EXISTS ix_waterassetdepreciation_farm
    ON waterassetdepreciation (farmid, depreciationdate);

-- -----------------------------------------------------------------------------
-- 5. The link from an expense row back to its asset.
--
-- 282 said a CapitalAsset expense exists; this says which asset it belongs to,
-- so the Expenses page can offer "open the asset" rather than showing a cost
-- with nowhere to go.
-- -----------------------------------------------------------------------------
ALTER TABLE waterexpenses ADD COLUMN IF NOT EXISTS watercapitalassetid integer;
CREATE INDEX IF NOT EXISTS ix_waterexpenses_capitalasset
    ON waterexpenses (watercapitalassetid);

-- Appended to the end of the composite type, like 282's columns, so no existing
-- ordinal moves.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_attribute
                   WHERE attrelid = 'waterexpenserow'::regclass
                     AND attname = 'watercapitalassetid' AND NOT attisdropped) THEN
        ALTER TYPE waterexpenserow ADD ATTRIBUTE watercapitalassetid integer CASCADE;
        ALTER TYPE waterexpenserow ADD ATTRIBUTE capitalassetname text CASCADE;
    END IF;
END $$;

CREATE OR REPLACE FUNCTION public.fnwaterexpenserows(p_farmid text)
RETURNS SETOF public.waterexpenserow
LANGUAGE sql
STABLE
AS $function$
    SELECT e.waterexpenseid, e.farmid::text, e.expensedate,
           e.waterexpensecategoryid, c.name::text,
           e.description::text, e.amount::numeric(14,2), e.paidto::text, e.paymentmethod::text,
           e.watercashaccountid, ca.accountname::text,
           e.receipturl::text,
           e.linkedwatervehicleid, e.linkedwatermachineid, e.linkedwaterproductionbatchid,
           e.supplierid, s.suppliername::text,
           COALESCE(e.amountpaid,
                    CASE WHEN COALESCE(e.paymentmethod, '') = 'Credit'
                         THEN 0 ELSE e.amount END)::numeric(14,2),
           GREATEST(COALESCE(e.amount, 0)
                    - COALESCE(e.amountpaid,
                               CASE WHEN COALESCE(e.paymentmethod, '') = 'Credit'
                                    THEN 0 ELSE e.amount END), 0)::numeric(14,2),
           e.paymentstatus::text,
           e.duedate,
           e.sourcetype::text, e.sourceid,
           e.status::text, e.notes::text,
           e.createdby::text, e.approvedby::text, e.approvedat,
           e.createdat, e.updatedat,
           -- 282. What kind of cost, which P&L line, which band, and where it
           -- came from -- resolved server-side so no screen has to re-derive it.
           ct.costtype,
           (COALESCE(e.financialcosttype, '') <> ''),
           l.line,
           fnwaterexpense_pllinelabel(l.line),
           fnwaterexpense_plsection(l.line),
           fnwaterexpense_sourcelabel(e.sourcetype::text),
           -- 283. The asset a capital cost belongs to.
           e.watercapitalassetid,
           cap.assetname::text
    FROM   waterexpenses e
    INNER  JOIN waterexpensecategories c ON c.waterexpensecategoryid = e.waterexpensecategoryid
    LEFT   JOIN watercashaccounts ca     ON ca.watercashaccountid    = e.watercashaccountid
    LEFT   JOIN watersuppliers s         ON s.watersupplierid        = e.supplierid
    LEFT   JOIN watercapitalassets cap   ON cap.watercapitalassetid  = e.watercapitalassetid
    CROSS  JOIN LATERAL (SELECT fnwaterexpense_costtype(
                                    e.financialcosttype::text, e.sourcetype::text,
                                    c.name::text, e.paymentmethod::text) AS costtype) ct
    CROSS  JOIN LATERAL (SELECT fnwaterexpense_plline(
                                    ct.costtype, e.sourcetype::text, c.name::text,
                                    fnwaterexpense_itemcategory(e.sourcetype::text, e.sourceid)) AS line) l
    WHERE  e.farmid = p_farmid
      AND  COALESCE(e.isdeleted, FALSE) = FALSE;
$function$;

-- -----------------------------------------------------------------------------
-- 6. A capital purchase on credit is a real payable.
--
-- See the header, point 3. The filter admits exactly two more sourcetypes and
-- nothing else, so 240's anti-recursion rule still holds for every row it was
-- written to catch.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fnwaterpayables(p_farmid text)
RETURNS TABLE(
    documenttype  text,
    documentid    integer,
    supplierid    integer,
    docdate       date,
    label         text,
    reference     text,
    totalcost     numeric,
    amountpaid    numeric,
    balance       numeric,
    cashaccountid integer,
    duedate       date)
LANGUAGE sql
STABLE
AS $function$
    SELECT 'RawMaterialPurchase'::text, pu.waterrawmaterialpurchaseid, pu.supplierid,
           pu.purchasedate::date,
           COALESCE(i.itemname, pu.suppliername, 'Raw material')::text,
           ('P' || pu.waterrawmaterialpurchaseid::text)::text,
           pu.totalcost, pu.amountpaid,
           GREATEST(pu.totalcost - pu.amountpaid, 0)::numeric(14,2),
           -- Always NULL: unlike poultryrawmaterialpurchases, the water table
           -- has no cash account column -- WaterRawMaterialPurchaseModel
           -- exposes one, but it is a projection, not storage.
           NULL::integer,
           NULL::date
    FROM   waterrawmaterialpurchases pu
    LEFT   JOIN waterrawmaterialitems i
           ON i.waterrawmaterialitemid = pu.waterrawmaterialitemid
    WHERE  pu.farmid = p_farmid
    UNION ALL
    SELECT 'Expense'::text, e.waterexpenseid, e.supplierid,
           e.expensedate::date,
           COALESCE(NULLIF(btrim(e.description), ''), c.name, 'Expense')::text,
           ('E' || e.waterexpenseid::text)::text,
           COALESCE(e.amount, 0)::numeric(14,2),
           COALESCE(e.amountpaid,
                    CASE WHEN COALESCE(e.paymentmethod, '') = 'Credit'
                         THEN 0 ELSE e.amount END)::numeric(14,2),
           GREATEST(COALESCE(e.amount, 0)
                    - COALESCE(e.amountpaid,
                               CASE WHEN COALESCE(e.paymentmethod, '') = 'Credit'
                                    THEN 0 ELSE e.amount END), 0)::numeric(14,2),
           e.watercashaccountid,
           e.duedate
    FROM   waterexpenses e
    LEFT   JOIN waterexpensecategories c
           ON c.waterexpensecategoryid = e.waterexpensecategoryid
    WHERE  lower(e.farmid::text) = lower(p_farmid)
      AND  e.supplierid IS NOT NULL
      AND  COALESCE(e.isdeleted, FALSE) = FALSE
      -- 047: only an approved expense has been recognised at all. A Draft is
      -- not yet a debt.
      AND  COALESCE(e.status, '') = 'Approved'
      -- 240: only bills a person typed in are payable; anything with a
      -- sourcetype is another document's shadow. 283 adds the one real
      -- exception -- a capital asset bought on credit is a debt to a supplier,
      -- not the shadow of another document, and neither of these two
      -- sourcetypes is ever generated BY a payment, so the recursion 240 was
      -- guarding against cannot return through here.
      AND  (e.sourcetype IS NULL
            OR e.sourcetype IN ('CapitalAsset', 'CapitalAssetCost'));
$function$;

-- -----------------------------------------------------------------------------
-- 7. The derived numbers, defined once.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fnwatercapitalasset_originalcost(p_assetid integer)
RETURNS numeric
LANGUAGE sql STABLE
AS $function$
    SELECT COALESCE(SUM(c.amount), 0)::numeric(14,2)
    FROM   watercapitalassetcosts c
    WHERE  c.watercapitalassetid = p_assetid AND c.status = 'Posted';
$function$;

CREATE OR REPLACE FUNCTION public.fnwatercapitalasset_accumulated(p_assetid integer)
RETURNS numeric
LANGUAGE sql STABLE
AS $function$
    -- Signed sum over an append-only ledger: a reversal is a negative row, so
    -- this needs no knowledge of which rows reversed which.
    SELECT COALESCE(SUM(d.amount), 0)::numeric(14,2)
    FROM   waterassetdepreciation d
    WHERE  d.watercapitalassetid = p_assetid;
$function$;

CREATE OR REPLACE FUNCTION public.fnwatercapitalasset_monthly(
    p_originalcost numeric, p_residual numeric, p_lifemonths integer
) RETURNS numeric
LANGUAGE sql IMMUTABLE
AS $function$
    -- Straight line, and only straight line. GREATEST guards the case an owner
    -- enters a residual above what the asset cost: the charge is zero, not a
    -- negative depreciation that would quietly increase profit.
    SELECT ROUND(GREATEST(COALESCE(p_originalcost, 0) - COALESCE(p_residual, 0), 0)
                 / NULLIF(p_lifemonths, 0), 2);
$function$;

COMMENT ON FUNCTION public.fnwatercapitalasset_monthly(numeric, numeric, integer) IS
    'Straight-line monthly charge: (cost - residual) / life in months. NULL when '
    'no useful life is set, which is what a Draft asset looks like.';

-- The whole financial picture of one asset, in one place, so the register, the
-- detail page and the depreciation engine cannot compute it three ways.
CREATE OR REPLACE FUNCTION public.fnwatercapitalasset_financials(p_assetid integer)
 RETURNS TABLE(originalcost numeric, residualvalue numeric, depreciableamount numeric,
               usefullifemonths integer, monthlydepreciation numeric,
               accumulateddepreciation numeric, currentbookvalue numeric,
               remainingdepreciable numeric, isfullydepreciated boolean)
LANGUAGE sql STABLE
AS $function$
    SELECT o.cost,
           a.residualvalue,
           GREATEST(o.cost - a.residualvalue, 0)::numeric(14,2),
           a.usefullifemonths,
           fnwatercapitalasset_monthly(o.cost, a.residualvalue, a.usefullifemonths),
           d.acc,
           -- Book value can never fall below residual value. Anything lower
           -- would say the company owns less than it agreed it still owns.
           GREATEST(o.cost - d.acc, a.residualvalue)::numeric(14,2),
           GREATEST(GREATEST(o.cost - a.residualvalue, 0) - d.acc, 0)::numeric(14,2),
           (GREATEST(o.cost - a.residualvalue, 0) - d.acc) <= 0.004
    FROM   watercapitalassets a
    CROSS  JOIN LATERAL (SELECT fnwatercapitalasset_originalcost(a.watercapitalassetid) AS cost) o
    CROSS  JOIN LATERAL (SELECT fnwatercapitalasset_accumulated(a.watercapitalassetid) AS acc) d
    WHERE  a.watercapitalassetid = p_assetid;
$function$;

-- -----------------------------------------------------------------------------
-- 8. Seeded categories.
--
-- Idempotent and per company: one that has never opened the page gets the list
-- on first read, and one that has renamed "Vehicles" to "Trucks" keeps its name.
--
-- The list is water's, not poultry's: a borehole and a sachet machine are the
-- assets these companies actually own.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.spwaterassetcategory_ensuredefaults(
    p_farmid text, p_createdby text DEFAULT NULL
) RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
    INSERT INTO waterassetcategories (farmid, categoryname, defaultusefullifemonths, sortorder, createdby)
    SELECT p_farmid, d.name, d.life, d.ord, p_createdby
    FROM  (VALUES
              ('Boreholes / Water Source',      240, 1),
              ('Water Treatment Plant',         120, 2),
              ('Sachet Machines',                84, 3),
              ('Bottling Machines',              84, 4),
              ('Storage Tanks',                 120, 5),
              ('Cold Room / Chillers',           84, 6),
              ('Generators',                     84, 7),
              ('Delivery Vehicles',              60, 8),
              ('Buildings / Factory',           240, 9),
              ('Distribution Equipment',         60, 10),
              ('Furniture',                      60, 11),
              ('IT / Computer Equipment',        36, 12),
              ('Land Improvements',             240, 13),
              ('Office Equipment',               60, 14),
              ('Other Assets',                   60, 15)
          ) AS d(name, life, ord)
    WHERE NOT EXISTS (
        SELECT 1 FROM waterassetcategories c
        WHERE  c.farmid = p_farmid AND lower(c.categoryname) = lower(d.name));
END;
$function$;

CREATE OR REPLACE FUNCTION public.spwaterassetcategory_getall(p_farmid text)
 RETURNS TABLE(waterassetcategoryid integer, farmid text, categoryname text,
               defaultusefullifemonths integer, sortorder integer, isactive boolean,
               assetcount integer)
LANGUAGE plpgsql
AS $function$
BEGIN
    PERFORM spwaterassetcategory_ensuredefaults(p_farmid, NULL);

    RETURN QUERY
    SELECT c.waterassetcategoryid, c.farmid::text, c.categoryname::text,
           c.defaultusefullifemonths, c.sortorder, c.isactive,
           (SELECT COUNT(*)::integer FROM watercapitalassets a
             WHERE a.waterassetcategoryid = c.waterassetcategoryid
               AND a.status <> 'Reversed')
    FROM   waterassetcategories c
    WHERE  c.farmid = p_farmid
    ORDER  BY c.sortorder, c.categoryname;
END;
$function$;

CREATE OR REPLACE FUNCTION public.spwaterassetcategory_upsert(
    p_farmid text, p_waterassetcategoryid integer, p_categoryname text,
    p_defaultusefullifemonths integer DEFAULT NULL, p_isactive boolean DEFAULT TRUE,
    p_createdby text DEFAULT NULL
) RETURNS integer
LANGUAGE plpgsql
AS $function$
DECLARE
    v_id integer := p_waterassetcategoryid;
BEGIN
    IF COALESCE(btrim(p_categoryname), '') = '' THEN
        RAISE EXCEPTION 'Category name is required.';
    END IF;

    IF v_id IS NULL THEN
        INSERT INTO waterassetcategories (farmid, categoryname, defaultusefullifemonths,
                                          sortorder, isactive, createdby)
        VALUES (p_farmid, btrim(p_categoryname), p_defaultusefullifemonths,
                COALESCE((SELECT MAX(c.sortorder) + 1 FROM waterassetcategories c
                           WHERE c.farmid = p_farmid), 1),
                COALESCE(p_isactive, TRUE), p_createdby)
        RETURNING waterassetcategoryid INTO v_id;
    ELSE
        UPDATE waterassetcategories c
        SET    categoryname = btrim(p_categoryname),
               defaultusefullifemonths = p_defaultusefullifemonths,
               isactive = COALESCE(p_isactive, c.isactive)
        WHERE  c.waterassetcategoryid = v_id AND c.farmid = p_farmid;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Asset category does not belong to this company.';
        END IF;
    END IF;

    RETURN v_id;
END;
$function$;

-- -----------------------------------------------------------------------------
-- 9. The money leg, written once and used by both writers.
--
-- Creates the waterexpenses row that IS the acquisition's cash and payable, and
-- stamps it CapitalAsset. Written inline rather than through
-- spwaterexpense_insert -- see the header, point 1 -- following 227's shape.
--
-- The expense is created Approved, because an acquisition that has already
-- moved money is not a draft. That also matters for fnwaterpayables, which only
-- counts Approved rows as debts.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.spwatercapitalassetexpense_post(
    p_farmid        text,
    p_assetid       integer,
    p_date          date,
    p_category      text,
    p_description   text,
    p_amount        numeric,
    p_paymentmethod text,
    p_supplierid    integer,
    p_amountpaid    numeric,
    p_duedate       date,
    p_cashaccountid integer,
    p_sourcetype    text,
    -- The SOURCE DOCUMENT this expense belongs to, which is not always the
    -- asset: see the header, point 3. An acquisition passes the asset id; an
    -- additional cost passes its own cost-row id, because the unique index
    -- allows only one live expense per (farm, sourcetype, sourceid).
    p_sourceid      integer,
    p_createdby     text
) RETURNS integer
LANGUAGE plpgsql
AS $function$
DECLARE
    v_catid  integer;
    v_expid  integer;
    v_acct   integer := p_cashaccountid;
    v_party  text;
    v_method text := COALESCE(NULLIF(btrim(p_paymentmethod), ''), 'Cash');
    v_paid   numeric(14,2);
    v_cat    text := COALESCE(NULLIF(btrim(p_category), ''), 'Capital Assets');
BEGIN
    -- The category, inline and idempotent, exactly as 227 does it: no
    -- dependency on another function's Postgres parameter naming.
    SELECT ec.waterexpensecategoryid INTO v_catid
    FROM   waterexpensecategories ec
    WHERE  ec.farmid = p_farmid
      AND  lower(ec.name) = lower(v_cat)
      AND  COALESCE(ec.isdeleted, FALSE) = FALSE
    LIMIT  1;

    IF v_catid IS NULL THEN
        INSERT INTO waterexpensecategories (farmid, name, isactive, isdeleted)
        VALUES (p_farmid, v_cat, TRUE, FALSE)
        RETURNING waterexpensecategoryid INTO v_catid;
    END IF;

    -- A Credit purchase is by definition unpaid until a supplier payment
    -- settles it, which is the same rule 047 gave every other water bill.
    v_paid := CASE WHEN v_method = 'Credit' THEN COALESCE(p_amountpaid, 0)
                   ELSE COALESCE(p_amountpaid, p_amount) END;
    IF v_paid < 0 THEN
        RAISE EXCEPTION 'Amount paid cannot be negative.';
    END IF;
    IF v_paid > p_amount THEN
        RAISE EXCEPTION 'Amount paid (%) cannot exceed the asset cost (%).',
              v_paid::numeric(14,2), p_amount::numeric(14,2);
    END IF;

    IF p_supplierid IS NOT NULL THEN
        SELECT s.suppliername INTO v_party
        FROM   watersuppliers s
        WHERE  s.watersupplierid = p_supplierid AND s.farmid = p_farmid;
        IF v_party IS NULL THEN
            RAISE EXCEPTION 'Supplier does not belong to this company.';
        END IF;
    END IF;

    -- The account the user chose, else the company's first active one -- the
    -- same fallback 091 used everywhere else on the water side.
    IF v_acct IS NULL AND v_paid > 0 THEN
        SELECT a.watercashaccountid INTO v_acct
        FROM   watercashaccounts a
        WHERE  a.farmid = p_farmid AND a.isactive = TRUE
        ORDER  BY a.watercashaccountid
        LIMIT  1;
    END IF;

    INSERT INTO waterexpenses
        (farmid, expensedate, waterexpensecategoryid, description, amount, paidto,
         paymentmethod, watercashaccountid, amountpaid, duedate,
         status, notes, createdby, approvedby, approvedat,
         supplierid, sourcetype, sourceid, financialcosttype, watercapitalassetid)
    VALUES
        (p_farmid, p_date, v_catid, p_description, p_amount, v_party,
         v_method, v_acct, v_paid, p_duedate,
         'Approved',
         'Auto-created from the asset register.',
         p_createdby, p_createdby, (now() at time zone 'utc'),
         -- sourceid identifies the source DOCUMENT; watercapitalassetid is the
         -- link back to the asset. They differ for an additional cost.
         p_supplierid, COALESCE(p_sourcetype, 'CapitalAsset'),
         COALESCE(p_sourceid, p_assetid),
         'CapitalAsset', p_assetid)
    RETURNING waterexpenseid INTO v_expid;

    -- Money out. Water's convention: a NEGATIVE amount on the transaction and a
    -- separate decrement of the account balance. See the header, point 2.
    IF v_paid > 0 AND v_acct IS NOT NULL THEN
        INSERT INTO watercashtransactions
            (farmid, watercashaccountid, transactiondate, transactiontype,
             sourcetype, sourceid, amount, description, createdby, approvedby, approvedat)
        VALUES
            (p_farmid, v_acct, p_date, 'CashOut',
             'Expense', v_expid, -v_paid,
             COALESCE(NULLIF(btrim(p_description), ''), 'Capital asset'),
             p_createdby, p_createdby, (now() at time zone 'utc'));

        UPDATE watercashaccounts a
        SET    currentbalance = a.currentbalance - v_paid,
               updatedat      = (now() at time zone 'utc')
        WHERE  a.watercashaccountid = v_acct AND a.farmid = p_farmid;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Cash account does not belong to this company.';
        END IF;
    END IF;

    RETURN v_expid;
END;
$function$;

-- -----------------------------------------------------------------------------
-- 10. Create an asset.
--
-- The acquisition amount is optional: a borehole that will be drilled cost by
-- cost starts at zero and grows. That is the construction workflow, without a
-- second workflow to maintain.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.spwatercapitalasset_create(
    p_farmid            text,
    p_assetname         text,
    p_assetcategoryid   integer DEFAULT NULL,
    p_description       text    DEFAULT NULL,
    p_acquisitiondate   date    DEFAULT NULL,
    p_inservicedate     date    DEFAULT NULL,
    p_amount            numeric DEFAULT NULL,
    p_residualvalue     numeric DEFAULT 0,
    p_usefullifemonths  integer DEFAULT NULL,
    p_supplierid        integer DEFAULT NULL,
    p_paymentmethod     text    DEFAULT 'Cash',
    p_amountpaid        numeric DEFAULT NULL,
    p_duedate           date    DEFAULT NULL,
    p_cashaccountid     integer DEFAULT NULL,
    p_expensecategory   text    DEFAULT NULL,
    p_location          text    DEFAULT NULL,
    p_serialnumber      text    DEFAULT NULL,
    p_notes             text    DEFAULT NULL,
    p_createdby         text    DEFAULT NULL
) RETURNS integer
LANGUAGE plpgsql
AS $function$
DECLARE
    v_id     integer;
    v_number text;
    v_date   date := COALESCE(p_acquisitiondate, (now() at time zone 'utc')::date);
    v_expid  integer;
    v_status text;
BEGIN
    IF COALESCE(btrim(p_assetname), '') = '' THEN
        RAISE EXCEPTION 'Asset name is required.';
    END IF;
    IF p_amount IS NOT NULL AND p_amount <= 0 THEN
        RAISE EXCEPTION 'Asset cost must be greater than 0.';
    END IF;
    IF p_assetcategoryid IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM waterassetcategories c
                       WHERE c.waterassetcategoryid = p_assetcategoryid AND c.farmid = p_farmid) THEN
        RAISE EXCEPTION 'Asset category does not belong to this company.';
    END IF;
    IF p_inservicedate IS NOT NULL AND p_inservicedate < v_date THEN
        RAISE EXCEPTION 'An asset cannot be in service before it was acquired.';
    END IF;

    -- Per-company running number, taken under the company's own row lock so two
    -- simultaneous saves cannot both claim AST-0007.
    PERFORM 1 FROM watercapitalassets a WHERE a.farmid = p_farmid FOR UPDATE;
    SELECT 'AST-' || lpad((COALESCE(MAX(substring(a.assetnumber from '[0-9]+$')::integer), 0) + 1)::text, 4, '0')
      INTO v_number
    FROM   watercapitalassets a
    WHERE  a.farmid = p_farmid AND a.assetnumber ~ '^AST-[0-9]+$';
    v_number := COALESCE(v_number, 'AST-0001');

    -- An asset is Active once it is earning: it is in service and the company
    -- has said how long it will last. Anything else is still Draft, and Draft is
    -- what a half-drilled borehole is.
    v_status := CASE WHEN p_inservicedate IS NOT NULL AND COALESCE(p_usefullifemonths, 0) > 0
                     THEN 'Active' ELSE 'Draft' END;

    INSERT INTO watercapitalassets
        (farmid, assetnumber, assetname, waterassetcategoryid, description,
         acquisitiondate, inservicedate, residualvalue, usefullifemonths,
         depreciationmethod, supplierid, location, serialnumber, status, notes, createdby)
    VALUES
        (p_farmid, v_number, btrim(p_assetname), p_assetcategoryid, p_description,
         v_date, p_inservicedate, COALESCE(p_residualvalue, 0), p_usefullifemonths,
         'StraightLine', p_supplierid, p_location, p_serialnumber, v_status, p_notes, p_createdby)
    RETURNING watercapitalassetid INTO v_id;

    IF COALESCE(p_amount, 0) > 0 THEN
        -- The ACQUISITION is keyed on the asset: there is exactly one per asset,
        -- so (farm, 'CapitalAsset', assetid) can never collide.
        v_expid := spwatercapitalassetexpense_post(
            p_farmid, v_id, v_date,
            COALESCE(p_expensecategory, 'Capital Assets'),
            btrim(p_assetname), p_amount, p_paymentmethod,
            p_supplierid, p_amountpaid, p_duedate, p_cashaccountid,
            'CapitalAsset', v_id, p_createdby);

        INSERT INTO watercapitalassetcosts
            (farmid, watercapitalassetid, costdate, description, costcategory,
             amount, sourcetype, waterexpenseid, supplierid, createdby)
        VALUES
            (p_farmid, v_id, v_date, btrim(p_assetname), 'Acquisition',
             p_amount, 'Acquisition', v_expid, p_supplierid, p_createdby);
    END IF;

    RETURN v_id;
END;
$function$;

-- -----------------------------------------------------------------------------
-- 11. Add a cost to an asset. The construction workflow.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.spwatercapitalassetcost_add(
    p_farmid          text,
    p_assetid         integer,
    p_costdate        date,
    p_description     text,
    p_costcategory    text,
    p_amount          numeric,
    p_supplierid      integer DEFAULT NULL,
    p_paymentmethod   text    DEFAULT 'Cash',
    p_amountpaid      numeric DEFAULT NULL,
    p_duedate         date    DEFAULT NULL,
    p_cashaccountid   integer DEFAULT NULL,
    p_expensecategory text    DEFAULT NULL,
    p_createdby       text    DEFAULT NULL
) RETURNS integer
LANGUAGE plpgsql
AS $function$
DECLARE
    v_status text;
    v_name   text;
    v_expid  integer;
    v_id     integer;
    v_date   date := COALESCE(p_costdate, (now() at time zone 'utc')::date);
BEGIN
    SELECT a.status, a.assetname INTO v_status, v_name
    FROM   watercapitalassets a
    WHERE  a.watercapitalassetid = p_assetid AND a.farmid = p_farmid;

    IF v_status IS NULL THEN
        RAISE EXCEPTION 'Asset not found for this company.';
    END IF;
    IF v_status IN ('Reversed', 'Disposed') THEN
        RAISE EXCEPTION 'Cannot add cost to a % asset.', lower(v_status);
    END IF;
    IF COALESCE(p_amount, 0) <= 0 THEN
        RAISE EXCEPTION 'Cost amount must be greater than 0.';
    END IF;

    -- Adding cost to an asset that is already being depreciated would change the
    -- monthly charge under months that have already been posted, and every one
    -- of those months would then be wrong. Block the unsafe edit rather than
    -- pretend to handle it.
    IF EXISTS (SELECT 1 FROM waterassetdepreciation d
               WHERE d.watercapitalassetid = p_assetid AND d.status = 'Posted') THEN
        RAISE EXCEPTION 'Depreciation has already been posted for this asset. Reverse it before changing the asset cost.';
    END IF;

    -- The COST ROW IS WRITTEN FIRST, and that order is required rather than
    -- stylistic. ux_waterexpenses_farmsource_active allows one live expense per
    -- (farm, sourcetype, sourceid), so an additional cost has to be keyed on
    -- something unique to itself. Its own id is the only such thing, and it does
    -- not exist until the row does. The expense is then linked back on.
    INSERT INTO watercapitalassetcosts
        (farmid, watercapitalassetid, costdate, description, costcategory,
         amount, sourcetype, waterexpenseid, supplierid, createdby)
    VALUES
        (p_farmid, p_assetid, v_date, p_description, p_costcategory,
         p_amount, 'AdditionalCost', NULL, p_supplierid, p_createdby)
    RETURNING watercapitalassetcostid INTO v_id;

    v_expid := spwatercapitalassetexpense_post(
        p_farmid, p_assetid, v_date,
        COALESCE(p_expensecategory, 'Capital Assets'),
        COALESCE(NULLIF(btrim(p_description), ''), v_name),
        p_amount, p_paymentmethod, p_supplierid,
        p_amountpaid, p_duedate, p_cashaccountid,
        'CapitalAssetCost', v_id, p_createdby);

    UPDATE watercapitalassetcosts c
    SET    waterexpenseid = v_expid
    WHERE  c.watercapitalassetcostid = v_id;

    RETURN v_id;
END;
$function$;

-- -----------------------------------------------------------------------------
-- 12. Edit an asset.
--
-- Metadata is always editable. The three financial fields -- cost is not among
-- them, it is the cost rows -- are frozen once depreciation has been posted,
-- because changing a useful life retroactively silently invalidates every month
-- already charged.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.spwatercapitalasset_update(
    p_farmid           text,
    p_assetid          integer,
    p_assetname        text,
    p_assetcategoryid  integer DEFAULT NULL,
    p_description      text    DEFAULT NULL,
    p_location         text    DEFAULT NULL,
    p_serialnumber     text    DEFAULT NULL,
    p_notes            text    DEFAULT NULL,
    p_inservicedate    date    DEFAULT NULL,
    p_usefullifemonths integer DEFAULT NULL,
    p_residualvalue    numeric DEFAULT NULL,
    p_setfinancials    boolean DEFAULT FALSE,
    p_updatedby        text    DEFAULT NULL
) RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
    v_status  text;
    v_acqdate date;
    v_posted  boolean;
    v_cost    numeric(14,2);
BEGIN
    SELECT a.status, a.acquisitiondate INTO v_status, v_acqdate
    FROM   watercapitalassets a
    WHERE  a.watercapitalassetid = p_assetid AND a.farmid = p_farmid;
    IF v_status IS NULL THEN
        RAISE EXCEPTION 'Asset not found for this company.';
    END IF;
    IF v_status = 'Reversed' THEN
        RAISE EXCEPTION 'A reversed asset cannot be edited.';
    END IF;

    v_posted := EXISTS (SELECT 1 FROM waterassetdepreciation d
                        WHERE d.watercapitalassetid = p_assetid AND d.status = 'Posted');

    IF p_setfinancials AND v_posted THEN
        RAISE EXCEPTION 'Depreciation has already been posted for this asset, so its in-service date, useful life and residual value are locked. Reverse the depreciation first.';
    END IF;
    IF p_setfinancials AND p_inservicedate IS NOT NULL AND p_inservicedate < v_acqdate THEN
        RAISE EXCEPTION 'An asset cannot be in service before it was acquired.';
    END IF;
    IF p_setfinancials AND p_usefullifemonths IS NOT NULL AND p_usefullifemonths <= 0 THEN
        RAISE EXCEPTION 'Useful life must be at least one month.';
    END IF;

    IF p_setfinancials THEN
        v_cost := fnwatercapitalasset_originalcost(p_assetid);
        IF p_residualvalue IS NOT NULL AND p_residualvalue > v_cost AND v_cost > 0 THEN
            RAISE EXCEPTION 'Residual value (%) cannot be more than the asset cost (%).',
                  p_residualvalue::numeric(14,2), v_cost;
        END IF;
    END IF;

    UPDATE watercapitalassets a
    SET    assetname = COALESCE(NULLIF(btrim(p_assetname), ''), a.assetname),
           waterassetcategoryid = COALESCE(p_assetcategoryid, a.waterassetcategoryid),
           description  = p_description,
           location     = p_location,
           serialnumber = p_serialnumber,
           notes        = p_notes,
           inservicedate    = CASE WHEN p_setfinancials THEN p_inservicedate ELSE a.inservicedate END,
           usefullifemonths = CASE WHEN p_setfinancials THEN p_usefullifemonths ELSE a.usefullifemonths END,
           residualvalue    = CASE WHEN p_setfinancials THEN COALESCE(p_residualvalue, 0) ELSE a.residualvalue END,
           -- Setting a life and a date is what puts an asset into service, so
           -- the status follows rather than needing its own button.
           status = CASE WHEN a.status IN ('Draft', 'Active') AND p_setfinancials THEN
                             CASE WHEN p_inservicedate IS NOT NULL AND COALESCE(p_usefullifemonths, 0) > 0
                                  THEN 'Active' ELSE 'Draft' END
                         ELSE a.status END,
           updatedby = p_updatedby,
           updatedat = (now() at time zone 'utc')
    WHERE  a.watercapitalassetid = p_assetid AND a.farmid = p_farmid;
END;
$function$;

-- -----------------------------------------------------------------------------
-- 13. Dispose.
--
-- Status, dates, notes, and proceeds that reach CASH but not profit. Gain or
-- loss on disposal is deliberately NOT computed: doing it properly means
-- comparing proceeds with book value and recognising the difference, and a
-- half-done version would report a gain the company never made.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.spwatercapitalasset_dispose(
    p_farmid        text,
    p_assetid       integer,
    p_disposaldate  date,
    p_proceeds      numeric DEFAULT NULL,
    p_cashaccountid integer DEFAULT NULL,
    p_notes         text    DEFAULT NULL,
    p_createdby     text    DEFAULT NULL
) RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
    v_status text;
    v_name   text;
    v_date   date := COALESCE(p_disposaldate, (now() at time zone 'utc')::date);
BEGIN
    SELECT a.status, a.assetname INTO v_status, v_name
    FROM   watercapitalassets a
    WHERE  a.watercapitalassetid = p_assetid AND a.farmid = p_farmid;
    IF v_status IS NULL THEN
        RAISE EXCEPTION 'Asset not found for this company.';
    END IF;
    IF v_status IN ('Disposed', 'Reversed') THEN
        RAISE EXCEPTION 'This asset is already %.', lower(v_status);
    END IF;
    IF COALESCE(p_proceeds, 0) > 0 AND p_cashaccountid IS NULL THEN
        RAISE EXCEPTION 'Select the cash account the sale proceeds went into.';
    END IF;

    UPDATE watercapitalassets a
    SET    status = 'Disposed', disposaldate = v_date,
           disposalproceeds = p_proceeds, disposalnotes = p_notes,
           updatedby = p_createdby, updatedat = (now() at time zone 'utc')
    WHERE  a.watercapitalassetid = p_assetid AND a.farmid = p_farmid;

    -- Money in. Cash only: selling a machine is not trading income and must not
    -- appear as revenue.
    IF COALESCE(p_proceeds, 0) > 0 THEN
        UPDATE watercashaccounts a
        SET    currentbalance = a.currentbalance + p_proceeds,
               updatedat = (now() at time zone 'utc')
        WHERE  a.watercashaccountid = p_cashaccountid AND a.farmid = p_farmid;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Cash account does not belong to this company.';
        END IF;

        INSERT INTO watercashtransactions
            (farmid, watercashaccountid, transactiondate, transactiontype,
             sourcetype, sourceid, amount, description, createdby, approvedby, approvedat)
        VALUES
            (p_farmid, p_cashaccountid, v_date, 'CashIn', 'AssetDisposal', p_assetid,
             p_proceeds, 'Disposal of ' || v_name, p_createdby, p_createdby,
             (now() at time zone 'utc'));
    END IF;
END;
$function$;

-- -----------------------------------------------------------------------------
-- 14. Reverse an acquisition.
--
-- Refused outright once anything downstream depends on it: do not silently
-- corrupt history. The three refusals are depreciation, supplier payments, and
-- disposal -- each of them a record that would be left pointing at nothing.
--
-- WHERE THIS DIFFERS FROM POULTRY: 270 DELETES the expense row. Water soft-
-- deletes it instead, because waterexpenses has an isdeleted column and every
-- other water writer respects it. That keeps the cost row's waterexpenseid
-- pointing at something readable, and fnwaterexpenserows / fnwaterpayables both
-- already filter isdeleted, so the row leaves every total exactly as a delete
-- would.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.spwatercapitalasset_reverse(
    p_farmid    text,
    p_assetid   integer,
    p_reason    text,
    p_createdby text DEFAULT NULL
) RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
    v_status text;
    r        record;
    -- Per-cost working values for the unwind loop below.
    v_acct   integer;
    v_paid   numeric(14,2);
    v_desc   text;
BEGIN
    SELECT a.status INTO v_status
    FROM   watercapitalassets a
    WHERE  a.watercapitalassetid = p_assetid AND a.farmid = p_farmid;
    IF v_status IS NULL THEN
        RAISE EXCEPTION 'Asset not found for this company.';
    END IF;
    IF v_status = 'Reversed' THEN
        RAISE EXCEPTION 'This asset has already been reversed.';
    END IF;
    IF COALESCE(btrim(p_reason), '') = '' THEN
        RAISE EXCEPTION 'A reason is required to reverse an asset.';
    END IF;
    IF v_status = 'Disposed' THEN
        RAISE EXCEPTION 'A disposed asset cannot be reversed.';
    END IF;

    IF EXISTS (SELECT 1 FROM waterassetdepreciation d
               WHERE d.watercapitalassetid = p_assetid AND d.status = 'Posted') THEN
        RAISE EXCEPTION 'Depreciation has been posted for this asset. Reverse the depreciation first.';
    END IF;

    IF EXISTS (SELECT 1
               FROM   watercapitalassetcosts c
               JOIN   supplierpaymentallocation sa
                 ON   sa.documenttype = 'Expense' AND sa.documentid = c.waterexpenseid
                AND   lower(sa.farmid) = lower(p_farmid) AND sa.module = 'water'
                AND   sa.status = 'Posted'
               WHERE  c.watercapitalassetid = p_assetid AND c.status = 'Posted') THEN
        RAISE EXCEPTION 'A supplier payment has been recorded against this asset. Reverse the payment on Supplier Payments first.';
    END IF;

    -- Unwind each cost's money leg, then mark it reversed. The cash is handed
    -- back with an opposite transaction rather than by deleting the original,
    -- so the cash ledger stays append-only like every other water ledger.
    FOR r IN SELECT c.watercapitalassetcostid, c.waterexpenseid
             FROM   watercapitalassetcosts c
             WHERE  c.watercapitalassetid = p_assetid AND c.status = 'Posted'
    LOOP
        IF r.waterexpenseid IS NOT NULL THEN
            -- v_acct / v_paid / v_desc are declared on the function rather than
            -- in a nested block. A nested DECLARE inside a loop is legal
            -- plpgsql, but it buys nothing here and reads worse; they are reset
            -- explicitly each iteration so a row that selects nothing cannot
            -- inherit the previous row's values.
            v_acct := NULL; v_paid := NULL; v_desc := NULL;

            SELECT e.watercashaccountid,
                   COALESCE(e.amountpaid,
                            CASE WHEN COALESCE(e.paymentmethod, '') = 'Credit'
                                 THEN 0 ELSE e.amount END),
                   e.description
            INTO   v_acct, v_paid, v_desc
            FROM   waterexpenses e
            WHERE  e.waterexpenseid = r.waterexpenseid AND e.farmid = p_farmid;

            IF COALESCE(v_paid, 0) > 0 AND v_acct IS NOT NULL THEN
                INSERT INTO watercashtransactions
                    (farmid, watercashaccountid, transactiondate, transactiontype,
                     sourcetype, sourceid, amount, description, createdby, approvedby, approvedat)
                VALUES
                    (p_farmid, v_acct, (now() at time zone 'utc'), 'CashIn',
                     'Expense', r.waterexpenseid, v_paid,
                     'Reversal of capital asset — ' || COALESCE(v_desc, ''),
                     p_createdby, p_createdby, (now() at time zone 'utc'));

                UPDATE watercashaccounts a
                SET    currentbalance = a.currentbalance + v_paid,
                       updatedat = (now() at time zone 'utc')
                WHERE  a.watercashaccountid = v_acct AND a.farmid = p_farmid;
            END IF;

            -- Soft delete, and zero the paid amount so no reader can treat the
            -- row as a settled bill on its way out.
            UPDATE waterexpenses e
            SET    isdeleted  = TRUE,
                   amountpaid = 0,
                   updatedat  = (now() at time zone 'utc')
            WHERE  e.waterexpenseid = r.waterexpenseid AND e.farmid = p_farmid;
        END IF;

        UPDATE watercapitalassetcosts c
        SET    status = 'Reversed', reversedby = p_createdby,
               reversedat = (now() at time zone 'utc'), reversalreason = p_reason
        WHERE  c.watercapitalassetcostid = r.watercapitalassetcostid;
    END LOOP;

    UPDATE watercapitalassets a
    SET    status = 'Reversed', reversedby = p_createdby,
           reversedat = (now() at time zone 'utc'), reversalreason = p_reason,
           updatedat = (now() at time zone 'utc')
    WHERE  a.watercapitalassetid = p_assetid AND a.farmid = p_farmid;
END;
$function$;

-- -----------------------------------------------------------------------------
-- 15. Reads.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.spwatercapitalasset_getall(
    p_farmid text, p_status text DEFAULT NULL, p_categoryid integer DEFAULT NULL
) RETURNS TABLE(watercapitalassetid integer, farmid text, assetnumber text, assetname text,
                waterassetcategoryid integer, categoryname text, description text,
                acquisitiondate date, inservicedate date, location text, serialnumber text,
                supplierid integer, suppliername text, status text, notes text,
                originalcost numeric, residualvalue numeric, depreciableamount numeric,
                usefullifemonths integer, monthlydepreciation numeric,
                accumulateddepreciation numeric, currentbookvalue numeric,
                remainingdepreciable numeric, isfullydepreciated boolean,
                costentries integer, depreciationentries integer,
                disposaldate date, disposalproceeds numeric,
                createdby text, createdat timestamp without time zone,
                updatedat timestamp without time zone,
                reversedby text, reversedat timestamp without time zone, reversalreason text)
LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT a.watercapitalassetid, a.farmid::text, a.assetnumber::text, a.assetname::text,
           a.waterassetcategoryid, c.categoryname::text, a.description::text,
           a.acquisitiondate, a.inservicedate, a.location::text, a.serialnumber::text,
           a.supplierid, s.suppliername::text, a.status::text, a.notes::text,
           f.originalcost, f.residualvalue, f.depreciableamount,
           f.usefullifemonths, f.monthlydepreciation,
           f.accumulateddepreciation, f.currentbookvalue,
           f.remainingdepreciable, f.isfullydepreciated,
           (SELECT COUNT(*)::integer FROM watercapitalassetcosts cc
             WHERE cc.watercapitalassetid = a.watercapitalassetid AND cc.status = 'Posted'),
           (SELECT COUNT(*)::integer FROM waterassetdepreciation dd
             WHERE dd.watercapitalassetid = a.watercapitalassetid AND dd.status = 'Posted'),
           a.disposaldate, a.disposalproceeds,
           a.createdby::text, a.createdat, a.updatedat,
           a.reversedby::text, a.reversedat, a.reversalreason::text
    FROM   watercapitalassets a
    LEFT   JOIN waterassetcategories c ON c.waterassetcategoryid = a.waterassetcategoryid
    LEFT   JOIN watersuppliers s ON s.watersupplierid = a.supplierid
    CROSS  JOIN LATERAL fnwatercapitalasset_financials(a.watercapitalassetid) f
    WHERE  a.farmid = p_farmid
      AND  (p_status IS NULL OR a.status = p_status)
      AND  (p_categoryid IS NULL OR a.waterassetcategoryid = p_categoryid)
    ORDER  BY a.acquisitiondate DESC, a.watercapitalassetid DESC;
END;
$function$;

CREATE OR REPLACE FUNCTION public.spwatercapitalassetcost_getall(
    p_farmid text, p_assetid integer
) RETURNS TABLE(watercapitalassetcostid integer, watercapitalassetid integer,
                costdate date, description text, costcategory text, amount numeric,
                sourcetype text, waterexpenseid integer, supplierid integer, suppliername text,
                paymentstatus text, amountpaid numeric, balance numeric,
                status text, createdby text, createdat timestamp without time zone,
                reversedby text, reversedat timestamp without time zone, reversalreason text)
LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT c.watercapitalassetcostid, c.watercapitalassetid,
           c.costdate, c.description::text, c.costcategory::text, c.amount,
           c.sourcetype::text, c.waterexpenseid, c.supplierid, s.suppliername::text,
           e.paymentstatus::text,
           COALESCE(e.amountpaid,
                    CASE WHEN COALESCE(e.paymentmethod, '') = 'Credit'
                         THEN 0 ELSE e.amount END)::numeric(14,2),
           GREATEST(COALESCE(e.amount, 0)
                    - COALESCE(e.amountpaid,
                               CASE WHEN COALESCE(e.paymentmethod, '') = 'Credit'
                                    THEN 0 ELSE e.amount END), 0)::numeric(14,2),
           c.status::text, c.createdby::text, c.createdat,
           c.reversedby::text, c.reversedat, c.reversalreason::text
    FROM   watercapitalassetcosts c
    LEFT   JOIN waterexpenses e ON e.waterexpenseid = c.waterexpenseid
    LEFT   JOIN watersuppliers s ON s.watersupplierid = c.supplierid
    WHERE  c.farmid = p_farmid AND c.watercapitalassetid = p_assetid
    ORDER  BY c.costdate, c.watercapitalassetcostid;
END;
$function$;

-- The five cards at the top of the register. Book value is a BALANCE, never a
-- period total: it is what the company owns today, not what it acquired between
-- two dates. Only "added in period" is period-scoped, and it says so.
CREATE OR REPLACE FUNCTION public.spwatercapitalasset_summary(
    p_farmid text, p_fromdate date DEFAULT NULL, p_todate date DEFAULT NULL
) RETURNS TABLE(totalassets integer, activeassets integer, draftassets integer,
                disposedassets integer, fullydepreciated integer,
                totalassetcost numeric, accumulateddepreciation numeric,
                currentbookvalue numeric, addedinperiod numeric, addedcount integer)
LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    WITH live AS (
        SELECT a.watercapitalassetid, a.status, a.acquisitiondate, f.*
        FROM   watercapitalassets a
        CROSS  JOIN LATERAL fnwatercapitalasset_financials(a.watercapitalassetid) f
        WHERE  a.farmid = p_farmid AND a.status <> 'Reversed'
    )
    SELECT COUNT(*)::integer,
           COUNT(*) FILTER (WHERE l.status = 'Active')::integer,
           COUNT(*) FILTER (WHERE l.status = 'Draft')::integer,
           COUNT(*) FILTER (WHERE l.status = 'Disposed')::integer,
           COUNT(*) FILTER (WHERE l.status = 'FullyDepreciated')::integer,
           COALESCE(SUM(l.originalcost), 0)::numeric(14,2),
           COALESCE(SUM(l.accumulateddepreciation), 0)::numeric(14,2),
           COALESCE(SUM(l.currentbookvalue), 0)::numeric(14,2),
           COALESCE((SELECT SUM(cc.amount) FROM watercapitalassetcosts cc
                      WHERE cc.farmid = p_farmid AND cc.status = 'Posted'
                        AND (p_fromdate IS NULL OR cc.costdate >= p_fromdate)
                        AND (p_todate   IS NULL OR cc.costdate <= p_todate)), 0)::numeric(14,2),
           COALESCE((SELECT COUNT(*) FROM watercapitalassets aa
                      WHERE aa.farmid = p_farmid AND aa.status <> 'Reversed'
                        AND (p_fromdate IS NULL OR aa.acquisitiondate >= p_fromdate)
                        AND (p_todate   IS NULL OR aa.acquisitiondate <= p_todate)), 0)::integer
    FROM   live l;
END;
$function$;

COMMIT;

-- -----------------------------------------------------------------------------
-- Post-conditions. New tables only -- nothing that existed has moved.
-- -----------------------------------------------------------------------------
SELECT 'no assets exist yet' AS check, COUNT(*) AS should_be_zero FROM watercapitalassets;

SELECT 'no water expense is capital yet' AS check, COUNT(*) AS should_be_zero
FROM   waterexpenses WHERE financialcosttype = 'CapitalAsset';

SELECT 'no depreciation exists yet' AS check, COUNT(*) AS should_be_zero
FROM   waterassetdepreciation;

-- The widened payable filter must not have admitted anything that exists today:
-- no current row carries a capital sourcetype, so today's payables are
-- byte-for-byte what they were before this file.
SELECT 'payables unchanged today' AS check, COUNT(*) AS should_be_zero
FROM   waterexpenses
WHERE  sourcetype IN ('CapitalAsset', 'CapitalAssetCost');
