-- =============================================================================
-- 304_PaymentHistoryReturnsCreatedAt.postgres.sql
--
-- Purpose
-- -------
-- The payments pages showed a date with no time. Six readers back them and none
-- returned a creation timestamp, so no amount of frontend formatting could have
-- helped -- the value was never in the payload.
--
-- These pages are thin wrappers around two SHARED components
-- (components/payments/payments-received-page.tsx and
-- components/balances/payments-ledger-page.tsx), which is also why they were
-- missed: the earlier frontend sweeps only walked app/.
--
-- WHAT EACH FUNCTION GETS
-- =======================
--     sppoultrycustomerpayment_history   poultrypayments.createddate GROUPED -> MIN()
--     sppoultrysupplierpayment_history   poultrysupplierpayments.createdat plain column
--     spwatercustomerpayment_history     waterpayments.createddate  GROUPED -> MIN()
--     spwatersupplierpayment_history     watersupplierpayments.createdat plain column
--     spgenericcustomerpayment_history   genericcustomerpayments.createdat plain column
--     spgenericsupplierpayment_history   genericsupplierpayments.createdat plain column
--
-- THE AGGREGATION TRAP
-- ====================
-- The two customer histories GROUP BY paymentgroupid -- one payment group is
-- several payment rows -- so a bare column reference there does not compile
-- ("column must appear in the GROUP BY clause"). They take MIN(), which is when
-- the group was first entered and matches each function's own
-- ORDER BY MIN(paymentdate). Whether a function is grouped was detected from its
-- body, not assumed.
--
-- The _allocations readers are deliberately NOT changed. They show the
-- DOCUMENT's date (a sale or an invoice); an entry time there would belong to
-- the document, not to the allocation row, and would be a different fact wearing
-- the same label.
--
-- HOW THIS FILE WAS PRODUCED
-- ==========================
-- Generated by transforming the live pg_get_functiondef output, not by retyping
-- it -- the same method as 302. Every byte outside a line marked "304:" is what
-- was deployed.
--
-- Output is normalised to `createdat` even though the base tables variously say
-- createddate and createdat, so the C# and the frontend know one name.
--
-- Adding a column to RETURNS TABLE changes the return type: DROP + CREATE, and
-- the grants are reissued at the end or every payments page 500s.
--
-- NO DATA CHANGES: read-only functions.
--
-- Order: after 303.
-- =============================================================================

\set ON_ERROR_STOP on

BEGIN;

DROP FUNCTION IF EXISTS public.sppoultrycustomerpayment_history(text, integer, integer, date, date);
DROP FUNCTION IF EXISTS public.sppoultrysupplierpayment_history(text, integer, text, integer, date, date);
DROP FUNCTION IF EXISTS public.spwatercustomerpayment_history(text, integer, integer, date, date);
DROP FUNCTION IF EXISTS public.spwatersupplierpayment_history(text, integer, text, integer, date, date);
DROP FUNCTION IF EXISTS public.spgenericcustomerpayment_history(text, integer, integer, date, date);
DROP FUNCTION IF EXISTS public.spgenericsupplierpayment_history(text, integer, text, integer, date, date);

CREATE OR REPLACE FUNCTION public.sppoultrycustomerpayment_history(p_farmid text, p_customerid integer DEFAULT NULL::integer, p_saleid integer DEFAULT NULL::integer, p_from date DEFAULT NULL::date, p_to date DEFAULT NULL::date)
 RETURNS TABLE(paymentgroupid uuid, paymentnumber text, customerid integer, customername text, paymentdate timestamp without time zone, totalamount numeric, paymentmethod text, reference text, note text, sourcetype text, status text, allocationcount integer, poultrycashaccountid integer, createdby text, reversedby text, reversedat timestamp without time zone, reversalreason text, saleid integer, saletotal numeric, balancebefore numeric, amountapplied numeric, balanceafter numeric, createdat timestamp)
 LANGUAGE sql
 STABLE
AS $function$
    SELECT pp.paymentgroupid,
           MIN(pp.paymentnumber)::text,
           MIN(pp.customerid),
           MIN(c.name)::text,
           MIN(pp.paymentdate),
           SUM(pp.amount)::numeric(14,2),
           MIN(pp.paymentmethod)::text,
           MIN(pp.reference)::text,
           MIN(pp.note)::text,
           MIN(pp.sourcetype)::text,
           MIN(COALESCE(pp.status, 'Posted'))::text,
           -- DISTINCT on the payment row, not COUNT(*): the joins below are
           -- 1:1 today, and this stays right if one of them ever is not.
           COUNT(DISTINCT pp.poultrypaymentid)::integer,
           MIN(pp.poultrycashaccountid),
           MIN(pp.createdby)::text,
           MIN(pp.reversedby)::text,
           MIN(pp.reversedat),
           MIN(pp.reversalreason)::text,
           -- One sale, or nothing. A payment across several sales has no single
           -- "balance before" to report, and saying so with NULL is what lets
           -- the page print "â€”" without guessing.
           CASE WHEN COUNT(DISTINCT pp.poultrypaymentid) = 1 THEN MIN(pp.saleid) END,
           CASE WHEN COUNT(DISTINCT pp.poultrypaymentid) = 1 THEN MIN(s.totalamount)::numeric(14,2) END,
           CASE WHEN COUNT(DISTINCT pp.poultrypaymentid) = 1 THEN MIN(ca.salebalancebefore)::numeric(14,2) END,
           CASE WHEN COUNT(DISTINCT pp.poultrypaymentid) = 1 THEN MIN(ca.amountapplied)::numeric(14,2) END,
           CASE WHEN COUNT(DISTINCT pp.poultrypaymentid) = 1 THEN MIN(ca.salebalanceafter)::numeric(14,2) END
           , MIN(pp.createddate)   -- 304: the entry time
    FROM   poultrypayments pp
    LEFT   JOIN customer c ON c.customerid = pp.customerid AND c.farmid = pp.farmid
    LEFT   JOIN sale s     ON s.saleid = pp.saleid AND s.farmid = pp.farmid
    -- Payments taken before 222 have no allocation row; those columns come back
    -- NULL and the page falls back to what it can show.
    LEFT   JOIN customerpaymentallocation ca
           ON  ca.module = 'poultry'
           AND ca.paymentid = pp.poultrypaymentid
           AND ca.farmid = pp.farmid
    WHERE  pp.farmid = p_farmid
      AND  (p_customerid IS NULL OR pp.customerid = p_customerid)
      AND  (p_from IS NULL OR pp.paymentdate::date >= p_from)
      AND  (p_to   IS NULL OR pp.paymentdate::date <= p_to)
      AND  (p_saleid IS NULL OR EXISTS (
              SELECT 1 FROM poultrypayments p2
              WHERE p2.paymentgroupid = pp.paymentgroupid AND p2.saleid = p_saleid))
    GROUP  BY pp.paymentgroupid
    ORDER  BY MIN(pp.paymentdate) DESC;
$function$;

CREATE OR REPLACE FUNCTION public.sppoultrysupplierpayment_history(p_farmid text, p_supplierid integer DEFAULT NULL::integer, p_documenttype text DEFAULT NULL::text, p_documentid integer DEFAULT NULL::integer, p_from date DEFAULT NULL::date, p_to date DEFAULT NULL::date)
 RETURNS TABLE(paymentid integer, supplierid integer, suppliername text, paymentdate timestamp without time zone, totalamount numeric, paymentmethod text, referenceno text, notes text, sourcetype text, status text, allocationcount integer, poultrycashaccountid integer, createdby text, reversedby text, reversedat timestamp without time zone, reversalreason text, createdat timestamp)
 LANGUAGE sql
 STABLE
AS $function$
    SELECT sp.poultrysupplierpaymentid, sp.supplierid, s.name::text, sp.paymentdate,
           sp.totalamount, sp.paymentmethod, sp.referenceno, sp.notes, sp.sourcetype, sp.status,
           (SELECT COUNT(*)::integer FROM supplierpaymentallocation sa
            WHERE sa.farmid = sp.farmid AND sa.module = 'poultry'
              AND sa.paymentid = sp.poultrysupplierpaymentid),
           sp.poultrycashaccountid, sp.createdby, sp.reversedby, sp.reversedat, sp.reversalreason
           , sp.createdat   -- 304: the entry time
    FROM   poultrysupplierpayments sp
    LEFT   JOIN supplier s ON s.supplierid = sp.supplierid AND s.farmid = sp.farmid
    WHERE  sp.farmid = p_farmid
      AND  (p_supplierid IS NULL OR sp.supplierid = p_supplierid)
      AND  (p_from IS NULL OR sp.paymentdate::date >= p_from)
      AND  (p_to   IS NULL OR sp.paymentdate::date <= p_to)
      AND  (p_documentid IS NULL OR EXISTS (
              SELECT 1 FROM supplierpaymentallocation sa
              WHERE sa.farmid = sp.farmid AND sa.module = 'poultry'
                AND sa.paymentid = sp.poultrysupplierpaymentid
                AND sa.documentid = p_documentid
                AND (p_documenttype IS NULL OR sa.documenttype = p_documenttype)))
    ORDER  BY sp.paymentdate DESC, sp.poultrysupplierpaymentid DESC;
$function$;

CREATE OR REPLACE FUNCTION public.spwatercustomerpayment_history(p_farmid text, p_customerid integer DEFAULT NULL::integer, p_saleid integer DEFAULT NULL::integer, p_from date DEFAULT NULL::date, p_to date DEFAULT NULL::date)
 RETURNS TABLE(paymentgroupid uuid, paymentnumber text, customerid integer, customername text, paymentdate timestamp without time zone, totalamount numeric, paymentmethod text, reference text, note text, sourcetype text, status text, allocationcount integer, watercashaccountid integer, createdby text, reversedby text, reversedat timestamp without time zone, reversalreason text, saleid integer, saletotal numeric, balancebefore numeric, amountapplied numeric, balanceafter numeric, createdat timestamp)
 LANGUAGE sql
 STABLE
AS $function$
    SELECT p.paymentgroupid,
           MIN(p.paymentnumber)::text,
           MIN(p.watercustomerid),
           MIN(c.name)::text,
           MIN(p.paymentdate),
           SUM(p.amount)::numeric(14,2),
           MIN(p.paymentmethod)::text,
           MIN(p.reference)::text,
           MIN(p.note)::text,
           MIN(p.sourcetype)::text,
           MIN(COALESCE(p.status, 'Posted'))::text,
           -- DISTINCT on the payment row, not COUNT(*): the joins below are 1:1
           -- today, and this stays right if one of them ever is not.
           COUNT(DISTINCT p.waterpaymentid)::integer,
           MIN(p.watercashaccountid),
           MIN(p.createdby)::text,
           MIN(p.reversedby)::text,
           MIN(p.reversedat),
           MIN(p.reversalreason)::text,
           CASE WHEN COUNT(DISTINCT p.waterpaymentid) = 1 THEN MIN(p.watersaleid) END,
           CASE WHEN COUNT(DISTINCT p.waterpaymentid) = 1 THEN MIN(s.totalamount)::numeric(14,2) END,
           CASE WHEN COUNT(DISTINCT p.waterpaymentid) = 1 THEN MIN(ca.salebalancebefore)::numeric(14,2) END,
           CASE WHEN COUNT(DISTINCT p.waterpaymentid) = 1 THEN MIN(ca.amountapplied)::numeric(14,2) END,
           CASE WHEN COUNT(DISTINCT p.waterpaymentid) = 1 THEN MIN(ca.salebalanceafter)::numeric(14,2) END
           , MIN(p.createddate)   -- 304: the entry time
    FROM   waterpayments p
    LEFT   JOIN watercustomers c ON c.watercustomerid = p.watercustomerid AND c.farmid = p.farmid
    LEFT   JOIN watersales s     ON s.watersaleid = p.watersaleid AND s.farmid = p.farmid
    -- Payments taken before 227 have no allocation row; those columns come back
    -- NULL and the page falls back to what it can show.
    LEFT   JOIN customerpaymentallocation ca
           ON  ca.module = 'water'
           AND ca.paymentid = p.waterpaymentid
           AND ca.farmid = p.farmid
    WHERE  p.farmid = p_farmid
      AND  (p_customerid IS NULL OR p.watercustomerid = p_customerid)
      AND  (p_from IS NULL OR p.paymentdate::date >= p_from)
      AND  (p_to   IS NULL OR p.paymentdate::date <= p_to)
      AND  (p_saleid IS NULL OR EXISTS (
              SELECT 1 FROM waterpayments p2
              WHERE p2.paymentgroupid = p.paymentgroupid AND p2.watersaleid = p_saleid))
    GROUP  BY p.paymentgroupid
    ORDER  BY MIN(p.paymentdate) DESC;
$function$;

CREATE OR REPLACE FUNCTION public.spwatersupplierpayment_history(p_farmid text, p_supplierid integer DEFAULT NULL::integer, p_documenttype text DEFAULT NULL::text, p_documentid integer DEFAULT NULL::integer, p_from date DEFAULT NULL::date, p_to date DEFAULT NULL::date)
 RETURNS TABLE(paymentid integer, supplierid integer, suppliername text, paymentdate timestamp without time zone, totalamount numeric, paymentmethod text, referenceno text, notes text, sourcetype text, status text, allocationcount integer, watercashaccountid integer, createdby text, reversedby text, reversedat timestamp without time zone, reversalreason text, createdat timestamp)
 LANGUAGE sql
 STABLE
AS $function$
    SELECT sp.watersupplierpaymentid,
           sp.supplierid,
           s.suppliername::text,
           sp.paymentdate,
           sp.totalamount,
           sp.paymentmethod::text,
           sp.referenceno::text,
           sp.notes::text,
           sp.sourcetype::text,
           COALESCE(sp.status, 'Posted')::text,
           (SELECT COUNT(*)::integer FROM supplierpaymentallocation sa
            WHERE sa.farmid = sp.farmid AND sa.module = 'water'
              AND sa.paymentid = sp.watersupplierpaymentid),
           sp.watercashaccountid,
           sp.createdby::text,
           sp.reversedby::text,
           sp.reversedat,
           sp.reversalreason::text
           , sp.createdat   -- 304: the entry time
    FROM   watersupplierpayments sp
    LEFT   JOIN watersuppliers s ON s.watersupplierid = sp.supplierid AND s.farmid = sp.farmid
    WHERE  sp.farmid = p_farmid
      AND  (p_supplierid IS NULL OR sp.supplierid = p_supplierid)
      AND  (p_from IS NULL OR sp.paymentdate::date >= p_from)
      AND  (p_to   IS NULL OR sp.paymentdate::date <= p_to)
      AND  (p_documentid IS NULL OR EXISTS (
              SELECT 1 FROM supplierpaymentallocation sa
              WHERE sa.paymentid = sp.watersupplierpaymentid
                AND sa.module = 'water'
                AND sa.documentid = p_documentid
                AND (p_documenttype IS NULL OR sa.documenttype = p_documenttype)))
    ORDER  BY sp.paymentdate DESC, sp.watersupplierpaymentid DESC;
$function$;

CREATE OR REPLACE FUNCTION public.spgenericcustomerpayment_history(p_farmid text, p_customerid integer DEFAULT NULL::integer, p_saleid integer DEFAULT NULL::integer, p_from date DEFAULT NULL::date, p_to date DEFAULT NULL::date)
 RETURNS TABLE(paymentid integer, partyid integer, partyname text, paymentdate timestamp without time zone, totalamount numeric, paymentmethod text, reference text, notes text, sourcetype text, status text, allocationcount integer, cashaccountid integer, createdby text, reversedby text, reversedat timestamp without time zone, reversalreason text, createdat timestamp)
 LANGUAGE sql
 STABLE
AS $function$
    SELECT p.genericcustomerpaymentid, p.genericcustomerid, c.customername::text,
           p.paymentdate, p.amount, p.paymentmethod::text, p.referenceno,
           p.notes::text, p.sourcetype,
           -- The balances UI speaks Posted/Reversed; generic has always stored
           -- Draft/Approved/Cancelled. Translated here rather than leaving the
           -- frontend to guess.
           CASE p.status WHEN 'Approved' THEN 'Posted'
                         WHEN 'Reversed' THEN 'Reversed'
                         ELSE p.status END::text,
           (SELECT COUNT(*)::integer FROM customerpaymentallocation ca
            WHERE ca.farmid = p_farmid AND ca.module = 'generic'
              AND ca.paymentid = p.genericcustomerpaymentid),
           p.genericcashaccountid, p.createdby::text,
           p.reversedby, p.reversedat, p.reversalreason
           , p.createdat   -- 304: the entry time
    FROM   genericcustomerpayments p
    LEFT   JOIN genericcustomers c ON c.genericcustomerid = p.genericcustomerid
    WHERE  p.farmid = p_farmid
      AND  p.status IN ('Approved', 'Reversed')
      AND  (p_customerid IS NULL OR p.genericcustomerid = p_customerid)
      AND  (p_from IS NULL OR p.paymentdate::date >= p_from)
      AND  (p_to   IS NULL OR p.paymentdate::date <= p_to)
      AND  (p_saleid IS NULL OR EXISTS (
                SELECT 1 FROM customerpaymentallocation ca
                WHERE ca.farmid = p_farmid AND ca.module = 'generic'
                  AND ca.paymentid = p.genericcustomerpaymentid AND ca.saleid = p_saleid))
    ORDER  BY p.paymentdate DESC, p.genericcustomerpaymentid DESC;
$function$;

CREATE OR REPLACE FUNCTION public.spgenericsupplierpayment_history(p_farmid text, p_supplierid integer DEFAULT NULL::integer, p_documenttype text DEFAULT NULL::text, p_documentid integer DEFAULT NULL::integer, p_from date DEFAULT NULL::date, p_to date DEFAULT NULL::date)
 RETURNS TABLE(paymentid integer, partyid integer, partyname text, paymentdate timestamp without time zone, totalamount numeric, paymentmethod text, reference text, notes text, sourcetype text, status text, allocationcount integer, cashaccountid integer, createdby text, reversedby text, reversedat timestamp without time zone, reversalreason text, createdat timestamp)
 LANGUAGE sql
 STABLE
AS $function$
    SELECT sp.genericsupplierpaymentid, sp.genericsupplierid, s.suppliername::text,
           sp.paymentdate, sp.amount, sp.paymentmethod::text, sp.referenceno,
           sp.notes::text, sp.sourcetype,
           (CASE WHEN COALESCE(sp.status, '') = 'Reversed' THEN 'Reversed' ELSE 'Posted' END)::text,
           (SELECT COUNT(*)::integer FROM supplierpaymentallocation sa
             WHERE sa.farmid = sp.farmid AND sa.module = 'generic'
               AND sa.paymentid = sp.genericsupplierpaymentid),
           sp.genericcashaccountid, sp.createdby, sp.reversedby, sp.reversedat, sp.reversalreason
           , sp.createdat   -- 304: the entry time
    FROM   genericsupplierpayments sp
    LEFT   JOIN genericsuppliers s ON s.genericsupplierid = sp.genericsupplierid
                                  AND s.farmid = sp.farmid
    WHERE  sp.farmid = p_farmid
      AND  (p_supplierid IS NULL OR sp.genericsupplierid = p_supplierid)
      AND  (p_from IS NULL OR sp.paymentdate::date >= p_from)
      AND  (p_to   IS NULL OR sp.paymentdate::date <= p_to)
      AND  (p_documentid IS NULL OR EXISTS (
               SELECT 1 FROM supplierpaymentallocation sa
               WHERE sa.farmid = sp.farmid AND sa.module = 'generic'
                 AND sa.paymentid = sp.genericsupplierpaymentid
                 AND sa.documentid = p_documentid
                 AND (p_documenttype IS NULL OR sa.documenttype = p_documenttype)))
    ORDER  BY sp.paymentdate DESC, sp.genericsupplierpaymentid DESC;
$function$;

-- -----------------------------------------------------------------------------
-- Grants. DROP FUNCTION takes them with it.
-- -----------------------------------------------------------------------------
DO $grants$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'poultryapp') THEN
        GRANT EXECUTE ON FUNCTION public.sppoultrycustomerpayment_history(text, integer, integer, date, date) TO poultryapp;
        GRANT EXECUTE ON FUNCTION public.sppoultrysupplierpayment_history(text, integer, text, integer, date, date) TO poultryapp;
        GRANT EXECUTE ON FUNCTION public.spwatercustomerpayment_history(text, integer, integer, date, date) TO poultryapp;
        GRANT EXECUTE ON FUNCTION public.spwatersupplierpayment_history(text, integer, text, integer, date, date) TO poultryapp;
        GRANT EXECUTE ON FUNCTION public.spgenericcustomerpayment_history(text, integer, integer, date, date) TO poultryapp;
        GRANT EXECUTE ON FUNCTION public.spgenericsupplierpayment_history(text, integer, text, integer, date, date) TO poultryapp;
    END IF;
END
$grants$;

COMMIT;

SELECT p.proname AS check,
       CASE WHEN pg_get_function_result(p.oid) ILIKE '%createdat%'
            THEN 'OK returns createdat' ELSE 'MISSING' END AS result
FROM   pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE  n.nspname = 'public' AND p.prokind = 'f'
  AND  p.proname ~ '(customerpayment|supplierpayment)_history'
ORDER  BY p.proname;
