using Npgsql; using NpgsqlTypes; using PoultryFarmAPIWeb.Models;
namespace PoultryFarmAPIWeb.Business
{
    public class RestaurantLoyaltyService : IRestaurantLoyaltyService
    {
        private readonly string _cs; public RestaurantLoyaltyService(string cs) => _cs = cs;
        static NpgsqlParameter TP(string n, string v) => new(n, System.Data.DbType.String) { Value = v };

        public async Task<LoyaltySettingsModel?> GetSettingsAsync(string farmId) { using var c=new NpgsqlConnection(_cs); using var cmd=new NpgsqlCommand("SELECT * FROM sprestaurant_loyalty_settings_get(p_farmid=>@F::text)",c); cmd.Parameters.Add(TP("@F",farmId)); await c.OpenAsync(); using var r=await cmd.ExecuteReaderAsync(); if(!await r.ReadAsync()) return null; return new() { LoyaltySettingId=r.GetInt32(0),FarmId=r.GetString(1),IsEnabled=r.GetBoolean(2),PointsPerCurrencyUnit=r.GetDecimal(3),PointsRedemptionRate=r.GetDecimal(4),MinimumRedeemPoints=r.GetInt32(5),PointsExpiryDays=r.GetInt32(6),TiersEnabled=r.GetBoolean(7),BronzeThreshold=r.GetInt32(8),SilverThreshold=r.GetInt32(9),GoldThreshold=r.GetInt32(10),PlatinumThreshold=r.GetInt32(11),BronzeMultiplier=r.GetDecimal(12),SilverMultiplier=r.GetDecimal(13),GoldMultiplier=r.GetDecimal(14),PlatinumMultiplier=r.GetDecimal(15),ReferralBonus=r.GetInt32(16),CreatedAt=r.GetDateTime(17),UpdatedAt=r.IsDBNull(18)?null:r.GetDateTime(18) }; }

        public async Task UpsertSettingsAsync(LoyaltySettingsModel m) { using var c=new NpgsqlConnection(_cs); using var cmd=new NpgsqlCommand("INSERT INTO restaurantloyaltysettings (farmid,isenabled,pointspercurrencyunit,pointsredemptionrate,minimumredeempoints,pointsexpirydays,tiersenabled,bronzethreshold,silverthreshold,goldthreshold,platinumthreshold,bronzemultiplier,silvermultiplier,goldmultiplier,platinummultiplier,referralbonus) VALUES (@FarmId,@Enabled,@PPUnit,@PRRate,@MinRdm,@ExpDays,@TiersOn,@BrnzT,@SlvrT,@GoldT,@PlatT,@BrnzM,@SlvrM,@GoldM,@PlatM,@RefBonus) ON CONFLICT (farmid) DO UPDATE SET isenabled=@Enabled,pointspercurrencyunit=@PPUnit,pointsredemptionrate=@PRRate,minimumredeempoints=@MinRdm,pointsexpirydays=@ExpDays,tiersenabled=@TiersOn,bronzethreshold=@BrnzT,silverthreshold=@SlvrT,goldthreshold=@GoldT,platinumthreshold=@PlatT,bronzemultiplier=@BrnzM,silvermultiplier=@SlvrM,goldmultiplier=@GoldM,platinummultiplier=@PlatM,referralbonus=@RefBonus,updatedat=NOW()",c); cmd.Parameters.AddWithValue("@FarmId",m.FarmId); cmd.Parameters.AddWithValue("@Enabled",m.IsEnabled); cmd.Parameters.AddWithValue("@PPUnit",m.PointsPerCurrencyUnit); cmd.Parameters.AddWithValue("@PRRate",m.PointsRedemptionRate); cmd.Parameters.AddWithValue("@MinRdm",m.MinimumRedeemPoints); cmd.Parameters.AddWithValue("@ExpDays",m.PointsExpiryDays); cmd.Parameters.AddWithValue("@TiersOn",m.TiersEnabled); cmd.Parameters.AddWithValue("@BrnzT",m.BronzeThreshold); cmd.Parameters.AddWithValue("@SlvrT",m.SilverThreshold); cmd.Parameters.AddWithValue("@GoldT",m.GoldThreshold); cmd.Parameters.AddWithValue("@PlatT",m.PlatinumThreshold); cmd.Parameters.AddWithValue("@BrnzM",m.BronzeMultiplier); cmd.Parameters.AddWithValue("@SlvrM",m.SilverMultiplier); cmd.Parameters.AddWithValue("@GoldM",m.GoldMultiplier); cmd.Parameters.AddWithValue("@PlatM",m.PlatinumMultiplier); cmd.Parameters.AddWithValue("@RefBonus",m.ReferralBonus); await c.OpenAsync(); await cmd.ExecuteNonQueryAsync(); }

        public async Task<List<LoyaltyAccountModel>> ListAccountsAsync(string farmId, string? tier = null) { using var c=new NpgsqlConnection(_cs); using var cmd=new NpgsqlCommand("SELECT * FROM sprestaurant_loyalty_account_list(p_farmid=>@F::text,p_tier=>@T::text)",c); cmd.Parameters.Add(TP("@F",farmId)); cmd.Parameters.Add(new NpgsqlParameter("@T",NpgsqlDbType.Text){Value=(object?)tier??DBNull.Value}); await c.OpenAsync(); using var r=await cmd.ExecuteReaderAsync(); var l=new List<LoyaltyAccountModel>(); while(await r.ReadAsync()) l.Add(new(){LoyaltyAccountId=r.GetInt32(0),FarmId=r.GetString(1),CustomerId=r.IsDBNull(2)?null:r.GetInt32(2),CustomerName=r.GetString(3),CustomerPhone=r.IsDBNull(4)?null:r.GetString(4),TotalPoints=r.GetInt32(5),LifetimePoints=r.GetInt32(6),CurrentTier=r.GetString(7),ReferralCode=r.IsDBNull(8)?null:r.GetString(8),ReferredBy=r.IsDBNull(9)?null:r.GetInt32(9),CreatedAt=r.GetDateTime(10),UpdatedAt=r.IsDBNull(11)?null:r.GetDateTime(11)}); return l; }

        public async Task<int> CreateAccountAsync(string farmId, int? customerId, string customerName, string? customerPhone) { using var c=new NpgsqlConnection(_cs); using var cmd=new NpgsqlCommand("SELECT sprestaurant_loyalty_account_create(p_farmid=>@F::text,p_customerid=>@a::int,p_customername=>@b::text,p_customerphone=>@c::text)",c); cmd.Parameters.Add(TP("@F",farmId)); cmd.Parameters.AddWithValue("@a",(object?)customerId??DBNull.Value); cmd.Parameters.AddWithValue("@b",customerName); cmd.Parameters.AddWithValue("@c",(object?)customerPhone??DBNull.Value); await c.OpenAsync(); return Convert.ToInt32(await cmd.ExecuteScalarAsync()); }

        public async Task EarnPointsAsync(int accountId, string farmId, int points, string description, int? orderId = null) { using var c=new NpgsqlConnection(_cs); using var cmd=new NpgsqlCommand("SELECT sprestaurant_loyalty_earn(p_accountid=>@A::int,p_farmid=>@F::text,p_points=>@P::int,p_description=>@D::text,p_orderid=>@O::int)",c); cmd.Parameters.AddWithValue("@A",accountId); cmd.Parameters.Add(TP("@F",farmId)); cmd.Parameters.AddWithValue("@P",points); cmd.Parameters.AddWithValue("@D",description); cmd.Parameters.AddWithValue("@O",(object?)orderId??DBNull.Value); await c.OpenAsync(); await cmd.ExecuteNonQueryAsync(); }

        public async Task<bool> RedeemPointsAsync(int accountId, string farmId, int points, string description) { using var c=new NpgsqlConnection(_cs); using var cmd=new NpgsqlCommand("SELECT sprestaurant_loyalty_redeem(p_accountid=>@A::int,p_farmid=>@F::text,p_points=>@P::int,p_description=>@D::text)",c); cmd.Parameters.AddWithValue("@A",accountId); cmd.Parameters.Add(TP("@F",farmId)); cmd.Parameters.AddWithValue("@P",points); cmd.Parameters.AddWithValue("@D",description); await c.OpenAsync(); return Convert.ToBoolean(await cmd.ExecuteScalarAsync()); }

        public async Task<List<PointTransactionModel>> GetTransactionsAsync(int accountId, string farmId) { using var c=new NpgsqlConnection(_cs); using var cmd=new NpgsqlCommand("SELECT * FROM sprestaurant_loyalty_transactions(p_accountid=>@A::int,p_farmid=>@F::text)",c); cmd.Parameters.AddWithValue("@A",accountId); cmd.Parameters.Add(TP("@F",farmId)); await c.OpenAsync(); using var r=await cmd.ExecuteReaderAsync(); var l=new List<PointTransactionModel>(); while(await r.ReadAsync()) l.Add(new(){PointTransactionId=r.GetInt32(0),TransactionType=r.GetString(1),Points=r.GetInt32(2),Description=r.IsDBNull(3)?null:r.GetString(3),OrderId=r.IsDBNull(4)?null:r.GetInt32(4),CreatedAt=r.GetDateTime(5)}); return l; }

        public async Task<LoyaltyStatsModel> GetStatsAsync(string farmId) { using var c=new NpgsqlConnection(_cs); using var cmd=new NpgsqlCommand("SELECT * FROM sprestaurant_loyalty_stats(p_farmid=>@F::text)",c); cmd.Parameters.Add(TP("@F",farmId)); await c.OpenAsync(); using var r=await cmd.ExecuteReaderAsync(); if(await r.ReadAsync()) return new(){TotalMembers=r.GetInt64(0),TotalPointsOutstanding=r.GetInt64(1),BronzeCount=r.GetInt64(2),SilverCount=r.GetInt64(3),GoldCount=r.GetInt64(4),PlatinumCount=r.GetInt64(5)}; return new(); }
    }
}
