using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Globalization;
using PoultryFarmAPIWeb.Models;

namespace PoultryFarmAPI.Business
{
    // Single QuestPDF renderer for every Water report + the daily closing.
    // Driven entirely by WaterReportPdfModel (see Models/WaterReportPdfModel.cs).
    public class WaterReportPdfDocument : IDocument
    {
        private readonly WaterReportPdfModel _m;
        public WaterReportPdfDocument(WaterReportPdfModel m) => _m = m;

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Margin(30);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Column(col =>
                {
                    col.Item().Text(_m.Title).SemiBold().FontSize(18).FontColor(Colors.Blue.Darken2);
                    if (!string.IsNullOrWhiteSpace(_m.CompanyName))
                        col.Item().Text($"Company: {_m.CompanyName}").FontColor(Colors.Grey.Darken1);
                    if (!string.IsNullOrWhiteSpace(_m.DateRange))
                        col.Item().Text($"Period: {_m.DateRange}").FontColor(Colors.Grey.Darken1);
                    if (!string.IsNullOrWhiteSpace(_m.GeneratedBy))
                        col.Item().Text($"Generated by: {_m.GeneratedBy}").FontColor(Colors.Grey.Darken1);
                    foreach (var f in _m.Filters)
                        col.Item().Text($"{f.Key}: {f.Value}").FontSize(9).FontColor(Colors.Grey.Darken1);
                });

                page.Content().PaddingVertical(10).Column(col =>
                {
                    col.Spacing(10);
                    if (_m.Sections.Count == 0)
                        col.Item().PaddingTop(8).Text("No data for the selected period.").Italic().FontColor(Colors.Grey.Darken1);

                    foreach (var section in _m.Sections)
                    {
                        if (!string.IsNullOrWhiteSpace(section.Heading))
                            col.Item().PaddingTop(6).Text(section.Heading).SemiBold().FontSize(12);

                        if (section.Pairs.Count > 0)
                            col.Item().Element(c => ComposePairs(c, section.Pairs));

                        if (section.Columns.Length > 0)
                            col.Item().Element(c => ComposeTable(c, section.Columns, section.Rows));
                    }
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated on ");
                    x.Span(DateTime.Now.ToString("g", CultureInfo.InvariantCulture)).SemiBold();
                    x.Span("  •  Page ");
                    x.CurrentPageNumber();
                    x.Span(" / ");
                    x.TotalPages();
                });
            });
        }

        private static void ComposePairs(IContainer container, List<KeyValuePair<string, string>> pairs)
        {
            container.Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(2);
                    columns.RelativeColumn(3);
                });
                foreach (var p in pairs)
                {
                    table.Cell().Element(PairCell).Text(p.Key).SemiBold();
                    table.Cell().Element(PairCell).Text(p.Value);
                }

                static IContainer PairCell(IContainer c) =>
                    c.PaddingVertical(3).BorderBottom(1).BorderColor(Colors.Grey.Lighten3);
            });
        }

        private static void ComposeTable(IContainer container, string[] headers, List<string[]> rows)
        {
            container.Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    for (int i = 0; i < headers.Length; i++) columns.RelativeColumn();
                });

                table.Header(header =>
                {
                    foreach (var h in headers)
                        header.Cell().Element(HeaderCell).Text(h).SemiBold().FontColor(Colors.White);
                });

                foreach (var row in rows)
                {
                    for (int i = 0; i < headers.Length; i++)
                        table.Cell().Element(BodyCell).Text(i < row.Length ? row[i] : string.Empty);
                }

                static IContainer HeaderCell(IContainer c) =>
                    c.Background(Colors.Blue.Darken2).PaddingVertical(4).PaddingHorizontal(4);
                static IContainer BodyCell(IContainer c) =>
                    c.PaddingVertical(3).PaddingHorizontal(4).BorderBottom(1).BorderColor(Colors.Grey.Lighten2);
            });
        }
    }
}
