using System.Globalization;
using System.Net;
using QuestPDF.Fluent;
using PoultryFarmAPI.Business;   // WaterReportPdfDocument
using PoultryFarmAPIWeb.Models;

namespace PoultryFarmAPIWeb.Business
{
    // Builds the daily-closing PDF and emails it via IEmailService. Used by the
    // daily-closing controller (auto-sent on submit + manual re-send). Reports
    // themselves are emailed client-side (jsPDF → POST /api/Email/Report); only
    // the closing-on-submit needs a server-side PDF (no rendered page at submit).
    public interface IWaterReportEmailService
    {
        Task EmailClosingAsync(WaterDailyClosingModel closing, string to, string? companyName);
    }

    public class WaterReportEmailService : IWaterReportEmailService
    {
        private readonly IEmailService _email;

        public WaterReportEmailService(IEmailService email)
        {
            _email = email;
        }

        private static string M(decimal d) => d.ToString("N2", CultureInfo.InvariantCulture);
        private static string D(DateTime d) => d.ToString("yyyy-MM-dd");

        public async Task EmailClosingAsync(WaterDailyClosingModel c, string to, string? companyName)
        {
            var model = new WaterReportPdfModel
            {
                Title = "Daily Closing Report",
                CompanyName = companyName,
                DateRange = D(c.ClosingDate),
                Sections = new List<WaterReportPdfSection>
                {
                    new WaterReportPdfSection
                    {
                        Heading = $"Closing for {D(c.ClosingDate)} (Status: {c.Status})",
                        Pairs = new List<KeyValuePair<string, string>>
                        {
                            new("Opening stock (bags)", M(c.OpeningStockBags)),
                            new("Bags produced", M(c.BagsProduced)),
                            new("Bags sold", M(c.BagsSold)),
                            new("Bags returned", M(c.BagsReturned)),
                            new("Bags damaged", M(c.BagsDamaged)),
                            new("Closing stock (bags)", M(c.ClosingStockBags)),
                            new("Total income", M(c.TotalIncome)),
                            new("Total expenses", M(c.TotalExpenses)),
                            new("Total production cost", M(c.TotalProductionCost)),
                            new("Cash at hand", M(c.CashAtHand)),
                            new("Actual cash counted", M(c.ActualCashCounted)),
                            new("Cash difference", M(c.CashDifference)),
                            new("Credit sales", M(c.CreditSales)),
                            new("Customer collections", M(c.CustomerCollections)),
                            new("Driver shortages", M(c.DriverShortagesTotal)),
                            new("MoMo balance", M(c.MoMoBalance)),
                            new("Bank balance", M(c.BankBalance)),
                            new("Submitted by", c.SubmittedBy ?? "—"),
                            new("Notes", string.IsNullOrWhiteSpace(c.ManagerNotes) ? "—" : c.ManagerNotes!),
                        },
                    },
                },
            };

            var pdf = new WaterReportPdfDocument(model).GeneratePdf();
            var generated = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm 'UTC'");
            var body = $@"
<div style=""font-family:Arial,Helvetica,sans-serif;color:#0f172a;line-height:1.5;"">
  <p>Hi,</p>
  <p>Please find the daily closing report attached as a PDF.</p>
  <p style=""color:#64748b;font-size:12px;"">Generated by Poultry Master at {generated}.</p>
</div>";
            await _email.SendAsync(
                to: new[] { to },
                subject: $"Daily Closing Report — {companyName ?? "Water company"} ({D(c.ClosingDate)})",
                body: body,
                isHtml: true,
                attachments: new[] { new EmailAttachment { FileName = $"closing-{D(c.ClosingDate)}.pdf", ContentType = "application/pdf", Content = pdf } });
        }
    }
}
