using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PoultryFarmAPIWeb.Business;
using PoultryFarmAPIWeb.Models;

namespace PoultryFarmAPIWeb.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    [Authorize]
    public class EmailController : ControllerBase
    {
        private readonly IEmailService _email;
        private readonly ILogger<EmailController> _logger;

        public EmailController(IEmailService email, ILogger<EmailController> logger)
        {
            _email = email;
            _logger = logger;
        }

        // POST: api/Email/Report
        // Multipart form upload:
        //   - file: the PDF report (required)
        //   - to:   recipient email (required for now; future: resolve from JWT)
        //   - subject: email subject (optional, defaults to "Your report from PoultryCore")
        //   - body:    HTML body (optional, default template used otherwise)
        //   - farmName: optional, used in default body
        //   - reportTitle: optional, used in default body
        [HttpPost("Report")]
        [RequestSizeLimit(20_000_000)] // 20 MB cap
        public async Task<IActionResult> SendReport(
            [FromForm] IFormFile file,
            [FromForm] string to,
            [FromForm] string? subject = null,
            [FromForm] string? body = null,
            [FromForm] string? farmName = null,
            [FromForm] string? reportTitle = null)
        {
            if (file == null || file.Length == 0)
                return BadRequest("Report file is required.");

            if (string.IsNullOrWhiteSpace(to))
                return BadRequest("Recipient email (to) is required.");

            // Basic recipient sanity check — let MimeKit do the real parsing later.
            if (!to.Contains('@'))
                return BadRequest("Recipient email looks malformed.");

            byte[] bytes;
            using (var ms = new MemoryStream())
            {
                await file.CopyToAsync(ms);
                bytes = ms.ToArray();
            }

            var resolvedSubject = !string.IsNullOrWhiteSpace(subject)
                ? subject
                : !string.IsNullOrWhiteSpace(reportTitle)
                    ? $"{reportTitle} — {farmName ?? "PoultryCore"}"
                    : "Your PoultryCore report";

            var resolvedBody = !string.IsNullOrWhiteSpace(body)
                ? body
                : BuildDefaultHtmlBody(reportTitle, farmName);

            var attachment = new EmailAttachment
            {
                FileName = string.IsNullOrWhiteSpace(file.FileName) ? "report.pdf" : file.FileName,
                ContentType = string.IsNullOrWhiteSpace(file.ContentType) ? "application/pdf" : file.ContentType,
                Content = bytes,
            };

            try
            {
                await _email.SendAsync(
                    to: new[] { to },
                    subject: resolvedSubject,
                    body: resolvedBody,
                    isHtml: true,
                    attachments: new[] { attachment });

                return Ok(new { success = true, message = $"Report emailed to {to}." });
            }
            catch (InvalidOperationException ex)
            {
                // Misconfiguration — surfaces helpful message to caller.
                _logger.LogError(ex, "Email send aborted due to misconfiguration.");
                return StatusCode(503, new { success = false, message = ex.Message });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to send report email to {Recipient}", to);
                return StatusCode(500, new { success = false, message = "Failed to send email. Check API logs." });
            }
        }

        private static string BuildDefaultHtmlBody(string? reportTitle, string? farmName)
        {
            var title = string.IsNullOrWhiteSpace(reportTitle) ? "report" : reportTitle;
            var farm = string.IsNullOrWhiteSpace(farmName) ? "" : $" for <strong>{System.Net.WebUtility.HtmlEncode(farmName)}</strong>";
            var generated = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm 'UTC'");
            return $@"
<div style=""font-family:Arial,Helvetica,sans-serif;color:#0f172a;line-height:1.5;"">
  <p>Hi,</p>
  <p>Your <strong>{System.Net.WebUtility.HtmlEncode(title)}</strong>{farm} is attached as a PDF.</p>
  <p style=""color:#64748b;font-size:12px;"">Generated by PoultryCore at {generated}.</p>
</div>";
        }
    }
}
