using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PoultryFarmAPIWeb.Business;
using PoultryFarmAPIWeb.Models;

namespace PoultryFarmAPIWeb.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    [Authorize]
    public class EmailController : ControllerBase
    {
        private readonly IEmailService _email;
        private readonly ILogger<EmailController> _logger;

        public EmailController(IEmailService email, ILogger<EmailController> logger)
        {
            _email = email;
            _logger = logger;
        }

        // POST: api/Email/Report
        // Multipart form upload:
        //   - file: the PDF report (required)
        //   - to:   recipient email (required for now; future: resolve from JWT)
        //   - subject: email subject (optional, defaults to "Your report from PoultryCore")
        //   - body:    HTML body (optional, default template used otherwise)
        //   - farmName: optional, used in default body
        //   - reportTitle: optional, used in default body
        [HttpPost("Report")]
        [RequestSizeLimit(20_000_000)] // 20 MB cap
        public async Task<IActionResult> SendReport([FromForm] SendReportRequest request)
        {
            var file = request.File;

            if (file == null || file.Length == 0)
                return BadRequest("Report file is required.");

            if (string.IsNullOrWhiteSpace(request.To))
                return BadRequest("Recipient email (to) is required.");

            // Basic recipient sanity check — let MimeKit do the real parsing later.
            if (!request.To.Contains('@'))
                return BadRequest("Recipient email looks malformed.");

            byte[] bytes;
            using (var ms = new MemoryStream())
            {
                await file.CopyToAsync(ms);
                bytes = ms.ToArray();
            }

            var resolvedSubject = !string.IsNullOrWhiteSpace(request.Subject)
                ? request.Subject
                : !string.IsNullOrWhiteSpace(request.ReportTitle)
                    ? $"{request.ReportTitle} — {request.FarmName ?? "PoultryCore"}"
                    : "Your PoultryCore report";

            var resolvedBody = !string.IsNullOrWhiteSpace(request.Body)
                ? request.Body
                : BuildDefaultHtmlBody(request.ReportTitle, request.FarmName);

            var attachment = new EmailAttachment
            {
                FileName = string.IsNullOrWhiteSpace(file.FileName) ? "report.pdf" : file.FileName,
                ContentType = string.IsNullOrWhiteSpace(file.ContentType) ? "application/pdf" : file.ContentType,
                Content = bytes,
            };

            try
            {
                await _email.SendAsync(
                    to: new[] { request.To },
                    subject: resolvedSubject,
                    body: resolvedBody,
                    isHtml: true,
                    attachments: new[] { attachment });

                return Ok(new { success = true, message = $"Report emailed to {request.To}." });
            }
            catch (InvalidOperationException ex)
            {
                // Misconfiguration — surfaces helpful message to caller.
                _logger.LogError(ex, "Email send aborted due to misconfiguration.");
                return StatusCode(503, new { success = false, message = ex.Message });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to send report email to {Recipient}", request.To);
                return StatusCode(500, new { success = false, message = "Failed to send email. Check API logs." });
            }
        }

        private static string BuildDefaultHtmlBody(string? reportTitle, string? farmName)
        {
            var title = string.IsNullOrWhiteSpace(reportTitle) ? "report" : reportTitle;
            var farm = string.IsNullOrWhiteSpace(farmName) ? "" : $" for <strong>{System.Net.WebUtility.HtmlEncode(farmName)}</strong>";
            var generated = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm 'UTC'");
            return $@"
<div style=""font-family:Arial,Helvetica,sans-serif;color:#0f172a;line-height:1.5;"">
  <p>Hi,</p>
  <p>Your <strong>{System.Net.WebUtility.HtmlEncode(title)}</strong>{farm} is attached as a PDF.</p>
  <p style=""color:#64748b;font-size:12px;"">Generated by PoultryCore at {generated}.</p>
</div>";
        }
    }

    /// <summary>
    /// Multipart form payload for <see cref="EmailController.SendReport"/>.
    /// Bound as a single model so Swashbuckle can describe the IFormFile alongside the text fields.
    /// </summary>
    public class SendReportRequest
    {
        /// <summary>The PDF report (required).</summary>
        public IFormFile File { get; set; } = default!;

        /// <summary>Recipient email (required for now; future: resolve from JWT).</summary>
        public string To { get; set; } = string.Empty;

        /// <summary>Email subject (optional, defaults to "Your PoultryCore report").</summary>
        public string? Subject { get; set; }

        /// <summary>HTML body (optional, default template used otherwise).</summary>
        public string? Body { get; set; }

        /// <summary>Optional, used in default body.</summary>
        public string? FarmName { get; set; }

        /// <summary>Optional, used in default body.</summary>
        public string? ReportTitle { get; set; }
    }
}
